import type { Alineacion } from '@/components/pastoral/pastoral-canvas-model'
import { PLANTILLAS_PROFESIONALES } from '@/components/pastoral/pastoral-professional-templates'

export type PlantillaVisual = {
  id: string
  nombre: string
  categoria: 'Cristianas' | 'Minimalistas' | 'Generales'
  fondo: string
  colorTexto: string
  titulo: { x: number; y: number; w: number; h: number; pt: number; alineacion: Alineacion; fuente: string }
  subtitulo?: { x: number; y: number; w: number; h: number; pt: number; alineacion: Alineacion; fuente: string }
  cuerpo?: { x: number; y: number; w: number; h: number; pt: number; alineacion: Alineacion; fuente: string }
}

export type PaletaPresentacion = {
  id: string
  label: string
  fondo: string
  titulo: string
  texto: string
  acento: string
  fuenteTitulo: string
  fuenteCuerpo: string
}

/* Temas: identidad visual completa. Canva se usa solo como referencia de variedad
   (editorial, tipográfico, papel, gradiente, elegante, juvenil), nunca como copia. */
export const PALETAS_PRESENTACION: PaletaPresentacion[] = [
  { id: 'editorial-blanco', label: 'Editorial blanco', fondo: '#FFFFFF', titulo: '#111827', texto: '#475569', acento: '#C0392B', fuenteTitulo: 'Georgia', fuenteCuerpo: 'Inter' },
  { id: 'crema-serif', label: 'Crema serif', fondo: 'linear-gradient(145deg,#FFFDF8 0%,#F2E8D8 100%)', titulo: '#3B3028', texto: '#67574B', acento: '#B7791F', fuenteTitulo: 'Garamond', fuenteCuerpo: 'Helvetica' },
  { id: 'papel-biblia', label: 'Papel bíblico', fondo: 'repeating-linear-gradient(0deg,rgba(92,69,54,.035) 0 1px,transparent 1px 5px),linear-gradient(#FBF7EE,#F2E7D4)', titulo: '#403329', texto: '#6A584A', acento: '#9A6B3E', fuenteTitulo: 'Palatino Linotype', fuenteCuerpo: 'Georgia' },
  { id: 'tipografico-azul', label: 'Tipográfico azul', fondo: 'linear-gradient(135deg,#F7FAFF 0%,#DDEBFA 100%)', titulo: '#102A43', texto: '#365B7A', acento: '#2563EB', fuenteTitulo: 'Arial Black', fuenteCuerpo: 'Inter' },
  { id: 'negro-oro', label: 'Negro y oro', fondo: 'linear-gradient(145deg,#121418 0%,#24201B 100%)', titulo: '#FFF9E8', texto: '#DDD4BF', acento: '#D4AF37', fuenteTitulo: 'Georgia', fuenteCuerpo: 'Helvetica' },
  { id: 'noche-azul', label: 'Noche azul', fondo: 'radial-gradient(circle at 78% 18%,rgba(96,165,250,.25),transparent 28%),linear-gradient(145deg,#07111F,#172554)', titulo: '#FFFFFF', texto: '#D4E4F7', acento: '#60A5FA', fuenteTitulo: 'Garamond', fuenteCuerpo: 'Inter' },
  { id: 'rojo-crema', label: 'Rojo crema', fondo: 'linear-gradient(135deg,#FFF9F3 0%,#F8E7DD 100%)', titulo: '#7F1D1D', texto: '#6B3D35', acento: '#DC2626', fuenteTitulo: 'Times New Roman', fuenteCuerpo: 'Inter' },
  { id: 'salvia-elegante', label: 'Salvia elegante', fondo: 'linear-gradient(145deg,#F5F8F1 0%,#DDE8D5 100%)', titulo: '#1F3A2D', texto: '#4D6455', acento: '#6B8E67', fuenteTitulo: 'Georgia', fuenteCuerpo: 'Inter' },
  { id: 'bosque-clasico', label: 'Bosque clásico', fondo: 'linear-gradient(145deg,#10271E 0%,#1E4936 100%)', titulo: '#FFF9E8', texto: '#D7E7DC', acento: '#B7C989', fuenteTitulo: 'Palatino Linotype', fuenteCuerpo: 'Inter' },
  { id: 'purpura-gradiente', label: 'Púrpura gradiente', fondo: 'linear-gradient(135deg,#312E81 0%,#6D28D9 55%,#A855F7 100%)', titulo: '#FFFFFF', texto: '#F0EAFE', acento: '#FACC15', fuenteTitulo: 'Arial Black', fuenteCuerpo: 'Inter' },
  { id: 'coral-editorial', label: 'Coral editorial', fondo: 'radial-gradient(circle at 15% 20%,rgba(251,146,60,.28),transparent 28%),linear-gradient(145deg,#FFF8F4,#FBE4E7)', titulo: '#4A2A2D', texto: '#765257', acento: '#F97316', fuenteTitulo: 'Trebuchet MS', fuenteCuerpo: 'Inter' },
  { id: 'juventud-neon', label: 'Juventud neón', fondo: 'radial-gradient(circle at 80% 20%,rgba(163,230,53,.28),transparent 25%),linear-gradient(145deg,#071A18,#0D2B26)', titulo: '#F7FEE7', texto: '#D9F99D', acento: '#A3E635', fuenteTitulo: 'Impact', fuenteCuerpo: 'Trebuchet MS' },
  { id: 'blanco-negro', label: 'Blanco y negro', fondo: '#F8FAFC', titulo: '#020617', texto: '#334155', acento: '#020617', fuenteTitulo: 'Helvetica', fuenteCuerpo: 'Inter' },
  { id: 'grafito', label: 'Grafito', fondo: 'repeating-linear-gradient(135deg,rgba(255,255,255,.018) 0 2px,transparent 2px 7px),linear-gradient(145deg,#20262F,#353D49)', titulo: '#F8FAFC', texto: '#D7DEE7', acento: '#94A3B8', fuenteTitulo: 'Helvetica', fuenteCuerpo: 'Inter' },
  { id: 'arena-organica', label: 'Arena orgánica', fondo: 'radial-gradient(circle at 82% 16%,rgba(180,83,9,.12),transparent 26%),radial-gradient(circle at 18% 80%,rgba(120,53,15,.10),transparent 30%),linear-gradient(145deg,#FBF5E9,#EAD8BD)', titulo: '#4A3525', texto: '#725A46', acento: '#B45309', fuenteTitulo: 'Garamond', fuenteCuerpo: 'Inter' },
  { id: 'azul-clasico', label: 'Azul clásico', fondo: 'linear-gradient(145deg,#0A1D38,#173A63)', titulo: '#FFF8E7', texto: '#DCE7F4', acento: '#D4AF37', fuenteTitulo: 'Times New Roman', fuenteCuerpo: 'Georgia' },
  { id: 'agua-moderna', label: 'Agua moderna', fondo: 'linear-gradient(135deg,#E9FFFB 0%,#B9ECE6 48%,#4FB9AE 100%)', titulo: '#0B3D3A', texto: '#225D58', acento: '#0F766E', fuenteTitulo: 'Arial Black', fuenteCuerpo: 'Inter' },
  { id: 'lavanda-editorial', label: 'Lavanda editorial', fondo: 'linear-gradient(145deg,#FBF9FF 0%,#E8E0F5 100%)', titulo: '#3A2D5C', texto: '#655A7D', acento: '#7C3AED', fuenteTitulo: 'Georgia', fuenteCuerpo: 'Inter' },
  { id: 'borgona-clasico', label: 'Borgoña clásico', fondo: 'linear-gradient(145deg,#3E101F,#6A2238)', titulo: '#FFF8EE', texto: '#F1DDE3', acento: '#E4B45B', fuenteTitulo: 'Garamond', fuenteCuerpo: 'Georgia' },
  { id: 'amanecer', label: 'Amanecer', fondo: 'linear-gradient(135deg,#FFF6E8 0%,#FFD9C7 48%,#F3D5E8 100%)', titulo: '#5A3134', texto: '#79555A', acento: '#E8795A', fuenteTitulo: 'Trebuchet MS', fuenteCuerpo: 'Inter' },
]

export const PLANTILLAS_VISUALES: PlantillaVisual[] = [
  /* La familia Litúrgico V2 aparece primero para revisión y uso inmediato. */
  ...PLANTILLAS_PROFESIONALES,

  /* Colección curada existente conservada después de la familia V2. */
  { id: 'editorial-marfil', nombre: 'Editorial marfil', categoria: 'Minimalistas', fondo: 'linear-gradient(145deg,#fffdf8 0%,#f4eee3 100%)', colorTexto: '#2F2924', titulo: { x: 8, y: 12, w: 58, h: 31, pt: 46, alineacion: 'izquierda', fuente: 'Georgia' }, subtitulo: { x: 8, y: 51, w: 72, h: 14, pt: 19, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 8, y: 70, w: 68, h: 16, pt: 16, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'versiculo-luz', nombre: 'Versículo luz', categoria: 'Cristianas', fondo: 'radial-gradient(circle at 72% 22%,rgba(96,165,250,.28),transparent 34%),linear-gradient(145deg,#07111f 0%,#172554 100%)', colorTexto: '#F8FAFC', titulo: { x: 16, y: 19, w: 68, h: 37, pt: 42, alineacion: 'centro', fuente: 'Garamond' }, subtitulo: { x: 28, y: 64, w: 44, h: 13, pt: 18, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'serie-horizonte', nombre: 'Serie horizonte', categoria: 'Generales', fondo: 'linear-gradient(120deg,#f7f9fc 0%,#edf3f8 52%,#dce8f3 100%)', colorTexto: '#183247', titulo: { x: 39, y: 13, w: 53, h: 31, pt: 42, alineacion: 'derecha', fuente: 'Helvetica' }, subtitulo: { x: 47, y: 52, w: 45, h: 14, pt: 19, alineacion: 'derecha', fuente: 'Inter' }, cuerpo: { x: 31, y: 72, w: 61, h: 14, pt: 16, alineacion: 'derecha', fuente: 'Inter' } },
  { id: 'biblia-papel', nombre: 'Biblia papel', categoria: 'Cristianas', fondo: 'repeating-linear-gradient(0deg,rgba(92,69,54,.035) 0 1px,transparent 1px 5px),linear-gradient(#fbf7ee,#f5eddf)', colorTexto: '#43352A', titulo: { x: 11, y: 12, w: 40, h: 23, pt: 30, alineacion: 'izquierda', fuente: 'Palatino Linotype' }, cuerpo: { x: 11, y: 43, w: 74, h: 38, pt: 20, alineacion: 'izquierda', fuente: 'Georgia' } },
  { id: 'conferencia-nitida', nombre: 'Conferencia nítida', categoria: 'Generales', fondo: 'linear-gradient(150deg,#0f2743 0%,#163b63 100%)', colorTexto: '#F8FAFC', titulo: { x: 7, y: 10, w: 77, h: 34, pt: 46, alineacion: 'izquierda', fuente: 'Arial Black' }, subtitulo: { x: 7, y: 53, w: 55, h: 14, pt: 18, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 7, y: 72, w: 45, h: 14, pt: 16, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'palabra-central', nombre: 'Palabra central', categoria: 'Cristianas', fondo: 'radial-gradient(circle at 50% 45%,rgba(163,197,133,.18),transparent 34%),linear-gradient(145deg,#102b20 0%,#173528 100%)', colorTexto: '#F7F6EE', titulo: { x: 15, y: 28, w: 70, h: 30, pt: 48, alineacion: 'centro', fuente: 'Impact' }, subtitulo: { x: 31, y: 65, w: 38, h: 13, pt: 18, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'juventud-suave', nombre: 'Juventud suave', categoria: 'Generales', fondo: 'radial-gradient(circle at 82% 18%,rgba(124,107,177,.20),transparent 26%),radial-gradient(circle at 18% 80%,rgba(242,140,130,.18),transparent 28%),linear-gradient(145deg,#fbf8ff,#f7f0f3)', colorTexto: '#392D4B', titulo: { x: 8, y: 48, w: 63, h: 27, pt: 39, alineacion: 'izquierda', fuente: 'Trebuchet MS' }, subtitulo: { x: 8, y: 77, w: 50, h: 12, pt: 17, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'noche-elegante', nombre: 'Noche elegante', categoria: 'Minimalistas', fondo: 'linear-gradient(135deg,#111827 0%,#291a33 58%,#4a1225 100%)', colorTexto: '#FFF8FA', titulo: { x: 42, y: 15, w: 49, h: 31, pt: 41, alineacion: 'derecha', fuente: 'Georgia' }, subtitulo: { x: 32, y: 54, w: 59, h: 14, pt: 18, alineacion: 'derecha', fuente: 'Helvetica' }, cuerpo: { x: 51, y: 73, w: 40, h: 13, pt: 16, alineacion: 'derecha', fuente: 'Helvetica' } },
  { id: 'clasico-liturgico', nombre: 'Clásico litúrgico', categoria: 'Cristianas', fondo: 'linear-gradient(145deg,#fffaf0 0%,#f0e5cf 100%)', colorTexto: '#3C3026', titulo: { x: 21, y: 14, w: 58, h: 28, pt: 38, alineacion: 'centro', fuente: 'Times New Roman' }, subtitulo: { x: 18, y: 51, w: 64, h: 14, pt: 18, alineacion: 'centro', fuente: 'Palatino Linotype' }, cuerpo: { x: 28, y: 71, w: 44, h: 14, pt: 16, alineacion: 'centro', fuente: 'Georgia' } },
  { id: 'creativo-pastel', nombre: 'Creativo pastel', categoria: 'Generales', fondo: 'radial-gradient(circle at 16% 20%,rgba(251,191,36,.30),transparent 24%),radial-gradient(circle at 84% 72%,rgba(244,114,182,.22),transparent 25%),linear-gradient(135deg,#fff9f1,#f3f5ff)', colorTexto: '#2E3147', titulo: { x: 7, y: 12, w: 50, h: 29, pt: 39, alineacion: 'izquierda', fuente: 'Arial Black' }, subtitulo: { x: 23, y: 52, w: 63, h: 14, pt: 18, alineacion: 'izquierda', fuente: 'Trebuchet MS' }, cuerpo: { x: 47, y: 72, w: 39, h: 13, pt: 16, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'pizarra-moderna', nombre: 'Pizarra moderna', categoria: 'Minimalistas', fondo: 'repeating-linear-gradient(135deg,rgba(255,255,255,.018) 0 2px,transparent 2px 7px),linear-gradient(145deg,#20262f,#303844)', colorTexto: '#F8FAFC', titulo: { x: 7, y: 13, w: 62, h: 30, pt: 42, alineacion: 'izquierda', fuente: 'Helvetica' }, subtitulo: { x: 7, y: 52, w: 77, h: 14, pt: 18, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 7, y: 71, w: 58, h: 14, pt: 16, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'amanecer-minimal', nombre: 'Amanecer minimal', categoria: 'Minimalistas', fondo: 'linear-gradient(145deg,#fff9ed 0%,#fee8d7 48%,#f8dce4 100%)', colorTexto: '#4C302B', titulo: { x: 15, y: 43, w: 70, h: 29, pt: 40, alineacion: 'centro', fuente: 'Garamond' }, subtitulo: { x: 26, y: 74, w: 48, h: 12, pt: 17, alineacion: 'centro', fuente: 'Inter' } },

  /* Biblioteca existente conservada para no perder opciones ya disponibles. */
  { id: 'predicacion-limpia', nombre: 'Predicación limpia', categoria: 'Cristianas', fondo: '#FFFFFF', colorTexto: '#0F172A', titulo: { x: 9, y: 11, w: 82, h: 30, pt: 42, alineacion: 'izquierda', fuente: 'Georgia' }, subtitulo: { x: 9, y: 45, w: 78, h: 17, pt: 23, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 9, y: 67, w: 78, h: 22, pt: 18, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'versiculo-protagonista', nombre: 'Versículo protagonista', categoria: 'Cristianas', fondo: '#0B1220', colorTexto: '#F8FAFC', titulo: { x: 10, y: 18, w: 80, h: 36, pt: 38, alineacion: 'centro', fuente: 'Georgia' }, subtitulo: { x: 17, y: 62, w: 66, h: 16, pt: 20, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'serie-dominical', nombre: 'Serie dominical', categoria: 'Cristianas', fondo: '#F4E8D4', colorTexto: '#3F2A1F', titulo: { x: 8, y: 14, w: 84, h: 32, pt: 40, alineacion: 'centro', fuente: 'Arial Black' }, subtitulo: { x: 14, y: 51, w: 72, h: 16, pt: 22, alineacion: 'centro', fuente: 'Inter' }, cuerpo: { x: 18, y: 73, w: 64, h: 15, pt: 17, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'oracion-serena', nombre: 'Oración serena', categoria: 'Cristianas', fondo: '#EDF6FF', colorTexto: '#15304A', titulo: { x: 12, y: 17, w: 76, h: 30, pt: 38, alineacion: 'centro', fuente: 'Garamond' }, cuerpo: { x: 15, y: 56, w: 70, h: 28, pt: 19, alineacion: 'centro', fuente: 'Georgia' } },
  { id: 'texto-biblico', nombre: 'Texto bíblico', categoria: 'Cristianas', fondo: '#F7F5EE', colorTexto: '#2E312B', titulo: { x: 12, y: 18, w: 76, h: 22, pt: 24, alineacion: 'centro', fuente: 'Georgia' }, cuerpo: { x: 14, y: 46, w: 72, h: 34, pt: 20, alineacion: 'centro', fuente: 'Georgia' } },
  { id: 'puntos-predica', nombre: 'Puntos de prédica', categoria: 'Cristianas', fondo: '#FFFFFF', colorTexto: '#172033', titulo: { x: 8, y: 10, w: 84, h: 24, pt: 34, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 10, y: 42, w: 78, h: 42, pt: 19, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'pregunta-central', nombre: 'Pregunta central', categoria: 'Cristianas', fondo: '#173528', colorTexto: '#F7F6EE', titulo: { x: 12, y: 20, w: 76, h: 42, pt: 38, alineacion: 'centro', fuente: 'Georgia' }, subtitulo: { x: 18, y: 69, w: 64, h: 14, pt: 18, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'serie-semanal', nombre: 'Serie semanal', categoria: 'Cristianas', fondo: '#202B58', colorTexto: '#F9FAFF', titulo: { x: 9, y: 15, w: 82, h: 30, pt: 40, alineacion: 'izquierda', fuente: 'Inter' }, subtitulo: { x: 9, y: 51, w: 66, h: 15, pt: 19, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 9, y: 72, w: 66, h: 14, pt: 16, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'cita-pastoral', nombre: 'Cita pastoral', categoria: 'Cristianas', fondo: '#FCF8F0', colorTexto: '#3B2F2F', titulo: { x: 14, y: 21, w: 72, h: 38, pt: 34, alineacion: 'centro', fuente: 'Garamond' }, subtitulo: { x: 24, y: 68, w: 52, h: 13, pt: 17, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'minimal-claro', nombre: 'Minimal claro', categoria: 'Minimalistas', fondo: '#F8FAFC', colorTexto: '#0F172A', titulo: { x: 8, y: 18, w: 84, h: 32, pt: 42, alineacion: 'izquierda', fuente: 'Helvetica' }, subtitulo: { x: 8, y: 59, w: 70, h: 16, pt: 20, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'minimal-oscuro', nombre: 'Minimal oscuro', categoria: 'Minimalistas', fondo: '#161A22', colorTexto: '#F8FAFC', titulo: { x: 10, y: 18, w: 80, h: 34, pt: 40, alineacion: 'centro', fuente: 'Inter' }, cuerpo: { x: 18, y: 60, w: 64, h: 22, pt: 18, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'editorial', nombre: 'Editorial', categoria: 'Minimalistas', fondo: '#F3F4F6', colorTexto: '#111827', titulo: { x: 7, y: 12, w: 86, h: 32, pt: 44, alineacion: 'izquierda', fuente: 'Georgia' }, subtitulo: { x: 7, y: 56, w: 60, h: 14, pt: 18, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'minimal-centrado', nombre: 'Minimal centrado', categoria: 'Minimalistas', fondo: '#FFFFFF', colorTexto: '#111827', titulo: { x: 15, y: 28, w: 70, h: 30, pt: 40, alineacion: 'centro', fuente: 'Inter' }, subtitulo: { x: 22, y: 64, w: 56, h: 14, pt: 18, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'minimal-calido', nombre: 'Minimal cálido', categoria: 'Minimalistas', fondo: '#FFF7E8', colorTexto: '#4A321D', titulo: { x: 10, y: 20, w: 80, h: 30, pt: 38, alineacion: 'centro', fuente: 'Georgia' }, cuerpo: { x: 20, y: 58, w: 60, h: 24, pt: 18, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'linea-lateral', nombre: 'Línea lateral', categoria: 'Minimalistas', fondo: '#FFFFFF', colorTexto: '#172033', titulo: { x: 14, y: 18, w: 70, h: 30, pt: 40, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 14, y: 59, w: 70, h: 24, pt: 17, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'mensaje-central', nombre: 'Mensaje central', categoria: 'Generales', fondo: '#4A1225', colorTexto: '#FFF7FA', titulo: { x: 10, y: 18, w: 80, h: 32, pt: 40, alineacion: 'centro', fuente: 'Trebuchet MS' }, subtitulo: { x: 16, y: 57, w: 68, h: 16, pt: 21, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'anuncio-simple', nombre: 'Anuncio simple', categoria: 'Generales', fondo: '#FFF7E8', colorTexto: '#4A321D', titulo: { x: 9, y: 12, w: 82, h: 30, pt: 38, alineacion: 'izquierda', fuente: 'Arial Black' }, subtitulo: { x: 9, y: 48, w: 74, h: 16, pt: 21, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 9, y: 70, w: 74, h: 17, pt: 17, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'conferencia', nombre: 'Conferencia', categoria: 'Generales', fondo: '#10213A', colorTexto: '#F8FAFC', titulo: { x: 8, y: 13, w: 84, h: 34, pt: 42, alineacion: 'izquierda', fuente: 'Inter' }, subtitulo: { x: 8, y: 54, w: 70, h: 15, pt: 20, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 8, y: 75, w: 70, h: 12, pt: 16, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'agenda', nombre: 'Agenda', categoria: 'Generales', fondo: '#F4F8FB', colorTexto: '#23374D', titulo: { x: 8, y: 10, w: 84, h: 25, pt: 34, alineacion: 'izquierda', fuente: 'Inter' }, cuerpo: { x: 10, y: 41, w: 78, h: 46, pt: 18, alineacion: 'izquierda', fuente: 'Inter' } },
  { id: 'anuncio-oscuro', nombre: 'Anuncio oscuro', categoria: 'Generales', fondo: '#28323F', colorTexto: '#F8FAFC', titulo: { x: 10, y: 20, w: 80, h: 34, pt: 42, alineacion: 'centro', fuente: 'Arial Black' }, subtitulo: { x: 17, y: 62, w: 66, h: 16, pt: 20, alineacion: 'centro', fuente: 'Inter' } },
  { id: 'reflexion', nombre: 'Reflexión', categoria: 'Generales', fondo: '#EEF3EA', colorTexto: '#1F3A2D', titulo: { x: 14, y: 18, w: 72, h: 31, pt: 38, alineacion: 'centro', fuente: 'Georgia' }, cuerpo: { x: 17, y: 57, w: 66, h: 28, pt: 18, alineacion: 'centro', fuente: 'Georgia' } },
]
