'use client'

import { Fragment, useState } from 'react'
import { Lightbulb } from 'lucide-react'

type RuleTopic = { id:string; step:number; label:string; technical:string; symbol:string; title:string; what:string; how:string; example?:string; exampleEs?:string; caution?:string; tip?:string }

const TOPICS: readonly RuleTopic[] = [
 {id:'sheva',step:1,label:'Dos puntos abajo',technical:'Sheva',symbol:'◌ְ',title:'Sheva · dos puntos debajo',what:'Busca dos puntitos verticales debajo de una letra. Ese signo se llama sheva: ◌ְ.',how:'A veces representa una vocal muy breve y otras veces indica que no hay vocal. Primero aprende a verlo; después aprenderás a distinguir sus dos funciones.',example:'שְׁמַע',exampleEs:'En שְׁמַע, los dos puntos están debajo de la primera letra. Se lee shemá.',caution:'No pronuncies todos los sheva igual. Su función depende de la palabra y de la sílaba.',tip:'Para encontrarlo, no mires dentro de la letra: mira justo debajo.'},
 {id:'dagesh',step:2,label:'Punto dentro',technical:'Dagesh',symbol:'בּ',title:'Dagesh · un punto dentro',what:'Cuando veas un punto dentro de una consonante, como en בּ, ese punto puede ser un dagesh.',how:'Para comenzar, compara la misma letra con y sin punto. En la pronunciación pedagógica del curso: בּ = b y ב = v; כּ = k y כ = j/kh; פּ = p y פ = f.',example:'בּ · ב   כּ · כ   פּ · פ',exampleEs:'La clave visual es comparar la letra con punto y sin punto.',caution:'Existen distintas funciones del dagesh. En esta etapa primero debes reconocerlo visualmente y notar los contrastes básicos.',tip:'Punto dentro = detente y comprueba si cambia la lectura.'},
 {id:'shin-sin',step:3,label:'Punto arriba',technical:'Shin / Sin',symbol:'שׁ · שׂ',title:'Shin y Sin · mira el punto de arriba',what:'שׁ y שׂ tienen la misma forma básica. Lo que cambia es el lado donde aparece el punto superior.',how:'Punto arriba a la derecha: שׁ = sh. Punto arriba a la izquierda: שׂ = s.',example:'שׁ = sh   ·   שׂ = s',tip:'Antes de leer ש, mira primero el punto superior.'},
 {id:'syllables',step:4,label:'Unir sonidos',technical:'Sílabas',symbol:'בָּ + רָ',title:'Sílabas · unir letra y vocal',what:'No intentes leer una palabra completa de golpe. Primero forma pequeños bloques de consonante + vocal.',how:'Reconoce la letra, mira el signo vocálico y pronuncia ese bloque. Luego une los bloques.',example:'בָּ + רָ + א',exampleEs:'ba · ra → bará',tip:'Primero lento y correcto. La velocidad llega después.'},
 {id:'matres',step:5,label:'Letras de apoyo',technical:'Matres',symbol:'א ה ו י',title:'Letras que ayudan a leer vocales',what:'Alef א, He ה, Vav ו y Yod י son consonantes, pero en ciertos contextos también ayudan a representar una vocal.',how:'No las aprendas como cuatro vocales nuevas. Aprende a reconocer cuándo una de estas letras está ayudando a leer la vocal de una palabra.',example:'אוֹר · תּוֹרָה · שִׁיר',caution:'Su función depende del contexto ortográfico.'},
 {id:'article',step:6,label:'El / la',technical:'Artículo',symbol:'הַ',title:'Artículo · el, la, los, las',what:'El hebreo puede pegar el artículo al comienzo de la palabra. La forma básica que aprenderás primero es הַ.',how:'Cuando veas הַ al inicio, sepáralo mentalmente de la palabra que sigue.',example:'הַדָּבָר',exampleEs:'ha-davár · la palabra / la cosa',caution:'Con algunas consonantes la vocalización puede cambiar. Primero domina el patrón básico.'},
 {id:'prefixes',step:7,label:'Piezas al inicio',technical:'Prefijos',symbol:'בְּ לְ כְּ וְ',title:'Prefijos · piezas pegadas al inicio',what:'Algunas palabras pequeñas no aparecen separadas: se pegan al comienzo de otra palabra.',how:'בְּ suele aportar en/con; לְ a/para; כְּ como; וְ normalmente conecta con y. Primero reconoce la pieza y después la palabra base.',example:'בְּרֵאשִׁית · לְאִישׁ',exampleEs:'en el principio · a/para un hombre',tip:'Lee por capas: pieza inicial → palabra base.'},
 {id:'gender',step:8,label:'Masculino / femenino',technical:'Género',symbol:'טוֹב · טוֹבָה',title:'Género · masculino y femenino',what:'El hebreo distingue género gramatical. Algunas terminaciones ayudan a reconocer muchas formas femeninas.',how:'Una terminación como ־ָה puede ser una pista de femenino. Compárala dentro de palabras completas.',example:'טוֹב · טוֹבָה',exampleEs:'tov · tová · bueno / buena',caution:'Es una pista frecuente, no una regla sin excepciones.'},
 {id:'number',step:9,label:'Singular / plural',technical:'Número',symbol:'־ִים · ־וֹת',title:'Número · singular y plural',what:'Muchas palabras muestran el plural mediante terminaciones que puedes aprender a reconocer visualmente.',how:'־ִים aparece frecuentemente en masculino plural y ־וֹת en femenino plural.',example:'טוֹבִים · טוֹבוֹת',exampleEs:'tovím · tovót',caution:'Hay excepciones de género y terminación.'},
 {id:'suffixes',step:10,label:'Piezas al final',technical:'Sufijos',symbol:'…־ךָ · …־וֹ',title:'Sufijos · piezas pegadas al final',what:'Un sufijo es una pequeña pieza que se añade al final de una palabra.',how:'Puede indicar persona, género, número u otra relación. Primero identifica la palabra base y después mira qué se añadió.',caution:'La forma de la palabra base puede cambiar al recibir un sufijo.'},
 {id:'possession',step:11,label:'Mi / tu / su',technical:'Posesión',symbol:'…־י · …־ךָ · …־וֹ',title:'Posesión · mi, tu, su',what:'En hebreo, ideas que en español expresamos con mi, tu o su pueden aparecer pegadas al final de la palabra.',how:'Mira el final antes de buscar un pronombre separado. La terminación puede decirte de quién es algo.'},
 {id:'construct',step:12,label:'“de” entre nombres',technical:'Constructo',symbol:'בֵּית + מֶלֶךְ',title:'Constructo · relacionar dos nombres',what:'Dos nombres pueden quedar unidos para expresar una relación que en español muchas veces traducimos usando de.',how:'Lee los dos nombres como una unidad. El primero queda ligado al segundo y puede cambiar de forma.',example:'בֵּית הַמֶּלֶךְ',exampleEs:'beit ha-mélej · la casa del rey',caution:'La definitud de la cadena depende del segundo elemento.'},
 {id:'roots',step:13,label:'Familia de palabras',technical:'Raíces',symbol:'כ · ת · ב',title:'Raíces · reconocer una familia',what:'Muchas palabras hebreas se estudian como familias relacionadas con una base consonántica.',how:'Aprende a separar piezas conocidas del inicio y del final para poder reconocer mejor la base.',caution:'No inventes una raíz por parecido visual; debe verificarse léxicamente.',tip:'Desarma por capas: prefijo → base → sufijo.'},
 {id:'verbs',step:14,label:'Acciones',technical:'Verbos',symbol:'אָמַר',title:'Verbos · cómo cambia una acción',what:'Los verbos cambian de forma para comunicar persona, género, número y cómo se presenta la acción.',how:'Empieza reconociendo el verbo base y qué parte cambió. Más adelante podrás distinguir qatal, yiqtol, imperativo, participio y formas secuenciales.',example:'אָמַר · יֹאמַר · אֱמֹר',exampleEs:'amár · yomár · emór',caution:'Qatal no equivale automáticamente a pasado ni yiqtol a futuro. El contexto es decisivo.'},
 {id:'qere-ketiv',step:15,label:'Escrito / leído',technical:'Qere / Ketiv',symbol:'קְרֵי / כְּתִיב',title:'Qere / Ketiv · escrito y leído',what:'En algunos lugares del texto masorético se conserva una forma escrita y, a la vez, una tradición distinta de lectura.',how:'Ketiv = lo escrito. Qere = lo que la tradición indica leer. Conserva las dos informaciones separadas.',caution:'Una forma no debe borrarse para sustituirla por la otra.'},
 {id:'tips',step:16,label:'Consejos',technical:'Tips',symbol:'💡',title:'Consejos del curso',what:'Aquí se reúnen las ayudas prácticas dadas por el instructor, separadas de las reglas lingüísticas.',how:'Úsalas para estudiar mejor: sesiones breves, repetición, escritura manual y aplicación inmediata en palabras reales.',tip:'Practica un poco cada día y vuelve a usar lo aprendido en lectura real.'},
]

function RuleCard({topic,onClose}:{topic:RuleTopic;onClose:()=>void}) { return <article className="col-span-3 overflow-hidden rounded-[20px] bg-white text-left shadow-sm ring-1 ring-indigo-200"><div className="px-5 py-5"><div className="text-center"><p className="text-[12px] font-black uppercase tracking-[.08em] text-indigo-500">Paso {topic.step} · {topic.technical}</p><div className="mt-3 flex min-h-[104px] items-center justify-center rounded-[16px] bg-indigo-50 px-3"><span dir="rtl" className="text-[3.6rem] font-black leading-none text-indigo-700">{topic.symbol}</span></div><h3 className="mt-4 text-[1.35rem] font-black leading-tight text-slate-950">{topic.title}</h3></div><details className="mt-5 border-t border-slate-100 pt-4" open><summary className="cursor-pointer list-none text-[15px] font-black leading-snug text-slate-800">Primero: ¿qué debo reconocer?</summary><p className="mt-2.5 text-[15px] leading-[1.65] text-slate-700">{topic.what}</p></details><details className="mt-4 border-t border-slate-100 pt-4"><summary className="cursor-pointer list-none text-[15px] font-black leading-snug text-slate-800">Después: ¿cómo funciona?</summary><p className="mt-2.5 text-[15px] leading-[1.65] text-slate-700">{topic.how}</p></details>{topic.example&&<details className="mt-4 border-t border-slate-100 pt-4"><summary className="cursor-pointer list-none text-[15px] font-black text-slate-800">Ver un ejemplo</summary><p lang="he" dir="rtl" className="mt-4 text-center text-[2.6rem] font-black text-indigo-700">{topic.example}</p>{topic.exampleEs&&<p className="mt-2 text-center text-[14px] font-semibold leading-relaxed text-slate-600">{topic.exampleEs}</p>}</details>}{topic.caution&&<details className="mt-4 border-t border-slate-100 pt-4"><summary className="cursor-pointer list-none text-[15px] font-black text-slate-800">Cuando ya lo entiendas</summary><p className="mt-2.5 text-[15px] leading-[1.65] text-slate-700">{topic.caution}</p></details>}<button type="button" onClick={onClose} className="mt-5 w-full py-2 text-center text-[14px] font-black text-slate-500">Cerrar</button></div>{topic.tip&&<div className="border-t border-amber-100 bg-amber-50/70 px-5 py-4"><p className="flex items-center gap-2 text-[13px] font-black uppercase tracking-[.06em] text-amber-800"><Lightbulb className="h-4 w-4"/>Tip del curso</p><p className="mt-2 text-[14px] font-semibold leading-[1.6] text-amber-900/80">{topic.tip}</p></div>}</article> }

export default function GrammarNavigator(){ const [open,setOpen]=useState<string|null>(null); return <section aria-label="Reglas del curso" className="mx-auto max-w-3xl text-center"><p className="mx-auto max-w-md text-[14px] font-semibold leading-relaxed text-slate-600">Empieza por el 1. El nombre técnico aparece debajo; lo importante primero es reconocer qué ves.</p><div className="mt-4 grid grid-cols-3 gap-2.5">{TOPICS.map((topic,index)=>{const selected=open===topic.id; const endOfRow=(index%3===2)||(index===TOPICS.length-1); const rowHasOpen=endOfRow&&open&&TOPICS.slice(index-(index%3),index+1).some(item=>item.id===open); return <Fragment key={topic.id}><button type="button" onClick={()=>setOpen(current=>current===topic.id?null:topic.id)} aria-expanded={selected} className={`flex min-h-[122px] flex-col items-center justify-center rounded-[18px] px-2 py-3 text-center transition active:scale-[.98] ${selected?'bg-indigo-600 text-white shadow-[0_8px_20px_rgba(79,70,229,.18)]':'bg-white text-slate-800 shadow-sm ring-1 ring-slate-200/80'}`}><span className={`text-[12px] font-black ${selected?'text-indigo-100':'text-indigo-500'}`}>{topic.step}</span><span dir="rtl" className={`mt-1.5 block max-w-full text-[1.85rem] font-black leading-none ${selected?'text-white':'text-indigo-700'}`}>{topic.symbol}</span><span className="mt-2 text-[13px] font-black leading-[1.15]">{topic.label}</span><span className={`mt-1 text-[11px] font-bold leading-tight ${selected?'text-indigo-100':'text-slate-500'}`}>{topic.technical}</span></button>{rowHasOpen&&<RuleCard topic={TOPICS.find(item=>item.id===open)!} onClose={()=>setOpen(null)}/>}</Fragment>})}</div></section> }
