'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Accessibility, ArrowLeft, BookOpenText, ChevronDown, ChevronRight, ExternalLink, History, PlayCircle, Sparkles, X } from 'lucide-react'
import AlefBetExplorer from '@/components/hebreo/AlefBetExplorer'
import { HEBREW_SUPPORT_COURSE } from '@/lib/hebreo/material-apoyo'

type SectionId = 'alef-bet' | 'vowels' | 'reading' | 'vocabulary' | 'grammar' | 'review'
type LearningSection = { id: SectionId; he: string; short: string; description: string; available: boolean }

const SECTIONS: readonly LearningSection[] = [
  { id: 'alef-bet', he: 'אָלֶף־בֵּית', short: 'Letras', description: 'Reconoce las 22 letras y sus formas.', available: true },
  { id: 'vowels', he: 'תְּנוּעוֹת', short: 'Vocales', description: 'Une signos vocálicos y consonantes.', available: false },
  { id: 'reading', he: 'קְרִיאָה', short: 'Lectura', description: 'Pasa de sílabas a palabras.', available: false },
  { id: 'vocabulary', he: 'מִלִּים', short: 'Palabras', description: 'Construye vocabulario bíblico.', available: false },
  { id: 'grammar', he: 'דִּקְדּוּק', short: 'Reglas', description: 'Comprende patrones esenciales.', available: false },
  { id: 'review', he: 'חֲזָרָה', short: 'Repaso', description: 'Refuerza lo que cuesta más.', available: false },
]

function LearningButton({ section, active, onClick }: { section: LearningSection; active: boolean; onClick: () => void }) {
  return <button type="button" aria-pressed={active} aria-controls={`hebrew-panel-${section.id}`} onClick={onClick} className="relative min-h-[104px] px-2 py-2 text-center transition-transform duration-200 active:scale-[0.97] motion-reduce:transition-none"><span aria-hidden="true" className={`absolute inset-x-2 inset-y-1 rounded-[18px] border shadow-[0_7px_20px_rgba(15,23,42,0.06)] ${active ? 'border-indigo-600 bg-indigo-600' : 'border-[#ded8c9] bg-[#fffdfa]'}`}><span className={`absolute -left-1.5 bottom-2 top-2 w-3 rounded-full border ${active ? 'border-indigo-500 bg-indigo-500' : 'border-[#ded8c9] bg-[#f4efe3]'}`} /><span className={`absolute -right-1.5 bottom-2 top-2 w-3 rounded-full border ${active ? 'border-indigo-500 bg-indigo-500' : 'border-[#ded8c9] bg-[#f4efe3]'}`} /></span><span className="relative z-10 flex min-h-[88px] flex-col items-center justify-center px-1"><span lang="he" dir="rtl" className={`text-[1.35rem] font-black ${active ? 'text-white' : 'text-indigo-700'}`}>{section.he}</span><span className={`mt-1.5 text-[12px] font-black ${active ? 'text-white' : 'text-slate-900'}`}>{section.short}</span><span className={`mt-1 text-[9px] font-black uppercase tracking-[0.08em] ${active ? 'text-indigo-100' : section.available ? 'text-emerald-700' : 'text-slate-400'}`}>{section.available ? 'Disponible' : 'vista'}</span></span></button>
}

function ArchitecturePreview({ id }: { id: Exclude<SectionId, 'alef-bet'> }) {
  const content = {
    vowels: ['Vocales y sílabas', 'ב + ַ = בַ', 'Una vocal, una combinación y una lectura por vez.'],
    reading: ['Lectura', 'מֶלֶךְ', 'Primero con ayudas; después se reducen hasta leer por cuenta propia.'],
    vocabulary: ['Vocabulario', 'מֶלֶךְ · rey', 'Palabras para aprender; el diccionario será una herramienta separada de consulta.'],
    grammar: ['Reglas', 'הַ  ·  מ־ל־ך', 'La gramática se presentará por capas, sin comenzar con tablas extensas.'],
    review: ['Repaso', 'ב', 'Sesiones breves enfocadas en lo que realmente necesita refuerzo.'],
  } as const
  const [title, hebrew, description] = content[id]
  return <div className="border-t border-slate-200 pt-5"><p className="text-lg font-black text-slate-950">{title}</p><p lang="he" dir="rtl" className="mt-6 text-center text-[4rem] font-black leading-none text-indigo-700">{hebrew}</p><p className="mt-5 text-sm leading-relaxed text-slate-600">{description}</p><p className="mt-5 border-t border-slate-200 pt-4 text-[12px] leading-relaxed text-slate-500">Vista de arquitectura del Bloque 1. Todavía no guarda actividad ni desbloquea contenido.</p></div>
}

function ProcessTestPreview({ onClose }: { onClose: () => void }) {
  const [step, setStep] = useState(0)
  const [finished, setFinished] = useState(false)
  const questions = [
    { type: 'Reconocer', prompt: '¿Cuál de estas letras es Bet?', options: ['ב', 'כ', 'פ'] },
    { type: 'Distinguir', prompt: 'Selecciona la letra diferente.', options: ['ד', 'ד', 'ר'] },
    { type: 'Lectura', prompt: '¿Qué palabra estás viendo?', hebrew: 'מֶלֶךְ', options: ['Rey', 'Casa', 'Paz'] },
  ] as const
  const current = questions[step]

  if (finished) return <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[0_18px_46px_rgba(15,23,42,0.10)]" aria-labelledby="resultado-prueba-title"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.12em] text-indigo-700">Ficha de resultado · ejemplo</p><h3 id="resultado-prueba-title" className="mt-1 text-2xl font-black text-slate-950">Vas construyendo una buena base</h3></div><button type="button" onClick={onClose} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-slate-100" aria-label="Cerrar resultado"><X className="h-5 w-5" /></button></div><div className="mt-6 divide-y divide-slate-200 border-y border-slate-200"><div className="py-4"><p className="text-[11px] font-black uppercase tracking-[0.1em] text-slate-400">Lo que ya reconoces</p><p className="mt-1 text-sm font-bold text-slate-800">Letras básicas y diferencias visuales claras.</p></div><div className="py-4"><p className="text-[11px] font-black uppercase tracking-[0.1em] text-slate-400">Conviene reforzar</p><p className="mt-1 text-sm font-bold text-slate-800">Letras parecidas y lectura sin transliteración.</p></div></div><div className="mt-5 rounded-[20px] bg-indigo-50 p-4"><p className="text-[11px] font-black uppercase tracking-[0.1em] text-indigo-700">Consejo de estudio</p><p className="mt-2 text-sm font-semibold leading-relaxed text-slate-800">Vas bien. Antes de añadir más contenido, dedica unos minutos a distinguir las letras que se parecen. Cuando las reconozcas sin detenerte, vuelve a probar tu proceso.</p></div><div className="mt-5 flex items-center gap-3 border-t border-slate-200 pt-4 text-[12px] text-slate-500"><History className="h-4 w-4 shrink-0" /><p>En la versión funcional, esta ficha se guardará en tu historial para comparar evaluaciones anteriores.</p></div></section>

  return <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[0_18px_46px_rgba(15,23,42,0.10)]" aria-labelledby="prueba-title"><div className="flex items-center justify-between"><p className="text-[11px] font-black uppercase tracking-[0.1em] text-slate-400">Paso {step + 1} de {questions.length}</p><button type="button" onClick={onClose} className="grid h-11 w-11 place-items-center rounded-full bg-slate-100" aria-label="Cerrar prueba"><X className="h-5 w-5" /></button></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600 transition-[width] motion-reduce:transition-none" style={{ width: `${((step + 1) / questions.length) * 100}%` }} /></div><p className="mt-7 text-[10px] font-black uppercase tracking-[0.12em] text-indigo-700">{current.type}</p><h3 id="prueba-title" className="mt-2 text-xl font-black leading-snug text-slate-950">{current.prompt}</h3>{'hebrew' in current && <p lang="he" dir="rtl" className="my-8 text-center text-[5rem] font-black leading-none text-slate-950">{current.hebrew}</p>}<div className="mt-6 grid gap-3">{current.options.map((option, index) => <button key={`${option}-${index}`} type="button" onClick={() => step < questions.length - 1 ? setStep(value => value + 1) : setFinished(true)} className={`min-h-14 rounded-[18px] border border-slate-200 bg-white px-5 font-black text-slate-800 active:bg-slate-50 ${current.type !== 'Lectura' ? 'text-[2rem]' : 'text-base'}`}>{option}</button>)}</div><p className="mt-5 text-[11px] leading-relaxed text-slate-400">Prototipo de recorrido: las respuestas aún no se califican ni se guardan.</p></section>
}

function SupportMaterialSection() {
  const [open, setOpen] = useState(false)
  return <section className="border-t border-slate-200 pt-5"><button type="button" onClick={() => setOpen(value => !value)} className="flex min-h-14 w-full items-center justify-between gap-4 text-left" aria-expanded={open}><div><p lang="he" dir="rtl" className="text-sm font-bold text-indigo-700">חומר עזר</p><h2 className="text-lg font-black text-slate-950">Material de apoyo</h2></div><ChevronDown className={`h-5 w-5 text-slate-400 transition-transform ${open ? 'rotate-180' : ''}`} /></button>{open && <div className="mt-4 space-y-3">{HEBREW_SUPPORT_COURSE.map(item => <article key={item.orden} className="overflow-hidden rounded-[20px] border border-slate-200 bg-white"><div className="flex gap-3 p-3"><div className="relative h-[72px] w-[112px] shrink-0 overflow-hidden rounded-[12px] bg-slate-100"><img src={item.miniatura} alt={`Miniatura del enlace de la clase ${item.orden}`} className="h-full w-full object-cover" loading="lazy" /><span className="absolute inset-0 grid place-items-center bg-slate-950/10"><PlayCircle className="h-7 w-7 text-white" /></span></div><div className="min-w-0"><p className="text-[9px] font-black uppercase tracking-[0.08em] text-amber-700">Clase {item.orden} · Pendiente</p><h3 className="mt-1 text-[13px] font-black leading-snug text-slate-900">{item.titulo}</h3><p className="mt-1 text-[11px] text-slate-500">{item.tema}</p></div></div><a href={item.url} target="_blank" rel="noopener noreferrer" className="flex min-h-11 items-center justify-between border-t border-slate-100 px-4 text-[12px] font-black text-indigo-700">Abrir video <ExternalLink className="h-3.5 w-3.5" /></a></article>)}</div>}</section>
}

export default function HebrewLearningHome() {
  const [simpleMode, setSimpleMode] = useState(false)
  const [openSection, setOpenSection] = useState<SectionId | null>(null)
  const [testOpen, setTestOpen] = useState(false)
  const activeSection = SECTIONS.find(section => section.id === openSection)

  return <main className="min-h-screen bg-[#fbfaf6] text-slate-950"><div className="mx-auto w-full max-w-5xl px-4 pb-16 pt-4 sm:px-6"><header className="mb-7"><div className="flex items-center justify-between"><Link href="/estudios" className="inline-flex min-h-11 items-center gap-2 text-sm font-black text-slate-600"><ArrowLeft className="h-5 w-5" /> Estudios</Link><button type="button" onClick={() => setSimpleMode(value => !value)} aria-pressed={simpleMode} className={`inline-flex min-h-11 items-center gap-2 rounded-full border px-4 text-sm font-black ${simpleMode ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-slate-200 bg-white text-slate-700'}`}><Accessibility className="h-4 w-4" /> Lectura</button></div><div className="mt-7"><p lang="he" dir="rtl" className="text-[1.1rem] font-bold text-indigo-700">עברית מקראית</p><h1 className="mt-1 text-[2.3rem] font-black tracking-[-0.04em]">Hebreo Bíblico</h1><p className="mt-1 text-base font-semibold text-slate-600">Aprende a leer paso a paso.</p></div></header>

  <section className="mb-8" aria-labelledby="areas-hebreo-title"><div className="flex items-end justify-between gap-3"><div><p className="text-[11px] font-black uppercase tracking-[0.12em] text-slate-400">Aprender</p><h2 id="areas-hebreo-title" className="text-xl font-black">Elige un área</h2></div><p className="text-right text-[10px] font-bold leading-tight text-slate-400">Solo Letras está activa.<br />Las demás son vistas.</p></div><div className="mt-4 grid grid-cols-3 gap-x-2 gap-y-3">{SECTIONS.map(section => <LearningButton key={section.id} section={section} active={openSection === section.id} onClick={() => setOpenSection(current => current === section.id ? null : section.id)} />)}</div>{activeSection && <section id={`hebrew-panel-${activeSection.id}`} className="mt-6"><div className="mb-4 flex items-center justify-between"><div><p lang="he" dir="rtl" className="text-sm font-bold text-indigo-700">{activeSection.he}</p><h3 className="text-xl font-black">{activeSection.short}</h3></div><button type="button" onClick={() => setOpenSection(null)} className="grid h-11 w-11 place-items-center rounded-full bg-slate-100" aria-label="Cerrar área"><X className="h-5 w-5" /></button></div>{activeSection.id === 'alef-bet' ? <AlefBetExplorer simpleMode={simpleMode} /> : <ArchitecturePreview id={activeSection.id} />}</section>}</section>

  <section className="mb-8 border-y border-slate-200 py-5" aria-labelledby="proceso-title"><div className="flex items-center justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[0.12em] text-indigo-700">Comprobar lo aprendido</p><h2 id="proceso-title" className="mt-0.5 text-xl font-black">¡Prueba tu proceso!</h2><p className="mt-1 max-w-sm text-[12px] leading-relaxed text-slate-500">Preguntas breves, una por una. Al terminar recibirás una ficha con fortalezas y qué conviene reforzar.</p></div><Sparkles className="h-7 w-7 shrink-0 text-indigo-600" /></div><button type="button" onClick={() => setTestOpen(true)} className="mt-4 flex min-h-14 w-full items-center justify-between rounded-[18px] bg-indigo-600 px-5 text-left text-sm font-black text-white shadow-[0_8px_22px_rgba(79,70,229,0.20)]">Comenzar prueba <ChevronRight className="h-5 w-5" /></button>{testOpen && <div className="mt-5"><ProcessTestPreview onClose={() => setTestOpen(false)} /></div>}</section>

  <section className="mb-8" aria-labelledby="historial-title"><button type="button" className="flex min-h-14 w-full items-center justify-between gap-4 text-left"><span className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-slate-100"><History className="h-5 w-5 text-slate-600" /></span><span><span id="historial-title" className="block text-sm font-black text-slate-900">Historial de progreso</span><span className="mt-0.5 block text-[11px] text-slate-500">Aquí vivirán tus fichas de evaluaciones anteriores.</span></span></span><ChevronRight className="h-5 w-5 shrink-0 text-slate-400" /></button><p className="mt-2 pl-14 text-[10px] leading-relaxed text-slate-400">Vista de arquitectura. No existe persistencia durante Bloque 1.</p></section>

  <SupportMaterialSection /><footer className="mt-8 flex items-center gap-3 border-t border-slate-200 pt-5 text-[11px] leading-relaxed text-slate-500"><BookOpenText className="h-4 w-4 shrink-0 text-indigo-500" /><p>Bloque 1 · Recorrido en validación. Sin audio, progreso persistente ni desbloqueos automáticos.</p></footer></div></main>
}
