'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ChevronDown, RotateCcw, SlidersHorizontal } from 'lucide-react'
import { deriveProgressMetrics, HEBREW_PRACTICE_QUESTIONS, selectAdaptiveQuestions, selectDifficultyQuestions, SKILL_LABELS, SKILL_ORDER, type HebrewDifficulty, type HebrewPracticeQuestion, type HebrewProgressAnswer, type HebrewProgressSession, type HebrewSkill } from '@/lib/hebreo/progress'
import { finishHebrewProgressSession, loadHebrewProgress, saveHebrewProgressAnswer, setHebrewReviewRequested, startHebrewProgressSession } from '@/lib/hebreo/progress-store'

const DIFFICULTIES: readonly { id: HebrewDifficulty; label: string; level: string }[] = [
  { id: 'initial', label: 'Básico', level: 'Nivel 1' }, { id: 'intermediate', label: 'Intermedio', level: 'Nivel 2' }, { id: 'advanced', label: 'Avanzado', level: 'Nivel 3' },
]
const LENGTHS = [10, 15, 20] as const

export default function HebrewProgressCoach() {
  const [historyOpen, setHistoryOpen] = useState(false), [customOpen, setCustomOpen] = useState(false)
  const [mode, setMode] = useState<'adaptive' | 'difficulty'>('adaptive')
  const [difficulty, setDifficulty] = useState<HebrewDifficulty>('initial'), [questionCount, setQuestionCount] = useState<number>(15)
  const [focusAreas, setFocusAreas] = useState<HebrewSkill[]>([]), [sessions, setSessions] = useState<HebrewProgressSession[]>([]), [answers, setAnswers] = useState<HebrewProgressAnswer[]>([])
  const [questions, setQuestions] = useState<HebrewPracticeQuestion[]>([]), [sessionId, setSessionId] = useState<string | null>(null)
  const [index, setIndex] = useState(0), [correct, setCorrect] = useState(0), [selected, setSelected] = useState<number | null>(null)
  const [lastAnswer, setLastAnswer] = useState<HebrewProgressAnswer | null>(null), [finished, setFinished] = useState(false), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState<string | null>(null)
  const refresh = useCallback(async () => { try { const data = await loadHebrewProgress(); setSessions(data.sessions); setAnswers(data.answers); setError(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cargar tu progreso.') } finally { setLoading(false) } }, [])
  useEffect(() => { void refresh() }, [refresh])
  const metrics = useMemo(() => deriveProgressMetrics(sessions, answers), [sessions, answers]), current = questions[index] ?? null, active = Boolean(sessionId && current && !finished), progress = questions.length ? Math.round(((index + (selected !== null ? 1 : 0)) / questions.length) * 100) : 0, level = DIFFICULTIES.find(item => item.id === difficulty)!
  function toggleArea(skill: HebrewSkill) { if (!active) setFocusAreas(previous => previous.includes(skill) ? previous.filter(item => item !== skill) : [...previous, skill]) }
  function buildDifficultyPractice() { const primary = selectDifficultyQuestions(difficulty, focusAreas, questionCount); if (primary.length >= questionCount) return primary; const used = new Set(primary.map(question => question.key)); const compatible = HEBREW_PRACTICE_QUESTIONS.filter(question => (!focusAreas.length || focusAreas.includes(question.skill)) && !used.has(question.key)); return [...primary, ...compatible].slice(0, questionCount) }
  async function begin() { setSaving(true); setError(null); try { let nextQuestions = mode === 'adaptive' ? selectAdaptiveQuestions(answers, focusAreas, questionCount) : buildDifficultyPractice(); if (!nextQuestions.length) nextQuestions = selectAdaptiveQuestions(answers, [], questionCount); const id = await startHebrewProgressSession(mode, mode === 'difficulty' ? difficulty : null, focusAreas); setQuestions([...nextQuestions]); setSessionId(id); setIndex(0); setCorrect(0); setSelected(null); setLastAnswer(null); setFinished(false) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo iniciar la práctica.') } finally { setSaving(false) } }
  async function answer(optionIndex: number) { if (!current || !sessionId || selected !== null || saving) return; setSaving(true); setSelected(optionIndex); const isCorrect = optionIndex === current.correctIndex; try { const saved = await saveHebrewProgressAnswer({ sessionId, questionKey: current.key, questionVersion: current.version, skill: current.skill, difficulty: current.difficulty, responseText: current.options[optionIndex], isCorrect }); setLastAnswer(saved); setAnswers(previous => [saved, ...previous]); if (isCorrect) setCorrect(value => value + 1); setError(null) } catch (cause) { setSelected(null); setError(cause instanceof Error ? cause.message : 'No se pudo guardar esta respuesta.') } finally { setSaving(false) } }
  async function toggleReview() { if (!lastAnswer || saving) return; setSaving(true); try { const nextValue = !lastAnswer.review_requested; await setHebrewReviewRequested(lastAnswer.id, nextValue); const updated = { ...lastAnswer, review_requested: nextValue }; setLastAnswer(updated); setAnswers(previous => previous.map(row => row.id === updated.id ? updated : row)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo actualizar el repaso.') } finally { setSaving(false) } }
  async function next() { if (selected === null || !sessionId) return; if (index + 1 < questions.length) { setIndex(value => value + 1); setSelected(null); setLastAnswer(null); return } setSaving(true); try { await finishHebrewProgressSession(sessionId); setFinished(true); setSelected(null); setLastAnswer(null); await refresh() } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cerrar la sesión.') } finally { setSaving(false) } }
  function resetPractice() { setSessionId(null); setQuestions([]); setIndex(0); setCorrect(0); setSelected(null); setLastAnswer(null); setFinished(false) }
  return <div className="mt-3 text-left">
    {!active && !finished && <><div className="rounded-[18px] bg-indigo-50/70 px-4 py-3"><p className="text-[13px] font-black text-slate-900">Descubre cómo va tu hebreo</p><p className="mt-1 text-[11px] leading-relaxed text-slate-500">Mide lo que ya reconoces, detecta qué necesitas reforzar y deja que las próximas prácticas se adapten a tus respuestas.</p><div className="mt-3 rounded-[14px] bg-white px-3 py-2 ring-1 ring-indigo-100"><span className="block text-[9px] font-black uppercase tracking-[0.1em] text-slate-400">Tu nivel de práctica</span><span className="block text-[13px] font-black text-indigo-700">{mode === 'adaptive' ? 'Adaptativo · según tu historial' : `${level.level} · ${level.label}`}</span></div></div>
      <p className="mt-4 text-[10px] font-black uppercase tracking-[0.1em] text-slate-400">¿Cómo quieres practicar?</p><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={() => setMode('adaptive')} className={`min-h-12 rounded-[16px] border px-3 text-[12px] font-black ${mode === 'adaptive' ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-slate-200 bg-white text-slate-600'}`}>Según mi progreso</button><button type="button" onClick={() => setMode('difficulty')} className={`min-h-12 rounded-[16px] border px-3 text-[12px] font-black ${mode === 'difficulty' ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-slate-200 bg-white text-slate-600'}`}>Elegir nivel</button></div>
      {mode === 'difficulty' && <div className="mt-3 grid grid-cols-3 gap-2">{DIFFICULTIES.map(item => <button key={item.id} type="button" onClick={() => setDifficulty(item.id)} className={`min-h-[52px] rounded-[16px] border px-1 ${difficulty === item.id ? 'border-indigo-300 bg-indigo-50 text-indigo-800' : 'border-slate-200 bg-white text-slate-500'}`}><span className="block text-[9px] font-black uppercase">{item.level}</span><span className="block text-[11px] font-black">{item.label}</span></button>)}</div>}
      <div className="mt-3 overflow-hidden rounded-[18px] border border-slate-200 bg-white"><button type="button" onClick={() => setCustomOpen(value => !value)} aria-expanded={customOpen} className="flex min-h-[52px] w-full items-center justify-between gap-3 px-4 text-left"><span className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4 text-indigo-600" /><span><span className="block text-[12px] font-black text-slate-800">Personalizar práctica</span><span className="block text-[9px] text-slate-400">Duración y áreas que quieres reforzar</span></span></span><ChevronDown className={`h-4 w-4 text-slate-400 transition-transform ${customOpen ? 'rotate-180' : ''}`} /></button>{customOpen && <div className="border-t border-slate-100 px-4 pb-4 pt-3"><p className="text-[10px] font-black uppercase tracking-[0.1em] text-slate-400">Cantidad de preguntas</p><div className="mt-2 grid grid-cols-3 gap-2">{LENGTHS.map(length => <button key={length} type="button" onClick={() => setQuestionCount(length)} className={`min-h-10 rounded-full border text-[11px] font-black ${questionCount === length ? 'border-indigo-300 bg-indigo-50 text-indigo-800' : 'border-slate-200 text-slate-500'}`}>{length}</button>)}</div><p className="mt-4 text-[10px] font-black uppercase tracking-[0.1em] text-slate-400">Áreas que quieres reforzar</p><div className="mt-2 flex flex-wrap gap-2">{SKILL_ORDER.map(skill => <button key={skill} type="button" aria-pressed={focusAreas.includes(skill)} onClick={() => toggleArea(skill)} className={`min-h-9 rounded-full border px-3 text-[10px] font-black ${focusAreas.includes(skill) ? 'border-indigo-300 bg-indigo-50 text-indigo-800' : 'border-slate-200 bg-white text-slate-500'}`}>{SKILL_LABELS[skill]}</button>)}</div><p className="mt-2 text-[10px] leading-relaxed text-slate-400">Si eliges pocas áreas, usamos todas las preguntas disponibles de esas áreas sin inventar contenido.</p></div>}</div>
      {mode === 'adaptive' && <div className="mt-3 rounded-[16px] bg-slate-50 px-4 py-3"><p className="text-[9px] font-black uppercase tracking-[0.1em] text-indigo-700">Qué conviene estudiar ahora</p><p className="mt-1 text-[11px] font-semibold leading-relaxed text-slate-600">{metrics.recommendation}</p></div>}<button type="button" onClick={() => void begin()} disabled={saving || loading} className="mt-4 min-h-12 w-full rounded-full bg-indigo-600 px-5 text-sm font-black text-white disabled:opacity-50">{saving ? 'Preparando…' : `Comenzar · ${questionCount} preguntas`}</button></>}
    {active && current && <><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.1em] text-indigo-700">{current.type} · {SKILL_LABELS[current.skill]}</p><p className="text-[11px] font-bold text-slate-400">Pregunta {index + 1} de {questions.length}</p></div><div className="text-right"><p className="text-lg font-black">{correct}</p><p className="text-[9px] font-black uppercase text-slate-400">Aciertos</p></div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600 transition-all" style={{ width: `${progress}%` }} /></div><div className="py-6 text-center"><p className="text-[1.08rem] font-black">{current.prompt}</p>{current.hebrew && <p lang="he" dir="rtl" className="mt-5 text-[3.6rem] font-black text-indigo-700">{current.hebrew}</p>}</div><div className="grid grid-cols-3 gap-2">{current.options.map((option, optionIndex) => { const chosen = selected === optionIndex, correctOption = selected !== null && current.correctIndex === optionIndex; return <button key={`${current.key}-${option}`} type="button" disabled={selected !== null || saving} onClick={() => void answer(optionIndex)} className={`min-h-[4.5rem] rounded-[16px] border px-2 py-3 text-lg font-black ${correctOption ? 'border-emerald-300 bg-emerald-50 text-emerald-800' : chosen ? 'border-rose-300 bg-rose-50 text-rose-800' : 'border-slate-200 bg-white text-slate-800'}`}>{option}</button> })}</div>{selected !== null && <div className="mt-4 border-t border-slate-200 pt-4"><p className={`text-sm font-black ${selected === current.correctIndex ? 'text-emerald-700' : 'text-rose-700'}`}>{selected === current.correctIndex ? 'Correcto' : 'Necesita repaso'}</p><p className="mt-1 text-[12px] font-semibold text-slate-500">{current.explanation}</p><button type="button" disabled={!lastAnswer || saving} onClick={() => void toggleReview()} className={`mt-3 min-h-10 rounded-full border px-4 text-[11px] font-black ${lastAnswer?.review_requested ? 'border-amber-300 bg-amber-50 text-amber-800' : 'border-slate-200 bg-white text-slate-600'}`}>{lastAnswer?.review_requested ? 'Marcado para repasar' : 'Quiero repasar'}</button><button type="button" onClick={() => void next()} disabled={saving || !lastAnswer} className="mt-3 min-h-12 w-full rounded-full bg-indigo-600 text-sm font-black text-white">{index + 1 === questions.length ? 'Terminar práctica' : 'Siguiente'}</button></div>}</>}
    {finished && <div className="text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600" /><h3 className="mt-2 text-xl font-black">Práctica terminada</h3><p className="mt-1 text-[12px] text-slate-500">Tus respuestas quedaron guardadas y ya forman parte de tu siguiente práctica adaptativa.</p><div className="mt-4 grid grid-cols-2 divide-x divide-slate-200 border-y border-slate-200 py-4"><div><p className="text-2xl font-black text-indigo-700">{questions.length ? Math.round((correct / questions.length) * 100) : 0}%</p><p className="text-[10px] font-black text-slate-500">Precisión</p></div><div><p className="text-2xl font-black">{correct}/{questions.length}</p><p className="text-[10px] font-black text-slate-500">Aciertos</p></div></div><button type="button" onClick={resetPractice} className="mt-4 inline-flex min-h-12 items-center gap-2 rounded-full bg-indigo-600 px-6 text-sm font-black text-white"><RotateCcw className="h-4 w-4" />Nueva práctica</button></div>}
    {error && <p role="alert" className="mt-3 text-center text-[11px] font-bold text-rose-600">{error}</p>}
    {!active && <div className="mt-5 border-t border-slate-200 pt-1"><button type="button" onClick={() => setHistoryOpen(value => !value)} aria-expanded={historyOpen} className="flex min-h-12 w-full items-center justify-between gap-3 text-left"><span><span className="block text-[10px] font-black uppercase tracking-[0.1em] text-slate-400">Tu historial</span><span className="block text-sm font-black">{sessions.filter(item => item.status === 'completed').length} sesiones completadas</span></span><ChevronDown className={`h-4 w-4 text-slate-400 ${historyOpen ? 'rotate-180' : ''}`} /></button>{historyOpen && <div className="border-t border-slate-200 py-4">{metrics.totalAttempts === 0 ? <p className="text-[12px] text-slate-500">Todavía no hay intentos objetivos. Completa una práctica para crear tu primera línea base.</p> : <><div className="grid grid-cols-3 divide-x divide-slate-200 border-y border-slate-200 py-3 text-center"><div><p className="text-xl font-black text-indigo-700">{metrics.accuracy ?? 0}%</p><p className="text-[9px] text-slate-400">Precisión</p></div><div><p className="text-xl font-black">{metrics.retention === null ? '—' : `${metrics.retention}%`}</p><p className="text-[9px] text-slate-400">Retención</p></div><div><p className="text-sm font-black">{metrics.trend}</p><p className="text-[9px] text-slate-400">Tendencia</p></div></div><div className="mt-4 space-y-2">{metrics.areas.filter(area => area.attempts > 0).map(area => <div key={area.skill} className="flex items-center justify-between rounded-[14px] bg-slate-50 px-3 py-2"><span><span className="block text-[11px] font-black">{SKILL_LABELS[area.skill]}</span><span className="text-[9px] text-slate-400">{area.correct}/{area.attempts} correctas</span></span><span className="text-[10px] font-black text-indigo-700">{area.state}</span></div>)}</div>{metrics.evolution !== null && <p className="mt-3 text-[11px] text-slate-500">Evolución: {metrics.evolution > 0 ? '+' : ''}{metrics.evolution} puntos.</p>}<div className="mt-4 rounded-[16px] bg-indigo-50 px-4 py-3"><p className="text-[9px] font-black uppercase text-indigo-700">Qué estudiar después</p><p className="mt-1 text-[11px] font-semibold text-slate-600">{metrics.recommendation}</p></div></>}</div>}</div>}
  </div>
}
