'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Accessibility, ArrowLeft, BookOpenText, ChevronDown, ExternalLink, PlayCircle } from 'lucide-react'
import AlefBetExplorer from '@/components/hebreo/AlefBetExplorer'
import { HEBREW_SUPPORT_COURSE } from '@/lib/hebreo/material-apoyo'

type SectionId = 'alef-bet' | 'vowels' | 'reading' | 'vocabulary' | 'grammar' | 'review'
type LearningSection = { id: SectionId; he: string; es: string; short: string; description: string; available: boolean }

const SECTIONS: readonly LearningSection[] = [
  { id: 'alef-bet', he: 'אָלֶף־בֵּית', es: 'Alef-bet', short: 'Letras', description: 'Reconoce las 22 letras, sus nombres, sonidos y formas especiales.', available: true },
  { id: 'vowels', he: 'תְּנוּעוֹת', es: 'Vocales y sílabas', short: 'Vocales', description: 'Aprende los signos vocálicos y cómo se unen con las consonantes.', available: false },
  { id: 'reading', he: 'קְרִיאָה', es: 'Lectura', short: 'Lectura', description: 'Pasa de sílabas a palabras y frases breves.', available: false },
  { id: 'vocabulary', he: 'מִלִּים', es: 'Vocabulario', short: 'Palabras', description: 'Aprende palabras frecuentes sin cargar la pantalla de definiciones.', available: false },
  { id: 'grammar', he: 'דִּקְדּוּק', es: 'Gramática', short: 'Reglas', description: 'Comprende reglas esenciales por capas y con ejemplos cortos.', available: false },
  { id: 'review', he: 'חֲזָרָה', es: 'Repaso', short: 'Repaso', description: 'Refuerza lo que necesite más práctica en sesiones breves.', available: false },
]

function FlowPreview() {
  return <section className="mb-8" aria-labelledby="flujo-hebreo-title"><p className="text-[11px] font-black uppercase tracking-[0.12em] text-slate-400">Cómo vas a avanzar</p><h2 id="flujo-hebreo-title" className="mt-0.5 text-xl font-black tracking-[-0.02em] text-slate-950">De reconocer a comprender</h2><div className="-mx-4 mt-3 overflow-x-auto px-4 pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><div className="flex min-w-max items-center gap-2">{['Reconozco', 'Distingo', 'Combino', 'Leo', 'Comprendo'].map((item, index) => <span key={item} className="flex items-center gap-2"><span className={`inline-flex min-h-11 items-center rounded-full border px-4 text-sm font-black ${index === 0 ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-slate-200 bg-white text-slate-700'}`}>{item}</span>{index < 4 && <span className="text-slate-300" aria-hidden="true">→</span>}</span>)}</div></div><p className="mt-2 text-[12px] leading-relaxed text-slate-500">Esta secuencia muestra la lógica general del curso. No representa progreso guardado todavía.</p></section>
}

function ProgressArchitecturePreview() {
  const areas = [['Letras', 'Fuerte', 'Reconoces la mayoría; conviene distinguir Bet y Kaf.'], ['Vocales', 'En proceso', 'Pataj está claro; Shewa todavía necesita práctica.'], ['Lectura', 'Por reforzar', 'Lees con nikud, pero aún dependes de algunas ayudas.']] as const
  return <section className="mb-8 border-y border-slate-200 py-6" aria-labelledby="progreso-hebreo-title"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[0.12em] text-indigo-700">Vista de diseño</p><h2 id="progreso-hebreo-title" className="mt-0.5 text-xl font-black tracking-[-0.02em] text-slate-950">Tu aprendizaje</h2><p className="mt-1 max-w-sm text-[13px] leading-relaxed text-slate-500">No medirá cuánto abriste, sino qué puedes reconocer, recordar, leer y comprender.</p></div><span className="shrink-0 rounded-full border border-slate-200 bg-white px-2.5 py-1.5 text-[10px] font-black text-slate-500">Diseño</span></div><div className="mt-5 divide-y divide-slate-200 border-y border-slate-200">{areas.map(([name, state, detail]) => <div key={name} className="py-4"><div className="flex items-center justify-between gap-4"><p className="text-sm font-black text-slate-900">{name}</p><p className="text-[12px] font-black text-indigo-700">{state}</p></div><p className="mt-1 text-[12px] leading-relaxed text-slate-500">{detail}</p></div>)}</div><div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-4"><div><p className="text-[11px] font-black uppercase tracking-[0.1em] text-slate-400">Palabras</p><p className="mt-1 text-lg font-black text-slate-950">Aprendidas · en práctica</p><p className="mt-1 text-[12px] text-slate-500">Los números aparecerán solo cuando existan datos reales.</p></div><div><p className="text-[11px] font-black uppercase tracking-[0.1em] text-slate-400">Enfoque sugerido</p><p className="mt-1 text-lg font-black text-slate-950">Confusiones visuales</p><p className="mt-1 text-[12px] text-slate-500">El sistema propondrá qué practicar según errores reales.</p></div></div></section>
}

function AssessmentArchitecturePreview() {
  const challenges = [['Reconocer', '¿Cuál de estas letras es Bet?', 'ב', 'כ', 'פ'], ['Distinguir', 'Encuentra la forma diferente.', 'ד', 'ר', 'ד'], ['Leer', 'Lee sin transliteración.', 'מֶלֶךְ', '—', '—']] as const
  return <section className="mb-8" aria-labelledby="evaluacion-hebreo-title"><p className="text-[11px] font-black uppercase tracking-[0.12em] text-slate-400">Evaluación continua</p><h2 id="evaluacion-hebreo-title" className="mt-0.5 text-xl font-black tracking-[-0.02em] text-slate-950">Practicar también mide</h2><p className="mt-1 text-[13px] leading-relaxed text-slate-500">Los retos serán breves y variados. Cada respuesta futura ayudará a descubrir fortalezas y puntos que conviene reforzar.</p><div className="-mx-4 mt-4 overflow-x-auto px-4 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><div className="flex min-w-max gap-3">{challenges.map(([kind, prompt, a, b, c]) => <article key={kind} className="w-[265px] rounded-[22px] border border-slate-200 bg-white p-4 shadow-[0_8px_24px_rgba(15,23,42,0.05)]"><p className="text-[10px] font-black uppercase tracking-[0.12em] text-indigo-700">{kind}</p><p className="mt-2 min-h-10 text-sm font-black leading-snug text-slate-900">{prompt}</p><div dir="rtl" className="mt-4 flex min-h-16 items-center justify-center gap-3 border-y border-slate-100 py-3">{[a, b, c].filter(item => item !== '—').map((item, index) => <span key={`${item}-${index}`} lang="he" className="min-w-14 text-center text-[2.35rem] font-black text-slate-950">{item}</span>)}</div><p className="mt-3 text-[11px] leading-relaxed text-slate-500">Ejemplo visual; no registra respuestas durante Bloque 1.</p></article>)}</div></div><div className="mt-3 flex items-center justify-between gap-4 border-y border-slate-200 py-4"><div><p className="text-sm font-black text-slate-900">Diagnóstico</p><p className="mt-0.5 text-[12px] leading-relaxed text-slate-500">Permitirá estimar desde dónde empezar sin cerrar la exploración libre.</p></div><span className="shrink-0 text-[11px] font-black text-slate-400">Futuro</span></div></section>
}

function VowelsArchitecturePreview() { return <div className="border-t border-slate-200 pt-5"><p className="text-sm font-black text-slate-900">Una vocal, una combinación, una lectura.</p><p className="mt-1 text-sm leading-relaxed text-slate-600">La pantalla enseñará una sola idea antes de pedir combinar signos.</p><div className="mt-6 flex items-end justify-between gap-4"><div><p className="text-[12px] font-black uppercase tracking-[0.1em] text-slate-400">Pataj</p><p lang="he" dir="rtl" className="mt-2 text-[5.5rem] font-medium leading-none text-indigo-700">ַ</p><p className="mt-3 text-base font-bold text-slate-700">Sonido parecido a “a”.</p></div><div className="min-w-[150px] text-right"><p className="text-[12px] font-black uppercase tracking-[0.1em] text-slate-400">Combina</p><p lang="he" dir="rtl" className="mt-3 text-[2.6rem] font-black leading-none text-slate-950">ב + ַ = בַ</p><p className="mt-3 text-lg font-black text-indigo-700">ba</p></div></div><p className="mt-6 border-t border-slate-200 pt-4 text-[12px] leading-relaxed text-slate-500">El sonido puede variar ligeramente según la tradición de pronunciación. Audio se añadirá únicamente cuando exista una fuente aprobada.</p></div> }
function ReadingArchitecturePreview() { return <div className="border-t border-slate-200 pt-5"><p className="text-sm font-black text-slate-900">De partes pequeñas a una palabra completa.</p><p className="mt-1 text-sm leading-relaxed text-slate-600">Primero se reconoce la forma; después se reducen las ayudas.</p><div className="mt-7 text-center"><p lang="he" dir="rtl" className="text-[4.6rem] font-black leading-none text-slate-950">מֶלֶךְ</p><p className="mt-4 text-lg font-black text-indigo-700">mélej</p><p className="mt-1 text-base font-bold text-slate-700">rey</p></div><div className="mt-6 grid grid-cols-3 gap-2 border-t border-slate-200 pt-4 text-center">{['Con nikud', 'Con ayuda', 'Sin ayuda'].map((item, index) => <div key={item} className="py-2"><p className="text-[11px] font-black uppercase tracking-[0.08em] text-slate-400">Paso {index + 1}</p><p className="mt-1 text-sm font-black text-slate-800">{item}</p></div>)}</div></div> }
function VocabularyArchitecturePreview() { return <div className="border-t border-slate-200 pt-5"><p className="text-sm font-black text-slate-900">Palabras que ya puedes reconocer al leer.</p><p className="mt-1 text-sm leading-relaxed text-slate-600">Vocabulario será aprendizaje progresivo; el diccionario será una herramienta separada de consulta.</p><div className="mt-7"><p lang="he" dir="rtl" className="text-[4.4rem] font-black leading-none text-slate-950">מֶלֶךְ</p><div className="mt-4 flex items-end justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="text-[12px] font-black uppercase tracking-[0.1em] text-slate-400">Significado</p><p className="mt-1 text-xl font-black text-slate-900">Rey</p></div><div className="text-right"><p className="text-[12px] font-black uppercase tracking-[0.1em] text-slate-400">Categoría</p><p className="mt-1 text-sm font-bold text-slate-700">Persona / título</p></div></div><p className="mt-4 text-[12px] leading-relaxed text-slate-500">La transliteración será ayuda opcional y no sustituirá aprender a leer las letras.</p></div></div> }
function GrammarArchitecturePreview() { return <div className="border-t border-slate-200 pt-5"><p className="text-sm font-black text-slate-900">Reglas por capas, no tablas de golpe.</p><p className="mt-1 text-sm leading-relaxed text-slate-600">La primera vista muestra solo lo necesario para entender una estructura.</p><div className="mt-6 divide-y divide-slate-200 border-y border-slate-200"><div className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-black text-slate-900">Artículo definido</p><p className="mt-0.5 text-[12px] text-slate-500">Una pieza pequeña que cambia cómo lees la palabra.</p></div><p lang="he" dir="rtl" className="text-[2.6rem] font-black text-indigo-700">הַ</p></div><div className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-black text-slate-900">Raíz</p><p className="mt-0.5 text-[12px] text-slate-500">Reconoce consonantes relacionadas antes de entrar en detalles.</p></div><p lang="he" dir="rtl" className="text-[2rem] font-black text-slate-950">מ־ל־ך</p></div></div><button type="button" className="mt-4 min-h-11 text-sm font-black text-indigo-700" aria-label="Vista de diseño de detalles gramaticales">Ver cómo se ampliarán los detalles</button></div> }
function ReviewArchitecturePreview() { return <div className="border-t border-slate-200 pt-5"><p className="text-sm font-black text-slate-900">Repasos cortos y sin presión.</p><p className="mt-1 text-sm leading-relaxed text-slate-600">Más adelante cada respuesta ayudará a decidir qué conviene volver a practicar.</p><div className="mt-7 text-center"><p className="text-[12px] font-black uppercase tracking-[0.1em] text-slate-400">Ejemplo de repaso</p><p lang="he" dir="rtl" className="mt-3 text-[6.5rem] font-medium leading-none text-slate-950">ב</p><p className="mt-3 text-sm font-bold text-slate-600">¿Reconoces esta letra?</p></div><div className="mt-6 grid gap-2">{['Lo sé', 'Necesito practicar', 'Repasar después'].map(item => <div key={item} className="flex min-h-12 items-center justify-center rounded-[16px] border border-slate-200 bg-white px-4 text-sm font-black text-slate-700">{item}</div>)}</div><p className="mt-3 text-[12px] leading-relaxed text-slate-500">Esta vista no guarda resultados ni calcula dominio durante Bloque 1.</p></div> }
function ArchitecturePreview({ section }: { section: LearningSection }) { if (section.id === 'vowels') return <VowelsArchitecturePreview />; if (section.id === 'reading') return <ReadingArchitecturePreview />; if (section.id === 'vocabulary') return <VocabularyArchitecturePreview />; if (section.id === 'grammar') return <GrammarArchitecturePreview />; return <ReviewArchitecturePreview /> }
function StagePanel({ section, simpleMode }: { section: LearningSection; simpleMode: boolean }) { return <section id={`hebrew-panel-${section.id}`} aria-live="polite" className="mt-6"><div className="mb-5 flex items-start justify-between gap-4"><div className="min-w-0"><p lang="he" dir="rtl" className="text-[15px] font-bold text-indigo-700">{section.he}</p><h2 className="mt-0.5 text-[1.55rem] font-black tracking-[-0.025em] text-slate-950">{section.es}</h2><p className="mt-1 max-w-xl text-[13px] leading-relaxed text-slate-500">{section.description}</p></div>{!section.available && <span className="inline-flex shrink-0 items-center rounded-full border border-slate-200 bg-white px-2.5 py-1.5 text-[10px] font-black text-slate-500">Diseño</span>}</div>{section.id === 'alef-bet' ? <AlefBetExplorer simpleMode={simpleMode} /> : <ArchitecturePreview section={section} />}</section> }
function LearningScrollButton({ section, active, onClick }: { section: LearningSection; active: boolean; onClick: () => void }) { return <button type="button" aria-pressed={active} aria-controls={`hebrew-panel-${section.id}`} onClick={onClick} className="relative min-h-[108px] px-2 py-2 text-center transition-transform duration-200 active:scale-[0.97] motion-reduce:transition-none"><span aria-hidden="true" className={`absolute inset-x-2 inset-y-1 rounded-[18px] border shadow-[0_7px_20px_rgba(15,23,42,0.06)] transition-colors ${active ? 'border-indigo-600 bg-indigo-600' : 'border-[#ded8c9] bg-[#fffdfa]'}`}><span className={`absolute -left-1.5 bottom-2 top-2 w-3 rounded-full border ${active ? 'border-indigo-500 bg-indigo-500' : 'border-[#ded8c9] bg-[#f4efe3]'}`} /><span className={`absolute -right-1.5 bottom-2 top-2 w-3 rounded-full border ${active ? 'border-indigo-500 bg-indigo-500' : 'border-[#ded8c9] bg-[#f4efe3]'}`} /></span><span className="relative z-10 flex min-h-[92px] flex-col items-center justify-center px-1"><span lang="he" dir="rtl" className={`block text-[1.35rem] font-black leading-tight ${active ? 'text-white' : 'text-indigo-700'}`}>{section.he}</span><span className={`mt-1.5 block text-[12px] font-black leading-tight ${active ? 'text-white' : 'text-slate-900'}`}>{section.short}</span><span className={`mt-1 block text-[9px] font-black uppercase tracking-[0.08em] ${active ? 'text-indigo-100' : section.available ? 'text-emerald-700' : 'text-slate-400'}`}>{section.available ? 'Disponible' : 'vista'}</span></span></button> }

function SupportMaterialSection() {
  const [open, setOpen] = useState(false)
  const verificationLabel = (status: 'pendiente' | 'verificado' | 'corregir') => status === 'verificado' ? 'Verificado' : status === 'corregir' ? 'Revisar enlace' : 'Pendiente'
  return <section className="mt-10 border-t border-slate-200 pt-6"><button type="button" onClick={() => setOpen(value => !value)} className="flex min-h-12 w-full items-center justify-between gap-4 text-left" aria-expanded={open}><div><p lang="he" dir="rtl" className="text-sm font-bold text-indigo-700">חומר עזר</p><h2 className="text-xl font-black tracking-[-0.02em] text-slate-950">Material de apoyo</h2><p className="mt-1 text-[12px] leading-relaxed text-slate-500">Curso externo complementario. No sustituye las fuentes ni la metodología de VIDA.</p></div><ChevronDown className={`h-5 w-5 shrink-0 text-slate-400 transition-transform ${open ? 'rotate-180' : ''}`} aria-hidden="true" /></button>{open && <div className="mt-5 space-y-3">{HEBREW_SUPPORT_COURSE.map(item => <article key={item.orden} className="overflow-hidden rounded-[20px] border border-slate-200 bg-white"><div className="flex gap-3 p-3"><div className="relative h-[78px] w-[122px] shrink-0 overflow-hidden rounded-[13px] bg-slate-100"><img src={item.miniatura} alt={`Miniatura del enlace de la clase ${item.orden}`} className="h-full w-full object-cover" loading="lazy" /><span className="absolute inset-0 grid place-items-center bg-slate-950/10"><PlayCircle className="h-8 w-8 text-white drop-shadow" aria-hidden="true" /></span></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-black uppercase tracking-[0.08em] text-slate-400">Clase {item.orden}</span><span className="text-[9px] font-black uppercase tracking-[0.08em] text-amber-700">{verificationLabel(item.verificacion)}</span></div><h3 className="mt-1 text-[13px] font-black leading-snug text-slate-900">{item.titulo}</h3><p className="mt-1 text-[11px] leading-snug text-slate-500">{item.tema}</p></div></div><a href={item.url} target="_blank" rel="noopener noreferrer" className="flex min-h-11 items-center justify-between border-t border-slate-100 px-4 text-[12px] font-black text-indigo-700">Abrir video en YouTube <ExternalLink className="h-3.5 w-3.5" aria-hidden="true" /></a></article>)}<p className="pt-2 text-[11px] leading-relaxed text-slate-500">Hasta corroborarlos visualmente, los 11 enlaces permanecen en estado pendiente y no se reemplaza ninguno de forma automática.</p></div>}</section>
}

export default function HebrewLearningHome() {
  const [simpleMode, setSimpleMode] = useState(false)
  const [openSection, setOpenSection] = useState<SectionId | null>('alef-bet')
  const activeSection = SECTIONS.find(section => section.id === openSection) ?? null
  return <main className="min-h-screen bg-[#fbfaf6] text-slate-950"><div className="mx-auto w-full max-w-5xl px-4 pb-16 pt-4 sm:px-6 sm:pt-6"><header className="mb-7"><div className="flex items-center justify-between gap-3"><Link href="/estudios" className="inline-flex min-h-11 items-center gap-2 rounded-full px-1 text-sm font-black text-slate-600"><ArrowLeft className="h-5 w-5" aria-hidden="true" /> Estudios</Link><button type="button" onClick={() => setSimpleMode(value => !value)} aria-pressed={simpleMode} className={`inline-flex min-h-11 items-center gap-2 rounded-full border px-4 text-sm font-black transition-colors ${simpleMode ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-slate-200 bg-white text-slate-700'}`}><Accessibility className="h-4 w-4" aria-hidden="true" /> Lectura</button></div><div className="mt-8 max-w-2xl"><p lang="he" dir="rtl" className="text-[1.15rem] font-bold text-indigo-700">עברית מקראית</p><h1 className="mt-1 text-[2.35rem] font-black tracking-[-0.04em] text-slate-950 sm:text-5xl">Hebreo Bíblico</h1><p className="mt-2 text-base font-semibold text-slate-600 sm:text-lg">Aprende a leer paso a paso.</p></div></header><FlowPreview /><ProgressArchitecturePreview /><AssessmentArchitecturePreview /><section aria-labelledby="areas-hebreo-title"><div className="flex items-end justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[0.12em] text-slate-400">Explorar</p><h2 id="areas-hebreo-title" className="mt-0.5 text-xl font-black tracking-[-0.02em] text-slate-950">Áreas de aprendizaje</h2></div><p className="text-right text-[11px] font-bold leading-tight text-slate-400">Alef-bet es el contenido activo.<br />Las demás vistas son de diseño.</p></div><div className="mt-4 grid grid-cols-3 gap-x-2 gap-y-3">{SECTIONS.map(section => <LearningScrollButton key={section.id} section={section} active={openSection === section.id} onClick={() => setOpenSection(current => current === section.id ? null : section.id)} />)}</div>{activeSection && <StagePanel section={activeSection} simpleMode={simpleMode} />}</section><SupportMaterialSection /><footer className="mt-10 flex items-center gap-3 border-t border-slate-200 pt-5 text-[11px] leading-relaxed text-slate-500"><BookOpenText className="h-4 w-4 shrink-0 text-indigo-500" aria-hidden="true" /><p>Bloque 1 · Arquitectura didáctica en validación. Sin audio, progreso persistente ni desbloqueos automáticos.</p></footer></div></main>
}
