'use client'

import { type FormEvent, useEffect, useState } from 'react'
import { ChevronDown, ChevronLeft, ChevronRight, Grid2X2, List, Search, X } from 'lucide-react'
import { HEBREW_LEARNING_GROUPS, type HebrewLearningGroupId } from '@/lib/hebreo/word-learning'

type ReadingMode = 'nikud' | 'plain'
type WordView = 'list' | 'cards'
type CatalogWord = { lexicalId:string; lemma:string; spanish:string|null; pronunciation:string|null; meaningNoteEs:string|null }
type CatalogResponse = { status:'ok'|'sin-sesion'|'no-disponible'; page:number; pageSize:number; total:number; totalPages:number; search:string; group:HebrewLearningGroupId; items:CatalogWord[] }
type DictionaryResponse = { status:'ok'; query:string; total:number; items:CatalogWord[] }

const PAGE_SIZE=60
const EMPTY_RESULT:CatalogResponse={status:'ok',page:1,pageSize:PAGE_SIZE,total:0,totalPages:0,search:'',group:'essentials',items:[]}
const HEBREW_MARKS=/[\u0591-\u05BD\u05BF\u05C1\u05C2\u05C4\u05C5\u05C7]/g
const HEBREW_LETTER=/[\u05D0-\u05EA]/
const LETTER_NAMES:Record<string,string>={א:'Alef',ב:'Bet',ג:'Guímel',ד:'Dálet',ה:'He',ו:'Vav',ז:'Zayin',ח:'Jet',ט:'Tet',י:'Yod',כ:'Kaf',ך:'Kaf final',ל:'Lamed',מ:'Mem',ם:'Mem final',נ:'Nun',ן:'Nun final',ס:'Sámej',ע:'Ayin',פ:'Pe',ף:'Pe final',צ:'Tsadi',ץ:'Tsadi final',ק:'Qof',ר:'Resh',ש:'Shin / Sin',ת:'Tav'}
const MARK_NAMES:Record<string,string>={'\u05B0':'Sheva','\u05B1':'Hataf Segol','\u05B2':'Hataf Pataj','\u05B3':'Hataf Qamats','\u05B4':'Hiriq','\u05B5':'Tsere','\u05B6':'Segol','\u05B7':'Pataj','\u05B8':'Qamats','\u05B9':'Holam','\u05BB':'Qubuts','\u05BC':'Dagesh','\u05C1':'punto de Shin','\u05C2':'punto de Sin','\u05C7':'Qamats qatan'}

function withoutNiqqud(value:string){return value.normalize('NFD').replace(HEBREW_MARKS,'').normalize('NFC')}
function formationParts(value:string){const parts:string[]=[];for(const char of Array.from(value.normalize('NFD'))){if(LETTER_NAMES[char])parts.push(`${char} ${LETTER_NAMES[char]}`);else if(MARK_NAMES[char])parts.push(MARK_NAMES[char])}return parts}
function pronunciationFromHebrew(value:string){const clusters:{letter:string;marks:string[]}[]=[];for(const char of Array.from(value.normalize('NFD'))){if(HEBREW_LETTER.test(char))clusters.push({letter:char,marks:[]});else if(clusters.length&&MARK_NAMES[char])clusters[clusters.length-1].marks.push(char)}return clusters.map((cluster,index)=>{const{letter,marks}=cluster;const has=(m:string)=>marks.includes(m);const last=index===clusters.length-1;if(letter==='ו'&&has('\u05BC')&&!marks.some(m=>['\u05B0','\u05B1','\u05B2','\u05B3','\u05B4','\u05B5','\u05B6','\u05B7','\u05B8','\u05B9','\u05BB','\u05C7'].includes(m)))return'u';if(letter==='ו'&&has('\u05B9'))return'o';let c='';switch(letter){case'א':case'ע':c='';break;case'ב':c=has('\u05BC')?'b':'v';break;case'ג':c='g';break;case'ד':c='d';break;case'ה':c=last&&marks.length===0?'':'h';break;case'ו':c='v';break;case'ז':c='z';break;case'ח':c='j';break;case'ט':c='t';break;case'י':c='y';break;case'כ':case'ך':c=has('\u05BC')?'k':'j';break;case'ל':c='l';break;case'מ':case'ם':c='m';break;case'נ':case'ן':c='n';break;case'ס':c='s';break;case'פ':case'ף':c=has('\u05BC')?'p':'f';break;case'צ':case'ץ':c='ts';break;case'ק':c='k';break;case'ר':c='r';break;case'ש':c=has('\u05C2')?'s':'sh';break;case'ת':c='t';break}let v='';if(has('\u05B4'))v='i';else if(has('\u05B5')||has('\u05B6')||has('\u05B1'))v='e';else if(has('\u05B7')||has('\u05B8')||has('\u05B2'))v='a';else if(has('\u05C7')||has('\u05B3')||has('\u05B9'))v='o';else if(has('\u05BB'))v='u';else if(has('\u05B0')&&!last)v='e';return c+v}).join('').replace(/yy/g,'y')}
function pronunciationFor(word:CatalogWord){return word.pronunciation??(word.lemma.match(HEBREW_MARKS)?pronunciationFromHebrew(word.lemma):null)??'—'}
function splitMeanings(value:string|null){return(value??'').split(/\s*[·;,/]\s*/).map(item=>item.trim()).filter(Boolean)}
function aggregateWords(words:CatalogWord[]){const grouped=new Map<string,CatalogWord&{meanings:string[]}>();for(const word of words){const key=word.lemma.normalize('NFC');const current=grouped.get(key);const meanings=splitMeanings(word.spanish);if(!current){grouped.set(key,{...word,meanings:[...new Set(meanings)]});continue}for(const meaning of meanings){if(!current.meanings.some(item=>item.toLocaleLowerCase('es')===meaning.toLocaleLowerCase('es')))current.meanings.push(meaning)}if(!current.pronunciation&&word.pronunciation)current.pronunciation=word.pronunciation;if(!current.meaningNoteEs&&word.meaningNoteEs)current.meaningNoteEs=word.meaningNoteEs}return Array.from(grouped.values()).map(({meanings,...word})=>({...word,spanish:meanings.length?meanings.join(' · '):word.spanish}))}
function WordText({word,mode,className}:{word:CatalogWord;mode:ReadingMode;className:string}){return <span lang="he" dir="rtl" className={className}>{mode==='nikud'?word.lemma:withoutNiqqud(word.lemma)}</span>}

function LearningDetail({word,onClose}:{word:CatalogWord;onClose:()=>void}){
  const[mode,setMode]=useState<ReadingMode>('nikud')
  useEffect(()=>setMode('nikud'),[word.lexicalId])
  const meanings=splitMeanings(word.spanish);const formation=formationParts(word.lemma);const pronunciation=pronunciationFor(word)
  return <article className="mt-3 overflow-hidden rounded-[28px] border border-indigo-100 bg-white shadow-[0_18px_50px_rgba(15,23,42,0.10)]">
    <div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><span className="text-[11px] font-black uppercase tracking-[0.12em] text-indigo-600">Estudiar palabra</span><button type="button" onClick={onClose} aria-label="Cerrar palabra" className="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-slate-500"><X className="h-4 w-4"/></button></div>
    <div className="p-5 text-center">
      <WordText word={word} mode={mode} className="block break-words text-[4.8rem] font-black leading-[1.15] text-slate-950"/>
      <p className="mt-2 text-[1.05rem] font-black text-indigo-700">{pronunciation}</p>
      <div className="mt-3 flex flex-wrap justify-center gap-1.5">{meanings.map(meaning=><span key={meaning} className="rounded-full bg-slate-100 px-3 py-1.5 text-[13px] font-black text-slate-800">{meaning}</span>)}</div>
      <button type="button" onClick={()=>setMode(current=>current==='nikud'?'plain':'nikud')} className={`mt-5 min-h-10 rounded-full px-4 text-[12px] font-black ${mode==='nikud'?'bg-indigo-600 text-white':'bg-indigo-50 text-indigo-700'}`}>{mode==='nikud'?'Ocultar niqqud':'Mostrar niqqud'}</button>
      <p className="mt-2 text-[11px] text-slate-400">El cambio afecta únicamente esta palabra abierta.</p>
      <div className="mt-5 divide-y divide-slate-200 border-y border-slate-200 text-left">
        <div className="py-3.5"><p className="text-[10px] font-black uppercase text-slate-400">Cómo se pronuncia</p><p className="mt-1 text-[15px] font-black text-slate-800">{pronunciation}</p></div>
        <div className="py-3.5"><p className="text-[10px] font-black uppercase text-slate-400">Qué significa</p><p className="mt-1 text-[14px] font-bold leading-relaxed text-slate-800">{word.meaningNoteEs??(meanings.length?`Puede significar: ${meanings.join(', ')}.`:'Sin significado español disponible.')}</p></div>
        <div className="py-3.5"><p className="text-[10px] font-black uppercase text-slate-400">Cómo se forma</p><p className="mt-1 text-[13px] leading-relaxed text-slate-700">{formation.length?formation.join(' + '):'Esta entrada todavía no aporta desglose de niqqud.'}</p></div>
      </div>
    </div>
  </article>
}

function PrimaryList({words,selectedId,onToggle}:{words:CatalogWord[];selectedId:string|null;onToggle:(word:CatalogWord)=>void}){
  return <div className="overflow-hidden rounded-[24px] border border-slate-200 bg-white">{words.map((word,index)=>{const selected=selectedId===word.lexicalId;const meanings=splitMeanings(word.spanish);return <div key={word.lexicalId} className={index?'border-t border-slate-100':''}>
    <button type="button" onClick={()=>onToggle(word)} className="flex min-h-[104px] w-full items-center justify-between gap-4 px-4 py-3 text-left active:bg-slate-50">
      <div className="min-w-0 flex-1"><WordText word={word} mode="nikud" className="block text-[3rem] font-black leading-[1.05] text-slate-950"/><p className="mt-1 text-[13px] font-black text-indigo-700">{pronunciationFor(word)}</p></div>
      <div className="max-w-[46%] text-right"><p className="text-[14px] font-black leading-snug text-slate-800">{meanings.length?meanings.join(' · '):'—'}</p><p className="mt-1 text-[10px] font-bold text-slate-400">{selected?'Cerrar':'Tocar para estudiar'}</p></div>
    </button>
    {selected&&<div className="px-3 pb-3"><LearningDetail word={word} onClose={()=>onToggle(word)}/></div>}
  </div>})}</div>
}

function CardsView({words,selectedId,onToggle}:{words:CatalogWord[];selectedId:string|null;onToggle:(word:CatalogWord)=>void}){
  return <div className="grid grid-cols-2 gap-3">{words.map(word=>{const meanings=splitMeanings(word.spanish);return <button key={word.lexicalId} type="button" onClick={()=>onToggle(word)} className="min-h-[160px] rounded-[24px] border border-slate-200 bg-white p-3 text-center active:scale-[0.985]"><WordText word={word} mode="nikud" className="block break-words text-[3.15rem] font-black leading-tight text-slate-950"/><span className="mt-2 block text-[13px] font-black text-indigo-700">{pronunciationFor(word)}</span><span className="mt-1 block text-[13px] font-black leading-snug text-slate-800">{meanings.length?meanings.join(' · '):'—'}</span></button>})}{selectedId&&words.find(word=>word.lexicalId===selectedId)&&<div className="col-span-2"><LearningDetail word={words.find(word=>word.lexicalId===selectedId)!} onClose={()=>onToggle(words.find(word=>word.lexicalId===selectedId)!)}/></div>}</div>
}

function WordsIntroduction(){const[open,setOpen]=useState(false);return <section className="border-y border-slate-200"><button type="button" onClick={()=>setOpen(value=>!value)} className="flex min-h-12 w-full items-center justify-between py-2 text-left"><span><span lang="he" dir="rtl" className="block text-[12px] font-black text-indigo-700">מִלִּים</span><span className="block text-sm font-black text-slate-950">Diccionario para aprender</span></span><ChevronDown className={`h-4 w-4 text-slate-400 transition ${open?'rotate-180':''}`}/></button>{open&&<div className="border-t border-slate-200 py-4 text-[13px] leading-relaxed text-slate-600"><p>La vista principal organiza el vocabulario en listas temáticas. Cada palabra aparece con niqqud para aprender su lectura.</p><p className="mt-2">Toca una palabra para abrir su ficha de estudio. Solo dentro de esa ficha puedes ocultar o volver a mostrar el niqqud.</p></div>}</section>}

export default function ReadingWordsExplorer(){
  const[view,setView]=useState<WordView>('list');const[group,setGroup]=useState<HebrewLearningGroupId>('essentials');const[page,setPage]=useState(1);const[result,setResult]=useState<CatalogResponse>(EMPTY_RESULT);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[searchInput,setSearchInput]=useState('');const[searching,setSearching]=useState(false);const[searchResult,setSearchResult]=useState<DictionaryResponse|null>(null);const[selectedId,setSelectedId]=useState<string|null>(null)
  const activeGroup=HEBREW_LEARNING_GROUPS.find(item=>item.id===group)??HEBREW_LEARNING_GROUPS[0]
  useEffect(()=>{let active=true;const controller=new AbortController();setLoading(true);setError(null);fetch(`/api/estudios/hebreo/palabras?page=${page}&pageSize=${PAGE_SIZE}&group=${group}`,{cache:'no-store',signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(response.status===401?'Tu sesión necesita renovarse.':'No se pudo cargar el catálogo.');const data=await response.json() as CatalogResponse;data.items=aggregateWords(data.items);if(active){setResult(data);setSelectedId(null)}}).catch(cause=>{if(active&&!controller.signal.aborted)setError(cause instanceof Error?cause.message:'No se pudo cargar el catálogo.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false;controller.abort()}},[page,group])
  function changeGroup(next:HebrewLearningGroupId){if(next===group)return;setGroup(next);setPage(1);setSearchResult(null);setSearchInput('');setSelectedId(null)}
  function toggleWord(word:CatalogWord){setSelectedId(current=>current===word.lexicalId?null:word.lexicalId)}
  async function submitSearch(event:FormEvent<HTMLFormElement>){event.preventDefault();const query=searchInput.trim();if(!query){setSearchResult(null);return}setSearching(true);setError(null);setSelectedId(null);try{const response=await fetch(`/api/estudios/hebreo/diccionario?q=${encodeURIComponent(query)}`,{cache:'no-store'});if(!response.ok)throw new Error('No se pudo consultar el diccionario.');const data=await response.json() as DictionaryResponse;data.items=aggregateWords(data.items);setSearchResult(data)}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo consultar el diccionario.')}finally{setSearching(false)}}
  function clearSearch(){setSearchInput('');setSearchResult(null);setSelectedId(null)}
  const visibleWords=searchResult?searchResult.items:result.items;const noResults=Boolean(searchResult&&searchResult.total===0);const needsPagination=!searchResult&&result.totalPages>1
  return <section aria-labelledby="reading-words-title" className="text-left">
    <div className="text-center"><p lang="he" dir="rtl" className="text-[1.25rem] font-black text-indigo-700">מִלִּים</p><h2 id="reading-words-title" className="text-[1.65rem] font-black text-slate-950">Palabras</h2><p className="mt-1 text-[13px] text-slate-500">Aprende por grupos, una palabra a la vez.</p></div>
    <div className="mt-5"><WordsIntroduction/></div>
    <div className="mt-4 grid grid-cols-2 gap-1 rounded-[17px] bg-slate-100 p-1"><button type="button" onClick={()=>{setView('list');setSelectedId(null)}} className={`flex min-h-10 items-center justify-center gap-2 rounded-[14px] text-[12px] font-black ${view==='list'?'bg-white text-indigo-700 shadow-sm':'text-slate-500'}`}><List className="h-4 w-4"/>Lista</button><button type="button" onClick={()=>{setView('cards');setSelectedId(null)}} className={`flex min-h-10 items-center justify-center gap-2 rounded-[14px] text-[12px] font-black ${view==='cards'?'bg-white text-indigo-700 shadow-sm':'text-slate-500'}`}><Grid2X2 className="h-4 w-4"/>Tarjetas</button></div>
    <div className="-mx-4 mt-4 overflow-x-auto px-4 pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><div className="flex min-w-max gap-2">{HEBREW_LEARNING_GROUPS.map(item=><button key={item.id} type="button" onClick={()=>changeGroup(item.id)} className={`min-h-11 rounded-full border px-4 text-[12px] font-black ${group===item.id?'border-indigo-600 bg-indigo-600 text-white':'border-slate-200 bg-white text-slate-600'}`}>{item.label}</button>)}</div></div>
    <div className="mt-3 rounded-[18px] bg-indigo-50/70 px-4 py-3"><p className="text-[13px] font-black text-indigo-950">{activeGroup.label}</p><p className="mt-0.5 text-[11px] leading-relaxed text-indigo-700/80">{activeGroup.description}</p></div>
    <form onSubmit={submitSearch} className="mt-4 flex min-h-11 items-center gap-2 rounded-[17px] border border-slate-200 bg-white px-3"><Search className="h-4 w-4 text-slate-400"/><input value={searchInput} onChange={event=>setSearchInput(event.target.value)} placeholder="Buscar gato, casa, שלום…" className="min-w-0 flex-1 bg-transparent py-2 text-[13px] outline-none"/><button type="submit" disabled={!searchInput.trim()||searching} className="text-[11px] font-black text-indigo-700 disabled:opacity-40">{searching?'Buscando…':'Buscar'}</button></form>
    <div className="mt-3 flex items-center justify-between text-[11px] text-slate-500"><span>{searchResult?`${visibleWords.length} palabras encontradas`:(loading?'Cargando palabras…':`${result.total.toLocaleString('es-SV')} entradas`)}</span>{searchResult&&<button type="button" onClick={clearSearch} className="font-black text-indigo-700">Volver al grupo</button>}</div>
    {error&&<div className="mt-4 rounded-[18px] bg-amber-50 p-4 text-center text-[12px] text-amber-900">{error}</div>}
    {noResults&&<div className="mt-5 border-y border-dashed border-slate-300 py-9 text-center"><p className="text-sm font-black text-slate-700">No encontramos esa palabra en el diccionario.</p><p className="mt-1 text-[11px] text-slate-400">Puedes usar el Traductor para una palabra o frase que todavía no esté indexada.</p></div>}
    {!error&&!noResults&&visibleWords.length>0&&<div className="mt-5">{view==='list'?<PrimaryList words={visibleWords} selectedId={selectedId} onToggle={toggleWord}/>:<CardsView words={visibleWords} selectedId={selectedId} onToggle={toggleWord}/>}</div>}
    {needsPagination&&<div className="mt-5 flex items-center justify-between gap-3 border-t border-slate-200 pt-4"><button type="button" disabled={page<=1||loading} onClick={()=>setPage(value=>Math.max(1,value-1))} className="flex min-h-10 items-center gap-1 rounded-full border bg-white px-3 text-[11px] font-black disabled:opacity-30"><ChevronLeft className="h-4 w-4"/>Anterior</button><p className="text-center text-[10px] font-black text-slate-500">{page} de {result.totalPages}</p><button type="button" disabled={page>=result.totalPages||loading} onClick={()=>setPage(value=>Math.min(result.totalPages,value+1))} className="flex min-h-10 items-center gap-1 rounded-full border bg-white px-3 text-[11px] font-black disabled:opacity-30">Siguiente<ChevronRight className="h-4 w-4"/></button></div>}
    {!error&&!searchResult&&!loading&&result.items.length===0&&<div className="mt-5 border-y border-dashed border-slate-300 py-9 text-center text-sm text-slate-500">Este grupo todavía no tiene palabras clasificadas.</div>}
  </section>
}
