const ENTITY_TRANSLATIONS: Record<string, string> = {
  Adam: 'Adán', Eve: 'Eva', Seth: 'Set', Enos: 'Enós', Cainan: 'Cainán', Enoch: 'Enoc',
  Methuselah: 'Matusalén', Lamech: 'Lamec', Noah: 'Noé', Shem: 'Sem', Arphaxad: 'Arfaxad',
  Salah: 'Sala', Eber: 'Heber', Reu: 'Reú', Nahor: 'Nacor', Terah: 'Taré', Ishmael: 'Ismael',
  Esau: 'Esaú', Reuben: 'Rubén', Simeon: 'Simeón', Levi: 'Leví', Judah: 'Judá', Naphtali: 'Neftalí',
  Asher: 'Aser', Issachar: 'Isacar', Zebulon: 'Zabulón', Dinah: 'Dina', Joseph: 'José', Moses: 'Moisés',
  Joshua: 'Josué', Othniel: 'Otoniel', 'Cushan-rishathaim': 'Cusan-risataim', Eglon: 'Eglón', Jabin: 'Jabín',
  Ehud: 'Aod', Deborah: 'Débora', Midian: 'Madián', Gideon: 'Gedeón', Abimelech: 'Abimelec',
  Jephthah: 'Jefté', Ibzan: 'Ibzán', Elon: 'Elón', Abdon: 'Abdón', Philistia: 'Filistea', Samson: 'Sansón',
  Sampson: 'Sansón', Eli: 'Elí', Saul: 'Saúl', Solomon: 'Salomón', Rehoboam: 'Roboam', Jeroboam: 'Jeroboam',
  Abijam: 'Abiam', Baasha: 'Baasa', Elah: 'Ela', Ahab: 'Acab', Elijah: 'Elías', Jehoshaphat: 'Josafat',
  Ahaziah: 'Ocozías', Jehoram: 'Joram', Elisha: 'Eliseo', Jehu: 'Jehú', Athaliah: 'Atalía', Joash: 'Joás',
  Jehoahaz: 'Joacaz', Jehoash: 'Joás', Jehoahash: 'Joás', Amaziah: 'Amasías', Uzziah: 'Uzías',
  Zachariah: 'Zacarías', Shallum: 'Salum', Menahem: 'Manahem', Pekahiah: 'Pekaía', Pekah: 'Peka',
  Jotham: 'Jotam', Ahaz: 'Acaz', Hoshea: 'Oseas', Hezekiah: 'Ezequías', Manasseh: 'Manasés', Amon: 'Amón',
  Josiah: 'Josías', Johoahaz: 'Joacaz', Jehoiakim: 'Joacim', Jeconiah: 'Jeconías', Zedekiah: 'Sedequías',
  Isaiah: 'Isaías', Jeremiah: 'Jeremías', Ezekiel: 'Ezequiel', Hosea: 'Oseas', Obadiah: 'Abdías', Jonah: 'Jonás',
  Micah: 'Miqueas', Nahum: 'Nahúm', Habakkuk: 'Habacuc', Zephaniah: 'Sofonías', Haggai: 'Hageo',
  Zechariah: 'Zacarías', Malachi: 'Malaquías', Mary: 'María', Jesus: 'Jesús', Herod: 'Herodes',
  'John the Baptist': 'Juan el Bautista', John: 'Juan', Peter: 'Pedro', Matthew: 'Mateo', Martha: 'Marta',
  Lazarus: 'Lázaro', Nicodemus: 'Nicodemo', Zaccheus: 'Zaqueo', Judas: 'Judas', Matthias: 'Matías',
  Stephen: 'Esteban', Philip: 'Felipe', Cornelius: 'Cornelio', Barnabas: 'Bernabé', Timothy: 'Timoteo',
  Lydia: 'Lidia', Eutychus: 'Eutico', Felix: 'Félix', Festus: 'Festo', Agrippa: 'Agripa', Bernice: 'Berenice',
  Paul: 'Pablo', Galilee: 'Galilea', Canaan: 'Canaán', Egypt: 'Egipto', Jerusalem: 'Jerusalén',
  Nazareth: 'Nazaret', Bethlehem: 'Belén', Samaria: 'Samaria', Caesarea: 'Cesarea', Ephesus: 'Éfeso',
  Athens: 'Atenas', Corinth: 'Corinto', Macedonia: 'Macedonia', Rome: 'Roma', Malta: 'Malta', Cyprus: 'Chipre',
  'Antioch in Pisidia': 'Antioquía de Pisidia', 'Antioch in Syria': 'Antioquía de Siria', Iconium: 'Iconio',
  Lystra: 'Listra', Derbe: 'Derbe', Berea: 'Berea', Perea: 'Perea', Ephraim: 'Efraín', Gethsemane: 'Getsemaní',
  Golgotha: 'Gólgota', Capernaum: 'Capernaúm', Gennesaret: 'Genesaret', Bethsaida: 'Betsaida', Chorazin: 'Corazín',
}

const EXACT: Record<string, string> = {
  'Creation of all things': 'Creación de todas las cosas',
  'Creation of Adam and Eve': 'Creación de Adán y Eva',
  'The Fall': 'La caída',
  'Cain kills Abel': 'Caín mata a Abel',
  'God curses Cain': 'Dios maldice a Caín',
  'Enoch taken up': 'Enoc es llevado por Dios',
  'God decides to destroy every living thing': 'Dios decide destruir todo ser viviente',
  'God instructs Noah to build the ark': 'Dios instruye a Noé para construir el arca',
  'The Great Flood begins': 'Comienza el gran diluvio',
  'The Great Flood': 'El gran diluvio',
  'Water covers the earth': 'Las aguas cubren la tierra',
  'The flood subsides': 'Las aguas del diluvio descienden',
  'Leaving the Ark': 'Salida del arca',
  'God makes a covenant with Noah': 'Dios hace pacto con Noé',
  'Noah gets drunk and Canaan is cursed': 'Noé se embriaga y Canaán es maldecido',
  "Nimrod's kingdom begins": 'Comienza el reino de Nimrod',
  'Tower of Babel': 'Torre de Babel',
  'Abraham enters Canaan': 'Abraham entra en Canaán',
  'Abrahamic Covenant': 'Pacto con Abraham',
  'Abraham goes to Egypt': 'Abraham va a Egipto',
  'Abraham and Lot Separate': 'Abraham y Lot se separan',
  'Sodom Destroyed': 'Destrucción de Sodoma',
  'Isaac Marries Rebekah': 'Isaac se casa con Rebeca',
  'Rachel dies giving birth to Benjamin': 'Raquel muere al dar a luz a Benjamín',
  'Joseph sold to Egypt': 'José es vendido y llevado a Egipto',
  'Joseph imprisoned': 'José es encarcelado',
  'Joseph Promoted in Egypt': 'José es elevado a autoridad en Egipto',
  '7 years of plenty': 'Siete años de abundancia',
  '7 years of famine': 'Siete años de hambre',
  "Joseph's brothers go to Egypt": 'Los hermanos de José van a Egipto',
  "Joseph's brothers return to Egypt": 'Los hermanos de José regresan a Egipto',
  'Moses Flees Pharaoh': 'Moisés huye del faraón',
  'Exodus from Egypt': 'Éxodo de Egipto',
  'Sojourn in Canaan and Egypt': 'Peregrinación en Canaán y Egipto',
  'Wilderness Wanderings': 'Peregrinación por el desierto',
  'Ten Commandments Given': 'Entrega de los Diez Mandamientos',
  'Tabernacle Built': 'Construcción del tabernáculo',
  'Crossing the Jordan into Canaan': 'Cruce del Jordán hacia Canaán',
  'War with Canaanites': 'Guerra con los cananeos',
  'Dividing the land': 'Reparto de la tierra',
  'Oppression by Ammon and Philistia': 'Opresión de Amón y Filistea',
  'Philistine Dominion': 'Dominio filisteo',
  'Sampson destroys Temple of Dagon': 'Sansón destruye el templo de Dagón',
  'Death of Eli, Ark Captured': 'Muerte de Elí y captura del arca',
  'United Kingdom': 'Reino unido de Israel',
  'David Kills Goliath': 'David mata a Goliat',
  "Construction of Solomon's Temple": 'Construcción del templo de Salomón',
  'Southern Kingdom (Judah)': 'Reino del sur (Judá)',
  'Northern Kingdom (Israel)': 'Reino del norte (Israel)',
  'Elijah Translated': 'Elías es llevado',
  "Job's Trial": 'Prueba de Job',
  'Espousal of Mary': 'Desposorio de María',
  'An Angel Speaks to Joseph in a Dream': 'Un ángel habla a José en un sueño',
  'Wise Men Visit Herod': 'Los sabios visitan a Herodes',
  'Wise Men Visit Jesus': 'Los sabios visitan a Jesús',
  'Joseph and Mary Flee to Egypt': 'José y María huyen a Egipto',
  'Herod slays male children': 'Herodes manda matar a los niños varones',
  'Joseph and Mary return from Egypt': 'José y María regresan de Egipto',
  'Joseph and Mary return to Nazareth': 'José y María regresan a Nazaret',
  'John the Baptist Begins Ministry': 'Juan el Bautista comienza su ministerio',
  'John Baptizes Jesus': 'Juan bautiza a Jesús',
  'Temptations of Jesus': 'Tentaciones de Jesús',
  'Jesus visits Galilee': 'Jesús visita Galilea',
  'Jesus Leaves Judea toward Galilee': 'Jesús sale de Judea rumbo a Galilea',
  'Jesus in Capernaum': 'Jesús en Capernaúm',
  'Fishers of Men': 'Pescadores de hombres',
  "Jesus' 1st Tour of Galilee": 'Primera gira de Jesús por Galilea',
  'Sermon on the Mount': 'Sermón del monte',
  'Healing the Leper': 'Sanidad del leproso',
  "Healing Centurion's Servant": 'Sanidad del siervo del centurión',
  "Peter's Mother-in-law and Others Healed": 'Sanidad de la suegra de Pedro y de otros enfermos',
  'Seaside Parables and Miracle': 'Parábolas junto al mar y un milagro',
  'Gadarene Demoniacs': 'Endemoniados gadarenos',
  'Healing the Man with Palsy': 'Sanidad del paralítico',
  'Jesus Calls Matthew': 'Jesús llama a Mateo',
  'Fasting Question': 'Pregunta sobre el ayuno',
  'Parable of the Winseskins': 'Parábola de los odres',
  'Capernaum Miracles': 'Milagros en Capernaúm',
  '3rd Tour of Galilee': 'Tercera gira por Galilea',
  'Apostles Chosen': 'Elección de los apóstoles',
  "Jesus' Message on John the Baptist": 'Mensaje de Jesús sobre Juan el Bautista',
  'Woe to Chorazin and Bethsaida': 'Ay de Corazín y Betsaida',
  'Corn on the Sabbath': 'Espigas en sábado',
  'Healing a Withered Hand': 'Sanidad de la mano seca',
  'Healing Multitudes': 'Sanidad de multitudes',
  'Blind and Dumb Demoniac and Following Discourse': 'Sanidad del endemoniado ciego y mudo y enseñanza posterior',
  '2nd Rejection at Nazareth': 'Segundo rechazo en Nazaret',
  'John the Baptist Imprisoned': 'Juan el Bautista es encarcelado',
  'John Beheaded': 'Juan el Bautista es decapitado',
  'Feeding of Five Thousand': 'Alimentación de los cinco mil',
  'Jesus Walks on Water': 'Jesús camina sobre el agua',
  'Healing in Gennesaret': 'Sanidades en Genesaret',
  'Commandments and Tradition Discourse': 'Enseñanza sobre los mandamientos y la tradición',
  'Healing Canaanite Daughter': 'Sanidad de la hija de la mujer cananea',
  'Healing a Crowd near Sea of Galilee': 'Sanidad de una multitud cerca del mar de Galilea',
  'Feeding of Four Thousand': 'Alimentación de los cuatro mil',
  'Discourse with Pharisees and Saducees': 'Diálogo con fariseos y saduceos',
  "Peter's Confession \"Upon this Rock\"": 'Confesión de Pedro: «Sobre esta roca»',
  'Foretelling the Death and Resurrection': 'Anuncio de la muerte y resurrección',
  'The Transfiguation': 'La transfiguración',
  'Healing a Boy with a Demon': 'Sanidad de un muchacho atormentado por un demonio',
  'Second Foretelling of Death and Resurrection': 'Segundo anuncio de la muerte y resurrección',
  "Tax Coin in a Fish's Mouth": 'Moneda del impuesto en la boca de un pez',
  'Teachings on Humility/Temptation/Reconciliation': 'Enseñanzas sobre humildad, tentación y reconciliación',
  'Jesus Teaches in Perea': 'Jesús enseña en Perea',
  'Healing Blind Bartimaeus': 'Sanidad del ciego Bartimeo',
  'Triumphal Entry': 'Entrada triunfal',
  'Holy Week': 'Semana de la pasión',
  'Temple Cleansed': 'Purificación del templo',
  'Fig Tree Cursed': 'La higuera es maldecida',
  'Teaching by the Fig Tree': 'Enseñanza junto a la higuera',
  'Debates in the Temple': 'Debates en el templo',
  'Olivet Discourse': 'Discurso del monte de los Olivos',
  'Sanhedrin Conspiracy': 'Conspiración del Sanedrín',
  'Judas Plans Betrayal': 'Judas planea la traición',
  'The Last Supper': 'La última cena',
  'Prayer and Betrayal in Gethsemane': 'Oración y traición en Getsemaní',
  'Jewish Trials': 'Juicios ante las autoridades judías',
  "Judas' Suicide": 'Muerte de Judas',
  'Roman Trials': 'Juicios ante las autoridades romanas',
  'Bearing Cross to Golgotha': 'Camino al Gólgota llevando la cruz',
  'Crucifixion and Burial': 'Crucifixión y sepultura',
  'Resurrection and Ascension': 'Resurrección y ascensión',
  'The Demoniac': 'El endemoniado',
  'Healing a Blind Man at Bethsaida': 'Sanidad de un ciego en Betsaida',
  "John's birth predicted": 'Anuncio del nacimiento de Juan',
  'The Annuciation': 'La anunciación',
  'Mary Visits Elizabeth': 'María visita a Elisabet',
  'Birth of John the Baptist': 'Nacimiento de Juan el Bautista',
  'Birth of Jesus': 'Nacimiento de Jesús',
  'Jesus Circumsized': 'Circuncisión de Jesús',
  'Temple Presentation of Jesus': 'Presentación de Jesús en el templo',
  'Childhood of Jesus': 'Infancia de Jesús',
  'Jesus as a child in the Temple': 'Jesús niño en el templo',
  'Jesus Growing Up': 'Crecimiento de Jesús',
  'Jesus Rejected at Nazareth': 'Jesús es rechazado en Nazaret',
  "Widow's Son Resurrected": 'Resurrección del hijo de la viuda',
  'Anointed by a Sinner Woman': 'Jesús es ungido por una mujer pecadora',
  "Jesus' 2nd Tour of Galilee": 'Segunda gira de Jesús por Galilea',
  'Samaritans Reject Jesus': 'Los samaritanos rechazan a Jesús',
  '70 Sent Out': 'Envío de los setenta',
  'Good Samaritan Parable Taught': 'Enseñanza de la parábola del buen samaritano',
  'Jesus meets Martha and Mary': 'Jesús visita a Marta y María',
  "Lord's Prayer Taught": 'Enseñanza del Padre Nuestro',
  'Woes and Parables with Pharisees': 'Ayes y parábolas ante los fariseos',
  'Healing Woman With 18-year Infirmity': 'Sanidad de una mujer enferma durante dieciocho años',
  'Mustard Seed and Leaven Teaching': 'Enseñanza de la semilla de mostaza y la levadura',
  'Teaching and Healing in Perea to Jerusalem': 'Enseñanzas y sanidades desde Perea hacia Jerusalén',
  'Lepers Healed': 'Sanidad de los leprosos',
  'Discourse on the Kingdom and Other Parables': 'Enseñanza sobre el reino y otras parábolas',
  'Zaccheus Converted and Parable of the Pounds': 'Conversión de Zaqueo y parábola de las minas',
  "John's Witness": 'Testimonio de Juan',
  'First Disciples Gathered': 'Primeros discípulos reunidos',
  'Water to Wine': 'El agua se convierte en vino',
  'Visiting Capernaum': 'Visita a Capernaúm',
  'First Passover and Temple Cleansing': 'Primera Pascua y purificación del templo',
  'Jesus and Nicodemus': 'Jesús y Nicodemo',
  'John the Baptist Witnesses': 'Testimonio de Juan el Bautista',
  'The Samaritan Woman': 'La mujer samaritana',
  'Bethesda pool healing': 'Sanidad en el estanque de Betesda',
  'Bread of Life Sermon': 'Discurso del pan de vida',
  'Feast of Tabernacles': 'Fiesta de los Tabernáculos',
  'Woman Caught in Adultery': 'La mujer sorprendida en adulterio',
  'Light of the World/I am discourse': 'Discurso «Luz del mundo / Yo soy»',
  'Blind Man Healed': 'Sanidad del hombre ciego',
  'The Good Shepherd Teaching': 'Enseñanza del buen pastor',
  'Feast of Dedication': 'Fiesta de la Dedicación',
  'Lazarus Raised form the Dead': 'Resurrección de Lázaro',
  'Chief Priests Conspire Against Jesus': 'Los principales sacerdotes conspiran contra Jesús',
  'Jesus Withdraws to Ephraim': 'Jesús se retira a Efraín',
  'Mary Anoints Jesus': 'María unge a Jesús',
  'Upper Room Discourse': 'Discurso en el aposento alto',
  'The Holy Spirit is promised': 'Promesa del Espíritu Santo',
  'Jesus ascends to Heaven': 'Jesús asciende al cielo',
  'Matthias replaces Judas': 'Matías reemplaza a Judas',
  'The Holy Spirit comes': 'Venida del Espíritu Santo',
  'Peter preaches at Pentecost': 'Pedro predica en Pentecostés',
  'The church grows': 'La iglesia crece',
  'Lame man healed': 'Sanidad de un hombre cojo',
  "Peter preaches in Solomon's Portico": 'Pedro predica en el pórtico de Salomón',
  "Peter and John's Trial": 'Pedro y Juan ante el concilio',
  'Believers pray for boldness': 'Los creyentes oran por valentía',
  'Believers share all things': 'Los creyentes comparten sus bienes',
  'Ananias and Sapphira lie to God': 'Ananías y Safira mienten a Dios',
  "Apostles work signs and wonders in Solomon's Portico": 'Los apóstoles hacen señales y prodigios en el pórtico de Salomón',
  'Apostles arrested, put on trial': 'Los apóstoles son arrestados y llevados a juicio',
  'Gamaliel advises the counsel and Apostles freed': 'Gamaliel aconseja al concilio y los apóstoles son liberados',
  'Seven chosen to serve': 'Siete son escogidos para servir',
  'Stephen is seized': 'Esteban es arrestado',
  'Stephen addresses the council': 'Esteban habla ante el concilio',
  'Stephen is stoned': 'Esteban es apedreado',
  'Saul persecutes the church': 'Saulo persigue a la iglesia',
  'Philip preaches in Samaria': 'Felipe predica en Samaria',
  'Conversion of Ethiopian Eunuch': 'Conversión del eunuco etíope',
  'Saul is converted': 'Conversión de Saulo',
  'Saul proclaims Jesus': 'Saulo proclama a Jesús',
  'Peter heals Aeneas and Dorcas': 'Pedro sana a Eneas y Dorcas',
  'Peter meets Cornelius': 'Pedro se encuentra con Cornelio',
  'Peter preaches to gentiles in Caesarea': 'Pedro predica a los gentiles en Cesarea',
  'Peter defends Gentile salvation': 'Pedro defiende la salvación de los gentiles',
  'Disciples first called Christians': 'Los discípulos son llamados cristianos por primera vez',
  'Herod kills James': 'Herodes mata a Jacobo',
  'Herod imprisons Peter': 'Herodes encarcela a Pedro',
  'An angel rescues Peter from prison': 'Un ángel libra a Pedro de la cárcel',
  'Herod dies': 'Muerte de Herodes',
  'First missionary journey begins': 'Comienza el primer viaje misionero',
  'First Missionary Journey': 'Primer viaje misionero',
  'Barnabas and Saul go to Cyprus': 'Bernabé y Saulo van a Chipre',
  'Return to Antioch in Syria': 'Regreso a Antioquía de Siria',
  'Second Missionary Journey': 'Segundo viaje misionero',
  'Jerusalem Council': 'Concilio de Jerusalén',
  'Paul and Barnabas part ways': 'Pablo y Bernabé se separan',
  'Second Missionary Journey begins': 'Comienza el segundo viaje misionero',
  'Timothy Joins Paul and Silas': 'Timoteo se une a Pablo y Silas',
  'Mission to Phrygia, Galatia and Asia': 'Misión en Frigia, Galacia y Asia',
  'Call to Macedonia': 'Llamado a Macedonia',
  "Lydia's Conversion": 'Conversión de Lidia',
  'Paul casts demon out of soothsayer': 'Pablo expulsa un demonio de una adivina',
  'Paul and Silas imprisoned': 'Pablo y Silas son encarcelados',
  'Philippian jailer converted': 'Conversión del carcelero de Filipos',
  'Paul and Silas released': 'Pablo y Silas son liberados',
  'Uproar in Thessalonica': 'Alboroto en Tesalónica',
  'Paul preaches in Athens': 'Pablo predica en Atenas',
  'Mission to Corinth, 1&2 Thess Written': 'Misión en Corinto y redacción de 1 y 2 Tesalonicenses',
  'Return from Second Missionary Journey': 'Regreso del segundo viaje misionero',
  'Third Missionary Journey': 'Tercer viaje misionero',
  'Third Missionary Journey Begins': 'Comienza el tercer viaje misionero',
  'Mission to Ephesus/1 Cor Written': 'Misión en Éfeso y redacción de 1 Corintios',
  'Riot in Ephesus': 'Alboroto en Éfeso',
  'Mission to Macedonia and Greece': 'Misión en Macedonia y Grecia',
  'Eutychus revived': 'Eutico vuelve a la vida',
  'Voyage to Miletus': 'Viaje a Mileto',
  'Paul speaks to Ephesian Elders': 'Pablo habla a los ancianos de Éfeso',
  'Voyage from Miletus to Jerusalem': 'Viaje de Mileto a Jerusalén',
  'Paul visits elders in Jerusalem': 'Pablo visita a los ancianos en Jerusalén',
  'Paul arrested in the Temple': 'Pablo es arrestado en el templo',
  'Paul gives his testimony': 'Pablo da su testimonio',
  'Paul goes before the Council': 'Pablo comparece ante el concilio',
  'The conspiracy to kill Paul': 'Conspiración para matar a Pablo',
  'Paul sent to Felix': 'Pablo es enviado ante Félix',
  'Paul appeals to Caesar': 'Pablo apela al César',
  'Agrippa and Bernice meet Festus': 'Agripa y Berenice se encuentran con Festo',
  'Paul goes before Agrippa': 'Pablo comparece ante Agripa',
  "Paul's Journey to Rome": 'Viaje de Pablo a Roma',
  'Journey to Rome begins': 'Comienza el viaje a Roma',
  'Paul is shipwrecked by a storm': 'Pablo naufraga durante una tormenta',
  'Paul stays at Malta': 'Pablo permanece en Malta',
  'Paul arrives at Rome': 'Pablo llega a Roma',
  "Paul's First Roman imprisonment": 'Primer encarcelamiento de Pablo en Roma',
  'Paul Writes Galatians': 'Pablo escribe Gálatas',
}

function translateEntity(value: string) {
  return value
    .split(/( and |, | \(|\))/)
    .map(part => ENTITY_TRANSLATIONS[part] ?? part)
    .join('')
}

export function theographicTitleEs(title: string) {
  const exact = EXACT[title]
  if (exact) return exact

  const patterns: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
    [/^Birth of (.+)$/, match => `Nacimiento de ${translateEntity(match[1])}`],
    [/^Lifetime of (.+)$/, match => `Vida de ${translateEntity(match[1])}`],
    [/^Death of (.+)$/, match => `Muerte de ${translateEntity(match[1])}`],
    [/^Reign of (.+)$/, match => `Reinado de ${translateEntity(match[1])}`],
    [/^Prophecies of (.+)$/, match => `Profecías de ${translateEntity(match[1])}`],
    [/^Judgeship of (.+)$/, match => `Período de ${translateEntity(match[1])} como juez`],
    [/^Deliverance by (.+)$/, match => `Liberación por medio de ${translateEntity(match[1])}`],
    [/^Subjugation by (.+)$/, match => `Dominio de ${translateEntity(match[1])}`],
    [/^Usurpation by (.+)$/, match => `Usurpación de ${translateEntity(match[1])}`],
    [/^Mission to (.+)$/, match => `Misión en ${translateEntity(match[1])}`],
  ]

  for (const [pattern, render] of patterns) {
    const match = title.match(pattern)
    if (match) return render(match)
  }

  // No mostramos inglés crudo al usuario cuando una etiqueta fuente todavía no tiene
  // localización editorial. La referencia bíblica visible mantiene el contexto exacto.
  return 'Historia bíblica relacionada'
}
