-- FASE H / Bloque 3 — lote 003 de glosas españolas conservadoras.
-- Política: insert-only. No modifica biblical_lexical_entries ni sobrescribe glosas existentes.
-- Batch id: fase_h_es_batch_003_20260820
--
-- Reversión exacta, si fuera necesaria:
-- DELETE FROM public.biblical_hebrew_spanish_glosses
-- WHERE provenance->>'batch_id' = 'fase_h_es_batch_003_20260820';

with map(source_gloss, display_gloss_es) as (
  values
  ('lightning','relámpago'),
  ('loin','lomo'),
  ('longing','anhelo'),
  ('lye','lejía'),
  ('madness','locura'),
  ('maiden','doncella'),
  ('mockery','burla'),
  ('necklace','collar'),
  ('neighbor','vecino'),
  ('nettle','ortiga'),
  ('not','no'),
  ('oar','remo'),
  ('offspring','descendencia'),
  ('palace','palacio'),
  ('perversity','perversidad'),
  ('piece','pieza'),
  ('plague','plaga'),
  ('plantation','plantación'),
  ('porch','pórtico'),
  ('power','poder'),
  ('prey','presa'),
  ('prince','príncipe'),
  ('quietness','quietud'),
  ('rebuke','reprensión'),
  ('report','informe'),
  ('resting','descanso'),
  ('rich','rico'),
  ('row','fila'),
  ('ruins','ruinas'),
  ('shadow','sombra'),
  ('sheaf','gavilla'),
  ('sin','pecado'),
  ('slander','calumnia'),
  ('smoothness','suavidad'),
  ('song','canción'),
  ('strength','fuerza'),
  ('stronghold','fortaleza'),
  ('sweetness','dulzura'),
  ('ten','diez'),
  ('testimony','testimonio'),
  ('then','entonces'),
  ('thicket','matorral'),
  ('thickness','grosor'),
  ('threshold','umbral'),
  ('to boil','hervir'),
  ('to breathe','respirar'),
  ('to cease','cesar'),
  ('to change','cambiar'),
  ('to contend','contender'),
  ('to curse','maldecir'),
  ('to defile','profanar'),
  ('to despise','despreciar'),
  ('to dig','cavar'),
  ('to eat','comer'),
  ('to escape','escapar'),
  ('to feed','alimentar'),
  ('to forget','olvidar'),
  ('to harden','endurecer'),
  ('to loathe','aborrecer'),
  ('to long for','anhelar'),
  ('to look','mirar'),
  ('to mix','mezclar'),
  ('to prosper','prosperar'),
  ('to provoke','provocar'),
  ('to rebuke','reprender'),
  ('to reject','rechazar'),
  ('to remain','permanecer'),
  ('to rest','descansar'),
  ('to restrain','contener'),
  ('to roast','asar'),
  ('to seek','buscar'),
  ('to shrivel','marchitarse'),
  ('to stand','estar de pie'),
  ('to swell','hincharse'),
  ('to weaken','debilitar'),
  ('to weigh','pesar'),
  ('treachery','traición'),
  ('turban','turbante'),
  ('turn','giro'),
  ('understanding','entendimiento'),
  ('veil','velo'),
  ('wailing','lamento'),
  ('weak','débil'),
  ('wealth','riqueza'),
  ('weary','cansado'),
  ('weight','peso'),
  ('window','ventana'),
  ('wonder','maravilla'),
  ('yoke','yugo'),
  ('accident','accidente'),
  ('acquisition','adquisición'),
  ('affliction','aflicción'),
  ('alabaster','alabastro'),
  ('alas!','¡ay!'),
  ('almond','almendra'),
  ('also','también'),
  ('anxiety','ansiedad'),
  ('appearance','apariencia'),
  ('apple','manzana'),
  ('appointment','nombramiento'),
  ('artisan','artesano'),
  ('associate','asociado'),
  ('at ease','tranquilo'),
  ('attentive','atento'),
  ('back','espalda'),
  ('backwards','hacia atrás'),
  ('balance','equilibrio'),
  ('bald','calvo'),
  ('baldness','calvicie'),
  ('balsam','bálsamo'),
  ('barefoot','descalzo'),
  ('base','base'),
  ('be foolish','ser necio'),
  ('be fresh','estar fresco'),
  ('be humble','ser humilde'),
  ('be loathsome','ser repugnante'),
  ('be ready','estar listo'),
  ('be sick','estar enfermo'),
  ('beauty','belleza'),
  ('behold','he aquí'),
  ('bell','campana'),
  ('belly','vientre'),
  ('beloved','amado'),
  ('bereavement','duelo'),
  ('bird','ave'),
  ('booth','cabaña'),
  ('boundary','límite'),
  ('breaking','ruptura'),
  ('breast','pecho'),
  ('brick','ladrillo'),
  ('broom','escoba'),
  ('bucket','cubo'),
  ('bulrush','junco'),
  ('bulwark','baluarte'),
  ('bush','arbusto'),
  ('cake','torta'),
  ('carcass','cadáver'),
  ('cassia','casia')
),
eligible as (
  select
    e.id as lexical_entry_id,
    e.source_gloss,
    map.display_gloss_es
  from public.biblical_lexical_entries e
  join map on map.source_gloss = e.source_gloss
  left join public.biblical_hebrew_spanish_glosses g
    on g.lexical_entry_id = e.id
  where e.language = 'hebrew'
    and e.review_status = 'approved'
    and e.enabled = true
    and e.display_gloss_es is null
    and g.lexical_entry_id is null
)
insert into public.biblical_hebrew_spanish_glosses (
  lexical_entry_id,
  display_gloss_es,
  alternative_glosses_es,
  confidence,
  derivation_method,
  source_gloss_snapshot,
  status,
  provenance
)
select
  lexical_entry_id,
  display_gloss_es,
  '{}'::text[],
  96,
  'exact_source_gloss_editorial_map_v1',
  source_gloss,
  'verified_derived',
  jsonb_build_object(
    'phase', 'FASE_H_BLOQUE_3',
    'batch_id', 'fase_h_es_batch_003_20260820',
    'source', 'STEPBible/TAHOT source_gloss en',
    'derivation', 'conservative exact English gloss mapping',
    'context_used_as_meaning', false
  )
from eligible
on conflict (lexical_entry_id) do nothing;
