-- Consolida el lote histórico y evita que filas generadas por IA compitan con el corpus editorial.
update public.biblical_context_units
set enabled = false,
    review_status = 'rejected',
    metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
      'disabled_reason', 'replaced-by-reviewed-editorial-corpus',
      'disabled_at', now()
    ),
    updated_at = now()
where metadata->>'coverage_batch' = 'historical-books'
  and metadata->>'generated_by_ai' = 'true';

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, chapter_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('josue-perfil','JOS',24,'Josué: tierra, fidelidad y renovación del pacto',
   'Josué relata el paso del Jordán, las campañas en Canaán, la distribución de la tierra y la renovación final del pacto bajo el liderazgo de Josué.',
   'El libro se sitúa en la transición desde una comunidad itinerante hacia asentamientos tribales en Canaán. La relación entre el relato, la arqueología y la formación histórica de Israel continúa siendo debatida.',
   'En la tradición judía, Josué abre los Profetas Anteriores. La posesión de la tierra permanece vinculada a la Torá, a la responsabilidad comunitaria y a la fidelidad del pacto.',
   'Combina discursos, relatos de cruce y batalla, listas territoriales, ciudades de refugio y ceremonias de pacto. El inicio y el final destacan obediencia, memoria y elección.',
   'Mostrar que el cumplimiento de la promesa exige confianza y obediencia, y que la tierra es recibida como responsabilidad de pacto, no como posesión humana absoluta.',
   'La fidelidad de Dios no elimina decisiones difíciles ni responsabilidad ética. La memoria del camino debe conducir a una vida de servicio y justicia.',
   'Los relatos de conquista no constituyen una autorización general para guerras modernas, colonialismo ni desplazamiento religioso. El lenguaje de destrucción total, la evidencia arqueológica y las diferentes perspectivas textuales requieren tratamiento responsable.',
   ARRAY['Josué','Jordán','tierra','pacto','herencia','memoria']::text[], ARRAY['israelitas','cananeos','gabaonitas','tribus de Israel']::text[], ARRAY['Jordán','Jericó','Hai','Siquem','Canaán']::text[]),
  ('jueces-perfil','JDG',21,'Jueces: ciclos de opresión y deterioro social',
   'Jueces narra una etapa fragmentada en la que Israel alterna infidelidad, opresión, clamor y liberación, mientras el orden social y religioso se deteriora progresivamente.',
   'El periodo refleja confederaciones tribales, ciudades cananeas y amenazas regionales antes de una monarquía centralizada. La cronología de los jueces no debe sumarse mecánicamente como una secuencia simple.',
   'En el Tanaj forma parte de los Profetas Anteriores. Sus relatos funcionan como memoria crítica de la infidelidad al pacto y de las consecuencias de abandonar la justicia.',
   'Una introducción doble, una serie de ciclos con libertadores y dos apéndices de caos crean una espiral descendente más que una colección de héroes ejemplares.',
   'Explicar que la liberación repetida no resuelve un corazón y una sociedad que rehúsan aprender, y preparar la pregunta por un liderazgo justo.',
   'Dios escucha a personas oprimidas, pero el libro también obliga a lamentar la normalización de violencia, idolatría y abuso dentro del propio pueblo.',
   'Los jueces no deben presentarse como modelos morales completos. El texto describe violencia sexual, guerra y venganza sin aprobar cada acto, y su estribillo sobre la ausencia de rey tampoco convierte automáticamente cualquier monarquía en solución divina.',
   ARRAY['jueces','opresión','clamor','liberación','idolatría','caos']::text[], ARRAY['israelitas','cananeos','madianitas','filisteos','amonitas']::text[], ARRAY['Canaán','Siquem','Galaad','Gaza']::text[]),
  ('rut-perfil','RUT',4,'Rut: lealtad, provisión y pertenencia',
   'Rut sigue a Noemí y a su nuera moabita desde pérdida y migración hasta provisión, redención familiar y una genealogía vinculada con David.',
   'La historia se desarrolla en la época de los jueces y refleja hambre, migración, espigueo, propiedad familiar, matrimonio y mecanismos de rescate dentro de una comunidad agraria.',
   'Rut es leída durante Shavuot. La inclusión de una mujer moabita en la historia de David destaca la fuerza de la hesed, la lealtad comprometida que cruza fronteras étnicas.',
   'La narración breve usa diálogos, bendiciones, ironía, cambios de vacío a plenitud y una genealogía final. Las iniciativas de Rut y Noemí impulsan la trama.',
   'Mostrar cómo la fidelidad cotidiana, la generosidad y las estructuras de cuidado pueden transformar una situación de vulnerabilidad y ampliar la comunidad del pacto.',
   'Dios suele ser reconocido mediante actos concretos de bondad, trabajo, hospitalidad y responsabilidad compartida, no únicamente mediante acontecimientos espectaculares.',
   'El libro no debe convertirse en una fórmula para conseguir pareja ni idealizar la dependencia económica. El término goel tiene funciones familiares y legales específicas que no equivalen exactamente a un romance moderno.',
   ARRAY['Rut','Noemí','Booz','hesed','goel','espigueo','David']::text[], ARRAY['moabitas','judíos de Belén']::text[], ARRAY['Moab','Belén']::text[]),
  ('1-samuel-perfil','1SA',31,'1 Samuel: profecía, monarquía y discernimiento del liderazgo',
   '1 Samuel narra la transición desde los jueces hacia la monarquía mediante Samuel, Saúl y el ascenso de David, mostrando posibilidades y peligros del poder.',
   'El libro refleja una sociedad tribal bajo presión filistea, el surgimiento de instituciones monárquicas y tensiones entre autoridad profética, sacerdotal y real.',
   'Samuel es contado entre los Profetas Anteriores. La petición de un rey se evalúa de manera ambivalente: puede responder a una necesidad política, pero también expresar deseo de ser como las demás naciones.',
   'Tres trayectorias se entrelazan: Samuel crece mientras la casa de Elí declina; Saúl asciende y fracasa; David es ungido y espera mientras es perseguido.',
   'Examinar qué hace legítimo a un líder ante Dios: no apariencia, carisma ni éxito militar, sino escucha, obediencia, justicia y responsabilidad.',
   'El llamado y el don no sustituyen el carácter. La autoridad saludable acepta corrección, protege al vulnerable y no convierte la misión en defensa del propio ego.',
   'El libro no enseña que toda crítica al líder sea rebelión. Los episodios de guerra, espíritu dañino y consulta a la médium de Endor requieren análisis contextual; no deben usarse para diagnosticar enfermedades ni promover prácticas ocultistas.',
   ARRAY['Samuel','Saúl','David','monarquía','profecía','obediencia']::text[], ARRAY['israelitas','filisteos','amalecitas']::text[], ARRAY['Silo','Ramá','Gilgal','Gabaá','Belén']::text[]),
  ('2-samuel-perfil','2SA',24,'2 Samuel: reino de David, pacto y consecuencias del poder',
   '2 Samuel presenta la consolidación del reino de David, la promesa dinástica, sus victorias y el colapso familiar y político que sigue a su abuso contra Betsabé y Urías.',
   'La unificación de tribus, la captura de Jerusalén, la administración real y las rebeliones internas reflejan la formación de un estado territorial en el antiguo Levante.',
   'La promesa a la casa de David se vuelve central para la esperanza bíblica, pero el libro conserva una crítica severa al rey y no oculta su pecado ni sus consecuencias.',
   'Una primera mitad de ascenso y estabilidad se quiebra en el capítulo 11. Desde allí, conflictos familiares, rebeliones y violencia responden narrativamente al abuso del rey.',
   'Afirmar la fidelidad del pacto sin convertirla en inmunidad para el gobernante; el mismo rey ungido permanece bajo la palabra profética y la justicia.',
   'La gracia no borra responsabilidad ni consecuencias. El poder debe proteger, y cuando explota a otra persona necesita verdad, arrepentimiento y reparación.',
   'David no debe presentarse como modelo perfecto ni Betsabé como seductora; el texto subraya la iniciativa y autoridad del rey. Las guerras y ejecuciones no son automáticamente aprobadas por el narrador.',
   ARRAY['David','Jerusalén','pacto davídico','Betsabé','Natán','Absalón']::text[], ARRAY['israelitas','filisteos','amonitas','arameos']::text[], ARRAY['Hebrón','Jerusalén','Rabá','Mahánayim']::text[]),
  ('1-reyes-perfil','1KI',22,'1 Reyes: templo, sabiduría y división del reino',
   '1 Reyes narra la sucesión de Salomón, la construcción del templo, el esplendor y fracaso de su reinado, la división del reino y el conflicto profético durante la casa de Acab.',
   'El libro refleja administración imperial, proyectos de construcción, comercio, trabajo forzado, alianzas matrimoniales y la división política entre Israel y Judá.',
   'Forma parte de los Profetas Anteriores y evalúa a los reyes según fidelidad a la Torá y al culto. El templo es central, pero no puede proteger a una nación injusta.',
   'El esplendor de Salomón se vuelve gradualmente advertencia; tras la división, fórmulas regias alternan con extensas narraciones proféticas de Elías.',
   'Evaluar la monarquía desde la alianza: sabiduría, culto y éxito pierden su sentido cuando se separan de justicia, lealtad y límites al poder.',
   'Los dones pueden convertirse en instrumentos de orgullo. La presencia de Dios no queda encerrada en edificios ni garantiza aprobación de sistemas opresivos.',
   'La riqueza de Salomón no debe usarse como promesa de prosperidad personal. Los relatos sobre otras religiones no autorizan hostilidad hacia sus practicantes actuales, y la sequía de Elías no debe manipularse como fórmula para controlar el clima.',
   ARRAY['Salomón','templo','sabiduría','reino dividido','Elías','Acab']::text[], ARRAY['israelitas','judíos','fenicios','arameos']::text[], ARRAY['Jerusalén','Samaria','Tiro','Carmelo']::text[]),
  ('2-reyes-perfil','2KI',25,'2 Reyes: profecía, reforma, caída y exilio',
   '2 Reyes continúa las historias de Elías y Eliseo, sigue las dinastías de Israel y Judá, narra la caída de Samaria y culmina con la destrucción de Jerusalén y el exilio babilónico.',
   'Asiria y Babilonia dominan el escenario internacional. Inscripciones imperiales, campañas militares, tributos y deportaciones ayudan a situar numerosos acontecimientos del libro.',
   'El libro interpreta el exilio mediante el pacto y la voz profética, pero conserva también relatos de misericordia, reforma y una pequeña esperanza en la liberación final de Joaquín.',
   'Ciclos proféticos iniciales dan paso a una narración regia cada vez más marcada por amenazas imperiales. Dos caídas —Samaria y Jerusalén— estructuran el desenlace.',
   'Explicar que la injusticia, la idolatría y el rechazo persistente de corrección tienen consecuencias históricas, sin presentar el desastre como ausencia definitiva de esperanza.',
   'La fidelidad requiere escuchar advertencias antes de la crisis. Incluso después de la pérdida, la memoria, el arrepentimiento y pequeños signos de restauración mantienen abierta la historia.',
   'El exilio no debe usarse para afirmar que toda tragedia nacional es castigo directo identificable. Las deportaciones y guerras describen sufrimiento real y no deben romantizarse como simples lecciones espirituales.',
   ARRAY['Eliseo','Asiria','Babilonia','Samaria','Jerusalén','exilio','reforma']::text[], ARRAY['israelitas','judíos','asirios','babilonios','arameos']::text[], ARRAY['Samaria','Jerusalén','Damasco','Nínive','Babilonia']::text[]),
  ('1-cronicas-perfil','1CH',29,'1 Crónicas: identidad, David y preparación del templo',
   '1 Crónicas recorre genealogías desde Adán, resume la caída de Saúl y concentra su atención en David, la organización del culto y la preparación para el templo.',
   'El libro refleja una comunidad posterior al exilio que necesita reconstruir identidad, genealogías, funciones levíticas y conexión con la historia anterior de Israel.',
   'En el orden del Tanaj, Crónicas cierra los Escritos. Su mirada relee el pasado para una comunidad que ya no posee el reino davídico de la misma manera, pero conserva culto, Torá y esperanza.',
   'Nueve capítulos genealógicos forman el portal del libro; después la narración selecciona episodios de David, especialmente aquellos relacionados con Jerusalén, el arca y el templo futuro.',
   'Afirmar que la comunidad restaurada pertenece a una historia más amplia y que la adoración, la memoria y la organización responsable permiten continuar después de una ruptura nacional.',
   'Recordar nombres y generaciones puede ser un acto espiritual de pertenencia. Preparar una obra que otro completará también posee valor y dignidad.',
   'Las genealogías no deben utilizarse para afirmar superioridad racial o pureza biológica. La imagen más favorable de David no niega los abusos narrados en Samuel; refleja una selección literaria con otro propósito pastoral.',
   ARRAY['genealogías','David','arca','levitas','templo','adoración']::text[], ARRAY['judíos retornados','levitas','sacerdotes','tribus de Israel']::text[], ARRAY['Jerusalén','Hebrón','Sion']::text[]),
  ('2-cronicas-perfil','2CH',36,'2 Crónicas: templo, reyes de Judá, reforma y retorno',
   '2 Crónicas continúa con Salomón, sigue exclusivamente la monarquía de Judá, evalúa reformas y crisis y concluye con el exilio y el decreto persa que permite regresar.',
   'El libro fue compuesto para una comunidad posterior al exilio que reconstruía vida alrededor del templo, Jerusalén y la Torá bajo dominio persa.',
   'A diferencia de Reyes, Crónicas presta atención particular a sacerdotes, levitas, asambleas, Pascuas y posibilidades de retorno incluso para personas del antiguo reino del norte.',
   'El templo de Salomón abre la obra, una cadena de reinados ocupa el centro y la destrucción culmina inmediatamente en una orden de regreso, creando un final abierto.',
   'Enseñar que la búsqueda de Dios, la escucha profética y la reforma pueden renovar a una comunidad, mientras la persistencia en violencia e idolatría conduce a pérdida.',
   'La restauración puede comenzar aun después de una catástrofe. Volver requiere humildad, memoria, acción comunitaria y disposición para reconstruir.',
   'Las fórmulas de retribución inmediata reflejan el énfasis pedagógico del cronista y no deben convertirse en explicación automática de toda enfermedad, derrota o prosperidad individual.',
   ARRAY['Salomón','templo','Judá','reforma','Pascua','exilio','Ciro']::text[], ARRAY['judíos','levitas','sacerdotes','asirios','babilonios','persas']::text[], ARRAY['Jerusalén','Judá','Babilonia','Persia']::text[]),
  ('esdras-perfil','EZR',10,'Esdras: retorno, templo, Torá e identidad comunitaria',
   'Esdras reúne memorias del retorno bajo Persia, la reconstrucción del templo y la misión del escriba Esdras para enseñar la Torá y reorganizar a la comunidad.',
   'El imperio persa permitió retornos y restauración de santuarios dentro de una política de administración provincial. Judá era una pequeña provincia vinculada a comunidades judías que permanecían en la diáspora.',
   'El templo restaurado, las genealogías y la enseñanza de la Torá fueron pilares de una identidad judía sin monarquía independiente. Partes del libro están escritas en arameo imperial.',
   'Edictos, listas, correspondencia aramea, narraciones de construcción y memorias en primera persona forman dos grandes movimientos: templo y reforma comunitaria.',
   'Mostrar que la restauración requiere reconstrucción material, memoria, enseñanza y discernimiento, pero también que las decisiones de identidad pueden producir dolor y deben examinarse críticamente.',
   'Volver a comenzar exige paciencia frente a oposición, colaboración entre generaciones y una relación renovada con la Escritura.',
   'Los conflictos sobre matrimonios mixtos no deben utilizarse para justificar racismo, xenofobia ni prohibiciones basadas en etnia. El problema se presenta dentro de preocupaciones antiguas de pacto e identidad y debe leerse junto con Rut y otras voces bíblicas.',
   ARRAY['retorno','templo','Torá','Esdras','genealogías','identidad']::text[], ARRAY['judíos retornados','persas','pueblos vecinos','levitas']::text[], ARRAY['Babilonia','Jerusalén','Yehud','Persia']::text[]),
  ('nehemias-perfil','NEH',13,'Nehemías: reconstrucción, justicia y reforma comunitaria',
   'Nehemías narra la reconstrucción de las murallas de Jerusalén, la defensa frente a oposición, la lectura pública de la Torá y varias reformas sociales y cultuales.',
   'Nehemías sirvió dentro de la administración persa y recibió autoridad como gobernador de Yehud. Las murallas tenían funciones defensivas, administrativas y simbólicas para una ciudad vulnerable.',
   'La lectura de la Torá, la confesión histórica y la celebración de Sucot expresan renovación comunitaria. El libro también preserva tensiones sobre sábado, templo, deuda e identidad.',
   'Memorias en primera persona, listas, oraciones y narración comunitaria se organizan alrededor de construcción física y reconstrucción social.',
   'Mostrar que el liderazgo puede combinar oración, planificación y acción, pero debe ser evaluado por su defensa del pobre, su transparencia y la manera en que ejerce autoridad.',
   'La reconstrucción espiritual incluye estructuras seguras, justicia económica, enseñanza y revisión constante de prácticas que se desvían del propósito original.',
   'Nehemías no debe usarse como manual empresarial infalible ni sus acciones enérgicas como autorización para intimidación pastoral. Sus reformas finales deben leerse dentro de una crisis postexílica específica.',
   ARRAY['Nehemías','muralla','Jerusalén','Torá','justicia económica','reforma']::text[], ARRAY['judíos retornados','persas','pueblos vecinos','levitas']::text[], ARRAY['Susa','Jerusalén','Yehud']::text[]),
  ('ester-perfil','EST',10,'Ester: diáspora, poder, identidad y supervivencia',
   'Ester narra cómo una joven judía llega a ser reina en Persia y, junto con Mardoqueo, enfrenta un decreto de exterminio contra su pueblo mediante estrategia, ayuno y acción política.',
   'La historia se desarrolla en la corte persa de Susa y refleja banquetes, burocracia imperial, decretos, jerarquías y vulnerabilidad de minorías dentro de un vasto imperio.',
   'Ester fundamenta la fiesta de Purim. El texto hebreo no menciona explícitamente a Dios, por lo que la tradición ha reflexionado sobre providencia oculta, agencia humana y supervivencia en la diáspora.',
   'Banquetes, inversiones de destino, ironía, repeticiones y una rápida cadena de decretos crean una narración donde quienes parecen poderosos terminan expuestos.',
   'Mostrar que la identidad puede requerir prudencia y valentía, y que las personas dentro de sistemas de poder pueden utilizar su posición para proteger a comunidades amenazadas.',
   'El silencio explícito sobre Dios no equivale a ausencia. La fe también puede expresarse mediante ayuno, sabiduría, solidaridad y decisiones costosas en circunstancias ambiguas.',
   'La historia no debe convertirse en fantasía romántica de concurso de belleza; las mujeres son reunidas bajo poder imperial. La violencia final y la muerte de enemigos requieren contexto de defensa y retórica antigua, no celebración ni imitación.',
   ARRAY['Ester','Mardoqueo','Amán','Purim','diáspora','providencia','Persia']::text[], ARRAY['judíos de la diáspora','persas']::text[], ARRAY['Susa','Persia']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context, authorial_intent,
  theological_reflection, interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select data.slug, data.book_code, source.id, 'book', 1, NULL, data.chapter_end, NULL,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/historicos/v1#' || data.slug,
  'historicos-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','historical-books','generated_by_ai',false,'review_level','editorial','restored_after_consolidation',true)
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary, historical_context=excluded.historical_context,
  jewish_context=excluded.jewish_context, literary_context=excluded.literary_context,
  authorial_intent=excluded.authorial_intent, theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions, key_terms=excluded.key_terms,
  people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status='approved', enabled=true,
  metadata=excluded.metadata, updated_at=now();