-- FASE D · Bloque 4 · Profetas mayores 2: Jeremías y Lamentaciones
update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code in ('JER','LAM');

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('jeremias-perfil','JER','book',1,NULL::smallint,52,NULL::smallint,
   'Jeremías: palabra profética, caída de Jerusalén y esperanza de pacto renovado',
   'Jeremías acompaña las últimas décadas de Judá, denuncia idolatría e injusticia, confronta falsas seguridades, vive el sitio y la caída de Jerusalén y anuncia restauración y un pacto escrito en el corazón.',
   'El ministerio de Jeremías atraviesa reformas de Josías, expansión babilónica, reinados inestables, sitio, destrucción y migraciones forzadas. El libro hebreo y la Septuaginta difieren significativamente en orden y extensión.',
   'Jeremías ocupa un lugar central en la memoria de la destrucción del primer templo. Su llamado a buscar el bienestar de la ciudad durante el exilio y su promesa de un nuevo pacto fueron ampliamente interpretados en tradiciones judías y cristianas.',
   'Oráculos, relatos biográficos, confesiones personales, acciones simbólicas, cartas y disputas están organizados de forma no cronológica. Una sección de esperanza interrumpe el material de juicio.',
   'Desmontar la confianza mágica en templo, nación o liderazgo, llamar a la justicia y preparar a la comunidad para sobrevivir al desastre sin perder la esperanza.',
   'La fidelidad puede incluir decir una verdad impopular, lamentar sus costos y trabajar por el bienestar de una comunidad aun cuando las circunstancias no sean las deseadas.',
   'No debe llamarse traidor a quien cuestiona nacionalismo religioso. Las diferencias textuales entre hebreo y griego no prueban corrupción deliberada. El nuevo pacto no autoriza desprecio hacia el pueblo judío ni la idea de que Dios descartó a Israel.',
   ARRAY['Jeremías','Babilonia','templo','exilio','nuevo pacto','corazón','justicia']::text[],
   ARRAY['judíos','babilonios','egipcios','profetas','exiliados']::text[],
   ARRAY['Jerusalén','Anatot','Babilonia','Egipto']::text[]),
  ('jeremias-1-20-llamado-conflicto','JER','section',1,NULL::smallint,20,NULL::smallint,
   'Llamado, acusación y conflicto del profeta',
   'Jeremías es llamado desde joven, denuncia abandono del pacto, anuncia amenaza del norte, confronta el discurso del templo y expresa sus propias quejas por el costo de su misión.',
   'Judá vivía entre la memoria de Asiria, la reforma de Josías y el ascenso de Babilonia. El templo de Jerusalén podía convertirse en símbolo de seguridad política y religiosa.',
   'El sermón del templo insiste en que presencia y culto no sustituyen justicia hacia extranjero, huérfano y viuda. Las confesiones de Jeremías muestran una voz profética vulnerable.',
   'Visiones de almendro y olla, acusaciones matrimoniales metafóricas, acciones simbólicas y lamentos personales crean una tensión creciente.',
   'Mostrar que la vocación profética implica denunciar estructuras injustas y que la palabra religiosa pierde credibilidad cuando protege violencia o explotación.',
   'Sentirse joven, cansado o herido no invalida un llamado. La honestidad ante Dios puede coexistir con perseverancia y límites humanos.',
   'Las metáforas matrimoniales no deben utilizarse para avergonzar sexualmente a mujeres ni justificar abuso conyugal. La promesa de protección al profeta no significa ausencia de dolor o oposición.',
   ARRAY['llamado','templo','profeta','justicia','confesiones','amenaza del norte']::text[],
   ARRAY['judíos','sacerdotes','profetas','pobres']::text[],
   ARRAY['Anatot','Jerusalén','templo']::text[]),
  ('jeremias-21-29-reyes-profetas','JER','section',21,NULL::smallint,29,NULL::smallint,
   'Reyes, falsos profetas y carta a los exiliados',
   'Jeremías confronta a reyes y profetas que prometen seguridad rápida, anuncia la caída de Jerusalén y envía a los exiliados una carta para construir, vivir y buscar el bienestar de Babilonia mientras esperan.',
   'Después de la primera deportación de 597 a. C., una comunidad quedó en Judá y otra vivió en Babilonia. Ambas competían por interpretar cuál grupo conservaba el futuro.',
   'La carta a los exiliados transforma la diáspora en espacio de responsabilidad y esperanza. Los setenta años expresan una espera larga y delimitada, no una fecha para cálculos modernos.',
   'Oráculos contra reyes, parábolas de pastores, visiones de higos, un yugo simbólico y cartas enfrentan mensajes religiosos de optimismo falso.',
   'Enseñar que una esperanza verdadera no niega duración ni dolor, y que la fidelidad en exilio incluye trabajar por el bien común sin confundir el imperio con el reino de Dios.',
   'La espera puede ser activa: formar hogares, cultivar, orar y contribuir al lugar presente mientras se conserva identidad y esperanza.',
   'Jeremías 29:11 se dirige a una comunidad exiliada y a un proceso generacional; no promete éxito inmediato a cada individuo. «Falso profeta» no debe aplicarse a toda persona que interpreta diferente sin evaluar fruto, contexto y responsabilidad.',
   ARRAY['reyes','falsos profetas','yugo','exilio','bienestar de la ciudad','esperanza']::text[],
   ARRAY['judíos de Judá','exiliados','babilonios','profetas']::text[],
   ARRAY['Jerusalén','Babilonia']::text[]),
  ('jeremias-30-33-consuelo','JER','section',30,NULL::smallint,33,NULL::smallint,
   'Libro de consolación y nuevo pacto',
   'En medio del sitio aparecen promesas de retorno, sanidad comunitaria, reconstrucción, un nuevo pacto escrito en el corazón y la compra de un campo como señal de futuro.',
   'Comprar tierra durante una invasión era una acción contraintuitiva que afirmaba continuidad más allá del desastre. Las promesas responden a Israel y Judá como comunidades heridas.',
   'El nuevo pacto conserva la Torá y la internaliza; no se presenta como eliminación de Israel. La restauración incluye perdón, conocimiento de Dios y renovación de ciudades y campos.',
   'Poemas de consuelo, imágenes de parto, promesas dinásticas y una acción legal crean un centro esperanzador rodeado por relatos de caída.',
   'Afirmar que el juicio no agota el propósito divino y que la restauración implica una relación renovada, memoria sanada y capacidad comunitaria de volver a vivir.',
   'La esperanza puede expresarse mediante una acción concreta aunque el entorno todavía parezca perdido. El corazón renovado une conocimiento, perdón y práctica.',
   'El nuevo pacto no justifica teología de sustitución ni hostilidad antijudía. Las promesas de sanidad no garantizan curación física inmediata para cada persona.',
   ARRAY['consolación','nuevo pacto','corazón','campo','retorno','perdón','restauración']::text[],
   ARRAY['Israel','Judá','exiliados']::text[],
   ARRAY['Jerusalén','Anatot','Samaria']::text[]),
  ('jeremias-34-45-sitio-caida','JER','section',34,NULL::smallint,45,NULL::smallint,
   'Sitio, liberación incumplida y caída de Jerusalén',
   'Durante el sitio se incumple la liberación de esclavos, Jeremías es encarcelado, Jerusalén cae, Gedalías es asesinado y un grupo huye a Egipto contra la advertencia profética.',
   'El sitio babilónico produjo hambre, destrucción, deportación y fragmentación política. La abolición temporal de deudas y servidumbre pudo relacionarse con crisis militar y pacto.',
   'La obediencia de los recabitas contrasta con la infidelidad de Judá. Baruc recibe una palabra personal que limita ambición y preserva vida dentro de una catástrofe.',
   'Relatos relativamente cronológicos muestran oportunidades de cambio rechazadas una tras otra hasta que la ciudad cae.',
   'Mostrar que las reformas oportunistas no sustituyen justicia sostenida y que el rechazo reiterado de advertencias puede cerrar opciones históricas.',
   'La fidelidad durante una crisis puede consistir en conservar verdad, proteger vida y renunciar a grandeza personal. El lamento no debe esconder decisiones humanas responsables.',
   'La caída no debe narrarse como si las víctimas civiles merecieran el sufrimiento. La orden de no ir a Egipto pertenece a una situación profética específica y no prohíbe toda migración por seguridad.',
   ARRAY['sitio','esclavitud','Jeremías','Baruc','Gedalías','Egipto','caída']::text[],
   ARRAY['judíos','babilonios','recabitas','refugiados']::text[],
   ARRAY['Jerusalén','Mizpa','Egipto']::text[]),
  ('jeremias-46-52-naciones-final','JER','section',46,NULL::smallint,52,NULL::smallint,
   'Oráculos sobre naciones y apéndice de la caída',
   'Oráculos confrontan Egipto, Filistea, Moab, Amón, Edom, Damasco, Cedar, Elam y Babilonia; el libro termina con un relato histórico de la destrucción y una nota de esperanza para Joaquín.',
   'Los pueblos mencionados fueron afectados por la expansión babilónica y por cambios imperiales. Los oráculos reflejan conflictos reales y también retórica profética contra orgullo y violencia.',
   'Babilonia, instrumento temporal de juicio, también queda bajo juicio. La liberación de Joaquín al final mantiene abierta la continuidad davídica.',
   'Colecciones geográficas de oráculos culminan en un extenso anuncio contra Babilonia y un apéndice paralelo a Reyes.',
   'Afirmar que ningún imperio que ejerce violencia posee autorización ilimitada, y que incluso después de la destrucción queda un pequeño signo de futuro.',
   'La esperanza puede sobrevivir en gestos modestos que no deshacen el daño, pero impiden declarar cerrada la historia.',
   'Las naciones antiguas no deben identificarse directamente con países modernos para producir predicciones. La caída de Babilonia no autoriza celebrar sufrimiento civil.',
   ARRAY['naciones','Egipto','Moab','Babilonia','Joaquín','imperio']::text[],
   ARRAY['egipcios','filisteos','moabitas','amonitas','edomitas','babilonios','judíos']::text[],
   ARRAY['Egipto','Moab','Edom','Damasco','Babilonia','Jerusalén']::text[]),
  ('lamentaciones-perfil','LAM','book',1,NULL::smallint,5,NULL::smallint,
   'Lamentaciones: duelo comunitario por Jerusalén',
   'Lamentaciones reúne cinco poemas que lloran la destrucción de Jerusalén, describen pérdida, hambre, humillación y silencio y buscan palabras para dirigirse a Dios después de una catástrofe nacional.',
   'Los poemas responden a la conquista babilónica y a la destrucción del templo en 586/587 a. C. El trauma afectó ciudad, culto, liderazgo, familias y economía.',
   'Eijá se lee en Tishá BeAv para recordar la destrucción de los templos y otras tragedias. El libro permite que la comunidad conserve memoria y duelo sin apresurar una explicación.',
   'Cuatro poemas emplean formas acrósticas y el quinto mantiene veintidós versos. La forma ordenada intenta contener una experiencia profundamente desordenada.',
   'Dar lenguaje público al dolor, reconocer responsabilidad sin silenciar a las víctimas y mantener abierta la conversación con Dios cuando la estructura religiosa ha colapsado.',
   'Lamentar en comunidad es una práctica de memoria y cuidado. La esperanza puede aparecer como una frase frágil dentro del dolor, no como exigencia de sentirse bien.',
   'El libro contiene imágenes intensas propias de poesía de guerra y duelo; no deben describirse de manera sensacionalista ni usarse para culpabilizar a quienes sufren. La tradición atribuye el libro a Jeremías, pero el texto no identifica explícitamente a su autor.',
   ARRAY['Eijá','Jerusalén','duelo','destrucción','templo','memoria','esperanza']::text[],
   ARRAY['habitantes de Jerusalén','exiliados','babilonios']::text[],
   ARRAY['Jerusalén','Sion','Babilonia']::text[]),
  ('lamentaciones-1-2-ciudad','LAM','section',1,NULL::smallint,2,NULL::smallint,
   'La ciudad abandonada y el día de destrucción',
   'Jerusalén aparece como una mujer que llora su aislamiento, pérdida de aliados y sufrimiento; el segundo poema dirige con mayor intensidad la queja hacia la acción divina y el fracaso de líderes.',
   'Las ciudades antiguas eran personificadas como mujeres o madres. La destrucción implicó deportación, ruina económica y pérdida del centro cultual.',
   'Hija de Sion es una figura poética comunitaria. Su voz permite que la ciudad sea sujeto de duelo y no solo objeto de análisis histórico.',
   'Acrósticos con voz en tercera y primera persona alternan observación y testimonio, haciendo visible tanto la ciudad como las personas dentro de ella.',
   'Reconocer que una comunidad herida necesita ser escuchada antes de ser corregida y que el lenguaje de fe puede incluir acusación, pregunta y memoria de abandono.',
   'El duelo no necesita ser ordenado emocionalmente para ser válido. Nombrar pérdida y ausencia puede preservar dignidad y abrir espacio para acompañamiento.',
   'La personificación femenina no debe usarse para sexualizar o culpar a mujeres reales. Las afirmaciones sobre juicio no permiten concluir que cada víctima individual merecía lo ocurrido.',
   ARRAY['hija de Sion','duelo','abandono','líderes','destrucción']::text[],
   ARRAY['habitantes de Jerusalén','líderes','exiliados']::text[],
   ARRAY['Jerusalén','Sion']::text[]),
  ('lamentaciones-3-5-esperanza-peticion','LAM','section',3,NULL::smallint,5,NULL::smallint,
   'Lamento individual, memoria de misericordia y petición comunitaria',
   'Una voz individual describe aflicción, recuerda la misericordia y espera; después la comunidad contrasta antiguas dignidades con su situación y termina pidiendo a Dios que la haga volver.',
   'El trauma continuó después de la caída mediante hambre, desplazamiento, trabajo forzado e inseguridad. La restauración no ocurrió de inmediato.',
   'Las líneas sobre misericordias nuevas cada mañana están dentro de un lamento extenso, no fuera del sufrimiento. La petición final conserva tensión porque termina con una pregunta no resuelta.',
   'El acróstico triple del capítulo 3 ocupa el centro; los capítulos 4 y 5 regresan a memoria colectiva y oración abierta.',
   'Mostrar que la esperanza bíblica puede surgir dentro del lamento sin negar la gravedad de la pérdida y que la comunidad tiene derecho a pedir restauración.',
   'Recordar fidelidad en medio del dolor no obliga a sentir alivio inmediato. La última oración permite permanecer esperando sin fingir cierre.',
   '«Bueno es esperar en silencio» no debe usarse para silenciar denuncias de abuso o injusticia. Las misericordias nuevas no invalidan terapia, apoyo comunitario ni procesos largos de duelo.',
   ARRAY['misericordia','espera','memoria','comunidad','retorno','oración']::text[],
   ARRAY['exiliados','sobrevivientes','comunidad de Judá']::text[],
   ARRAY['Jerusalén','Sion']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/profetas-mayores/v1#' || data.slug,
  'profetas-mayores-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','major-prophets','generated_by_ai',false,'review_level','editorial')
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();