-- FASE D · Bloque 4 · Poesía y sabiduría 2: Salmos
update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code = 'PSA';

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('salmos-perfil','PSA','book',1,NULL::smallint,150,NULL::smallint,
   'Salmos: oración, poesía y memoria de Israel',
   'Salmos reúne ciento cincuenta poemas de alabanza, lamento, confianza, sabiduría, realeza, acción de gracias y peregrinación que enseñan a la comunidad a hablar con Dios en toda circunstancia.',
   'Los salmos surgieron y fueron recopilados durante distintos periodos de la historia de Israel, desde memorias monárquicas hasta contextos de templo, exilio y restauración. Los títulos preservan tradiciones antiguas, pero no siempre permiten fechar con certeza cada poema.',
   'Tehillim ocupa un lugar central en la oración judía diaria, las fiestas, el duelo y la celebración. Algunos salmos forman Hallel, otros acompañan peregrinaciones y muchos fueron reutilizados en nuevas circunstancias.',
   'La colección está dividida en cinco libros y utiliza paralelismo, imágenes, repeticiones, acrósticos, inclusiones y cambios de voz. Un salmo expresa una voz poética, no necesariamente una crónica literal de cada detalle.',
   'Formar una comunidad capaz de alabar, lamentar, confesar, protestar, recordar y esperar ante Dios, integrando emoción, memoria y fidelidad.',
   'La oración bíblica no exige ocultar miedo, enojo o tristeza. Llevar esas emociones a Dios puede impedir que se conviertan en violencia o desesperanza y puede abrir camino hacia confianza y justicia.',
   'Las metáforas no deben leerse como descripciones científicas. Los salmos imprecatorios expresan dolor y petición de justicia, pero no autorizan venganza personal ni violencia religiosa. Las atribuciones a David u otras figuras deben distinguir tradición del título y certeza histórica.',
   ARRAY['Tehillim','alabanza','lamento','confianza','realeza','sabiduría','peregrinación']::text[],
   ARRAY['Israel','levitas','peregrinos','comunidad de adoración']::text[],
   ARRAY['Jerusalén','Sion','templo']::text[]),
  ('salmos-1-2-portal','PSA','section',1,NULL::smallint,2,NULL::smallint,
   'Portal del salterio: Torá y rey',
   'Los dos primeros salmos presentan la vida arraigada en la enseñanza de Dios y la oposición de las naciones al rey ungido, estableciendo sabiduría y realeza como claves de lectura.',
   'La imagen del árbol junto a corrientes y el lenguaje de entronización pertenecen a mundos agrícolas y monárquicos del antiguo Cercano Oriente.',
   'El estudio de la Torá de día y de noche se relaciona con una vida formada continuamente por la enseñanza. El Salmo 2 fue leído dentro de expectativas davídicas y mesiánicas posteriores.',
   'El contraste entre dos caminos en Salmo 1 se une al conflicto entre reinos en Salmo 2. Ambos terminan con imágenes de destino y refugio.',
   'Invitar al lector a entrar al salterio desde una vida orientada por la enseñanza y la confianza en el gobierno de Dios, no por la presión de mayorías o poderes.',
   'La estabilidad espiritual no significa ausencia de estaciones difíciles; describe raíces profundas que permiten perseverar y producir fruto en su tiempo.',
   'El justo no debe imaginarse como persona sin preguntas ni fallas. El lenguaje de quebrar naciones pertenece a poesía real antigua y no autoriza dominación política o violencia cristiana.',
   ARRAY['Torá','dos caminos','árbol','ungido','naciones','refugio']::text[],
   ARRAY['justos','malvados','naciones','reyes']::text[],
   ARRAY['Sion']::text[]),
  ('salmos-libro-1','PSA','section',3,NULL::smallint,41,NULL::smallint,
   'Libro I: lamentos de David, confianza y refugio',
   'El primer libro contiene numerosos salmos atribuidos a David que alternan persecución, enfermedad, confesión, confianza, celebración de la creación y deseo de justicia.',
   'Las referencias a enemigos, corte real, guerra y enfermedad reflejan experiencias comunes de vulnerabilidad en sociedades antiguas, pero muchos poemas fueron adaptados para uso comunitario posterior.',
   'La tradición davídica permite que la experiencia del rey se convierta en lenguaje de oración para toda persona. Salmos como 8, 19, 23 y 32 ocupan lugares importantes en liturgia y enseñanza.',
   'Los poemas usan cambios rápidos entre queja y confianza. El nombre divino, el refugio, el camino y la presencia aparecen como hilos repetidos.',
   'Enseñar a expresar peligro, culpa y gratitud sin abandonar la relación con Dios, y mostrar que la confianza puede desarrollarse dentro del problema antes de su resolución.',
   'La persona puede pedir ayuda con honestidad y, a la vez, recordar experiencias previas de cuidado. La oración no necesita negar el cuerpo ni las emociones.',
   'Los enemigos del salmista no deben identificarse automáticamente con personas que discrepan con nosotros. Las descripciones de enfermedad no permiten diagnósticos médicos ni afirmar que toda dolencia procede de culpa.',
   ARRAY['David','refugio','enemigos','creación','confesión','pastor','presencia']::text[],
   ARRAY['orantes','enemigos','comunidad de Israel']::text[],
   ARRAY['Sion','templo']::text[]),
  ('salmos-libro-2','PSA','section',42,NULL::smallint,72,NULL::smallint,
   'Libro II: sed de Dios, crisis y esperanza real',
   'El segundo libro inicia con anhelo por la presencia divina, reúne salmos de los hijos de Coré y de David y concluye con una oración por un rey que defienda al pobre y extienda justicia.',
   'La distancia del santuario, las guerras, la corte y las relaciones internacionales aparecen en poemas que pudieron reutilizarse durante crisis nacionales y personales.',
   'Los hijos de Coré están vinculados con servicio musical. El Salmo 72 imagina la función real como defensa del vulnerable y fue asociado posteriormente con esperanza mesiánica.',
   'Refranes repetidos, diálogos con el alma y colecciones atribuidas a distintos grupos crean una unidad donde la ausencia percibida se mueve hacia confianza y justicia pública.',
   'Mostrar que el deseo de Dios puede convivir con desaliento y que la adoración auténtica incluye esperar un liderazgo que proteja a quienes carecen de poder.',
   'Hablar con el alma no es negar la tristeza; es recordar en medio de ella. La esperanza puede repetirse antes de sentirse plenamente.',
   'El desaliento del salmista no debe estigmatizarse ni tratarse como simple falta de fe. Las imágenes del rey universal no autorizan imperios religiosos modernos.',
   ARRAY['hijos de Coré','sed','alma','santuario','rey','pobre','justicia']::text[],
   ARRAY['levitas','rey','pobres','naciones']::text[],
   ARRAY['Jordán','Sion','Jerusalén']::text[]),
  ('salmos-libro-3','PSA','section',73,NULL::smallint,89,NULL::smallint,
   'Libro III: crisis del santuario y del pacto davídico',
   'El tercer libro enfrenta la prosperidad del injusto, la destrucción del santuario, la vulnerabilidad nacional y la aparente contradicción entre la promesa a David y la caída del reino.',
   'Muchos salmos reflejan o fueron releídos a la luz de derrotas, invasiones y destrucción de Jerusalén. La memoria del templo y de la dinastía se convierte en pregunta teológica.',
   'Asaf y los hijos de Coré representan tradiciones levíticas. El Salmo 73 encuentra nueva perspectiva dentro del santuario, mientras el 89 termina sin resolver completamente la crisis del pacto.',
   'La colección se oscurece progresivamente y culmina con un lamento sobre la promesa real. El Salmo 88 es notable porque no termina con una declaración explícita de alivio.',
   'Dar lenguaje a una comunidad cuya experiencia parece contradecir sus convicciones y permitir que la fe sostenga preguntas sin fabricar una resolución rápida.',
   'No toda oración termina emocionalmente en triunfo. Permanecer dirigiéndose a Dios en la oscuridad también puede ser una forma de fidelidad.',
   'La prosperidad visible no demuestra aprobación divina. El Salmo 88 no debe corregirse artificialmente con un final alegre ni usarse para decir que la tristeza es permanente; conserva una voz legítima dentro de una colección más amplia.',
   ARRAY['Asaf','santuario','crisis','prosperidad del injusto','pacto davídico','lamento']::text[],
   ARRAY['levitas','comunidad de Judá','enemigos nacionales']::text[],
   ARRAY['Jerusalén','Sion','santuario']::text[]),
  ('salmos-libro-4','PSA','section',90,NULL::smallint,106,NULL::smallint,
   'Libro IV: Dios reina más allá de la caída del reino',
   'El cuarto libro comienza con una oración atribuida a Moisés y responde a la crisis monárquica proclamando que Dios reina, recordando la creación, el éxodo y la fragilidad humana.',
   'Después de la pérdida de la monarquía, la comunidad podía reencontrar estabilidad en el reinado divino, la memoria del desierto y el orden de la creación.',
   'Los salmos de entronización son importantes en la liturgia judía. El Salmo 92 se asocia con el sábado y los Salmos 95–99 llaman a la adoración universal.',
   'La mortalidad humana en Salmo 90 conduce a proclamaciones de reinado y a una revisión histórica que reconoce repetidas infidelidades.',
   'Reorientar la confianza desde instituciones humanas caídas hacia el gobierno duradero de Dios y una vida sabia que reconoce sus límites.',
   'Contar los días no significa vivir con miedo, sino recibir el tiempo con humildad, responsabilidad y gratitud. La adoración puede restaurar perspectiva después de pérdidas colectivas.',
   '«No te sucederá mal» en el Salmo 91 no es garantía de invulnerabilidad física ni debe utilizarse para rechazar medidas de seguridad. La protección poética se lee dentro de una colección que reconoce sufrimiento real.',
   ARRAY['Moisés','mortalidad','Dios reina','sábado','creación','éxodo','sabiduría']::text[],
   ARRAY['Israel','naciones','adoradores']::text[],
   ARRAY['desierto','Sion']::text[]),
  ('salmos-libro-5','PSA','section',107,NULL::smallint,150,NULL::smallint,
   'Libro V: retorno, peregrinación, Torá y alabanza final',
   'El último libro celebra rescate y retorno, incluye el gran poema de la Torá, los cánticos de ascenso, nuevos salmos davídicos y una conclusión donde toda la creación es llamada a alabar.',
   'Los temas de reunión desde las naciones, peregrinación a Jerusalén y reconstrucción comunitaria encajan con experiencias posteriores al exilio, aunque las piezas tienen orígenes diversos.',
   'Los Salmos 113–118 forman el Hallel usado en fiestas; los Salmos 120–134 acompañan la memoria de ascenso a Jerusalén; el Salmo 119 medita extensamente en la Torá.',
   'Acción de gracias, acrósticos, peregrinación y una creciente secuencia de aleluyas llevan al salterio desde múltiples crisis hacia una doxología abierta.',
   'Mostrar que una comunidad restaurada necesita recordar liberaciones, caminar junta, amar la enseñanza y convertir su historia en alabanza que incluya a toda la creación.',
   'La gratitud no borra el pasado; lo transforma en memoria que sostiene el presente. La peregrinación recuerda que la vida espiritual es camino compartido.',
   'El Salmo 137 conserva dolor de exiliados y lenguaje extremo contra Babilonia; no autoriza daño a civiles ni venganza. El Salmo 119 no enseña perfeccionismo, sino una relación perseverante con la enseñanza.',
   ARRAY['retorno','Hallel','cánticos de ascenso','Torá','peregrinación','aleluya']::text[],
   ARRAY['exiliados','peregrinos','levitas','naciones']::text[],
   ARRAY['Babilonia','Jerusalén','Sion']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select
  data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/poesia-sabiduria/v1#' || data.slug,
  'poesia-sabiduria-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','poetry-wisdom','generated_by_ai',false,'review_level','editorial')
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();