-- FASE D · Bloque 4 · Lote histórico 4: Esdras, Nehemías y Ester
update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code in ('EZR','NEH','EST');

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('esdras-perfil','EZR','book',1,NULL::smallint,10,NULL::smallint,
   'Esdras: retorno, templo, Torá e identidad comunitaria',
   'Esdras reúne memorias del retorno bajo Persia, la reconstrucción del templo y la misión del escriba Esdras para enseñar la Torá y reorganizar a la comunidad.',
   'El imperio persa permitió retornos y restauración de santuarios dentro de una política de administración provincial. Judá era una pequeña provincia vinculada a comunidades judías que permanecían en la diáspora.',
   'El templo restaurado, las genealogías y la enseñanza de la Torá fueron pilares de una identidad judía sin monarquía independiente. Partes del libro están escritas en arameo imperial.',
   'Edictos, listas, correspondencia aramea, narraciones de construcción y memorias en primera persona forman dos grandes movimientos: templo y reforma comunitaria.',
   'Mostrar que la restauración requiere reconstrucción material, memoria, enseñanza y discernimiento, pero también que las decisiones de identidad pueden producir dolor y deben examinarse críticamente.',
   'Volver a comenzar exige paciencia frente a oposición, colaboración entre generaciones y una relación renovada con la Escritura.',
   'Los conflictos sobre matrimonios mixtos no deben utilizarse para justificar racismo, xenofobia ni prohibiciones basadas en etnia. El problema se presenta dentro de preocupaciones antiguas de pacto e identidad y debe leerse junto con Rut y otras voces bíblicas.',
   ARRAY['retorno','templo','Torá','Esdras','genealogías','identidad']::text[],
   ARRAY['judíos retornados','persas','pueblos vecinos','levitas']::text[],
   ARRAY['Babilonia','Jerusalén','Yehud','Persia']::text[]),
  ('esdras-1-6-templo','EZR','section',1,NULL::smallint,6,NULL::smallint,
   'Retorno y reconstrucción del templo',
   'Ciro autoriza el retorno, grupos dirigidos por Sesbasar y Zorobabel vuelven, restauran el altar y reconstruyen el templo a pesar de oposición y demoras.',
   'Los reyes persas administraban diversidad religiosa mediante decretos y autoridades provinciales. Las interrupciones de la obra se relacionan con cambios políticos y disputas territoriales.',
   'El segundo templo no iguala la memoria del primero, y la reacción combina alegría y llanto. Hageo y Zacarías apoyan proféticamente la reconstrucción.',
   'Listas de retornados, una ceremonia de fundamento, cartas oficiales y una investigación de archivos convierten la obra local en un asunto imperial.',
   'Enseñar que la restauración puede parecer modesta y enfrentar interrupciones, pero la memoria, la cooperación y la perseverancia permiten concluir una tarea comunitaria.',
   'La comparación con un pasado ideal puede producir duelo, pero no debe impedir reconocer la obra presente. Celebrar y lamentar pueden coexistir.',
   'Los adversarios del relato no deben identificarse sin matices con comunidades étnicas posteriores. La negativa a colaborar refleja disputas de autoridad y culto, no una licencia general para excluir ayuda externa.',
   ARRAY['Ciro','Zorobabel','altar','segundo templo','oposición','retorno']::text[],
   ARRAY['judíos retornados','persas','pueblos de la región']::text[],
   ARRAY['Babilonia','Jerusalén','Ecbatana']::text[]),
  ('esdras-7-10-tora','EZR','section',7,NULL::smallint,10,NULL::smallint,
   'Esdras, enseñanza de la Torá y crisis matrimonial',
   'Esdras llega con autorización persa, organiza recursos para el templo, enseña la ley y enfrenta una crisis por matrimonios con personas de otros pueblos.',
   'Los escribas adquirieron creciente importancia en una comunidad administrada por Persia. El matrimonio, la tierra y la pertenencia estaban vinculados a continuidad familiar y política.',
   'Esdras es recordado como maestro de la Torá. La confesión colectiva reconoce infidelidad, pero la separación de familias genera una de las tensiones éticas más difíciles del libro.',
   'Una misión autorizada y una oración de humildad conducen a listas y procedimientos comunitarios. El libro termina de forma abrupta, sin mostrar plenamente las consecuencias humanas.',
   'Afirmar la importancia de estudiar, practicar y enseñar, a la vez que obliga a examinar cómo una comunidad protege identidad sin causar injusticia.',
   'La fidelidad a la Escritura necesita humildad, transparencia y atención a quienes pueden resultar heridos por decisiones institucionales.',
   'El texto no enseña superioridad étnica. No debe utilizarse para separar familias actuales ni condenar matrimonios interraciales; la Biblia conserva otras voces que integran extranjeros fieles y cuestionan lecturas absolutas.',
   ARRAY['Esdras','Torá','escriba','confesión','matrimonios mixtos','identidad']::text[],
   ARRAY['judíos retornados','levitas','pueblos vecinos']::text[],
   ARRAY['Babilonia','Jerusalén']::text[]),
  ('nehemias-perfil','NEH','book',1,NULL::smallint,13,NULL::smallint,
   'Nehemías: reconstrucción, justicia y reforma comunitaria',
   'Nehemías narra la reconstrucción de las murallas de Jerusalén, la defensa frente a oposición, la lectura pública de la Torá y varias reformas sociales y cultuales.',
   'Nehemías sirvió dentro de la administración persa y recibió autoridad como gobernador de Yehud. Las murallas tenían funciones defensivas, administrativas y simbólicas para una ciudad vulnerable.',
   'La lectura de la Torá, la confesión histórica y la celebración de Sucot expresan renovación comunitaria. El libro también preserva tensiones sobre sábado, templo, deuda e identidad.',
   'Memorias en primera persona, listas, oraciones y narración comunitaria se organizan alrededor de construcción física y reconstrucción social.',
   'Mostrar que el liderazgo puede combinar oración, planificación y acción, pero debe ser evaluado por su defensa del pobre, su transparencia y la manera en que ejerce autoridad.',
   'La reconstrucción espiritual incluye estructuras seguras, justicia económica, enseñanza y revisión constante de prácticas que se desvían del propósito original.',
   'Nehemías no debe usarse como manual empresarial infalible ni sus acciones enérgicas como autorización para intimidación pastoral. Sus reformas finales deben leerse dentro de una crisis postexílica específica.',
   ARRAY['Nehemías','muralla','Jerusalén','Torá','justicia económica','reforma']::text[],
   ARRAY['judíos retornados','persas','pueblos vecinos','levitas']::text[],
   ARRAY['Susa','Jerusalén','Yehud']::text[]),
  ('nehemias-1-7-murallas','NEH','section',1,NULL::smallint,7,NULL::smallint,
   'Oración, organización y reconstrucción de las murallas',
   'Nehemías recibe noticias de Jerusalén, obtiene permiso real, inspecciona la ciudad y coordina familias y oficios para reconstruir mientras enfrenta burla, amenazas y conspiraciones.',
   'Una ciudad sin murallas estaba expuesta militarmente y debilitada administrativamente. La autorización persa y el acceso a materiales fueron esenciales para el proyecto.',
   'La oración de Nehemías confiesa pecados colectivos y apela al pacto. La lista de constructores muestra una obra distribuida entre sacerdotes, familias, artesanos y autoridades.',
   'Oración, petición política, inspección discreta, listas de trabajo y escenas de oposición presentan una estrategia que adapta sus respuestas sin abandonar la tarea.',
   'Enseñar que la fe responsable puede investigar, planificar, distribuir tareas, proteger a la comunidad y responder a amenazas sin depender de improvisación permanente.',
   'Orar y organizar no son opuestos. Una visión compartida se fortalece cuando cada persona entiende su responsabilidad y la seguridad se toma en serio.',
   'La oposición no significa automáticamente que un proyecto tenga aprobación divina; las metas y métodos también necesitan evaluación. Los enemigos no deben convertirse en etiquetas para cualquier persona que hace preguntas legítimas.',
   ARRAY['Nehemías','murallas','oración','planificación','oposición','trabajo comunitario']::text[],
   ARRAY['judíos retornados','samaritanos','amonitas','árabes']::text[],
   ARRAY['Susa','Jerusalén']::text[]),
  ('nehemias-8-10-renovacion','NEH','section',8,NULL::smallint,10,NULL::smallint,
   'Lectura de la Torá, Sucot y renovación',
   'Esdras lee la Torá ante la asamblea, los levitas explican su sentido, la comunidad celebra Sucot, confiesa su historia y firma compromisos de pacto.',
   'Las reuniones públicas y la enseñanza bilingüe o explicativa respondían a una población formada por retornados con experiencias lingüísticas y sociales diversas.',
   'Nehemías 8 es fundamental para la lectura pública y comprensible de la Escritura. La fiesta de Sucot conecta a la comunidad asentada con la memoria de vivir en tiendas.',
   'Lectura, explicación, emoción, celebración y confesión forman una pedagogía donde comprender conduce tanto a alegría como a responsabilidad.',
   'Mostrar que la Escritura debe ser comprendida, no solamente recitada, y que una renovación auténtica integra celebración, memoria, confesión y compromisos concretos.',
   'La comprensión puede producir lágrimas, pero el propósito no es mantener a la comunidad en culpa permanente. La alegría compartida y el cuidado de quien no tiene provisión son parte de la respuesta.',
   '«El gozo del Señor es su fuerza» no debe utilizarse para silenciar duelo o tristeza. En el pasaje, la alegría surge junto con explicación, arrepentimiento y distribución de alimentos.',
   ARRAY['Esdras','Torá','Sucot','confesión','alegría','pacto']::text[],
   ARRAY['judíos retornados','levitas']::text[],
   ARRAY['Jerusalén']::text[]),
  ('nehemias-11-13-reformas','NEH','section',11,NULL::smallint,13,NULL::smallint,
   'Repoblación, dedicación y reformas finales',
   'Se organizan habitantes de Jerusalén, se dedica la muralla y Nehemías enfrenta descuido del templo, comercio en sábado y matrimonios que amenazan la transmisión comunitaria.',
   'Repoblar una capital requería incentivos y reorganización. El templo dependía de contribuciones, almacenes y funciones levíticas dentro de una economía frágil.',
   'El sábado, el servicio levítico y la transmisión de lengua e identidad son preocupaciones centrales. Las reacciones severas de Nehemías reflejan urgencia y conflicto, no necesariamente un modelo universal de liderazgo.',
   'La alegría de la dedicación es seguida por un final incómodo: las reformas no permanecen automáticamente y el líder vuelve a encontrar problemas.',
   'Comunicar que una ceremonia exitosa no garantiza continuidad; las instituciones necesitan cuidado, justicia y revisión después del entusiasmo inicial.',
   'La fidelidad diaria después de una inauguración es tan importante como el evento público. Las reformas deben proteger la vida comunitaria sin deshumanizar a las personas.',
   'Los actos físicos y amenazas de Nehemías no autorizan coerción religiosa. Los conflictos matrimoniales y lingüísticos no justifican racismo ni hostilidad contra familias multiculturales.',
   ARRAY['dedicación','sábado','levitas','reforma','Jerusalén','identidad']::text[],
   ARRAY['judíos retornados','levitas','comerciantes','pueblos vecinos']::text[],
   ARRAY['Jerusalén','Asdod','Tiro']::text[]),
  ('ester-perfil','EST','book',1,NULL::smallint,10,NULL::smallint,
   'Ester: diáspora, poder, identidad y supervivencia',
   'Ester narra cómo una joven judía llega a ser reina en Persia y, junto con Mardoqueo, enfrenta un decreto de exterminio contra su pueblo mediante estrategia, ayuno y acción política.',
   'La historia se desarrolla en la corte persa de Susa y refleja banquetes, burocracia imperial, decretos, jerarquías y vulnerabilidad de minorías dentro de un vasto imperio.',
   'Ester fundamenta la fiesta de Purim. El texto hebreo no menciona explícitamente a Dios, por lo que la tradición ha reflexionado sobre providencia oculta, agencia humana y supervivencia en la diáspora.',
   'Banquetes, inversiones de destino, ironía, repeticiones y una rápida cadena de decretos crean una narración donde quienes parecen poderosos terminan expuestos.',
   'Mostrar que la identidad puede requerir prudencia y valentía, y que las personas dentro de sistemas de poder pueden utilizar su posición para proteger a comunidades amenazadas.',
   'El silencio explícito sobre Dios no equivale a ausencia. La fe también puede expresarse mediante ayuno, sabiduría, solidaridad y decisiones costosas en circunstancias ambiguas.',
   'La historia no debe convertirse en fantasía romántica de concurso de belleza; las mujeres son reunidas bajo poder imperial. La violencia final y la muerte de enemigos requieren contexto de defensa y retórica antigua, no celebración ni imitación.',
   ARRAY['Ester','Mardoqueo','Amán','Purim','diáspora','providencia','Persia']::text[],
   ARRAY['judíos de la diáspora','persas']::text[],
   ARRAY['Susa','Persia']::text[]),
  ('ester-1-4-crisis','EST','section',1,NULL::smallint,4,NULL::smallint,
   'Corte persa, ascenso de Ester y decreto de exterminio',
   'Tras la destitución de Vasti, Ester es llevada al palacio y llega a ser reina; Mardoqueo descubre una conspiración y el ascenso de Amán conduce a un decreto contra los judíos.',
   'La corte controlaba acceso, matrimonios reales y administración mediante eunucos y funcionarios. Los decretos imperiales se distribuyen por una red multilingüe.',
   'La identidad de Ester permanece oculta al inicio. El ayuno colectivo del capítulo 4 sustituye una mención explícita de oración y prepara su decisión de presentarse ante el rey.',
   'Banquetes y decisiones aparentemente casuales construyen tensión hasta la pregunta de Mardoqueo sobre haber llegado al reino para una hora como esta.',
   'Mostrar cómo una amenaza colectiva obliga a pasar de supervivencia privada a responsabilidad pública, sin negar el miedo ni el riesgo real.',
   'La valentía no es ausencia de temor. Ester escucha, convoca a la comunidad y actúa después de prepararse, mostrando una combinación de dependencia y estrategia.',
   '«Para esta hora» no significa que toda posición social sea prueba segura de un destino divino específico. Vasti no debe ser demonizada por negarse a aparecer ante una corte intoxicada.',
   ARRAY['Vasti','Ester','Mardoqueo','Amán','decreto','ayuno','valentía']::text[],
   ARRAY['judíos de la diáspora','persas']::text[],
   ARRAY['Susa','Persia']::text[]),
  ('ester-5-9-reversion','EST','section',5,NULL::smallint,9,NULL::smallint,
   'Banquetes, caída de Amán y reversión del decreto',
   'Ester se presenta ante el rey, organiza banquetes, expone a Amán y obtiene un nuevo decreto que permite a los judíos defenderse, mientras Mardoqueo recibe autoridad.',
   'La supuesta irrevocabilidad de decretos persas crea la necesidad narrativa de emitir una autorización contraria. La defensa comunitaria ocurre dentro de un sistema imperial violento.',
   'Purim recuerda la transformación de duelo en celebración y el envío de porciones y ayuda al pobre. El nombre de la fiesta proviene del pur o suerte usada por Amán.',
   'Insomnio, lectura de archivos, banquetes y honores invertidos producen una reversión cuidadosamente escalonada donde el instrumento preparado contra Mardoqueo alcanza a Amán.',
   'Mostrar que la arrogancia y el uso genocida del poder pueden ser desenmascarados, y que la acción política debe buscar la supervivencia de quienes están bajo amenaza.',
   'La celebración bíblica incluye memoria del peligro y solidaridad material. La liberación no debe borrar la responsabilidad de cuidar a quienes siguen vulnerables.',
   'El número de muertos y la petición de un día adicional plantean preguntas éticas. Deben leerse como conflicto de supervivencia dentro de violencia imperial, no como autorización para venganzas religiosas o étnicas.',
   ARRAY['banquetes','reversión','Amán','Mardoqueo','Purim','defensa']::text[],
   ARRAY['judíos de la diáspora','persas','enemigos del pueblo judío']::text[],
   ARRAY['Susa','provincias persas']::text[]),
  ('ester-10-conclusion','EST','section',10,NULL::smallint,10,NULL::smallint,
   'Mardoqueo y el bienestar de su pueblo',
   'El breve cierre presenta el poder imperial de Asuero y la elevada posición de Mardoqueo, quien busca el bienestar de su pueblo y habla paz para su comunidad.',
   'Las conclusiones de corte suelen registrar tributo, autoridad y memoria oficial. El relato termina sin transformar el imperio en una sociedad ideal.',
   'Mardoqueo es recordado por utilizar influencia a favor de su pueblo, y Purim mantiene viva la memoria de amenaza y supervivencia.',
   'Un epílogo administrativo contrasta con los banquetes y peligros anteriores y resume el resultado político de la reversión.',
   'Concluir que la influencia pública debe medirse por el bienestar y la paz que procura para otros, especialmente para comunidades amenazadas.',
   'La promoción personal encuentra sentido cuando se convierte en servicio y defensa del prójimo, no solamente en seguridad privada.',
   'El éxito de Mardoqueo no significa que todos los problemas de la diáspora desaparecieron ni que cercanía al poder garantice justicia permanente.',
   ARRAY['Mardoqueo','bienestar','paz','influencia','diáspora']::text[],
   ARRAY['judíos de la diáspora','persas']::text[],
   ARRAY['Susa','Persia']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select
  data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/historicos/v1#' || data.slug,
  'historicos-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','historical-books','generated_by_ai',false,'review_level','editorial')
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();