-- FASE D · Bloque 4 · Poesía y sabiduría 3: Proverbios
update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code = 'PRO';

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('proverbios-perfil','PRO','book',1,NULL::smallint,31,NULL::smallint,
   'Proverbios: sabiduría práctica, carácter y temor de Dios',
   'Proverbios reúne instrucciones, colecciones de dichos y poemas que forman criterio para hablar, trabajar, relacionarse, administrar recursos, ejercer poder y escoger entre sabiduría y necedad.',
   'La sabiduría era cultivada en hogares, cortes y escuelas de escribas del antiguo Cercano Oriente. Algunas secciones muestran afinidades con colecciones egipcias y otras tradiciones, reelaboradas dentro de la fe de Israel.',
   'Mishlé pertenece a los Escritos. El temor de YHWH funciona como principio de conocimiento y vincula la habilidad práctica con reverencia, justicia y humildad.',
   'El libro reúne varios encabezados y colecciones. Usa paralelismo, contraste, comparación, personificación de Sabiduría y Necedad y observaciones breves que requieren aplicarse con discernimiento.',
   'Formar personas capaces de reconocer consecuencias probables, controlar palabras y deseos, proteger al vulnerable y aprender de corrección, sin reducir la vida a reglas mecánicas.',
   'La sabiduría se cultiva mediante escucha, práctica y humildad. Una decisión prudente no controla el futuro, pero puede orientar la vida hacia justicia, paz y responsabilidad.',
   'Los proverbios son máximas generales, no promesas universales ni fórmulas para culpar a quien sufre. Dos dichos aparentemente distintos pueden responder a situaciones diferentes; deben leerse en contexto y en diálogo con Job y Eclesiastés.',
   ARRAY['sabiduría','necedad','temor de YHWH','palabras','trabajo','justicia','disciplina']::text[],
   ARRAY['sabios','jóvenes','familias','reyes','pobres']::text[],
   ARRAY['Israel','Jerusalén']::text[]),
  ('proverbios-1-9-instrucciones','PRO','section',1,NULL::smallint,9,NULL::smallint,
   'Discursos de formación y las dos mujeres simbólicas',
   'Una voz parental exhorta a buscar sabiduría, resistir presión de grupos violentos, cuidar el corazón y reconocer las invitaciones opuestas de Sabiduría y Necedad.',
   'La instrucción familiar y la preparación de jóvenes para la vida pública eran esenciales en sociedades sin sistemas educativos universales. Calles, puertas y plazas eran espacios de decisión social.',
   'La Sabiduría personificada habla públicamente y es presentada junto a Dios en la creación. La tradición judía la relaciona con la Torá sin convertir la figura poética en una deidad independiente.',
   'Discursos extensos, advertencias y poemas culminan en dos banquetes simbólicos: uno conduce a vida y otro a destrucción.',
   'Invitar a formar deseos y criterio antes de enfrentar decisiones complejas, y mostrar que toda elección repetida construye un tipo de persona.',
   'Cuidar el corazón significa atender la fuente de pensamientos, motivaciones y decisiones, no vigilar emociones con miedo. La sabiduría llama con claridad y puede aprenderse.',
   'Las advertencias sobre la mujer ajena pertenecen a una instrucción dirigida principalmente a varones jóvenes y no deben usarse para culpar a mujeres por decisiones masculinas. Sabiduría y Necedad son personificaciones literarias, no estereotipos de género aplicables a personas reales.',
   ARRAY['Sabiduría','Necedad','corazón','camino','disciplina','tentación']::text[],
   ARRAY['jóvenes','familias','sabios']::text[],
   ARRAY['calles','plazas','puertas de la ciudad']::text[]),
  ('proverbios-10-22-dichos-salomon','PRO','section',10,NULL::smallint,22,NULL::smallint,
   'Dichos de Salomón sobre vida cotidiana',
   'Cientos de máximas breves contrastan justo y malvado, diligencia y pereza, verdad y engaño, generosidad y codicia, dominio propio y habla destructiva.',
   'Los dichos reflejan agricultura, comercio, tribunales, hogares, servicio real y relaciones vecinales. Su brevedad facilitaba memoria y enseñanza oral.',
   'La justicia se mide también por balanzas honestas, cuidado del pobre y uso responsable de palabras. La bendición no se separa de conducta comunitaria.',
   'El paralelismo antitético domina: una línea ilumina a la otra mediante contraste. Los temas reaparecen sin un orden sistemático rígido, imitando decisiones repetidas de la vida.',
   'Entrenar la percepción moral para detectar pequeñas prácticas que, acumuladas, producen confianza, violencia, estabilidad o ruina.',
   'El carácter se manifiesta en hábitos cotidianos más que en momentos excepcionales. Escuchar antes de hablar y trabajar con integridad son prácticas espirituales.',
   '«La bendición enriquece» no garantiza riqueza a toda persona justa. Los dichos sobre pobreza describen causas diversas y no permiten concluir que todo pobre es perezoso o que toda persona rica es virtuosa.',
   ARRAY['justicia','diligencia','lengua','riqueza','pobreza','honestidad','generosidad']::text[],
   ARRAY['trabajadores','comerciantes','pobres','ricos','familias']::text[],
   ARRAY['campos','mercados','tribunales']::text[]),
  ('proverbios-22-24-sabios','PRO','section',22,NULL::smallint,24,NULL::smallint,
   'Palabras de los sabios y formación social',
   'Esta colección exhorta a escuchar, no explotar al pobre, evitar amistades que normalizan ira o deudas imprudentes y aplicar el corazón al conocimiento.',
   'La sección comparte formas y algunos temas con la Instrucción egipcia de Amenemope, mostrando intercambio cultural y adaptación sapiencial en la antigüedad.',
   'Israel puede recibir observaciones verdaderas de otras culturas y situarlas bajo el temor de Dios y la justicia del pacto. La sabiduría no depende de aislamiento cultural.',
   'Series de instrucciones más extensas sustituyen el ritmo de dichos individuales y concluyen con apéndices que observan campos descuidados, tribunales y relaciones.',
   'Formar criterio para relaciones, economía y poder, enseñando que aprovecharse de quien carece de defensa provoca una respuesta divina y social.',
   'La sabiduría aprende de observación, tradición y corrección. Reconocer una mala influencia no exige despreciar a la persona, pero sí establecer límites.',
   'Las advertencias sobre deudas no condenan moralmente a toda persona endeudada ni sustituyen análisis económico. La conexión con Amenemope no demuestra plagio simple ni resta valor al texto bíblico.',
   ARRAY['sabios','pobre','deuda','ira','conocimiento','límites']::text[],
   ARRAY['sabios','pobres','acreedores','gobernantes']::text[],
   ARRAY['campos','tribunales']::text[]),
  ('proverbios-25-29-coleccion-ezequias','PRO','section',25,NULL::smallint,29,NULL::smallint,
   'Colección transmitida por los hombres de Ezequías',
   'Dichos copiados en tiempos de Ezequías tratan liderazgo, conflictos, moderación, respuesta al enemigo, justicia pública y consecuencias de gobernantes corruptos.',
   'La nota editorial muestra un proceso de recopilación posterior a Salomón. La corte de Ezequías pudo patrocinar escribas que preservaron y organizaron materiales antiguos.',
   'El rey ideal investiga, escucha y defiende justicia. Proverbios 25 sobre alimentar al enemigo fue retomado en interpretaciones judías y cristianas como superación de la venganza.',
   'Comparaciones memorables y grupos temáticos sobre corte, pleitos y gobierno muestran sabiduría aplicada al poder público.',
   'Enseñar que la autoridad necesita transparencia, autocontrol y atención a consecuencias colectivas; una sociedad cambia según la calidad moral de quienes gobiernan.',
   'Responder al daño con dignidad y límites puede romper ciclos de hostilidad. Buscar justicia no exige imitar la conducta del adversario.',
   '«Sin profecía el pueblo se desenfrena» puede traducirse como falta de visión o revelación, pero el contexto apunta a enseñanza y ley, no a dependencia de predicciones personales. Alimentar al enemigo no obliga a permanecer en situaciones inseguras.',
   ARRAY['Ezequías','rey','gobierno','enemigo','autocontrol','justicia pública']::text[],
   ARRAY['reyes','funcionarios','litigantes','pueblo']::text[],
   ARRAY['Jerusalén','corte real']::text[]),
  ('proverbios-30-31-final','PRO','section',30,NULL::smallint,31,NULL::smallint,
   'Agur, Lemuel y el poema de la mujer de valor',
   'Agur reconoce los límites del conocimiento y observa patrones de la creación; la madre de Lemuel instruye al rey sobre dominio propio y defensa del vulnerable; un acróstico final celebra a una mujer competente y sabia.',
   'Los nombres Agur y Lemuel no se identifican con certeza. El poema final refleja una casa con actividad económica, comercio, producción textil, administración y ayuda al pobre.',
   'Eshet jayil se canta tradicionalmente en hogares judíos. El término describe fuerza, capacidad y valor, no un ideal físico. La enseñanza al rey vincula autoridad con defensa de quien no puede hablar.',
   'Colecciones numéricas, oráculos, enseñanza materna y un acróstico de veintidós versos cierran el libro ampliando la sabiduría más allá de una sola voz masculina o israelita identificable.',
   'Concluir que la sabiduría reconoce límites, utiliza poder para defender al vulnerable y se hace visible en competencia, generosidad, previsión y temor de Dios.',
   'El valor de una persona no depende de apariencia, estado civil ni productividad incesante. El poema honra una vida integral dentro de un contexto antiguo, no establece una lista obligatoria para todas las mujeres.',
   'Proverbios 31 no debe usarse para imponer sobrecarga doméstica o estándares corporales y sociales. La mujer descrita posee agencia económica y sabiduría; el texto no exige que una sola persona realice simultáneamente cada actividad mencionada.',
   ARRAY['Agur','Lemuel','mujer de valor','rey','humildad','pobre','sabiduría']::text[],
   ARRAY['reyes','mujeres','familias','pobres','comerciantes']::text[],
   ARRAY['corte','hogar','mercado']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select
  data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/poesia-sabiduria/v1#' || data.slug,
  'poesia-sabiduria-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','poetry-wisdom','generated_by_ai',false,'review_level','editorial')
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();