-- FASE D · Bloque 4 · Lote histórico 3: Crónicas
update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code in ('1CH','2CH');

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('1-cronicas-perfil','1CH','book',1,NULL::smallint,29,NULL::smallint,
   '1 Crónicas: identidad, David y preparación del templo',
   '1 Crónicas recorre genealogías desde Adán, resume la caída de Saúl y concentra su atención en David, la organización del culto y la preparación para el templo.',
   'El libro refleja una comunidad posterior al exilio que necesita reconstruir identidad, genealogías, funciones levíticas y conexión con la historia anterior de Israel.',
   'En el orden del Tanaj, Crónicas cierra los Escritos. Su mirada relee el pasado para una comunidad que ya no posee el reino davídico de la misma manera, pero conserva culto, Torá y esperanza.',
   'Nueve capítulos genealógicos forman el portal del libro; después la narración selecciona episodios de David, especialmente aquellos relacionados con Jerusalén, el arca y el templo futuro.',
   'Afirmar que la comunidad restaurada pertenece a una historia más amplia y que la adoración, la memoria y la organización responsable permiten continuar después de una ruptura nacional.',
   'Recordar nombres y generaciones puede ser un acto espiritual de pertenencia. Preparar una obra que otro completará también posee valor y dignidad.',
   'Las genealogías no deben utilizarse para afirmar superioridad racial o pureza biológica. La imagen más favorable de David no niega los abusos narrados en Samuel; refleja una selección literaria con otro propósito pastoral.',
   ARRAY['genealogías','David','arca','levitas','templo','adoración']::text[],
   ARRAY['judíos retornados','levitas','sacerdotes','tribus de Israel']::text[],
   ARRAY['Jerusalén','Hebrón','Sion']::text[]),
  ('1-cronicas-1-9-genealogias','1CH','section',1,NULL::smallint,9,NULL::smallint,
   'Genealogías y reconstrucción de pertenencia',
   'Listas desde Adán hasta familias de Israel, levitas, sacerdotes y habitantes de Jerusalén conectan a la comunidad posterior al exilio con toda la historia bíblica.',
   'Después de deportaciones y retornos, las genealogías podían respaldar pertenencia familiar, servicio cultual, propiedad y memoria colectiva, aunque no siempre funcionan como registros biológicos exhaustivos.',
   'Las listas integran a Judá, Benjamín, levitas y también a tribus del norte, expresando una visión de todo Israel más amplia que la población inmediata de Jerusalén.',
   'Nombres, líneas familiares, notas narrativas y variaciones respecto a otras genealogías crean una teología de continuidad más que una cronología moderna completa.',
   'Comunicar que ninguna generación comienza desde cero y que la restauración requiere recordar tanto figuras conocidas como personas aparentemente anónimas.',
   'Dios puede sostener una historia comunitaria mediante vidas ordinarias cuyos nombres rara vez ocupan el centro. La pertenencia no depende únicamente de notoriedad.',
   'Las diferencias entre genealogías no deben ocultarse ni forzarse en un esquema único. Las listas antiguas pueden seleccionar, abreviar o organizar nombres por objetivos literarios y sociales.',
   ARRAY['genealogías','Adán','tribus','levitas','retorno','Jerusalén']::text[],
   ARRAY['judíos retornados','levitas','sacerdotes']::text[],
   ARRAY['Jerusalén','Judá','Benjamín']::text[]),
  ('1-cronicas-10-29-david','1CH','section',10,NULL::smallint,29,NULL::smallint,
   'David, el arca y la preparación del templo',
   'Tras la muerte de Saúl, David reúne a Israel, establece Jerusalén, lleva el arca, organiza músicos y servidores, recibe la promesa dinástica y prepara recursos para el templo que edificará Salomón.',
   'El autor relee tradiciones monárquicas desde una época sin rey davídico gobernante. La organización cultual y las ofrendas reflejan preocupaciones de la comunidad del segundo templo.',
   'Los levitas, cantores y porteros reciben amplio espacio. David aparece como organizador del culto y como modelo de preparación generosa para una obra futura.',
   'Discursos, listas de servidores, cánticos y preparativos sustituyen varios conflictos familiares narrados en Samuel y dirigen la atención hacia el templo.',
   'Mostrar que el liderazgo fiel reúne, organiza, da recursos y prepara a la siguiente generación sin apropiarse de una tarea que Dios ha asignado a otra persona.',
   'La madurez acepta límites: David no construirá el templo, pero puede contribuir con visión, recursos, oración y acompañamiento a Salomón.',
   'La selección positiva del cronista no autoriza negar los pecados de David conocidos por otros libros. Las cifras de ofrendas y ejércitos deben leerse según convenciones antiguas y debates textuales.',
   ARRAY['David','arca','levitas','cantores','Salomón','templo','ofrenda']::text[],
   ARRAY['israelitas','levitas','sacerdotes']::text[],
   ARRAY['Jerusalén','Sion','Ornán']::text[]),
  ('2-cronicas-perfil','2CH','book',1,NULL::smallint,36,NULL::smallint,
   '2 Crónicas: templo, reyes de Judá, reforma y retorno',
   '2 Crónicas continúa con Salomón, sigue exclusivamente la monarquía de Judá, evalúa reformas y crisis y concluye con el exilio y el decreto persa que permite regresar.',
   'El libro fue compuesto para una comunidad posterior al exilio que reconstruía vida alrededor del templo, Jerusalén y la Torá bajo dominio persa.',
   'A diferencia de Reyes, Crónicas presta atención particular a sacerdotes, levitas, asambleas, Pascuas y posibilidades de retorno incluso para personas del antiguo reino del norte.',
   'El templo de Salomón abre la obra, una cadena de reinados ocupa el centro y la destrucción culmina inmediatamente en una orden de regreso, creando un final abierto.',
   'Enseñar que la búsqueda de Dios, la escucha profética y la reforma pueden renovar a una comunidad, mientras la persistencia en violencia e idolatría conduce a pérdida.',
   'La restauración puede comenzar aun después de una catástrofe. Volver requiere humildad, memoria, acción comunitaria y disposición para reconstruir.',
   'Las fórmulas de retribución inmediata reflejan el énfasis pedagógico del cronista y no deben convertirse en explicación automática de toda enfermedad, derrota o prosperidad individual.',
   ARRAY['Salomón','templo','Judá','reforma','Pascua','exilio','Ciro']::text[],
   ARRAY['judíos','levitas','sacerdotes','asirios','babilonios','persas']::text[],
   ARRAY['Jerusalén','Judá','Babilonia','Persia']::text[]),
  ('2-cronicas-1-9-salomon','2CH','section',1,NULL::smallint,9,NULL::smallint,
   'Salomón y la dedicación del templo',
   'Salomón pide sabiduría, construye y dedica el templo, ora por perdón y restauración y recibe la visita de la reina de Sabá antes de concluir su reinado.',
   'La arquitectura, artesanía, comercio y administración reflejan memoria de una monarquía capaz de movilizar recursos regionales y mano de obra especializada.',
   'La oración de dedicación destaca confesión, retorno y la posibilidad de que Dios escuche desde los cielos. También incluye al extranjero que busca al Dios de Israel.',
   'El cronista omite varios conflictos de sucesión y concentra la narración en sabiduría, templo, oración, gloria y reconocimiento internacional.',
   'Presentar el templo como lugar de oración y encuentro, sin confundirlo con una garantía automática contra juicio o pérdida.',
   'Los espacios sagrados deben servir a la reconciliación, escucha y hospitalidad. La belleza del culto necesita acompañarse de justicia y humildad.',
   'La promesa de sanar la tierra se dirige al pueblo del pacto dentro de un contexto de templo y arrepentimiento; no debe convertirse en fórmula política nacionalista para cualquier país moderno.',
   ARRAY['Salomón','sabiduría','templo','dedicación','oración','reina de Sabá']::text[],
   ARRAY['judíos','fenicios','extranjeros']::text[],
   ARRAY['Jerusalén','Tiro']::text[]),
  ('2-cronicas-10-28-reyes','2CH','section',10,NULL::smallint,28,NULL::smallint,
   'Reyes de Judá entre búsqueda, conflicto y reforma parcial',
   'Desde Roboam hasta Acaz, los reyes de Judá alternan momentos de escucha, orgullo, guerra, reforma y alianza equivocada, mientras profetas y levitas llaman a volver a Dios.',
   'Judá vive bajo presión de Israel, Aram y potencias vecinas. Fortificaciones, ejércitos y alianzas muestran la fragilidad de un reino pequeño entre poderes regionales.',
   'El cronista destaca asambleas, enseñanza de la Torá y apertura hacia tribus del norte, especialmente durante reformas como la de Josafat.',
   'Cada reinado se presenta como una evaluación moral con discursos proféticos y consecuencias, construyendo ejemplos positivos y negativos para la comunidad posterior.',
   'Mostrar que buscar a Dios implica más que una campaña religiosa: requiere justicia, enseñanza, humildad y perseverancia cuando llegan poder y éxito.',
   'Una buena decisión pasada no garantiza fidelidad futura. La comunidad necesita corrección continua y no debe confundir expansión institucional con salud espiritual.',
   'La relación inmediata entre conducta y resultado no explica toda experiencia humana. Las enfermedades de reyes no deben usarse para afirmar que la atención médica demuestra falta de fe.',
   ARRAY['Roboam','Asa','Josafat','Uzías','Acaz','reforma','profetas']::text[],
   ARRAY['judíos','israelitas del norte','arameos','edomitas']::text[],
   ARRAY['Jerusalén','Judá','Samaria','Damasco']::text[]),
  ('2-cronicas-29-36-reforma-exilio','2CH','section',29,NULL::smallint,36,NULL::smallint,
   'Ezequías, Josías, destrucción y decreto de retorno',
   'Ezequías restaura el templo y celebra una Pascua inclusiva; Josías encuentra el libro de la ley y reforma el culto, pero los últimos reyes conducen a la destrucción y al exilio antes del decreto de Ciro.',
   'La expansión asiria, el dominio egipcio y la conquista babilónica condicionan los reinados finales. Bajo Persia, comunidades deportadas obtuvieron oportunidades limitadas de retorno y reconstrucción.',
   'Las Pascuas de Ezequías y Josías muestran la centralidad de memoria, purificación y participación. El cierre con Ciro conecta Crónicas con la esperanza de regresar a Jerusalén.',
   'Dos grandes reformas interrumpen una trayectoria de decadencia. La última frase queda incompleta en sentido narrativo: quien pertenezca al pueblo debe subir.',
   'Afirmar que la reforma sincera puede reunir y sanar, pero que no siempre elimina consecuencias históricas acumuladas; aun así, Dios puede abrir una nueva etapa después del exilio.',
   'La esperanza madura no niega ruinas. Escucha una invitación, se levanta y participa en la reconstrucción con memoria de lo aprendido.',
   'La destrucción de objetos cultuales antiguos no autoriza atacar lugares religiosos actuales. El decreto de Ciro debe entenderse en política imperial persa y no presentarse como conversión personal segura.',
   ARRAY['Ezequías','Josías','Pascua','libro de la ley','exilio','Ciro','retorno']::text[],
   ARRAY['judíos','israelitas del norte','asirios','egipcios','babilonios','persas']::text[],
   ARRAY['Jerusalén','Babilonia','Persia']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select
  data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/historicos/v1#' || data.slug,
  'historicos-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','historical-books','generated_by_ai',false,'review_level','editorial')
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();