-- FASE D · Bloque 4 · piloto textual, parte 3/3: textos y variantes.
with source as (select id from public.biblical_sources where slug='stepbible-lexical-pilot'),
data as (select * from jsonb_to_recordset($data$[{"b":"PSA","c":23,"v":1,"l":"hebrew","o":"יְהוָ֥ה רֹ֝עִ֗י לֹ֣א אֶחְסָֽר׃","n":"יהוה רעי לא אחסר","t":"Yahweh ro‘i lo’ ’echsar","e":"Yahvé es mi pastor; no careceré.","d":"rtl","cnt":4,"a":"verified","ln":[21230,21233],"fh":"84e118a97e5725e3847cdfdd593873513021c790c63cc91a0d41fca2b5db2ed5","eh":"4a112c7e27da3b2a0cf76f468975f62ebef04173f2656580ecc64dd38dee7ea4","bp":"TAHOT source reading L"},{"b":"JHN","c":3,"v":16,"l":"greek","o":"οὕτως γὰρ ἠγάπησεν ὁ θεὸς τὸν κόσμον, ὥστε τὸν υἱὸν τὸν μονογενῆ ἔδωκεν, ἵνα πᾶς ὁ πιστεύων εἰς αὐτὸν μὴ ἀπόληται ἀλλ᾽ ἔχῃ ζωὴν αἰώνιον.","n":"ουτως γαρ ηγαπησεν ο θεος τον κοσμον ωστε τον υιον τον μονογενη εδωκεν ινα πας ο πιστευων εις αυτον μη αποληται αλλ᾽ εχη ζωην αιωνιον","t":"houtōs gar ēgapēsen ho theos ton kosmon hōste ton huion ton monogenē edōken ina pas ho pisteuōn eis auton mē apolētai all᾽ echē zōēn aiōnion","e":"Porque así amó Dios al mundo: dio al Hijo único, para que todo el que cree en él no perezca, sino que tenga vida eterna.","d":"ltr","cnt":25,"a":"verified","ln":[87972,87997],"fh":"ab8eaaeb68e17a1dcfa34e1e9350358f22f03bc2a97244d848750ad81044bc8e","eh":"3b36d9f586fe932d4fa21065ab6fe556f2788d2b2fe0ac252b48099e21853cfa","bp":"NA27/NA28"}]$data$::jsonb) as x(
 b text,c smallint,v smallint,l text,o text,n text,t text,e text,d text,cnt smallint,a text,ln jsonb,fh text,eh text,bp text
))
insert into public.biblical_verse_texts(source_id,book_code,chapter,verse,language,original_text,normalized_text,transliteration,literal_translation_es,text_direction,token_count,analysis_status,source_locator,provider_version,content_hash,review_status,enabled,approved_at,metadata)
select source.id,d.b,d.c,d.v,d.l,d.o,d.n,d.t,d.e,d.d,d.cnt,d.a,
 (case when d.b='PSA' then 'https://github.com/STEPBible/STEPBible-Data/blob/b86d26cdb1f51729e73b5b4eb7f7ccadc5dfba39/Translators%20Amalgamated%20OT%2BNT/TAHOT%20Job-Sng%20-%20Translators%20Amalgamated%20Hebrew%20OT%20-%20STEPBible.org%20CC%20BY.txt' else 'https://github.com/STEPBible/STEPBible-Data/blob/b86d26cdb1f51729e73b5b4eb7f7ccadc5dfba39/Translators%20Amalgamated%20OT%2BNT/TAGNT%20Mat-Jhn%20-%20Translators%20Amalgamated%20Greek%20NT%20-%20STEPBible.org%20CC-BY.txt' end)||'#L'||(d.ln->>0)||'-L'||(d.ln->>1),
 'STEPBible-Data@b86d26cdb1f51729e73b5b4eb7f7ccadc5dfba39',encode(extensions.digest(concat_ws('|',d.b,d.c::text,d.v::text,d.l,d.o,d.n,d.t,d.e,d.cnt::text,d.bp,'b86d26cdb1f51729e73b5b4eb7f7ccadc5dfba39'),'sha256'),'hex'),
 'approved',true,now(),jsonb_build_object('source_commit','b86d26cdb1f51729e73b5b4eb7f7ccadc5dfba39','source_file_hash',d.fh,'source_excerpt_hash',d.eh,'source_lines',d.ln,'base_text_policy',d.bp,'translation_kind','editorial_literal','generated_by_ai',false,'review_level','source_validated')
from data d cross join source
on conflict(source_id,book_code,chapter,verse,language) do update set original_text=excluded.original_text,normalized_text=excluded.normalized_text,transliteration=excluded.transliteration,literal_translation_es=excluded.literal_translation_es,text_direction=excluded.text_direction,token_count=excluded.token_count,analysis_status=excluded.analysis_status,source_locator=excluded.source_locator,provider_version=excluded.provider_version,content_hash=excluded.content_hash,review_status='approved',enabled=true,approved_at=coalesce(public.biblical_verse_texts.approved_at,excluded.approved_at),metadata=excluded.metadata,updated_at=now();

with source as (select id from public.biblical_sources where slug='stepbible-lexical-pilot'),
data as (select * from jsonb_to_recordset($data$[{"b":"JHN","c":3,"v":16,"l":"greek","k":"jhn-3-16-autou-addition","w":11,"t":"addition","br":null,"vr":"αὐτοῦ","ws":"La lectura αὐτοῦ aparece en Tregelles, Textus Receptus y el texto Bizantino; NA27/NA28 no la incluyen.","wi":[],"ed":["Treg","TR","Byz"],"sg":"Añade “de él/suyo” después de “Hijo”; explicita la relación posesiva sin cambiar el referente del contexto.","ln":87982,"ref":"Jhn.3.16#11=ko","si":"G0846_a","dw":11,"mod":10},{"b":"JHN","c":3,"v":16,"l":"greek","k":"jhn-3-16-alla-orthographic","w":23,"t":"orthographic","br":"ἀλλ᾽","vr":"ἀλλὰ","ws":"TAGNT registra ἀλλ᾽ como lectura principal y señala ἀλλὰ en SBL, Westcott-Hort, Tregelles, Textus Receptus y Bizantino.","wi":[],"ed":["SBL","WH","Treg","TR","Byz"],"sg":"Es una diferencia de elisión ortográfica; no cambia la traducción “sino/pero”.","ln":87994,"ref":"Jhn.3.16#23=NKO","si":null,"dw":22,"mod":null}]$data$::jsonb) as x(
 b text,c smallint,v smallint,l text,k text,w smallint,t text,br text,vr text,ws text,wi jsonb,ed jsonb,sg text,ln integer,ref text,si text,dw smallint,mod smallint
))
insert into public.biblical_textual_variants(source_id,verse_text_id,variant_key,anchor_word_index,reading_type,base_reading,variant_reading,witness_summary,witnesses,editions,significance_es,source_locator,provider_version,content_hash,review_status,enabled,approved_at,metadata)
select source.id,vt.id,d.k,d.w,d.t,d.br,d.vr,d.ws,d.wi,d.ed,d.sg,'https://github.com/STEPBible/STEPBible-Data/blob/b86d26cdb1f51729e73b5b4eb7f7ccadc5dfba39/Translators%20Amalgamated%20OT%2BNT/TAGNT%20Mat-Jhn%20-%20Translators%20Amalgamated%20Greek%20NT%20-%20STEPBible.org%20CC-BY.txt#L'||d.ln,'STEPBible-Data@b86d26cdb1f51729e73b5b4eb7f7ccadc5dfba39',
 encode(extensions.digest(concat_ws('|',d.k,d.w::text,d.t,coalesce(d.br,''),coalesce(d.vr,''),d.ws,d.ed::text,d.sg,d.ln::text,'b86d26cdb1f51729e73b5b4eb7f7ccadc5dfba39'),'sha256'),'hex'),
 'approved',true,now(),jsonb_strip_nulls(jsonb_build_object('source_commit','b86d26cdb1f51729e73b5b4eb7f7ccadc5dfba39','source_file_hash','ab8eaaeb68e17a1dcfa34e1e9350358f22f03bc2a97244d848750ad81044bc8e','source_excerpt_hash','3b36d9f586fe932d4fa21065ab6fe556f2788d2b2fe0ac252b48099e21853cfa','source_reference',d.ref,'source_line',d.ln,'source_lexical_id',d.si,'display_word_index',d.dw,'modifies_source_word_index',d.mod,'generated_by_ai',false,'review_level','source_validated'))
from data d cross join source join public.biblical_verse_texts vt on vt.source_id=source.id and vt.book_code=d.b and vt.chapter=d.c and vt.verse=d.v and vt.language=d.l
on conflict(source_id,verse_text_id,variant_key) do update set anchor_word_index=excluded.anchor_word_index,reading_type=excluded.reading_type,base_reading=excluded.base_reading,variant_reading=excluded.variant_reading,witness_summary=excluded.witness_summary,witnesses=excluded.witnesses,editions=excluded.editions,significance_es=excluded.significance_es,source_locator=excluded.source_locator,provider_version=excluded.provider_version,content_hash=excluded.content_hash,review_status='approved',enabled=true,approved_at=coalesce(public.biblical_textual_variants.approved_at,excluded.approved_at),metadata=excluded.metadata,updated_at=now();

do $validate$
declare s uuid;vt integer;v integer;bad integer;
begin
 select id into s from public.biblical_sources where slug='stepbible-lexical-pilot';
 select count(*) into vt from public.biblical_verse_texts where source_id=s and enabled and review_status='approved';
 select count(*) into v from public.biblical_textual_variants where source_id=s and enabled and review_status='approved';
 select count(*) into bad from (select content_hash from public.biblical_verse_texts where source_id=s and enabled union all select content_hash from public.biblical_textual_variants where source_id=s and enabled) q where content_hash is null or content_hash !~ '^[0-9a-f]{64}$';
 if vt<>2 then raise exception 'Se esperaban 2 textos; se obtuvieron %',vt; end if;
 if v<>2 then raise exception 'Se esperaban 2 variantes; se obtuvieron %',v; end if;
 if bad<>0 then raise exception 'Hashes de textos o variantes inválidos: %',bad; end if;
end $validate$;