-- FASE D · Bloque 4 · Cartas paulinas: Gálatas–Colosenses
select internal.import_biblical_context_batch(
  'paulinas-galatas-colosenses',
  'paulinas-galatas-colosenses-v1-2026-08-02',
  $books$[
    {
      "code":"GAL","slug":"galatas","name":"Gálatas","chapters":6,
      "summary":"Gálatas responde a una crisis en comunidades gentiles presionadas para adoptar circuncisión y otras marcas identitarias judías. Pablo defiende que la pertenencia al pueblo de Dios se recibe por la fidelidad de Jesucristo y se vive por el Espíritu en amor.",
      "historical":"La ubicación exacta de las iglesias y la fecha dependen del debate entre Galacia del norte y del sur. La carta refleja tensiones del movimiento de Jesús sobre cómo integrar a gentiles sin convertirlos primero en judíos.",
      "jewish":"Pablo argumenta desde Abraham, la Torá y las promesas de Israel. Su discusión es una controversia judía del siglo I sobre gentiles y pacto, no un rechazo étnico del judaísmo ni una condena general de la Torá.",
      "literary":"Tras un saludo abrupto, Pablo narra su llamado y encuentros apostólicos, desarrolla una argumentación bíblica sobre promesa y ley, y concluye con exhortaciones sobre libertad, Espíritu y nueva creación.",
      "intent":"Proteger la libertad de creyentes gentiles frente a requisitos identitarios que Pablo considera innecesarios para pertenecer al Mesías, y mostrar que esa libertad produce servicio amoroso y no egoísmo.",
      "reflection":"La gracia libera de tener que ganar pertenencia, pero también libera para cargar las necesidades de otros. La identidad espiritual no debe convertirse en superioridad cultural.",
      "cautions":"La oposición entre ley y fe no autoriza antisemitismo ni desprecio de la Torá. Las expresiones polémicas deben ubicarse en una disputa concreta. «No hay varón ni mujer» afirma igualdad de pertenencia y no debe usarse para borrar experiencias humanas.",
      "terms":["justificación","fe","fidelidad","Torá","promesa","Espíritu","libertad","nueva creación"],
      "groups":["gálatas","gentiles","judíos creyentes","maestros rivales"],
      "places":["Galacia","Jerusalén","Antioquía"]
    },
    {
      "code":"EPH","slug":"efesios","name":"Efesios","chapters":6,
      "summary":"Efesios presenta el propósito de Dios de reunir todas las cosas en Cristo y formar de judíos y gentiles una comunidad reconciliada que viva con unidad, madurez y resistencia espiritual.",
      "historical":"La carta circuló probablemente entre comunidades de Asia Menor. La ausencia de saludos personales y diferencias de estilo han generado debate académico sobre autoría paulina directa o elaboración dentro de su escuela.",
      "jewish":"La imagen de gentiles acercados a la ciudadanía de Israel depende de las promesas y Escrituras judías. La reconciliación no significa que la iglesia deba despreciar o reemplazar al pueblo judío.",
      "literary":"Una larga bendición y oración abre tres capítulos de identidad y reconciliación; los capítulos finales traducen esa visión en unidad, ética doméstica y la metáfora de la armadura de Dios.",
      "intent":"Formar comunidades capaces de reconocer la gracia compartida, superar hostilidades étnicas y sociales, usar sus dones para madurar y resistir fuerzas que deshumanizan.",
      "reflection":"La unidad bíblica no es uniformidad: personas diversas son llamadas a una paz construida con verdad, paciencia y cuidado mutuo.",
      "cautions":"Los códigos domésticos no justifican control, abuso conyugal ni esclavitud. La armadura es una metáfora ética y espiritual, no una invitación a violencia física. La autoría debe presentarse como tema debatido.",
      "terms":["en Cristo","gracia","misterio","unidad","cuerpo","nueva humanidad","armadura"],
      "groups":["judíos","gentiles","comunidades de Asia Menor","familias antiguas"],
      "places":["Éfeso","Asia Menor"]
    },
    {
      "code":"PHP","slug":"filipenses","name":"Filipenses","chapters":4,
      "summary":"Filipenses es una carta de amistad y colaboración enviada desde prisión. Pablo agradece el apoyo de la comunidad, presenta a Cristo como modelo de humildad y anima a perseverar con gozo, unidad y discernimiento.",
      "historical":"Filipos era una colonia romana en Macedonia. La ubicación del encarcelamiento de Pablo se debate entre Roma, Éfeso y Cesarea; cada opción afecta la fecha propuesta.",
      "jewish":"Pablo relee su propia identidad israelita y sus logros sin despreciar su origen. El lenguaje de ciudadanía y Escritura se sitúa en una comunidad gentil dentro del mundo romano.",
      "literary":"La carta combina agradecimiento, informe personal, himno o poema cristológico, exhortaciones, polémica y reconocimiento del don económico. Algunos estudios proponen que reúne más de una carta, aunque no hay consenso.",
      "intent":"Fortalecer una colaboración misionera bajo presión, sanar tensiones internas y orientar honor, ambición y ciudadanía alrededor del servicio de Cristo.",
      "reflection":"El gozo cristiano no niega prisión, ansiedad o conflicto. Nace de pertenencia, amistad, esperanza y una práctica humilde de lo verdadero y justo.",
      "cautions":"«Todo lo puedo» se refiere a aprender contentamiento en abundancia y necesidad, no a éxito ilimitado. «No se inquieten» no culpabiliza a quien padece ansiedad ni sustituye atención profesional.",
      "terms":["gozo","koinonía","humildad","ciudadanía","contentamiento","día de Cristo"],
      "groups":["filipenses","ciudadanos romanos","colaboradores de Pablo"],
      "places":["Filipos","Macedonia"]
    },
    {
      "code":"COL","slug":"colosenses","name":"Colosenses","chapters":4,
      "summary":"Colosenses exalta la suficiencia y supremacía de Cristo, advierte contra prácticas que prometen plenitud mediante poderes, ascetismo o reglas, y llama a una vida comunitaria renovada.",
      "historical":"Colosas era una ciudad de Frigia en Asia Menor. La naturaleza exacta de la enseñanza rival es incierta. El estilo y vocabulario producen debate sobre autoría paulina directa o de un colaborador cercano.",
      "jewish":"La carta utiliza categorías de creación, sabiduría, circuncisión, festividades y ángeles. Estas referencias no deben convertirse en una caricatura del judaísmo; parecen formar parte de una mezcla local difícil de reconstruir.",
      "literary":"Acción de gracias y poema cristológico conducen a una defensa de la plenitud en Cristo; luego siguen exhortaciones bautismales, reglas comunitarias, códigos domésticos y saludos extensos.",
      "intent":"Asegurar a la comunidad que no necesita someterse a sistemas espirituales adicionales para alcanzar plenitud, y traducir la nueva identidad en compasión, perdón, paz y responsabilidad.",
      "reflection":"La madurez no se demuestra por experiencias secretas o rigor visible, sino por una vida enraizada en Cristo que trata a otros con dignidad.",
      "cautions":"Las referencias a fiestas, comidas y sábados no autorizan desprecio del judaísmo. Los códigos domésticos no justifican abuso ni esclavitud. La identidad de la enseñanza rival y la autoría son debatidas.",
      "terms":["imagen","plenitud","poderes","circuncisión","nueva humanidad","paz","sabiduría"],
      "groups":["colosenses","gentiles","judíos de Asia Menor","familias antiguas"],
      "places":["Colosas","Laodicea","Asia Menor"]
    }
  ]$books$::jsonb,
  $sections$[
    {"code":"GAL","slug":"galatas-1-2","start":1,"end":2,"title":"Evangelio, llamado y mesa compartida","summary":"Pablo defiende su misión entre gentiles, recuerda sus encuentros con líderes de Jerusalén y relata el conflicto de Antioquía sobre comer juntos.","intent":"Afirmar que el evangelio recibido no exige que gentiles adopten identidad judía y mostrar que la verdad teológica se prueba en una mesa sin segregación.","cautions":"El conflicto entre Pablo y Pedro no debe exagerarse como ruptura absoluta entre cristianismo y judaísmo. La frase sobre «obras de ley» posee un debate interpretativo amplio.","terms":["evangelio","gentiles","Jerusalén","Antioquía","mesa","justificación"],"reflection":"La coherencia espiritual incluye revisar con quién compartimos comunidad y qué barreras mantenemos por temor.","groups":["gentiles","judíos creyentes","apóstoles"],"places":["Jerusalén","Antioquía","Galacia"]},
    {"code":"GAL","slug":"galatas-3-4","start":3,"end":4,"title":"Promesa, Torá, filiación y herencia","summary":"Pablo argumenta desde Abraham que la bendición alcanza a las naciones por la promesa y describe la función temporal de la ley antes de la plena filiación en Cristo.","intent":"Reafirmar la igualdad de herederos y explicar por qué la circuncisión no es requisito para gentiles que han recibido el Espíritu.","cautions":"La Torá no es presentada simplemente como mala. Las metáforas de pedagogo, esclavitud y dos mujeres deben leerse dentro del argumento y no usarse para despreciar a judíos o a mujeres.","terms":["Abraham","promesa","Torá","pedagogo","filiación","herencia"],"reflection":"La pertenencia como hijo o hija es don, no premio por conformidad cultural.","groups":["descendientes de Abraham","gentiles","judíos"],"places":["Galacia","Jerusalén"]},
    {"code":"GAL","slug":"galatas-5-6","start":5,"end":6,"title":"Libertad, fruto del Espíritu y nueva creación","summary":"La libertad se expresa sirviendo por amor, caminando por el Espíritu, restaurando con mansedumbre y sembrando para el bien de todos.","intent":"Evitar que libertad signifique autosuficiencia y formar una comunidad cuyo carácter sea fruto del Espíritu y cuidado mutuo.","cautions":"La lista de obras de la carne no debe usarse para vigilancia humillante. Restaurar exige seguridad, límites y rendición de cuentas; no encubrir daño.","terms":["libertad","amor","carne","Espíritu","fruto","cargas","nueva creación"],"reflection":"La libertad madura no pregunta solamente qué puede hacer, sino cómo puede amar y proteger al otro.","groups":["comunidades de Galacia"],"places":["Galacia"]},
    {"code":"EPH","slug":"efesios-1-3","start":1,"end":3,"title":"Bendición, gracia y una nueva humanidad","summary":"La carta celebra el propósito de reunir todo en Cristo, la salvación por gracia y la reconciliación de judíos y gentiles en un solo cuerpo y templo vivo.","intent":"Dar identidad a comunidades diversas y mostrar que el misterio revelado produce paz, acceso compartido y pertenencia sin hostilidad.","cautions":"Elección y predestinación tienen diversas interpretaciones y no deben usarse para declarar que ciertas personas carecen de posibilidad. «Un solo pueblo» no borra a Israel ni justifica reemplazo antijudío.","terms":["elección","gracia","paz","nueva humanidad","misterio","templo"],"reflection":"La gracia derriba orgullo y hostilidad porque nadie construye por sí solo su lugar en la familia de Dios.","groups":["judíos","gentiles","comunidades de Asia Menor"],"places":["Éfeso","Asia Menor"]},
    {"code":"EPH","slug":"efesios-4-5","start":4,"end":5,"title":"Unidad, dones y vida en la luz","summary":"La vocación común se vive con humildad, dones que edifican, lenguaje verdadero, perdón, sabiduría y relaciones caracterizadas por amor y respeto.","intent":"Mover a la iglesia desde identidad recibida hacia madurez práctica, usando diferencias para edificar en vez de competir.","cautions":"La sumisión mutua contextualiza las instrucciones domésticas. Ningún texto autoriza control coercitivo, violencia conyugal ni silenciamiento de víctimas.","terms":["unidad","dones","cuerpo","verdad","perdón","luz","sumisión mutua"],"reflection":"Madurar significa aprender a decir verdad sin destruir, manejar enojo y usar capacidades para el bien común.","groups":["comunidad cristiana","familias antiguas"],"places":["Asia Menor"]},
    {"code":"EPH","slug":"efesios-6","start":6,"end":6,"title":"Relaciones de poder y armadura de Dios","summary":"La carta habla a hijos, padres, esclavos y amos dentro de estructuras antiguas y termina describiendo una armadura para resistir poderes espirituales mediante verdad, justicia, paz, fe y oración.","intent":"Introducir responsabilidad y límites dentro de jerarquías existentes y orientar la lucha de la comunidad contra fuerzas que corrompen, no contra seres humanos.","cautions":"El texto no aprueba esclavitud ni autoriza disciplina violenta. La armadura es una metáfora no violenta; no debe militarizar la fe ni demonizar adversarios humanos.","terms":["hijos","padres","esclavos","amos","armadura","oración"],"reflection":"La resistencia espiritual se practica con verdad, justicia, paz y perseverancia, no mediante dominación.","groups":["familias antiguas","personas esclavizadas","amos"],"places":["Asia Menor"]},
    {"code":"PHP","slug":"filipenses-1","start":1,"end":1,"title":"Colaboración, prisión y una vida digna del evangelio","summary":"Pablo agradece la colaboración, interpreta su prisión como oportunidad y llama a la comunidad a mantenerse unida frente a presión y rivalidad.","intent":"Convertir incertidumbre sobre el encarcelamiento en una visión de misión compartida y valor comunitario.","cautions":"Desear «partir y estar con Cristo» expresa la tensión de un prisionero y no debe utilizarse para romantizar la muerte ni ignorar señales de crisis emocional.","terms":["koinonía","prisión","evangelio","ciudadanía","valor"],"reflection":"Una vida fiel puede encontrar propósito en circunstancias limitantes sin negar el dolor ni renunciar al cuidado personal.","groups":["filipenses","guardia imperial","predicadores rivales"],"places":["Filipos"]},
    {"code":"PHP","slug":"filipenses-2","start":2,"end":2,"title":"Humildad de Cristo y colaboradores fieles","summary":"El poema sobre Cristo redefine honor mediante vaciamiento y obediencia; Timoteo y Epafrodito aparecen como ejemplos concretos de servicio y cuidado.","intent":"Sanar competencia y enseñar que la verdadera grandeza busca el bien ajeno sin convertir el servicio en autoaniquilación.","cautions":"El vaciamiento de Cristo no exige tolerar abuso, borrar límites ni abandonar necesidades básicas. La cristología del pasaje posee debates históricos que deben reconocerse.","terms":["humildad","forma de Dios","siervo","Timoteo","Epafrodito"],"reflection":"La humildad no niega dignidad; usa libertad y posición para levantar a otros.","groups":["filipenses","colaboradores de Pablo"],"places":["Filipos"]},
    {"code":"PHP","slug":"filipenses-3-4","start":3,"end":4,"title":"Identidad, ciudadanía, reconciliación y contentamiento","summary":"Pablo relativiza sus credenciales, corre hacia la meta, llama a reconciliar a Evodia y Síntique y enseña a enfrentar ansiedad y necesidad mediante oración, comunidad y contentamiento aprendido.","intent":"Desplazar la confianza de estatus y logros hacia Cristo, reparar relaciones y formar estabilidad interior en circunstancias cambiantes.","cautions":"La crítica a los «perros» pertenece a una controversia interna y no autoriza lenguaje antijudío. Oración y pensamiento saludable complementan, no sustituyen, ayuda clínica para ansiedad.","terms":["justicia","meta","ciudadanía","reconciliación","ansiedad","contentamiento"],"reflection":"La paz se cultiva mediante oración, hábitos mentales honestos, reconciliación y apoyo material, no mediante negación.","groups":["filipenses","Evodia","Síntique","colaboradores"],"places":["Filipos"]},
    {"code":"COL","slug":"colosenses-1","start":1,"end":1,"title":"Cristo, creación y reconciliación","summary":"La acción de gracias conduce a un poema que presenta a Cristo como imagen de Dios, cabeza de la creación y de la iglesia, y agente de reconciliación.","intent":"Fundar la identidad de la comunidad en una visión amplia de Cristo que supere miedo a poderes y fortalezca esperanza y madurez.","cautions":"«Primogénito» expresa rango y relación con la creación, no necesariamente que Cristo sea una criatura. La reconciliación universal tiene interpretaciones diversas.","terms":["imagen","primogénito","creación","cuerpo","reconciliación","misterio"],"reflection":"Una fe centrada en Cristo integra creación, comunidad y reconciliación en vez de reducir la salvación a beneficio privado.","groups":["colosenses","comunidades gentiles"],"places":["Colosas"]},
    {"code":"COL","slug":"colosenses-2","start":2,"end":2,"title":"Plenitud frente a reglas y poderes","summary":"La comunidad es exhortada a permanecer arraigada en Cristo y no quedar cautiva por filosofías, ascetismo, calendarios o culto de ángeles que prometen una plenitud adicional.","intent":"Liberar del temor a poderes espirituales y de prácticas que producen apariencia de sabiduría pero no transforman deseos ni relaciones.","cautions":"No se conoce con certeza la enseñanza rival. Las referencias a comida, fiesta, luna nueva y sábado no justifican despreciar prácticas judías ni conciencia personal.","terms":["plenitud","circuncisión","poderes","sombra","ángeles","ascetismo"],"reflection":"La seguridad espiritual no depende de acumular técnicas secretas, sino de una vida arraigada y discernida en comunidad.","groups":["colosenses","maestros locales"],"places":["Colosas"]},
    {"code":"COL","slug":"colosenses-3-4","start":3,"end":4,"title":"Nueva humanidad, hogares y misión cotidiana","summary":"Vestirse de compasión, perdón y amor transforma la comunidad; luego la carta aborda hogares antiguos, oración, sabiduría pública y una red extensa de colaboradores.","intent":"Mostrar que la unión con Cristo produce prácticas visibles de dignidad, paz, trabajo responsable, lenguaje sabio y relaciones reparadas.","cautions":"Los códigos domésticos reflejan jerarquías antiguas y no autorizan esclavitud, abuso ni obediencia a órdenes dañinas. «Perdonar» no elimina seguridad ni justicia.","terms":["nueva humanidad","compasión","perdón","paz","hogar","oración","sabiduría"],"reflection":"La espiritualidad se vuelve creíble en la forma de hablar, trabajar, resolver conflictos y reconocer a colaboradores invisibilizados.","groups":["familias antiguas","personas esclavizadas","colaboradores de Pablo"],"places":["Colosas","Laodicea"]}
  ]$sections$::jsonb
);