-- FASE D · Bloque 4
-- Catálogo temático amplio para concordancias internas.
-- No copia texto bíblico protegido: registra conceptos, intenciones y referencias.

with source as (
  select id
  from public.biblical_sources
  where slug = 'open-cross-ref'
    and enabled = true
    and review_status = 'approved'
  limit 1
),
dataset(canonical_term, normalized_term, description, source_locator, content_hash) as (
  values
('Oración', 'oracion', 'Comunicación con Dios, petición, gratitud, intercesión, perseverancia y confianza.', 'editorial-theme:oracion', 'concordance-rich-v1:oracion'),
('Amor', 'amor', 'Amor de Dios, amor al prójimo, entrega, fidelidad y vida comunitaria.', 'editorial-theme:amor', 'concordance-rich-v1:amor'),
('Fe', 'fe', 'Confianza en Dios, fidelidad, perseverancia y respuesta humana a su promesa.', 'editorial-theme:fe', 'concordance-rich-v1:fe'),
('Esperanza', 'esperanza', 'Confianza futura en Dios en medio del sufrimiento, la espera y la incertidumbre.', 'editorial-theme:esperanza', 'concordance-rich-v1:esperanza'),
('Perdón', 'perdon', 'Perdón divino, arrepentimiento, reconciliación y perdón entre personas.', 'editorial-theme:perdon', 'concordance-rich-v1:perdon'),
('Salvación', 'salvacion', 'Liberación del pecado, gracia, fe, vida nueva y reconciliación con Dios.', 'editorial-theme:salvacion', 'concordance-rich-v1:salvacion'),
('Ansiedad y preocupación', 'ansiedad y preocupacion', 'Preocupación, temor por el futuro, descanso y confianza en el cuidado de Dios.', 'editorial-theme:ansiedad', 'concordance-rich-v1:ansiedad'),
('Miedo y valentía', 'miedo y valentia', 'Temor, seguridad, valor y confianza en la presencia de Dios.', 'editorial-theme:miedo', 'concordance-rich-v1:miedo'),
('Paz', 'paz', 'Shalom, reconciliación, descanso interior y paz con Dios y con los demás.', 'editorial-theme:paz', 'concordance-rich-v1:paz'),
('Sabiduría', 'sabiduria', 'Discernimiento, prudencia, conocimiento aplicado y temor de Dios.', 'editorial-theme:sabiduria', 'concordance-rich-v1:sabiduria'),
('Pecado', 'pecado', 'Rebelión, culpa, consecuencias, confesión y restauración.', 'editorial-theme:pecado', 'concordance-rich-v1:pecado'),
('Espíritu Santo', 'espiritu santo', 'Presencia y obra del Espíritu, guía, consuelo, dones y transformación.', 'editorial-theme:espiritu_santo', 'concordance-rich-v1:espiritu_santo'),
('Familia', 'familia', 'Relaciones familiares, crianza, honra, cuidado y vida en el hogar.', 'editorial-theme:familia', 'concordance-rich-v1:familia'),
('Matrimonio', 'matrimonio', 'Pacto matrimonial, fidelidad, servicio mutuo y reconciliación conyugal.', 'editorial-theme:matrimonio', 'concordance-rich-v1:matrimonio'),
('Amistad', 'amistad', 'Lealtad, compañía, consejo, corrección y relaciones sanas.', 'editorial-theme:amistad', 'concordance-rich-v1:amistad'),
('Dinero y mayordomía', 'dinero y mayordomia', 'Uso responsable de recursos, generosidad, contentamiento y peligro de la avaricia.', 'editorial-theme:dinero', 'concordance-rich-v1:dinero'),
('Trabajo y vocación', 'trabajo y vocacion', 'Trabajo diligente, servicio, propósito, descanso y justicia laboral.', 'editorial-theme:trabajo', 'concordance-rich-v1:trabajo'),
('Justicia', 'justicia', 'Rectitud, defensa del vulnerable, juicio justo y justicia de Dios.', 'editorial-theme:justicia', 'concordance-rich-v1:justicia'),
('Servicio', 'servicio', 'Servicio humilde a Dios y al prójimo, dones y responsabilidad comunitaria.', 'editorial-theme:servicio', 'concordance-rich-v1:servicio'),
('Iglesia y comunidad', 'iglesia y comunidad', 'Comunidad de creyentes, unidad, adoración, misión y cuidado mutuo.', 'editorial-theme:iglesia', 'concordance-rich-v1:iglesia'),
('Adoración', 'adoracion', 'Respuesta reverente a Dios mediante vida, oración, canto y obediencia.', 'editorial-theme:adoracion', 'concordance-rich-v1:adoracion'),
('Sanidad y enfermedad', 'sanidad y enfermedad', 'Enfermedad, cuidado, oración, medicina, sufrimiento y esperanza.', 'editorial-theme:sanidad', 'concordance-rich-v1:sanidad'),
('Sufrimiento', 'sufrimiento', 'Dolor, prueba, perseverancia, lamento y presencia de Dios.', 'editorial-theme:sufrimiento', 'concordance-rich-v1:sufrimiento'),
('Duelo y muerte', 'duelo y muerte', 'Pérdida, consuelo, esperanza de resurrección y acompañamiento en el duelo.', 'editorial-theme:duelo', 'concordance-rich-v1:duelo'),
('Identidad y propósito', 'identidad y proposito', 'Dignidad humana, nueva identidad, llamado y propósito delante de Dios.', 'editorial-theme:identidad', 'concordance-rich-v1:identidad'),
('Humildad', 'humildad', 'Actitud de servicio, dependencia de Dios y renuncia al orgullo.', 'editorial-theme:humildad', 'concordance-rich-v1:humildad'),
('Obediencia', 'obediencia', 'Escuchar y responder a Dios con fidelidad, amor y práctica.', 'editorial-theme:obediencia', 'concordance-rich-v1:obediencia'),
('Liderazgo', 'liderazgo', 'Servicio, carácter, responsabilidad, autoridad y cuidado de personas.', 'editorial-theme:liderazgo', 'concordance-rich-v1:liderazgo'),
('Sexualidad y pureza', 'sexualidad y pureza', 'Cuerpo, fidelidad, deseo, pureza, matrimonio y dignidad.', 'editorial-theme:sexualidad', 'concordance-rich-v1:sexualidad'),
('Palabras y comunicación', 'palabras y comunicacion', 'Uso responsable del habla, verdad, ánimo, chisme y control de la lengua.', 'editorial-theme:palabras', 'concordance-rich-v1:palabras'),
('Tiempo y prioridades', 'tiempo y prioridades', 'Uso sabio del tiempo, prioridades, descanso y brevedad de la vida.', 'editorial-theme:tiempo', 'concordance-rich-v1:tiempo'),
('Gratitud', 'gratitud', 'Agradecimiento a Dios, contentamiento y reconocimiento de sus dones.', 'editorial-theme:gratitud', 'concordance-rich-v1:gratitud')
)
insert into public.biblical_concordance_terms (
  canonical_term, normalized_term, language, description, source_id,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select
  d.canonical_term, d.normalized_term, 'es', d.description, s.id,
  d.source_locator, 'concordance-rich-v1-2026-08-02', encode(digest(d.content_hash, 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('editorial_scope', 'tema_biblico', 'generated_by_ai', false, 'catalog_version', 'rich-v1')
from dataset d
cross join source s
on conflict (normalized_term, language, source_id)
do update set
  canonical_term = excluded.canonical_term,
  description = excluded.description,
  source_locator = excluded.source_locator,
  provider_version = excluded.provider_version,
  content_hash = excluded.content_hash,
  review_status = 'approved',
  enabled = true,
  metadata = excluded.metadata,
  updated_at = now();

with source as (
  select id from public.biblical_sources
  where slug = 'open-cross-ref' and enabled = true and review_status = 'approved' limit 1
),
dataset(normalized_term, alias, normalized_alias, alias_kind) as (
  values
('oracion','orar','orar','synonym'),('oracion','oración','oracion','synonym'),('oracion','plegaria','plegaria','synonym'),('oracion','rezar','rezar','synonym'),('oracion','hablar con Dios','hablar con dios','question_intent'),('oracion','pedir a Dios','pedir a dios','question_intent'),('oracion','interceder','interceder','synonym'),('oracion','intercesión','intercesion','synonym'),('oracion','acción de gracias','accion de gracias','question_intent'),('oracion','dar gracias','dar gracias','question_intent'),('oracion','cómo orar','como orar','question_intent'),('oracion','Dios escucha','dios escucha','question_intent'),('oracion','Dios responde','dios responde','question_intent'),('oracion','vida de oración','vida de oracion','question_intent'),
('amor','amar','amar','synonym'),('amor','amor de Dios','amor de dios','question_intent'),('amor','amor al prójimo','amor al projimo','question_intent'),('amor','caridad','caridad','synonym'),('amor','afecto','afecto','synonym'),('amor','compasión','compasion','synonym'),('amor','cómo amar','como amar','question_intent'),('amor','Dios me ama','dios me ama','question_intent'),('amor','amor verdadero','amor verdadero','question_intent'),('amor','amor cristiano','amor cristiano','question_intent'),('amor','amar enemigos','amar enemigos','question_intent'),('amor','amor incondicional','amor incondicional','question_intent'),
('fe','creer','creer','synonym'),('fe','confianza en Dios','confianza en dios','question_intent'),('fe','tener fe','tener fe','question_intent'),('fe','falta de fe','falta de fe','question_intent'),('fe','aumentar mi fe','aumentar mi fe','question_intent'),('fe','duda','duda','synonym'),('fe','dudas de fe','dudas de fe','question_intent'),('fe','fidelidad','fidelidad','synonym'),('fe','caminar por fe','caminar por fe','question_intent'),('fe','vivir por fe','vivir por fe','question_intent'),('fe','qué es la fe','que es la fe','question_intent'),
('esperanza','esperar en Dios','esperar en dios','question_intent'),('esperanza','esperanza cristiana','esperanza cristiana','question_intent'),('esperanza','no perder esperanza','no perder esperanza','question_intent'),('esperanza','futuro','futuro','synonym'),('esperanza','ánimo','animo','synonym'),('esperanza','desánimo','desanimo','synonym'),('esperanza','Dios tiene propósito','dios tiene proposito','question_intent'),('esperanza','esperanza en tiempos difíciles','esperanza en tiempos dificiles','question_intent'),('esperanza','seguir adelante','seguir adelante','question_intent'),
('perdon','perdonar','perdonar','synonym'),('perdon','perdón de Dios','perdon de dios','question_intent'),('perdon','cómo perdonar','como perdonar','question_intent'),('perdon','no puedo perdonar','no puedo perdonar','question_intent'),('perdon','culpa','culpa','synonym'),('perdon','reconciliación','reconciliacion','synonym'),('perdon','pedir perdón','pedir perdon','question_intent'),('perdon','arrepentirse','arrepentirse','synonym'),('perdon','misericordia','misericordia','synonym'),('perdon','borrar pecados','borrar pecados','question_intent'),
('salvacion','ser salvo','ser salvo','question_intent'),('salvacion','cómo salvarme','como salvarme','question_intent'),('salvacion','salvación eterna','salvacion eterna','question_intent'),('salvacion','gracia','gracia','synonym'),('salvacion','nuevo nacimiento','nuevo nacimiento','question_intent'),('salvacion','nacer de nuevo','nacer de nuevo','question_intent'),('salvacion','redención','redencion','synonym'),('salvacion','vida eterna','vida eterna','question_intent'),('salvacion','evangelio','evangelio','synonym'),('salvacion','aceptar a Jesús','aceptar a jesus','question_intent'),
('ansiedad y preocupacion','ansiedad','ansiedad','synonym'),('ansiedad y preocupacion','preocupación','preocupacion','synonym'),('ansiedad y preocupacion','preocupado','preocupado','synonym'),('ansiedad y preocupacion','estrés','estres','synonym'),('ansiedad y preocupacion','no puedo dormir','no puedo dormir','question_intent'),('ansiedad y preocupacion','miedo al futuro','miedo al futuro','question_intent'),('ansiedad y preocupacion','ataque de ansiedad','ataque de ansiedad','question_intent'),('ansiedad y preocupacion','cómo dejar de preocuparme','como dejar de preocuparme','question_intent'),('ansiedad y preocupacion','Dios cuida de mí','dios cuida de mi','question_intent'),('ansiedad y preocupacion','descansar en Dios','descansar en dios','question_intent'),
('miedo y valentia','miedo','miedo','synonym'),('miedo y valentia','temor','temor','synonym'),('miedo y valentia','pánico','panico','synonym'),('miedo y valentia','valentía','valentia','synonym'),('miedo y valentia','ser valiente','ser valiente','question_intent'),('miedo y valentia','no tengas miedo','no tengas miedo','question_intent'),('miedo y valentia','Dios está conmigo','dios esta conmigo','question_intent'),('miedo y valentia','inseguridad','inseguridad','synonym'),('miedo y valentia','cómo vencer el miedo','como vencer el miedo','question_intent'),
('paz','paz interior','paz interior','question_intent'),('paz','shalom','shalom','transliteration'),('paz','tranquilidad','tranquilidad','synonym'),('paz','descanso','descanso','synonym'),('paz','paz de Dios','paz de dios','question_intent'),('paz','cómo tener paz','como tener paz','question_intent'),('paz','conflicto','conflicto','synonym'),('paz','reconciliarse','reconciliarse','synonym'),('paz','vivir en paz','vivir en paz','question_intent'),
('sabiduria','sabiduría','sabiduria','synonym'),('sabiduria','discernimiento','discernimiento','synonym'),('sabiduria','tomar decisiones','tomar decisiones','question_intent'),('sabiduria','qué debo hacer','que debo hacer','question_intent'),('sabiduria','prudencia','prudencia','synonym'),('sabiduria','consejo','consejo','synonym'),('sabiduria','pedir sabiduría','pedir sabiduria','question_intent'),('sabiduria','decisión difícil','decision dificil','question_intent'),('sabiduria','dirección de Dios','direccion de dios','question_intent'),
('pecado','pecado','pecado','synonym'),('pecado','tentación','tentacion','synonym'),('pecado','caer en pecado','caer en pecado','question_intent'),('pecado','culpa','culpa','synonym'),('pecado','desobediencia','desobediencia','synonym'),('pecado','vicio','vicio','synonym'),('pecado','cómo vencer el pecado','como vencer el pecado','question_intent'),('pecado','confesar pecados','confesar pecados','question_intent'),('pecado','arrepentimiento','arrepentimiento','synonym'),
('espiritu santo','Espíritu Santo','espiritu santo','synonym'),('espiritu santo','ruaj','ruaj','transliteration'),('espiritu santo','Espíritu de Dios','espiritu de dios','question_intent'),('espiritu santo','llenura del Espíritu','llenura del espiritu','question_intent'),('espiritu santo','dones espirituales','dones espirituales','question_intent'),('espiritu santo','fruto del Espíritu','fruto del espiritu','question_intent'),('espiritu santo','guía del Espíritu','guia del espiritu','question_intent'),('espiritu santo','Consolador','consolador','synonym'),('espiritu santo','bautismo en el Espíritu','bautismo en el espiritu','question_intent'),
('familia','familia','familia','synonym'),('familia','hogar','hogar','synonym'),('familia','padres','padres','synonym'),('familia','hijos','hijos','synonym'),('familia','crianza','crianza','synonym'),('familia','matrimonio','matrimonio','synonym'),('familia','problemas familiares','problemas familiares','question_intent'),('familia','honrar padres','honrar padres','question_intent'),('familia','educar hijos','educar hijos','question_intent'),('familia','familia cristiana','familia cristiana','question_intent'),
('matrimonio','matrimonio','matrimonio','synonym'),('matrimonio','esposo','esposo','synonym'),('matrimonio','esposa','esposa','synonym'),('matrimonio','pareja','pareja','synonym'),('matrimonio','divorcio','divorcio','synonym'),('matrimonio','infidelidad','infidelidad','synonym'),('matrimonio','problemas de pareja','problemas de pareja','question_intent'),('matrimonio','amor matrimonial','amor matrimonial','question_intent'),('matrimonio','casarse','casarse','synonym'),('matrimonio','relación conyugal','relacion conyugal','question_intent'),
('amistad','amistad','amistad','synonym'),('amistad','amigos','amigos','synonym'),('amistad','mejores amigos','mejores amigos','question_intent'),('amistad','amistad tóxica','amistad toxica','question_intent'),('amistad','soledad','soledad','synonym'),('amistad','compañerismo','companerismo','synonym'),('amistad','buen amigo','buen amigo','question_intent'),('amistad','traición de un amigo','traicion de un amigo','question_intent'),
('dinero y mayordomia','dinero','dinero','synonym'),('dinero y mayordomia','finanzas','finanzas','synonym'),('dinero y mayordomia','deudas','deudas','synonym'),('dinero y mayordomia','riqueza','riqueza','synonym'),('dinero y mayordomia','pobreza','pobreza','synonym'),('dinero y mayordomia','ofrenda','ofrenda','synonym'),('dinero y mayordomia','diezmo','diezmo','synonym'),('dinero y mayordomia','generosidad','generosidad','synonym'),('dinero y mayordomia','avaricia','avaricia','synonym'),('dinero y mayordomia','administrar dinero','administrar dinero','question_intent'),('dinero y mayordomia','mayordomía','mayordomia','synonym'),('dinero y mayordomia','prosperidad','prosperidad','synonym'),
('trabajo y vocacion','trabajo','trabajo','synonym'),('trabajo y vocacion','empleo','empleo','synonym'),('trabajo y vocacion','vocación','vocacion','synonym'),('trabajo y vocacion','negocio','negocio','synonym'),('trabajo y vocacion','desempleo','desempleo','synonym'),('trabajo y vocacion','jefe','jefe','synonym'),('trabajo y vocacion','empleado','empleado','synonym'),('trabajo y vocacion','trabajar para Dios','trabajar para dios','question_intent'),('trabajo y vocacion','propósito profesional','proposito profesional','question_intent'),('trabajo y vocacion','éxito laboral','exito laboral','question_intent'),
('justicia','justicia','justicia','synonym'),('justicia','injusticia','injusticia','synonym'),('justicia','corrupción','corrupcion','synonym'),('justicia','opresión','opresion','synonym'),('justicia','derechos','derechos','synonym'),('justicia','defender al pobre','defender al pobre','question_intent'),('justicia','juicio de Dios','juicio de dios','question_intent'),('justicia','hacer lo correcto','hacer lo correcto','question_intent'),('justicia','equidad','equidad','synonym'),
('servicio','servir','servir','synonym'),('servicio','servicio','servicio','synonym'),('servicio','ministerio','ministerio','synonym'),('servicio','ayudar a otros','ayudar a otros','question_intent'),('servicio','voluntariado','voluntariado','synonym'),('servicio','siervo','siervo','synonym'),('servicio','dones para servir','dones para servir','question_intent'),('servicio','liderazgo de servicio','liderazgo de servicio','question_intent'),
('iglesia y comunidad','iglesia','iglesia','synonym'),('iglesia y comunidad','congregación','congregacion','synonym'),('iglesia y comunidad','comunidad cristiana','comunidad cristiana','question_intent'),('iglesia y comunidad','cuerpo de Cristo','cuerpo de cristo','question_intent'),('iglesia y comunidad','reunirse','reunirse','synonym'),('iglesia y comunidad','comunión','comunion','synonym'),('iglesia y comunidad','unidad de la iglesia','unidad de la iglesia','question_intent'),('iglesia y comunidad','problemas en la iglesia','problemas en la iglesia','question_intent'),
('adoracion','adoración','adoracion','synonym'),('adoracion','alabanza','alabanza','synonym'),('adoracion','adorar','adorar','synonym'),('adoracion','cantar a Dios','cantar a dios','question_intent'),('adoracion','culto','culto','synonym'),('adoracion','música cristiana','musica cristiana','question_intent'),('adoracion','adoración en espíritu y verdad','adoracion en espiritu y verdad','question_intent'),('adoracion','dar gloria a Dios','dar gloria a dios','question_intent'),
('sanidad y enfermedad','sanidad','sanidad','synonym'),('sanidad y enfermedad','enfermedad','enfermedad','synonym'),('sanidad y enfermedad','salud','salud','synonym'),('sanidad y enfermedad','milagro de sanidad','milagro de sanidad','question_intent'),('sanidad y enfermedad','orar por enfermos','orar por enfermos','question_intent'),('sanidad y enfermedad','dolor físico','dolor fisico','question_intent'),('sanidad y enfermedad','Dios sana','dios sana','question_intent'),('sanidad y enfermedad','medicina','medicina','synonym'),('sanidad y enfermedad','estar enfermo','estar enfermo','question_intent'),
('sufrimiento','sufrimiento','sufrimiento','synonym'),('sufrimiento','dolor','dolor','synonym'),('sufrimiento','prueba','prueba','synonym'),('sufrimiento','por qué sufro','por que sufro','question_intent'),('sufrimiento','Dios permite el dolor','dios permite el dolor','question_intent'),('sufrimiento','tribulación','tribulacion','synonym'),('sufrimiento','aflicción','afliccion','synonym'),('sufrimiento','momento difícil','momento dificil','question_intent'),('sufrimiento','lamento','lamento','synonym'),
('duelo y muerte','duelo','duelo','synonym'),('duelo y muerte','muerte','muerte','synonym'),('duelo y muerte','perdí a un ser querido','perdi a un ser querido','question_intent'),('duelo y muerte','luto','luto','synonym'),('duelo y muerte','consuelo por muerte','consuelo por muerte','question_intent'),('duelo y muerte','funeral','funeral','synonym'),('duelo y muerte','resurrección','resurreccion','synonym'),('duelo y muerte','vida después de la muerte','vida despues de la muerte','question_intent'),
('identidad y proposito','identidad','identidad','synonym'),('identidad y proposito','quién soy','quien soy','question_intent'),('identidad y proposito','propósito de vida','proposito de vida','question_intent'),('identidad y proposito','para qué nací','para que naci','question_intent'),('identidad y proposito','valor personal','valor personal','question_intent'),('identidad y proposito','Dios me creó','dios me creo','question_intent'),('identidad y proposito','identidad en Cristo','identidad en cristo','question_intent'),('identidad y proposito','llamado de Dios','llamado de dios','question_intent'),('identidad y proposito','autoestima','autoestima','synonym'),
('humildad','humildad','humildad','synonym'),('humildad','orgullo','orgullo','synonym'),('humildad','soberbia','soberbia','synonym'),('humildad','ser humilde','ser humilde','question_intent'),('humildad','ego','ego','synonym'),('humildad','vanidad','vanidad','synonym'),('humildad','Dios resiste al soberbio','dios resiste al soberbio','question_intent'),('humildad','humillarse ante Dios','humillarse ante dios','question_intent'),
('obediencia','obediencia','obediencia','synonym'),('obediencia','obedecer a Dios','obedecer a dios','question_intent'),('obediencia','desobediencia','desobediencia','synonym'),('obediencia','voluntad de Dios','voluntad de dios','question_intent'),('obediencia','hacer lo que Dios dice','hacer lo que dios dice','question_intent'),('obediencia','mandamientos','mandamientos','synonym'),('obediencia','seguir a Jesús','seguir a jesus','question_intent'),
('liderazgo','liderazgo','liderazgo','synonym'),('liderazgo','líder','lider','synonym'),('liderazgo','pastor','pastor','synonym'),('liderazgo','autoridad','autoridad','synonym'),('liderazgo','dirigir','dirigir','synonym'),('liderazgo','liderazgo cristiano','liderazgo cristiano','question_intent'),('liderazgo','mal liderazgo','mal liderazgo','question_intent'),('liderazgo','ser un buen líder','ser un buen lider','question_intent'),('liderazgo','responsabilidad espiritual','responsabilidad espiritual','question_intent'),
('sexualidad y pureza','sexualidad','sexualidad','synonym'),('sexualidad y pureza','sexo','sexo','synonym'),('sexualidad y pureza','pureza','pureza','synonym'),('sexualidad y pureza','pornografía','pornografia','synonym'),('sexualidad y pureza','adulterio','adulterio','synonym'),('sexualidad y pureza','fornicación','fornicacion','synonym'),('sexualidad y pureza','tentación sexual','tentacion sexual','question_intent'),('sexualidad y pureza','cuerpo templo','cuerpo templo','question_intent'),('sexualidad y pureza','relaciones sexuales','relaciones sexuales','question_intent'),('sexualidad y pureza','deseo sexual','deseo sexual','question_intent'),
('palabras y comunicacion','palabras','palabras','synonym'),('palabras y comunicacion','lengua','lengua','synonym'),('palabras y comunicacion','chisme','chisme','synonym'),('palabras y comunicacion','mentira','mentira','synonym'),('palabras y comunicacion','insulto','insulto','synonym'),('palabras y comunicacion','hablar bien','hablar bien','question_intent'),('palabras y comunicacion','controlar la lengua','controlar la lengua','question_intent'),('palabras y comunicacion','comunicación','comunicacion','synonym'),('palabras y comunicacion','decir la verdad','decir la verdad','question_intent'),('palabras y comunicacion','palabras que edifican','palabras que edifican','question_intent'),
('tiempo y prioridades','tiempo','tiempo','synonym'),('tiempo y prioridades','prioridades','prioridades','synonym'),('tiempo y prioridades','perder el tiempo','perder el tiempo','question_intent'),('tiempo y prioridades','organizar mi vida','organizar mi vida','question_intent'),('tiempo y prioridades','descanso','descanso','synonym'),('tiempo y prioridades','día de reposo','dia de reposo','question_intent'),('tiempo y prioridades','aprovechar el tiempo','aprovechar el tiempo','question_intent'),('tiempo y prioridades','vida corta','vida corta','question_intent'),
('gratitud','gratitud','gratitud','synonym'),('gratitud','agradecimiento','agradecimiento','synonym'),('gratitud','dar gracias','dar gracias','question_intent'),('gratitud','ser agradecido','ser agradecido','question_intent'),('gratitud','contentamiento','contentamiento','synonym'),('gratitud','quejarse','quejarse','synonym'),('gratitud','acción de gracias','accion de gracias','question_intent'),('gratitud','gracias a Dios','gracias a dios','question_intent')
),
resolved as (
  select t.id as term_id, d.alias, d.normalized_alias, d.alias_kind
  from dataset d join source s on true
  join public.biblical_concordance_terms t on t.normalized_term=d.normalized_term and t.language='es' and t.source_id=s.id
)
insert into public.biblical_concordance_aliases(term_id,alias,normalized_alias,alias_kind,review_status,enabled)
select term_id,alias,normalized_alias,alias_kind,'approved',true from resolved
on conflict(term_id,normalized_alias) do update set alias=excluded.alias,alias_kind=excluded.alias_kind,review_status='approved',enabled=true;

with source as (
  select id from public.biblical_sources where slug='open-cross-ref' and enabled=true and review_status='approved' limit 1
),
dataset(normalized_term,book_code,book_name,chapter,verse,reference_label,relevance,relation_kind) as (
  values
('oracion','MAT','Mateo',6,6,'Mateo 6:6',100,'conceptual'),('oracion','MAT','Mateo',6,7,'Mateo 6:7',100,'conceptual'),('oracion','PHP','Filipenses',4,6,'Filipenses 4:6',95,'conceptual'),('oracion','1TH','1 Tesalonicenses',5,17,'1 Tesalonicenses 5:17',95,'conceptual'),('oracion','JAS','Santiago',5,16,'Santiago 5:16',90,'conceptual'),('oracion','LUK','Lucas',11,1,'Lucas 11:1',90,'conceptual'),
('amor','JHN','Juan',3,16,'Juan 3:16',100,'conceptual'),('amor','1CO','1 Corintios',13,4,'1 Corintios 13:4',100,'conceptual'),('amor','MAT','Mateo',22,37,'Mateo 22:37',95,'conceptual'),('amor','JHN','Juan',13,34,'Juan 13:34',95,'conceptual'),('amor','1JN','1 Juan',4,8,'1 Juan 4:8',95,'conceptual'),('amor','ROM','Romanos',5,8,'Romanos 5:8',90,'conceptual'),
('fe','HEB','Hebreos',11,1,'Hebreos 11:1',100,'conceptual'),('fe','ROM','Romanos',10,17,'Romanos 10:17',95,'conceptual'),('fe','MRK','Marcos',9,24,'Marcos 9:24',95,'conceptual'),('fe','2CO','2 Corintios',5,7,'2 Corintios 5:7',90,'conceptual'),('fe','JAS','Santiago',2,17,'Santiago 2:17',90,'conceptual'),('fe','GAL','Gálatas',2,20,'Gálatas 2:20',90,'conceptual'),
('esperanza','ROM','Romanos',15,13,'Romanos 15:13',100,'conceptual'),('esperanza','JER','Jeremías',29,11,'Jeremías 29:11',90,'conceptual'),('esperanza','PSA','Salmos',42,5,'Salmos 42:5',95,'conceptual'),('esperanza','LAM','Lamentaciones',3,22,'Lamentaciones 3:22',90,'conceptual'),('esperanza','1PE','1 Pedro',1,3,'1 Pedro 1:3',90,'conceptual'),
('perdon','1JN','1 Juan',1,9,'1 Juan 1:9',100,'conceptual'),('perdon','MAT','Mateo',6,14,'Mateo 6:14',95,'conceptual'),('perdon','EPH','Efesios',4,32,'Efesios 4:32',95,'conceptual'),('perdon','COL','Colosenses',3,13,'Colosenses 3:13',90,'conceptual'),('perdon','PSA','Salmos',51,1,'Salmos 51:1',90,'conceptual'),
('salvacion','EPH','Efesios',2,8,'Efesios 2:8',100,'conceptual'),('salvacion','ROM','Romanos',10,9,'Romanos 10:9',100,'conceptual'),('salvacion','JHN','Juan',3,16,'Juan 3:16',100,'conceptual'),('salvacion','ACT','Hechos',4,12,'Hechos 4:12',95,'conceptual'),('salvacion','TIT','Tito',3,5,'Tito 3:5',90,'conceptual'),
('ansiedad y preocupacion','PHP','Filipenses',4,6,'Filipenses 4:6',100,'conceptual'),('ansiedad y preocupacion','1PE','1 Pedro',5,7,'1 Pedro 5:7',100,'conceptual'),('ansiedad y preocupacion','MAT','Mateo',6,25,'Mateo 6:25',95,'conceptual'),('ansiedad y preocupacion','PSA','Salmos',55,22,'Salmos 55:22',90,'conceptual'),('ansiedad y preocupacion','JHN','Juan',14,27,'Juan 14:27',95,'conceptual'),
('miedo y valentia','ISA','Isaías',41,10,'Isaías 41:10',100,'conceptual'),('miedo y valentia','PSA','Salmos',23,4,'Salmos 23:4',100,'conceptual'),('miedo y valentia','JOS','Josué',1,9,'Josué 1:9',95,'conceptual'),('miedo y valentia','2TI','2 Timoteo',1,7,'2 Timoteo 1:7',95,'conceptual'),('miedo y valentia','PSA','Salmos',56,3,'Salmos 56:3',90,'conceptual'),
('paz','JHN','Juan',14,27,'Juan 14:27',100,'conceptual'),('paz','PHP','Filipenses',4,7,'Filipenses 4:7',100,'conceptual'),('paz','ROM','Romanos',5,1,'Romanos 5:1',95,'conceptual'),('paz','COL','Colosenses',3,15,'Colosenses 3:15',90,'conceptual'),('paz','ISA','Isaías',26,3,'Isaías 26:3',95,'conceptual'),
('sabiduria','JAS','Santiago',1,5,'Santiago 1:5',100,'conceptual'),('sabiduria','PRO','Proverbios',3,5,'Proverbios 3:5',100,'conceptual'),('sabiduria','PRO','Proverbios',1,7,'Proverbios 1:7',95,'conceptual'),('sabiduria','ECC','Eclesiastés',7,12,'Eclesiastés 7:12',85,'conceptual'),('sabiduria','COL','Colosenses',1,9,'Colosenses 1:9',90,'conceptual'),
('pecado','ROM','Romanos',3,23,'Romanos 3:23',100,'conceptual'),('pecado','ROM','Romanos',6,23,'Romanos 6:23',100,'conceptual'),('pecado','1JN','1 Juan',1,9,'1 Juan 1:9',95,'conceptual'),('pecado','JAS','Santiago',1,14,'Santiago 1:14',90,'conceptual'),('pecado','1CO','1 Corintios',10,13,'1 Corintios 10:13',95,'conceptual'),
('espiritu santo','JHN','Juan',14,26,'Juan 14:26',100,'conceptual'),('espiritu santo','ACT','Hechos',1,8,'Hechos 1:8',100,'conceptual'),('espiritu santo','GAL','Gálatas',5,22,'Gálatas 5:22',95,'conceptual'),('espiritu santo','1CO','1 Corintios',12,4,'1 Corintios 12:4',90,'conceptual'),('espiritu santo','ROM','Romanos',8,26,'Romanos 8:26',95,'conceptual'),
('familia','EPH','Efesios',6,1,'Efesios 6:1',95,'conceptual'),('familia','EPH','Efesios',6,4,'Efesios 6:4',95,'conceptual'),('familia','JOS','Josué',24,15,'Josué 24:15',100,'conceptual'),('familia','COL','Colosenses',3,20,'Colosenses 3:20',90,'conceptual'),('familia','PRO','Proverbios',22,6,'Proverbios 22:6',90,'conceptual'),
('matrimonio','GEN','Génesis',2,24,'Génesis 2:24',100,'conceptual'),('matrimonio','EPH','Efesios',5,25,'Efesios 5:25',95,'conceptual'),('matrimonio','1CO','1 Corintios',13,4,'1 Corintios 13:4',90,'conceptual'),('matrimonio','MAT','Mateo',19,6,'Mateo 19:6',95,'conceptual'),('matrimonio','HEB','Hebreos',13,4,'Hebreos 13:4',90,'conceptual'),
('amistad','PRO','Proverbios',17,17,'Proverbios 17:17',100,'conceptual'),('amistad','PRO','Proverbios',27,17,'Proverbios 27:17',95,'conceptual'),('amistad','JHN','Juan',15,13,'Juan 15:13',95,'conceptual'),('amistad','ECC','Eclesiastés',4,9,'Eclesiastés 4:9',90,'conceptual'),('amistad','1CO','1 Corintios',15,33,'1 Corintios 15:33',90,'conceptual'),
('dinero y mayordomia','MAT','Mateo',6,24,'Mateo 6:24',100,'conceptual'),('dinero y mayordomia','1TI','1 Timoteo',6,10,'1 Timoteo 6:10',100,'conceptual'),('dinero y mayordomia','PRO','Proverbios',3,9,'Proverbios 3:9',90,'conceptual'),('dinero y mayordomia','2CO','2 Corintios',9,7,'2 Corintios 9:7',95,'conceptual'),('dinero y mayordomia','PHP','Filipenses',4,12,'Filipenses 4:12',90,'conceptual'),
('trabajo y vocacion','COL','Colosenses',3,23,'Colosenses 3:23',100,'conceptual'),('trabajo y vocacion','PRO','Proverbios',14,23,'Proverbios 14:23',95,'conceptual'),('trabajo y vocacion','2TH','2 Tesalonicenses',3,10,'2 Tesalonicenses 3:10',90,'conceptual'),('trabajo y vocacion','ECC','Eclesiastés',3,13,'Eclesiastés 3:13',85,'conceptual'),('trabajo y vocacion','EPH','Efesios',6,7,'Efesios 6:7',90,'conceptual'),
('justicia','MIC','Miqueas',6,8,'Miqueas 6:8',100,'conceptual'),('justicia','AMO','Amós',5,24,'Amós 5:24',100,'conceptual'),('justicia','ISA','Isaías',1,17,'Isaías 1:17',95,'conceptual'),('justicia','MAT','Mateo',5,6,'Mateo 5:6',90,'conceptual'),('justicia','PSA','Salmos',82,3,'Salmos 82:3',95,'conceptual'),
('servicio','MRK','Marcos',10,45,'Marcos 10:45',100,'conceptual'),('servicio','GAL','Gálatas',5,13,'Gálatas 5:13',95,'conceptual'),('servicio','1PE','1 Pedro',4,10,'1 Pedro 4:10',95,'conceptual'),('servicio','JHN','Juan',13,14,'Juan 13:14',90,'conceptual'),('servicio','ROM','Romanos',12,11,'Romanos 12:11',90,'conceptual'),
('iglesia y comunidad','ACT','Hechos',2,42,'Hechos 2:42',100,'conceptual'),('iglesia y comunidad','HEB','Hebreos',10,25,'Hebreos 10:25',100,'conceptual'),('iglesia y comunidad','1CO','1 Corintios',12,27,'1 Corintios 12:27',95,'conceptual'),('iglesia y comunidad','EPH','Efesios',4,3,'Efesios 4:3',90,'conceptual'),('iglesia y comunidad','MAT','Mateo',18,20,'Mateo 18:20',90,'conceptual'),
('adoracion','JHN','Juan',4,23,'Juan 4:23',100,'conceptual'),('adoracion','PSA','Salmos',95,6,'Salmos 95:6',95,'conceptual'),('adoracion','ROM','Romanos',12,1,'Romanos 12:1',95,'conceptual'),('adoracion','PSA','Salmos',150,1,'Salmos 150:1',90,'conceptual'),('adoracion','HEB','Hebreos',13,15,'Hebreos 13:15',90,'conceptual'),
('sanidad y enfermedad','JAS','Santiago',5,14,'Santiago 5:14',100,'conceptual'),('sanidad y enfermedad','PSA','Salmos',103,3,'Salmos 103:3',90,'conceptual'),('sanidad y enfermedad','MRK','Marcos',2,17,'Marcos 2:17',85,'conceptual'),('sanidad y enfermedad','2CO','2 Corintios',12,9,'2 Corintios 12:9',95,'conceptual'),('sanidad y enfermedad','3JN','3 Juan',1,2,'3 Juan 1:2',80,'conceptual'),
('sufrimiento','ROM','Romanos',8,18,'Romanos 8:18',100,'conceptual'),('sufrimiento','JAS','Santiago',1,2,'Santiago 1:2',90,'conceptual'),('sufrimiento','PSA','Salmos',34,18,'Salmos 34:18',100,'conceptual'),('sufrimiento','2CO','2 Corintios',4,17,'2 Corintios 4:17',90,'conceptual'),('sufrimiento','JOB','Job',1,21,'Job 1:21',85,'conceptual'),
('duelo y muerte','JHN','Juan',11,25,'Juan 11:25',100,'conceptual'),('duelo y muerte','1TH','1 Tesalonicenses',4,13,'1 Tesalonicenses 4:13',100,'conceptual'),('duelo y muerte','PSA','Salmos',34,18,'Salmos 34:18',95,'conceptual'),('duelo y muerte','REV','Apocalipsis',21,4,'Apocalipsis 21:4',95,'conceptual'),('duelo y muerte','ECC','Eclesiastés',3,4,'Eclesiastés 3:4',85,'conceptual'),
('identidad y proposito','GEN','Génesis',1,27,'Génesis 1:27',100,'conceptual'),('identidad y proposito','EPH','Efesios',2,10,'Efesios 2:10',100,'conceptual'),('identidad y proposito','2CO','2 Corintios',5,17,'2 Corintios 5:17',95,'conceptual'),('identidad y proposito','PSA','Salmos',139,14,'Salmos 139:14',95,'conceptual'),('identidad y proposito','1PE','1 Pedro',2,9,'1 Pedro 2:9',95,'conceptual'),
('humildad','PHP','Filipenses',2,3,'Filipenses 2:3',100,'conceptual'),('humildad','JAS','Santiago',4,6,'Santiago 4:6',95,'conceptual'),('humildad','MIC','Miqueas',6,8,'Miqueas 6:8',90,'conceptual'),('humildad','1PE','1 Pedro',5,6,'1 Pedro 5:6',95,'conceptual'),('humildad','PRO','Proverbios',16,18,'Proverbios 16:18',95,'conceptual'),
('obediencia','JHN','Juan',14,15,'Juan 14:15',100,'conceptual'),('obediencia','1SA','1 Samuel',15,22,'1 Samuel 15:22',95,'conceptual'),('obediencia','JAS','Santiago',1,22,'Santiago 1:22',100,'conceptual'),('obediencia','DEU','Deuteronomio',6,5,'Deuteronomio 6:5',95,'conceptual'),('obediencia','LUK','Lucas',11,28,'Lucas 11:28',90,'conceptual'),
('liderazgo','MRK','Marcos',10,42,'Marcos 10:42',100,'conceptual'),('liderazgo','1TI','1 Timoteo',3,2,'1 Timoteo 3:2',95,'conceptual'),('liderazgo','1PE','1 Pedro',5,2,'1 Pedro 5:2',95,'conceptual'),('liderazgo','PRO','Proverbios',11,14,'Proverbios 11:14',90,'conceptual'),('liderazgo','LUK','Lucas',22,26,'Lucas 22:26',95,'conceptual'),
('sexualidad y pureza','1CO','1 Corintios',6,18,'1 Corintios 6:18',100,'conceptual'),('sexualidad y pureza','MAT','Mateo',5,28,'Mateo 5:28',95,'conceptual'),('sexualidad y pureza','1TH','1 Tesalonicenses',4,3,'1 Tesalonicenses 4:3',95,'conceptual'),('sexualidad y pureza','HEB','Hebreos',13,4,'Hebreos 13:4',90,'conceptual'),('sexualidad y pureza','JOB','Job',31,1,'Job 31:1',90,'conceptual'),
('palabras y comunicacion','EPH','Efesios',4,29,'Efesios 4:29',100,'conceptual'),('palabras y comunicacion','JAS','Santiago',3,5,'Santiago 3:5',100,'conceptual'),('palabras y comunicacion','PRO','Proverbios',18,21,'Proverbios 18:21',95,'conceptual'),('palabras y comunicacion','COL','Colosenses',4,6,'Colosenses 4:6',90,'conceptual'),('palabras y comunicacion','MAT','Mateo',12,36,'Mateo 12:36',90,'conceptual'),
('tiempo y prioridades','EPH','Efesios',5,16,'Efesios 5:16',100,'conceptual'),('tiempo y prioridades','PSA','Salmos',90,12,'Salmos 90:12',100,'conceptual'),('tiempo y prioridades','ECC','Eclesiastés',3,1,'Eclesiastés 3:1',95,'conceptual'),('tiempo y prioridades','MAT','Mateo',6,33,'Mateo 6:33',95,'conceptual'),('tiempo y prioridades','MRK','Marcos',6,31,'Marcos 6:31',85,'conceptual'),
('gratitud','1TH','1 Tesalonicenses',5,18,'1 Tesalonicenses 5:18',100,'conceptual'),('gratitud','PSA','Salmos',100,4,'Salmos 100:4',95,'conceptual'),('gratitud','COL','Colosenses',3,17,'Colosenses 3:17',95,'conceptual'),('gratitud','PHP','Filipenses',4,11,'Filipenses 4:11',90,'conceptual'),('gratitud','LUK','Lucas',17,15,'Lucas 17:15',85,'conceptual')
),
resolved as (
 select t.id term_id,d.*,s.id source_id from dataset d join source s on true
 join public.biblical_concordance_terms t on t.normalized_term=d.normalized_term and t.language='es' and t.source_id=s.id
)
insert into public.biblical_concordance_occurrences(term_id,book_code,book_name,chapter,verse,reference_label,relevance,relation_kind,source_id,source_locator,provider_version,content_hash,review_status,enabled,metadata)
select term_id,book_code,book_name,chapter,verse,reference_label,relevance,relation_kind,source_id,
'editorial-reference:'||lower(book_code)||':'||chapter||':'||verse,'concordance-rich-v1-2026-08-02',
encode(digest(normalized_term||':'||book_code||':'||chapter||':'||verse||':'||relation_kind,'sha256'),'hex'),'approved',true,
jsonb_build_object('editorial_relation',true,'generated_by_ai',false,'catalog_version','rich-v1')
from resolved
on conflict(term_id,book_code,chapter,verse,relation_kind,source_id) do update set
book_name=excluded.book_name,reference_label=excluded.reference_label,relevance=excluded.relevance,source_locator=excluded.source_locator,provider_version=excluded.provider_version,content_hash=excluded.content_hash,review_status='approved',enabled=true,metadata=excluded.metadata,updated_at=now();
