create table if not exists public.pilot_participants (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  cohort text not null default 'piloto-inicial',
  active boolean not null default true,
  invited_by uuid null references public.profiles(id) on delete set null,
  invited_at timestamptz not null default now(),
  notes text null,
  constraint pilot_participants_cohort_length check (char_length(cohort) between 1 and 80),
  constraint pilot_participants_notes_length check (notes is null or char_length(notes) <= 1000)
);

create table if not exists public.pilot_onboarding_progress (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  role_snapshot text not null,
  onboarding_version integer not null default 1,
  current_step integer not null default 0,
  completed boolean not null default false,
  notifications_prompted boolean not null default false,
  notifications_enabled boolean,
  completed_at timestamptz,
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pilot_onboarding_role_length check (char_length(role_snapshot) between 1 and 40),
  constraint pilot_onboarding_step_nonnegative check (current_step >= 0)
);

create table if not exists public.pilot_usage_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  event_name text not null,
  route text,
  ministry_id uuid null references public.ministerios(id) on delete set null,
  session_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint pilot_usage_event_name_length check (char_length(event_name) between 1 and 80),
  constraint pilot_usage_route_length check (route is null or char_length(route) <= 240),
  constraint pilot_usage_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create table if not exists public.pilot_issue_reports (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role_snapshot text not null,
  route text,
  description text not null,
  expected_result text,
  device_info jsonb not null default '{}'::jsonb,
  status text not null default 'nuevo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint pilot_issue_status check (status in ('nuevo', 'revisando', 'resuelto')),
  constraint pilot_issue_description_length check (char_length(description) between 5 and 4000),
  constraint pilot_issue_expected_length check (expected_result is null or char_length(expected_result) <= 4000),
  constraint pilot_issue_route_length check (route is null or char_length(route) <= 240),
  constraint pilot_issue_device_object check (jsonb_typeof(device_info) = 'object')
);

create index if not exists pilot_participants_active_idx
  on public.pilot_participants (active, invited_at desc);
create index if not exists pilot_usage_events_profile_time_idx
  on public.pilot_usage_events (profile_id, occurred_at desc);
create index if not exists pilot_usage_events_name_time_idx
  on public.pilot_usage_events (event_name, occurred_at desc);
create index if not exists pilot_issue_reports_status_time_idx
  on public.pilot_issue_reports (status, created_at desc);

create or replace function public.is_pilot_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.activo = true
      and coalesce(p.estado_cuenta, 'activo') = 'activo'
      and (
        p.rol::text in ('pastor', 'administrador')
        or coalesce(p.es_pastor_general, false) = true
      )
  );
$$;

revoke all on function public.is_pilot_manager() from public;
grant execute on function public.is_pilot_manager() to authenticated;

create or replace function public.touch_pilot_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.touch_pilot_updated_at() from public;
grant execute on function public.touch_pilot_updated_at() to authenticated;

drop trigger if exists pilot_onboarding_touch_updated_at on public.pilot_onboarding_progress;
create trigger pilot_onboarding_touch_updated_at
before update on public.pilot_onboarding_progress
for each row execute function public.touch_pilot_updated_at();

drop trigger if exists pilot_issue_touch_updated_at on public.pilot_issue_reports;
create trigger pilot_issue_touch_updated_at
before update on public.pilot_issue_reports
for each row execute function public.touch_pilot_updated_at();

alter table public.pilot_participants enable row level security;
alter table public.pilot_onboarding_progress enable row level security;
alter table public.pilot_usage_events enable row level security;
alter table public.pilot_issue_reports enable row level security;

drop policy if exists "pilot_participants_select" on public.pilot_participants;
create policy "pilot_participants_select"
on public.pilot_participants for select
to authenticated
using (profile_id = auth.uid() or public.is_pilot_manager());

drop policy if exists "pilot_participants_manage" on public.pilot_participants;
create policy "pilot_participants_manage"
on public.pilot_participants for all
to authenticated
using (public.is_pilot_manager())
with check (public.is_pilot_manager());

drop policy if exists "pilot_onboarding_select" on public.pilot_onboarding_progress;
create policy "pilot_onboarding_select"
on public.pilot_onboarding_progress for select
to authenticated
using (profile_id = auth.uid() or public.is_pilot_manager());

drop policy if exists "pilot_onboarding_insert_own" on public.pilot_onboarding_progress;
create policy "pilot_onboarding_insert_own"
on public.pilot_onboarding_progress for insert
to authenticated
with check (
  profile_id = auth.uid()
  and exists (
    select 1 from public.pilot_participants pp
    where pp.profile_id = auth.uid() and pp.active = true
  )
);

drop policy if exists "pilot_onboarding_update" on public.pilot_onboarding_progress;
create policy "pilot_onboarding_update"
on public.pilot_onboarding_progress for update
to authenticated
using (profile_id = auth.uid() or public.is_pilot_manager())
with check (profile_id = auth.uid() or public.is_pilot_manager());

drop policy if exists "pilot_usage_select" on public.pilot_usage_events;
create policy "pilot_usage_select"
on public.pilot_usage_events for select
to authenticated
using (profile_id = auth.uid() or public.is_pilot_manager());

drop policy if exists "pilot_usage_insert_own" on public.pilot_usage_events;
create policy "pilot_usage_insert_own"
on public.pilot_usage_events for insert
to authenticated
with check (
  profile_id = auth.uid()
  and exists (
    select 1 from public.pilot_participants pp
    where pp.profile_id = auth.uid() and pp.active = true
  )
);

drop policy if exists "pilot_issue_select" on public.pilot_issue_reports;
create policy "pilot_issue_select"
on public.pilot_issue_reports for select
to authenticated
using (profile_id = auth.uid() or public.is_pilot_manager());

drop policy if exists "pilot_issue_insert_own" on public.pilot_issue_reports;
create policy "pilot_issue_insert_own"
on public.pilot_issue_reports for insert
to authenticated
with check (
  profile_id = auth.uid()
  and exists (
    select 1 from public.pilot_participants pp
    where pp.profile_id = auth.uid() and pp.active = true
  )
);

drop policy if exists "pilot_issue_manage" on public.pilot_issue_reports;
create policy "pilot_issue_manage"
on public.pilot_issue_reports for update
to authenticated
using (public.is_pilot_manager())
with check (public.is_pilot_manager());

grant select, insert, update, delete on public.pilot_participants to authenticated;
grant select, insert, update on public.pilot_onboarding_progress to authenticated;
grant select, insert on public.pilot_usage_events to authenticated;
grant usage, select on sequence public.pilot_usage_events_id_seq to authenticated;
grant select, insert, update on public.pilot_issue_reports to authenticated;
