-- FASE D · Bloque 4 · Hebreos, Santiago, 1–2 Pedro y Judas
select internal.import_biblical_context_batch(
  'hebreos-generales',
  'hebreos-generales-v1-2026-08-02',
  $books$[
    {
      "code":"HEB","slug":"hebreos","name":"Hebreos","chapters":13,
      "summary":"Hebreos es una homilía escrita para una comunidad cansada. Presenta a Jesús como revelación definitiva, sumo sacerdote y mediador, relee tabernáculo, pacto y sacrificio y llama a perseverar en fe, esperanza y amor.",
      "historical":"El autor, destinatarios y lugar son desconocidos. La obra parece anterior o cercana al final del siglo I y presupone profundo conocimiento de la Septuaginta y del culto israelita. No fue escrita por Pablo según el consenso académico actual.",
      "jewish":"Toda la argumentación ocurre dentro de las Escrituras y categorías judías: ángeles, Moisés, sacerdocio, Melquisedec, pacto, santuario y sacrificio. No debe leerse como desprecio del pueblo judío o de la Biblia hebrea.",
      "literary":"Alterna exposiciones bíblicas y exhortaciones. Sus comparaciones de mayor a menor conducen a advertencias, imágenes de acceso al santuario y una extensa galería de fe.",
      "intent":"Fortalecer a una comunidad tentada a retroceder, mostrando que la obra de Jesús ofrece acceso, conciencia purificada, solidaridad en el sufrimiento y esperanza firme.",
      "reflection":"La perseverancia no nace del miedo, sino de acercarse con confianza, recordar a quienes fueron fieles y sostenerse mutuamente.",
      "cautions":"Las expresiones sobre pacto antiguo, sacrificios y sacerdocio no justifican supersesionismo ni antisemitismo. Las advertencias severas no deben usarse para manipular mediante terror. El sacrificio de Cristo no normaliza abuso ni exige soportarlo.",
      "terms":["sumo sacerdote","Melquisedec","pacto","santuario","sacrificio","fe","reposo"],
      "groups":["comunidad cristiana de trasfondo judío","sacerdotes","peregrinos"],
      "places":["Jerusalén","santuario celestial"]
    },
    {
      "code":"JAS","slug":"santiago","name":"Santiago","chapters":5,
      "summary":"Santiago reúne sabiduría práctica sobre pruebas, pobreza y riqueza, escucha, parcialidad, obras, lengua, conflictos, paciencia, oración y cuidado mutuo.",
      "historical":"La carta se dirige a las «doce tribus en la dispersión», probablemente comunidades de seguidores judíos de Jesús. La identidad del autor y la fecha son debatidas, aunque la tradición la asocia con Santiago, hermano de Jesús.",
      "jewish":"Su forma de sabiduría recuerda Proverbios, profetas, Levítico y enseñanzas de Jesús. Fe, obras y justicia social se desarrollan dentro de una ética judía de pacto.",
      "literary":"Es una exhortación sapiencial con imágenes breves, preguntas, contrastes, denuncias proféticas y conexiones temáticas más que una argumentación lineal.",
      "intent":"Formar comunidades íntegras donde escuchar conduce a actuar, la fe protege al pobre, el habla no destruye y la oración acompaña enfermedad, pecado y restauración.",
      "reflection":"La espiritualidad madura une convicción y acción. Lo que una comunidad cree se vuelve visible en cómo habla, comparte y trata a quien tiene menos poder.",
      "cautions":"Las pruebas no deben atribuirse automáticamente a falta de fe. La oración por sanidad no sustituye atención médica. «Fe sin obras» no compra salvación, sino que cuestiona una confesión sin fruto.",
      "terms":["sabiduría","pruebas","obras","parcialidad","lengua","ricos","oración"],
      "groups":["doce tribus en la dispersión","ricos","pobres","maestros"],
      "places":["diáspora"]
    },
    {
      "code":"1PE","slug":"1-pedro","name":"1 Pedro","chapters":5,
      "summary":"1 Pedro anima a comunidades minoritarias de Asia Menor a vivir con esperanza, santidad, hospitalidad y testimonio bajo presión social, identificándose como pueblo peregrino y casa espiritual.",
      "historical":"La carta se dirige a provincias romanas de Asia Menor. La naturaleza de la presión parece principalmente social y local, aunque puede incluir hostilidad oficial. La autoría petrina directa y el papel de Silvano son debatidos.",
      "jewish":"Los títulos de Israel —pueblo escogido, sacerdocio, nación santa— se aplican a comunidades mixtas mediante lenguaje de la Septuaginta. Esto no debe usarse para declarar descartado al pueblo judío.",
      "literary":"Una bendición inicial conduce a exhortaciones de identidad, códigos domésticos, enseñanza sobre sufrimiento, dones comunitarios y liderazgo humilde.",
      "intent":"Dar identidad y esperanza a personas marginadas, enseñar una conducta pública honorable y promover solidaridad sin responder al mal con mal.",
      "reflection":"La esperanza permite resistir sin imitar la hostilidad del entorno. Ser peregrino no significa desentenderse del mundo, sino vivir con una lealtad distinta.",
      "cautions":"Los textos sobre esclavos, esposas y sufrimiento no obligan a permanecer en abuso ni legitiman jerarquías dañinas. La sumisión civil no elimina conciencia, protección o denuncia. Sufrir por hacer el bien no significa buscar sufrimiento.",
      "terms":["esperanza viva","peregrinos","santidad","casa espiritual","sufrimiento","hospitalidad"],
      "groups":["comunidades de Asia Menor","gentiles","judíos","personas esclavizadas"],
      "places":["Ponto","Galacia","Capadocia","Asia","Bitinia"]
    },
    {
      "code":"2PE","slug":"2-pedro","name":"2 Pedro","chapters":3,
      "summary":"2 Pedro exhorta a crecer en virtud y conocimiento, denuncia maestros destructivos y responde a quienes se burlan de la promesa del regreso de Cristo y del juicio.",
      "historical":"La carta presenta un testamento final de Pedro, pero su autoría es una de las más debatidas del Nuevo Testamento por estilo, relación con Judas y recepción tardía.",
      "jewish":"Utiliza relatos de ángeles, diluvio, Sodoma, Balaam y lenguaje apocalíptico judío. La paciencia divina y la renovación futura se entienden dentro de esas tradiciones.",
      "literary":"Un prólogo sobre virtud y testimonio apostólico conduce a una larga denuncia de falsos maestros y termina con una defensa de la promesa y exhortación a crecer.",
      "intent":"Proteger a comunidades de enseñanza que combina arrogancia, explotación y negación de responsabilidad futura, y sostener una esperanza paciente y ética.",
      "reflection":"La espera no es pasividad: el tiempo abierto invita a transformación, conocimiento responsable y una vida de paz.",
      "cautions":"«Un día como mil años» no es una fórmula para calcular fechas. La destrucción de los elementos y la nueva tierra tienen varias interpretaciones. Las acusaciones contra maestros no autorizan deshumanizar opositores ni afirmar culpa sin evidencia.",
      "terms":["conocimiento","virtud","falsos maestros","día del Señor","nueva tierra","paciencia"],
      "groups":["comunidades cristianas","maestros rivales"],
      "places":["Asia Menor"]
    },
    {
      "code":"JUD","slug":"judas","name":"Judas","chapters":1,
      "summary":"Judas llama a defender la fe frente a infiltrados que convierten la gracia en licencia, abusan de autoridad y dividen la comunidad, utilizando numerosos ejemplos bíblicos y tradiciones judías antiguas.",
      "historical":"La carta se presenta como escrita por Judas, hermano de Santiago. Su fecha y contexto preciso son inciertos. Comparte material con 2 Pedro y refleja conocimiento de 1 Enoc y una tradición sobre Moisés.",
      "jewish":"La carta muestra que comunidades tempranas leían Escritura junto con literatura judía del Segundo Templo. Citar 1 Enoc no convierte automáticamente toda la obra en Escritura ni la vuelve irrelevante.",
      "literary":"Es una breve exhortación polémica con series de tríadas, ejemplos de juicio, metáforas intensas, una cita de Enoc y una doxología final.",
      "intent":"Alertar sobre líderes que explotan y dividen, llamar a discernimiento y combinar firmeza con misericordia hacia personas confundidas.",
      "reflection":"Defender la fe no consiste en agresividad. Requiere cuidar a la comunidad, reconocer patrones de abuso y tratar con misericordia a quien duda.",
      "cautions":"El lenguaje polémico no debe usarse para etiquetar o deshumanizar a cualquier discrepante. Las tradiciones sobre ángeles y Moisés no ofrecen instrucciones ocultistas. La misericordia debe practicarse con límites seguros.",
      "terms":["fe","gracia","1 Enoc","Miguel","división","misericordia"],
      "groups":["comunidad cristiana","maestros abusivos","personas que dudan"],
      "places":["comunidades del Mediterráneo oriental"]
    }
  ]$books$::jsonb,
  $sections$[
    {"code":"HEB","slug":"hebreos-1-4","start":1,"end":4,"title":"El Hijo, Moisés y el reposo prometido","summary":"Jesús es presentado por encima de ángeles y como Hijo fiel sobre la casa; la historia del desierto sirve para llamar a escuchar hoy y entrar en el reposo de Dios.","intent":"Afirmar la grandeza de Jesús y usar la memoria del desierto para fomentar atención, confianza y apoyo mutuo.","cautions":"Comparar a Jesús con ángeles y Moisés no autoriza despreciar el judaísmo. El reposo no es premio por productividad ni excusa para culpabilizar a quien está agotado.","terms":["Hijo","ángeles","Moisés","hoy","reposo","palabra"],"reflection":"La comunidad persevera cuando escucha a tiempo y evita que alguien enfrente solo el cansancio o la duda.","groups":["Israel en el desierto","comunidad creyente"],"places":["desierto","tierra prometida"]},
    {"code":"HEB","slug":"hebreos-5-7","start":5,"end":7,"title":"Sacerdocio, madurez y Melquisedec","summary":"El autor presenta a Jesús como sumo sacerdote compasivo, exhorta a avanzar hacia madurez y desarrolla la figura de Melquisedec para hablar de un sacerdocio diferente.","intent":"Dar confianza para acercarse a Dios y explicar que el sacerdocio de Jesús no depende de genealogía levítica.","cautions":"Melquisedec no debe convertirse en especulación genealógica o mística sin base textual. Las advertencias de Hebreos 6 no deben usarse para declarar irremediablemente perdida a una persona que busca volver.","terms":["sumo sacerdote","compasión","madurez","Melquisedec","promesa","esperanza"],"reflection":"La madurez incluye aprender a recibir misericordia y convertirse en una persona capaz de sostener esperanza para otros.","groups":["sacerdotes","descendientes de Abraham","comunidad creyente"],"places":["Jerusalén","santuario"]},
    {"code":"HEB","slug":"hebreos-8-10","start":8,"end":10,"title":"Pacto, santuario y acceso confiado","summary":"Hebreos compara pactos y santuarios, interpreta la muerte de Jesús como ofrenda decisiva y llama a acercarse, mantener esperanza y reunirse para animarse.","intent":"Asegurar que el perdón y el acceso a Dios no dependen de repetir sacrificios y formar una comunidad que persevera junta.","cautions":"«Obsoleto» describe el argumento sobre el pacto y el culto dentro de una obra judía; no significa que el pueblo judío sea obsoleto. La sangre sacrificial es lenguaje cultual y no glorifica violencia o abuso.","terms":["nuevo pacto","santuario","conciencia","sangre","acceso","asamblea"],"reflection":"La confianza espiritual se fortalece cuando las personas se acercan con sinceridad y se animan en vez de aislarse.","groups":["Israel","sacerdotes","comunidad creyente"],"places":["tabernáculo","santuario celestial"]},
    {"code":"HEB","slug":"hebreos-11-13","start":11,"end":13,"title":"Testigos, perseverancia y vida comunitaria","summary":"Una galería de personajes muestra fe que actúa sin poseer todavía todo lo prometido; después la carta llama a correr con perseverancia, practicar hospitalidad y recordar a líderes.","intent":"Situar las dificultades presentes dentro de una historia amplia de confianza y traducir la esperanza en amor, hospitalidad, justicia y solidaridad.","cautions":"Las historias de fe no garantizan rescate inmediato ni deben utilizarse para culpar a quien no obtiene el resultado esperado. «Obedecer a líderes» no elimina evaluación, límites ni denuncia de abuso.","terms":["fe","testigos","carrera","disciplina","hospitalidad","líderes"],"reflection":"La fe perseverante no es éxito constante; puede confiar, actuar y sostener a otros aun cuando la promesa todavía no se ve completa.","groups":["personajes de Israel","peregrinos","personas encarceladas"],"places":["Jerusalén","campamento"]},
    {"code":"JAS","slug":"santiago-1","start":1,"end":1,"title":"Pruebas, sabiduría y escuchar para actuar","summary":"Santiago habla de perseverancia, sabiduría, riqueza pasajera, origen de la tentación y una recepción de la palabra que se vuelve acción y cuidado del vulnerable.","intent":"Formar una respuesta madura a la presión y corregir una religiosidad que escucha sin transformar conducta.","cautions":"Considerar gozo no significa disfrutar el dolor ni negar ayuda. Dios no tienta al mal; las personas que sufren no deben ser culpadas por toda prueba.","terms":["pruebas","sabiduría","tentación","palabra","huérfanos","viudas"],"reflection":"La sabiduría ayuda a atravesar pruebas con honestidad y convierte la escucha en cuidado concreto.","groups":["personas pobres","personas ricas","huérfanos","viudas"],"places":["diáspora"]},
    {"code":"JAS","slug":"santiago-2-3","start":2,"end":3,"title":"Parcialidad, fe activa y poder de la lengua","summary":"La comunidad es confrontada por favorecer al rico, se muestra que una fe sin obras está inerte y se advierte a maestros sobre el daño producido por el habla.","intent":"Vincular confesión con trato igualitario y formar una sabiduría pacífica que no usa palabras para bendecir y destruir a la vez.","cautions":"Santiago y Pablo responden a problemas diferentes y no deben forzarse como enemigos. La advertencia sobre la lengua no justifica silenciar denuncias de injusticia.","terms":["parcialidad","ley real","fe","obras","maestros","lengua","sabiduría"],"reflection":"La fe se hace visible cuando la dignidad del pobre pesa más que el prestigio y cuando las palabras crean paz sin ocultar verdad.","groups":["ricos","pobres","maestros","comunidad"],"places":["diáspora"]},
    {"code":"JAS","slug":"santiago-4-5","start":4,"end":5,"title":"Conflictos, riqueza, paciencia y oración","summary":"Santiago rastrea conflictos hasta deseos desordenados, cuestiona planes arrogantes, denuncia salarios retenidos y concluye con paciencia, oración y restauración.","intent":"Confrontar ambición y explotación, enseñar dependencia humilde y construir una comunidad que ora y recupera a quien se extravía.","cautions":"La unción y oración por enfermos no sustituyen atención médica. La denuncia contra ricos se dirige a acumulación y fraude, no declara culpable a toda persona con recursos.","terms":["conflictos","humildad","salarios","paciencia","unción","oración"],"reflection":"La oración responsable camina junto a justicia económica, cuidado médico, confesión segura y acompañamiento.","groups":["comerciantes","trabajadores","ricos","enfermos","ancianos"],"places":["diáspora"]},
    {"code":"1PE","slug":"1-pedro-1-2","start":1,"end":2,"title":"Esperanza viva y pueblo peregrino","summary":"La nueva esperanza se relaciona con santidad, amor, deseo de la palabra y una identidad de piedras vivas y sacerdocio dentro de sociedades que observan a la comunidad.","intent":"Dar dignidad a personas desplazadas socialmente y formar un testimonio visible mediante conducta honorable y servicio.","cautions":"Aplicar títulos de Israel a la iglesia no autoriza teología de reemplazo. La sujeción a instituciones humanas no exige obedecer órdenes injustas o peligrosas.","terms":["esperanza viva","santidad","piedras vivas","sacerdocio","peregrinos"],"reflection":"Pertenecer a Dios puede ofrecer estabilidad sin convertir a la comunidad en enemiga del mundo que la rodea.","groups":["comunidades de Asia Menor","gentiles","autoridades romanas"],"places":["Asia Menor"]},
    {"code":"1PE","slug":"1-pedro-3-4","start":3,"end":4,"title":"Relaciones, sufrimiento y dones comunitarios","summary":"La carta aborda matrimonios antiguos, respuesta no vengativa, esperanza explicada con respeto, sufrimiento injusto, hospitalidad y uso responsable de dones.","intent":"Ayudar a comunidades vulnerables a resistir sin reproducir hostilidad y a construir hogares y reuniones donde el servicio sea mutuo.","cautions":"Las instrucciones a esposas no obligan a permanecer con una persona abusiva. «Vaso más frágil» refleja una situación social y corporal antigua y no niega igualdad ni capacidad. El pasaje sobre espíritus encarcelados es debatido.","terms":["honor","esperanza","conciencia","bautismo","hospitalidad","dones"],"reflection":"Responder con respeto no significa callar el daño; significa conservar integridad mientras se buscan seguridad y justicia.","groups":["esposas","esposos","comunidad perseguida"],"places":["Asia Menor"]},
    {"code":"1PE","slug":"1-pedro-5","start":5,"end":5,"title":"Liderazgo humilde, ansiedad y resistencia","summary":"Ancianos deben cuidar sin dominar, jóvenes practicar humildad y toda la comunidad entregar sus preocupaciones a Dios mientras resiste al adversario.","intent":"Definir autoridad pastoral como cuidado voluntario y no control, y fortalecer a una comunidad que enfrenta presión.","cautions":"«Echar ansiedad» no sustituye terapia, medicina o redes de apoyo. La imagen del adversario como león no debe usarse para diagnosticar demonios detrás de cada problema.","terms":["ancianos","rebaño","humildad","ansiedad","adversario","resistencia"],"reflection":"El cuidado espiritual sano no domina; acompaña, comparte cargas y reconoce cuándo hace falta ayuda especializada.","groups":["ancianos","jóvenes","comunidad"],"places":["Babilonia simbólica","Asia Menor"]},
    {"code":"2PE","slug":"2-pedro-1","start":1,"end":1,"title":"Virtud, testimonio y palabra profética","summary":"La comunidad debe añadir a la fe virtud, conocimiento y amor; el autor recuerda la transfiguración y presenta la profecía como luz que no nace de interpretación arbitraria.","intent":"Unir conocimiento y carácter y sostener la esperanza en testimonio recibido y Escritura interpretada responsablemente.","cautions":"La «naturaleza divina» no significa que humanos se vuelvan dioses. La profecía no autoriza interpretaciones privadas desconectadas de texto, comunidad y evidencia.","terms":["virtud","conocimiento","transfiguración","profecía","lucero"],"reflection":"Crecer espiritualmente no es acumular secretos, sino formar carácter y amor mediante conocimiento responsable.","groups":["comunidad cristiana","testigos apostólicos"],"places":["monte de la transfiguración"]},
    {"code":"2PE","slug":"2-pedro-2","start":2,"end":2,"title":"Falsos maestros y explotación","summary":"Ejemplos de juicio y la historia de Balaam denuncian a líderes que prometen libertad mientras explotan, engañan y viven sin responsabilidad.","intent":"Proteger a la comunidad de enseñanza que utiliza deseo, autoridad y promesas para obtener beneficio personal.","cautions":"Las metáforas duras no autorizan insultar a toda persona que discrepa. Las acusaciones de abuso o explotación requieren investigación y protección, no rumor.","terms":["falsos maestros","Balaam","codicia","libertad","explotación"],"reflection":"La libertad verdadera no convierte a otros en objetos ni usa espiritualidad para obtener poder.","groups":["maestros abusivos","comunidad"],"places":["Sodoma","Gomorra"]},
    {"code":"2PE","slug":"2-pedro-3","start":3,"end":3,"title":"Demora, paciencia y nueva creación","summary":"Frente a burlas por la demora, la carta interpreta el tiempo como paciencia para el arrepentimiento y llama a esperar cielos nuevos y tierra nueva practicando paz y santidad.","intent":"Responder a la desilusión sin fijar fechas y convertir la esperanza futura en responsabilidad presente.","cautions":"Mil años no equivalen a un código cronológico. El lenguaje de fuego y elementos admite debates textuales y cosmológicos; no predice un evento moderno específico.","terms":["demora","paciencia","día del Señor","elementos","nueva tierra"],"reflection":"La espera responsable cuida el mundo y busca paz; no abandona la vida presente por especulación.","groups":["comunidad","burladores"],"places":["creación"]},
    {"code":"JUD","slug":"judas-1","start":1,"end":1,"title":"Defender la fe con discernimiento y misericordia","summary":"Judas denuncia líderes divisivos mediante ejemplos bíblicos y tradiciones antiguas, y termina llamando a edificarse, orar, esperar misericordia y rescatar con prudencia.","intent":"Proteger a la comunidad de explotación y formar una defensa de la fe que preserve misericordia y dependencia de Dios.","cautions":"Las referencias a ángeles, Enoc y Miguel describen tradiciones judías antiguas y no enseñan técnicas espirituales. «Rescatar del fuego» no autoriza coerción ni acciones peligrosas.","terms":["fe","Enoc","Miguel","división","misericordia","doxología"],"reflection":"La firmeza más segura permanece humilde: cuida a quien duda y no convierte la defensa de la fe en dominio.","groups":["comunidad","líderes divisivos","personas que dudan"],"places":["comunidades del Mediterráneo oriental"]}
  ]$sections$::jsonb
);