insert into public.biblical_sources (
  slug,
  name,
  source_type,
  language,
  website,
  license_url,
  license_notes,
  license_status,
  provider,
  provider_ref,
  provider_version,
  content_hash,
  attribution,
  review_status,
  enabled,
  metadata,
  approved_at
)
values (
  'pleiades-gazetteer',
  'Pleiades: A Gazetteer of Past Places',
  'historical',
  'mul',
  'https://pleiades.stoa.org/',
  'https://creativecommons.org/licenses/by/3.0/',
  'El contenido publicado por Pleiades puede reutilizarse bajo CC BY 3.0. Cada fragmento conserva un URI estable y la atribución del proyecto.',
  'verified',
  'Pleiades',
  'gazetteer',
  'accessed-2026-07-31',
  null,
  'Pleiades: A Gazetteer of Past Places, Ancient World Mapping Center e Institute for the Study of the Ancient World. Licencia CC BY 3.0.',
  'approved',
  true,
  jsonb_build_object(
    'api_template', 'https://pleiades.stoa.org/places/{pid}/json',
    'stable_place_uris', true,
    'peer_reviewed', true,
    'content_imported', 'limited_editorial_summaries',
    'license_verified_at', '2026-07-31'
  ),
  now()
)
on conflict (slug) do update set
  name = excluded.name,
  source_type = excluded.source_type,
  language = excluded.language,
  website = excluded.website,
  license_url = excluded.license_url,
  license_notes = excluded.license_notes,
  license_status = excluded.license_status,
  provider = excluded.provider,
  provider_ref = excluded.provider_ref,
  provider_version = excluded.provider_version,
  content_hash = excluded.content_hash,
  attribution = excluded.attribution,
  review_status = excluded.review_status,
  enabled = excluded.enabled,
  metadata = excluded.metadata,
  approved_at = excluded.approved_at,
  updated_at = now();

insert into public.biblical_context_fragments (
  slug,
  source_id,
  title,
  content,
  content_kind,
  context_type,
  language,
  book_code,
  chapter_start,
  verse_start,
  chapter_end,
  verse_end,
  reference_label,
  source_locator,
  period_label,
  location_names,
  people_groups,
  topics,
  provider_version,
  content_hash,
  review_status,
  enabled,
  approved_at,
  metadata
)
values
  (
    'roma-capital-romanos',
    (select id from public.biblical_sources where slug = 'pleiades-gazetteer'),
    'Roma, capital del mundo romano',
    'Pleiades identifica a Roma como la capital de la República y del Imperio romano. Este resumen editorial sitúa la carta a los Romanos dentro del principal centro político del mundo romano, sin atribuir a la fuente afirmaciones teológicas sobre la comunidad cristiana.',
    'editorial_summary',
    'place',
    'spa',
    'ROM',
    1,
    null,
    16,
    null,
    'Romanos 1–16',
    'https://pleiades.stoa.org/places/423025',
    'República e Imperio romano',
    array['Roma'],
    array['Romanos'],
    array['capital imperial', 'mundo romano', 'geografía histórica'],
    'pleiades-place-423025-accessed-2026-07-31',
    'a2f4808cb82111e86f5b4c56f22cb6266d501fae422562992c2965e02bc4767c',
    'approved',
    true,
    now(),
    jsonb_build_object(
      'pleiades_id', '423025',
      'canonical_uri', 'https://pleiades.stoa.org/places/423025',
      'api_uri', 'https://pleiades.stoa.org/places/423025/json',
      'source_description', 'The capital of the Roman Republic and Empire',
      'editorial_relation', 'La relación con Romanos fue preparada por Vida Internacional.'
    )
  ),
  (
    'roma-capital-hechos-28',
    (select id from public.biblical_sources where slug = 'pleiades-gazetteer'),
    'La llegada de Pablo a Roma',
    'Pleiades identifica a Roma como la capital de la República y del Imperio romano. Este resumen editorial ayuda a ubicar la etapa final de Hechos 28 en la capital imperial; la relación con el pasaje fue preparada por Vida Internacional.',
    'editorial_summary',
    'place',
    'spa',
    'ACT',
    28,
    14,
    28,
    31,
    'Hechos 28:14–31',
    'https://pleiades.stoa.org/places/423025',
    'Imperio romano',
    array['Roma'],
    array['Romanos', 'Pablo'],
    array['capital imperial', 'viaje de Pablo', 'geografía histórica'],
    'pleiades-place-423025-accessed-2026-07-31',
    'fb892d134ef1edd6b4954d27e0c8495bc5ac5fdb808b79ddbc3ef3300ec98969',
    'approved',
    true,
    now(),
    jsonb_build_object(
      'pleiades_id', '423025',
      'canonical_uri', 'https://pleiades.stoa.org/places/423025',
      'api_uri', 'https://pleiades.stoa.org/places/423025/json',
      'source_description', 'The capital of the Roman Republic and Empire',
      'editorial_relation', 'La relación con Hechos 28 fue preparada por Vida Internacional.'
    )
  )
on conflict (slug) do update set
  source_id = excluded.source_id,
  title = excluded.title,
  content = excluded.content,
  content_kind = excluded.content_kind,
  context_type = excluded.context_type,
  language = excluded.language,
  book_code = excluded.book_code,
  chapter_start = excluded.chapter_start,
  verse_start = excluded.verse_start,
  chapter_end = excluded.chapter_end,
  verse_end = excluded.verse_end,
  reference_label = excluded.reference_label,
  source_locator = excluded.source_locator,
  period_label = excluded.period_label,
  location_names = excluded.location_names,
  people_groups = excluded.people_groups,
  topics = excluded.topics,
  provider_version = excluded.provider_version,
  content_hash = excluded.content_hash,
  review_status = excluded.review_status,
  enabled = excluded.enabled,
  approved_at = excluded.approved_at,
  metadata = excluded.metadata,
  updated_at = now();
