-- FASE D · Bloque 4 · 1–3 Juan y Apocalipsis
select internal.import_biblical_context_batch(
  'juan-apocalipsis',
  'juan-apocalipsis-v1-2026-08-02',
  $books$[
    {
      "code":"1JN","slug":"1-juan","name":"1 Juan","chapters":5,
      "summary":"1 Juan ofrece seguridad y discernimiento a una comunidad dividida. Une confesión sobre Jesús venido en carne, obediencia, amor fraternal, verdad y confianza delante de Dios.",
      "historical":"La carta o sermón pertenece al entorno de las comunidades joánicas a fines del siglo I. Una separación interna y desacuerdos cristológicos parecen estar detrás del texto, aunque no es posible reconstruir cada detalle con certeza.",
      "jewish":"El lenguaje de luz, mandamiento, justicia, pecado, testimonio y vida eterna está profundamente conectado con las Escrituras judías y con el Evangelio de Juan. La polémica es intracomunitaria y no autoriza hostilidad hacia judíos.",
      "literary":"No tiene saludo epistolar convencional. Avanza en espiral, retomando luz, pecado, amor, verdad, anticristos, testimonio y seguridad con contrastes repetidos.",
      "intent":"Ayudar a la comunidad a distinguir verdad y engaño sin perder el centro ético del amor, y ofrecer confianza a quienes temen no pertenecer a Dios.",
      "reflection":"La seguridad espiritual no depende de perfección instantánea, sino de caminar en verdad, confesar, recibir perdón y amar de manera concreta.",
      "cautions":"«Anticristo» aparece en plural y dentro de una ruptura comunitaria; no debe aplicarse automáticamente a políticos o grupos actuales. «El amor perfecto echa fuera el temor» no culpabiliza a personas con ansiedad o trauma. Los contrastes no autorizan declarar que cualquiera que discrepa carece de Dios.",
      "terms":["luz","comunión","pecado","amor","anticristo","testimonio","vida eterna"],
      "groups":["comunidad joánica","maestros separados","hermanos y hermanas"],
      "places":["Asia Menor"]
    },
    {
      "code":"2JN","slug":"2-juan","name":"2 Juan","chapters":1,
      "summary":"2 Juan exhorta a una «señora elegida» y sus hijos a caminar en verdad y amor, y a no apoyar a docentes itinerantes que niegan que Jesucristo vino en carne.",
      "historical":"Las comunidades cristianas dependían de hospitalidad para maestros viajeros. La «señora elegida» puede ser una mujer real, una iglesia personificada o ambas dimensiones; el debate permanece abierto.",
      "jewish":"Verdad, mandamiento y amor continúan categorías bíblicas y joánicas. La controversia se dirige a una enseñanza cristológica concreta, no a la población judía.",
      "literary":"Es una nota breve que equilibra amor y límites: saludo, mandamiento conocido, advertencia sobre engañadores y esperanza de visita personal.",
      "intent":"Proteger una red doméstica o eclesial de docentes que utilizan hospitalidad para difundir una enseñanza considerada destructiva, sin separar verdad y amor.",
      "reflection":"La hospitalidad necesita discernimiento. Amar no obliga a financiar o facilitar prácticas que dañan a la comunidad.",
      "cautions":"«No recibir en casa» no prohíbe toda cortesía hacia quien piensa distinto ni justifica hostilidad. Se refiere al apoyo material y reconocimiento de maestros itinerantes dentro de una crisis específica.",
      "terms":["señora elegida","verdad","amor","mandamiento","engañadores","hospitalidad"],
      "groups":["comunidad joánica","maestros itinerantes"],
      "places":["Asia Menor"]
    },
    {
      "code":"3JN","slug":"3-juan","name":"3 Juan","chapters":1,
      "summary":"3 Juan elogia la hospitalidad de Gayo, recomienda a Demetrio y denuncia el liderazgo controlador de Diótrefes, quien rechaza colaboradores y expulsa a quienes los reciben.",
      "historical":"La carta refleja redes de maestros itinerantes y tensiones de autoridad en iglesias domésticas. La comunicación, reputación y hospitalidad eran esenciales para la misión.",
      "jewish":"La verdad se demuestra al apoyar a quienes trabajan por el Nombre y al rechazar la imitación del mal. El marco sigue siendo ético y comunitario, no antijudío.",
      "literary":"Una carta personal breve usa elogio, recomendación y denuncia para contrastar tres figuras: Gayo, Diótrefes y Demetrio.",
      "intent":"Respaldar la hospitalidad responsable, confrontar liderazgo que monopoliza información y poder y preservar la cooperación entre comunidades.",
      "reflection":"Un líder no es confiable solo porque ocupa el primer lugar. La verdad también se reconoce en cómo recibe colaboradores y trata a quienes discrepan.",
      "cautions":"La denuncia de Diótrefes no autoriza campañas de rumor. Las acusaciones contra líderes requieren evidencia, procesos justos y protección para quienes puedan sufrir represalias.",
      "terms":["Gayo","Diótrefes","Demetrio","verdad","hospitalidad","autoridad"],
      "groups":["iglesias domésticas","maestros itinerantes","líderes locales"],
      "places":["Asia Menor"]
    },
    {
      "code":"REV","slug":"apocalipsis","name":"Apocalipsis","chapters":22,
      "summary":"Apocalipsis es una profecía y revelación dirigida a siete iglesias de Asia. Mediante visiones simbólicas denuncia la idolatría imperial, llama a perseverar en el testimonio de Jesús y culmina con juicio del mal, nueva creación y la presencia de Dios entre la humanidad.",
      "historical":"Juan escribe desde Patmos a comunidades de Asia Menor bajo el dominio romano, probablemente hacia fines del siglo I, aunque existen propuestas anteriores. La presión incluía culto imperial, economía, prestigio cívico y hostilidad local; no todos los lectores sufrían la misma intensidad.",
      "jewish":"El libro está tejido con Daniel, Ezequiel, Isaías, Éxodo, Zacarías, Salmos y otras Escrituras. Sus símbolos pertenecen a la apocalíptica judía y deben interpretarse desde ese mundo antes de relacionarlos con acontecimientos posteriores.",
      "literary":"Combina carta, profecía y apocalipsis. Series de siete, escenas celestiales, ciclos de conflicto, himnos y contrastes entre Babilonia y la nueva Jerusalén organizan la obra.",
      "intent":"Revelar el verdadero carácter del poder imperial, sostener a comunidades presionadas y formar una resistencia fiel que adora a Dios y al Cordero en lugar de la bestia.",
      "reflection":"La esperanza cristiana no huye de la creación: espera su renovación. La victoria del Cordero redefine poder mediante testimonio fiel, justicia y entrega, no dominio violento.",
      "cautions":"Apocalipsis no debe usarse como código para identificar políticos, vacunas, tecnologías o países modernos sin evidencia. «Sinagoga de Satanás» describe conflictos locales y no autoriza antisemitismo. 666, el milenio y las secuencias tienen interpretaciones diversas. Las imágenes violentas son simbólicas y no legitiman violencia religiosa.",
      "terms":["revelación","Cordero","bestia","Babilonia","666","testimonio","nueva Jerusalén","nueva creación"],
      "groups":["siete iglesias","Imperio romano","naciones","mártires"],
      "places":["Patmos","Éfeso","Esmirna","Pérgamo","Tiatira","Sardis","Filadelfia","Laodicea","Babilonia simbólica","nueva Jerusalén"]
    }
  ]$books$::jsonb,
  $sections$[
    {"code":"1JN","slug":"1-juan-1-2","start":1,"end":2,"title":"Luz, confesión y conocimiento de Dios","summary":"La proclamación de la vida conduce a comunión; caminar en luz implica confesar pecado, recibir perdón, obedecer y amar, mientras la comunidad discierne a quienes se separaron.","intent":"Unir confesión cristológica, honestidad moral y amor fraternal como señales inseparables de comunión con Dios.","cautions":"«Si decimos que no tenemos pecado» no autoriza confesiones forzadas ni exposición pública insegura. «Anticristos» describe opositores internos de la comunidad, no una lista de enemigos modernos.","terms":["vida","comunión","luz","confesión","abogado","mandamiento","anticristos"],"reflection":"Caminar en luz no significa no fallar; significa dejar de esconder, recibir gracia y aprender a amar con verdad.","groups":["comunidad joánica","personas separadas"],"places":["Asia Menor"]},
    {"code":"1JN","slug":"1-juan-3-4","start":3,"end":4,"title":"Hijos de Dios, amor concreto y discernimiento","summary":"La identidad como hijos de Dios se expresa practicando justicia, amando con acciones, examinando los espíritus y confesando a Jesús venido en carne.","intent":"Proteger a la comunidad de espiritualidad sin ética y enseñar que el amor visible y la confesión encarnada son criterios de discernimiento.","cautions":"Los contrastes entre hijos de Dios y del diablo no permiten deshumanizar personas. Dar la vida por otros no exige permanecer en abuso ni ignorar autocuidado. Probar espíritus no significa sospechar de toda emoción o condición de salud mental.","terms":["hijos de Dios","justicia","Caín","amor","corazón","espíritus","encarnación"],"reflection":"El amor no es solo emoción o discurso; comparte recursos, protege y permite que la verdad examine nuestras acciones.","groups":["hermanos y hermanas","maestros rivales","personas necesitadas"],"places":["Asia Menor"]},
    {"code":"1JN","slug":"1-juan-5","start":5,"end":5,"title":"Fe, testimonio y seguridad de vida eterna","summary":"La fe en Jesús vence al mundo, el testimonio de Dios confirma la vida en el Hijo y la carta concluye con confianza en la oración y una advertencia sobre ídolos.","intent":"Dar seguridad a la comunidad y orientar su confianza hacia el testimonio de Dios, la obediencia amorosa y la vida recibida en el Hijo.","cautions":"El pasaje del agua y la sangre tiene distintas interpretaciones. La oración conforme a la voluntad de Dios no garantiza cualquier petición. El «pecado de muerte» es debatido y no debe usarse para declarar a una persona sin esperanza.","terms":["fe","mundo","agua","sangre","testimonio","vida eterna","ídolos"],"reflection":"La seguridad espiritual puede convivir con humildad: confía en Dios sin pretender controlar sus respuestas.","groups":["comunidad joánica"],"places":["Asia Menor"]},
    {"code":"2JN","slug":"2-juan-1","start":1,"end":1,"title":"Verdad, amor y límites a la hospitalidad","summary":"El anciano celebra que algunos caminan en verdad, recuerda el mandamiento del amor y advierte contra apoyar a engañadores itinerantes.","intent":"Mantener juntas una comunidad amorosa y una práctica responsable de la hospitalidad y el apoyo material.","cautions":"Establecer límites a un docente no autoriza hostigamiento ni rechazo de toda persona con dudas. La identidad de la señora elegida permanece debatida.","terms":["anciano","señora elegida","verdad","amor","engañadores","casa"],"reflection":"Los límites pueden ser una forma de amor cuando protegen a la comunidad sin negar la dignidad del otro.","groups":["señora elegida","hijos","maestros itinerantes"],"places":["Asia Menor"]},
    {"code":"3JN","slug":"3-juan-1","start":1,"end":1,"title":"Hospitalidad y abuso de autoridad","summary":"Gayo es elogiado por apoyar colaboradores; Diótrefes es confrontado por querer el primer lugar y controlar la recepción; Demetrio recibe buen testimonio.","intent":"Defender redes abiertas de colaboración y mostrar que la autoridad debe evaluarse por verdad, hospitalidad y trato a otros.","cautions":"No debe llamarse «Diótrefes» a cualquier líder con quien se discrepa. Las denuncias requieren hechos verificables y mecanismos que reduzcan represalias.","terms":["Gayo","Diótrefes","Demetrio","hospitalidad","verdad","primer lugar"],"reflection":"El liderazgo sano no teme compartir espacio, recibir voces externas ni ser evaluado por la comunidad.","groups":["líderes locales","maestros itinerantes","iglesia doméstica"],"places":["Asia Menor"]},
    {"code":"REV","slug":"apocalipsis-1-3","start":1,"end":3,"title":"Visión del Hijo del Hombre y mensajes a las siete iglesias","summary":"Juan recibe una visión en Patmos y transmite mensajes que reconocen perseverancia, denuncian acomodación y llaman a escuchar al Espíritu en situaciones locales distintas.","intent":"Presentar a Jesús como Señor de las iglesias y evaluar a cada comunidad por fidelidad, amor, justicia, discernimiento y resistencia a la idolatría.","cautions":"Los mensajes fueron dirigidos primero a iglesias históricas. «Sinagoga de Satanás» no describe al judaísmo en general. «Jezabel» es un símbolo polémico y no autoriza insultar o controlar a mujeres.","terms":["Patmos","Hijo del Hombre","siete iglesias","candelabros","testimonio","vencer"],"reflection":"Una comunidad puede conservar doctrina y perder amor, o tener actividad y carecer de justicia; escuchar requiere examen completo.","groups":["siete iglesias","autoridades locales","comunidades judías locales"],"places":["Patmos","Éfeso","Esmirna","Pérgamo","Tiatira","Sardis","Filadelfia","Laodicea"]},
    {"code":"REV","slug":"apocalipsis-4-7","start":4,"end":7,"title":"Trono, Cordero, sellos y multitud de las naciones","summary":"La adoración celestial centra el poder en el Creador y el Cordero; al abrirse los sellos se revela sufrimiento bajo conquista e injusticia, y una multitud innumerable aparece delante de Dios.","intent":"Reorientar la imaginación desde el trono imperial hacia el trono de Dios y mostrar que la victoria pertenece al Cordero y a un pueblo multinacional fiel.","cautions":"Los jinetes no deben asignarse automáticamente a acontecimientos actuales. Las tribus y el número 144,000 tienen interpretaciones simbólicas y literales diversas; no sirven para excluir a otros creyentes.","terms":["trono","Cordero","rollo","sellos","jinetes","144000","multitud"],"reflection":"Adorar al Cordero cuestiona formas de poder basadas en conquista y recuerda que el sufrimiento de los fieles es visto.","groups":["ancianos","criaturas vivientes","tribus de Israel","naciones"],"places":["cielo","tierra"]},
    {"code":"REV","slug":"apocalipsis-8-11","start":8,"end":11,"title":"Trompetas, testigos y llamado al arrepentimiento","summary":"Trompetas evocan plagas y colapso ecológico, un rollo vuelve a ser comido, dos testigos anuncian la verdad y la séptima trompeta proclama el reino de Dios.","intent":"Advertir que sistemas violentos dañan creación y humanidad, llamar al arrepentimiento y mostrar que el testimonio puede parecer derrotado sin ser silenciado definitivamente.","cautions":"Las plagas son visiones simbólicas y no deben usarse para anunciar que cada desastre natural es juicio directo. Las identidades de los dos testigos son debatidas y no autorizan autoproclamaciones peligrosas.","terms":["trompetas","plagas","rollo","dos testigos","templo","séptima trompeta"],"reflection":"El testimonio fiel dice verdad sin controlar el resultado y mantiene esperanza aun cuando el poder intenta silenciarlo.","groups":["habitantes de la tierra","testigos","naciones"],"places":["Jerusalén simbólica","templo","tierra"]},
    {"code":"REV","slug":"apocalipsis-12-14","start":12,"end":14,"title":"Mujer, dragón, bestias y fidelidad del Cordero","summary":"Un conflicto cósmico muestra al dragón persiguiendo, dos bestias representando poder coercitivo y propaganda, la marca como lealtad económica y política y el Cordero con su pueblo.","intent":"Desenmascarar mecanismos imperiales que exigen adoración, controlar comercio y difundir engaño, y llamar a perseverancia sin imitar a la bestia.","cautions":"La mujer no es una persona moderna específica. La marca y 666 no deben identificarse automáticamente con microchips, documentos, vacunas o productos. La relación probable con Nerón y otras lecturas debe presentarse como debate histórico.","terms":["mujer","dragón","bestia del mar","bestia de la tierra","marca","666","Cordero"],"reflection":"La fidelidad resiste la presión de comprar seguridad al precio de la conciencia y evita convertirse en aquello que denuncia.","groups":["pueblo de Dios","imperio","naciones"],"places":["cielo","mar","tierra","monte Sion"]},
    {"code":"REV","slug":"apocalipsis-15-18","start":15,"end":18,"title":"Copas, Babilonia y caída de la economía imperial","summary":"Las copas completan el ciclo de juicio y Babilonia aparece como ciudad seductora enriquecida mediante lujo, violencia y explotación antes de su caída y del lamento de comerciantes y reyes.","intent":"Exponer el costo humano de la prosperidad imperial y llamar a salir de sistemas que convierten vidas y creación en mercancía.","cautions":"Babilonia es símbolo de Roma y de patrones imperiales, no una etiqueta automática para cualquier ciudad o iglesia. La figura femenina no autoriza misoginia ni lenguaje degradante contra mujeres.","terms":["copas","Babilonia","lujo","comercio","mercancías","caída"],"reflection":"Una economía puede parecer gloriosa mientras oculta sufrimiento. Salir de Babilonia implica revisar cómo participamos en explotación.","groups":["reyes","comerciantes","marineros","pueblos explotados"],"places":["Babilonia simbólica","Roma","mar"]},
    {"code":"REV","slug":"apocalipsis-19-22","start":19,"end":22,"title":"Victoria, juicio, milenio y nueva creación","summary":"La caída de Babilonia conduce a celebración, derrota final del mal, milenio, juicio, nueva Jerusalén, río de vida y una creación donde Dios habita con la humanidad.","intent":"Afirmar que el mal y la muerte no tienen la última palabra y orientar la esperanza hacia justicia, comunión, sanidad de las naciones y renovación de la creación.","cautions":"El jinete y las escenas de juicio son visión apocalíptica, no licencia para violencia humana. Premilenialismo, amilenialismo y postmilenialismo son lecturas distintas. El lago de fuego y el juicio poseen debates teológicos y no deben usarse para amenazas personales. La nueva Jerusalén no es escapismo de la tierra, sino creación renovada.","terms":["jinete fiel","milenio","juicio","nueva Jerusalén","río de vida","árbol de vida","nueva creación"],"reflection":"La historia culmina no en una huida solitaria, sino en Dios habitando con una humanidad sanada y una creación restaurada.","groups":["naciones","santos","habitantes de la nueva Jerusalén"],"places":["nueva Jerusalén","nueva tierra","río de vida"]}
  ]$sections$::jsonb
);