-- FASE D · Bloque 4 · Cartas pastorales y Filemón
select internal.import_biblical_context_batch(
  'pastorales-filemon',
  'pastorales-filemon-v1-2026-08-02',
  $books$[
    {
      "code":"1TI","slug":"1-timoteo","name":"1 Timoteo","chapters":6,
      "summary":"1 Timoteo orienta a un colaborador encargado de enfrentar enseñanzas conflictivas, ordenar la oración comunitaria, reconocer líderes confiables y cuidar distintos grupos dentro de la casa de Dios.",
      "historical":"La carta refleja comunidades urbanas de Asia Menor donde hogares, patronazgo, reputación pública y redes docentes eran importantes. La autoría paulina directa es ampliamente debatida por vocabulario, estructura eclesial y relación con las cartas indiscutidas.",
      "jewish":"Las discusiones sobre genealogías, ley, Adán y Eva y viudas se desarrollan dentro de comunidades que reciben las Escrituras de Israel. No deben presentarse como rechazo del judaísmo.",
      "literary":"Alterna instrucciones personales, listas de cualidades, fórmulas de fe, regulaciones comunitarias y advertencias contra disputas y amor al dinero.",
      "intent":"Proteger a la comunidad de enseñanza especulativa y abuso de autoridad, formar liderazgo íntegro y relacionar doctrina con cuidado práctico, reputación y justicia.",
      "reflection":"El liderazgo espiritual se mide por carácter, servicio, autocontrol y trato responsable de personas vulnerables, no por carisma o posición.",
      "cautions":"Los pasajes sobre mujeres, viudas y liderazgo poseen debates históricos y denominacionales; no deben usarse para silenciar, controlar o negar dignidad. «Raíz de todos los males» se refiere al amor al dinero, no al dinero en sí.",
      "terms":["sana enseñanza","casa de Dios","supervisor","diácono","viudas","piedad","dinero"],
      "groups":["comunidad de Éfeso","líderes","mujeres","viudas","personas esclavizadas"],
      "places":["Éfeso","Asia Menor"]
    },
    {
      "code":"2TI","slug":"2-timoteo","name":"2 Timoteo","chapters":4,
      "summary":"2 Timoteo presenta una exhortación personal a conservar el evangelio, soportar dificultades con sabiduría, transmitir la enseñanza a personas fieles y permanecer en las Escrituras y la misión.",
      "historical":"La carta se presenta desde prisión cerca de la muerte de Pablo. La relación con la biografía paulina y su autoría es debatida, aunque su forma busca transmitir memoria, legado y continuidad ministerial.",
      "jewish":"Las Escrituras conocidas desde la infancia de Timoteo son principalmente las Escrituras judías. La frase sobre inspiración debe leerse primero dentro de esa realidad histórica.",
      "literary":"Combina memoria familiar, imágenes de soldado, atleta y agricultor, himnos breves, listas de vicios, encargo solemne y saludos personales.",
      "intent":"Preparar a una nueva generación para enseñar con fidelidad, corregir sin violencia verbal y resistir vergüenza, abandono y distorsión del mensaje.",
      "reflection":"Transmitir la fe requiere verdad y ternura: firmeza sin agresión, memoria sin idealización y perseverancia sin ocultar cansancio.",
      "cautions":"Las metáforas militares no autorizan violencia física ni cultura de guerra. «Toda Escritura» no debe usarse para evitar contexto, género literario o estudio histórico. Soportar sufrimiento no significa permanecer en abuso.",
      "terms":["don","depósito","testimonio","Escritura","sana enseñanza","corona"],
      "groups":["Timoteo","colaboradores de Pablo","maestros rivales"],
      "places":["Roma","Éfeso","Asia Menor"]
    },
    {
      "code":"TIT","slug":"tito","name":"Tito","chapters":3,
      "summary":"Tito instruye sobre liderazgo en Creta, enseñanza adaptada a distintos grupos, buenas obras, trato público y corrección de conflictos que amenazan la comunidad.",
      "historical":"La carta se sitúa en comunidades de Creta dentro del mundo romano. Su autoría y fecha, como las demás Pastorales, son debatidas. Las estructuras domésticas y de patronazgo condicionan sus exhortaciones.",
      "jewish":"Las controversias sobre mitos y mandamientos humanos no permiten despreciar la tradición judía. La carta usa categorías de promesa, salvación y pueblo celoso de buenas obras.",
      "literary":"Un encargo de establecer ancianos conduce a instrucciones por grupos, resúmenes teológicos sobre gracia y salvación y advertencias contra disputas improductivas.",
      "intent":"Vincular doctrina con carácter público, liderazgo sin codicia, cuidado doméstico y buenas obras que beneficien a la sociedad.",
      "reflection":"La gracia no produce indiferencia ética; educa para vivir con dominio propio, justicia, bondad y hospitalidad.",
      "cautions":"La cita «los cretenses son siempre mentirosos» reproduce una voz polémica antigua y no autoriza estereotipos étnicos. Los códigos domésticos no justifican abuso ni esclavitud. Las restricciones ministeriales son debatidas.",
      "terms":["ancianos","sana enseñanza","gracia","buenas obras","dominio propio"],
      "groups":["cretenses","líderes","familias antiguas","personas esclavizadas"],
      "places":["Creta","Nicópolis"]
    },
    {
      "code":"PHM","slug":"filemon","name":"Filemón","chapters":1,
      "summary":"Filemón es una breve carta de mediación en la que Pablo devuelve a Onésimo y pide que sea recibido no solo dentro de una relación legal desigual, sino como hermano amado.",
      "historical":"La esclavitud era una institución central del mundo romano. La situación exacta de Onésimo —fugitivo, enviado o implicado en una disputa— no puede determinarse con certeza.",
      "jewish":"La apelación a amor, comunión, deuda y fraternidad se relaciona con la ética de las comunidades del Mesías y con tradiciones bíblicas de liberación y trato al vulnerable, aunque la carta no cita directamente la Torá.",
      "literary":"Es una carta retórica cuidadosamente construida: agradecimiento, apelación afectiva, juego con el nombre Onésimo, promesa de pago y presión moral indirecta sobre Filemón.",
      "intent":"Transformar una relación de poder mediante la identidad compartida en Cristo y persuadir a Filemón para que actúe voluntariamente con dignidad, acogida y generosidad.",
      "reflection":"El evangelio cuestiona relaciones en las que una persona es tratada como propiedad y llama a reconocerla como familia y colaboradora.",
      "cautions":"La carta no debe usarse para defender esclavitud ni para exigir que una persona vulnerable regrese a una situación peligrosa. Los estudios debaten si Pablo pide manumisión explícita o una transformación que apunta hacia ella.",
      "terms":["Onésimo","Filemón","hermano","comunión","deuda","libertad"],
      "groups":["personas esclavizadas","propietarios romanos","iglesia doméstica"],
      "places":["Colosas"]
    }
  ]$books$::jsonb,
  $sections$[
    {"code":"1TI","slug":"1-timoteo-1-2","start":1,"end":2,"title":"Enseñanza, oración y conducta comunitaria","summary":"Timoteo debe confrontar especulación, usar la ley legítimamente y organizar una oración pública que favorezca paz, modestia y testimonio.","intent":"Reorientar la comunidad desde disputas hacia amor, conciencia limpia, oración amplia y una vida pública confiable.","cautions":"1 Timoteo 2:11–15 posee importantes debates lingüísticos, históricos y teológicos. No debe aislarse para negar educación, voz o seguridad a las mujeres.","terms":["ley","conciencia","oración","mediador","mujeres","enseñanza"],"reflection":"La verdad no se protege mediante miedo o humillación, sino formando conciencia, oración y relaciones dignas.","groups":["comunidad de Éfeso","hombres","mujeres","gobernantes"],"places":["Éfeso"]},
    {"code":"1TI","slug":"1-timoteo-3-4","start":3,"end":4,"title":"Liderazgo, casa de Dios y entrenamiento en piedad","summary":"Se describen cualidades de supervisores y diáconos, la iglesia es llamada columna de la verdad y Timoteo debe responder a enseñanzas ascéticas con ejemplo y formación.","intent":"Definir liderazgo por carácter probado y preparar a un colaborador joven para enseñar sin despreciar el cuerpo ni los dones de Dios.","cautions":"Las listas no son una licencia para ocultar faltas graves detrás de reputación. La discusión sobre mujeres diáconos y funciones ministeriales debe reconocer distintas lecturas.","terms":["supervisor","diácono","casa de Dios","misterio","piedad","don"],"reflection":"El carácter cotidiano y la capacidad de cuidar pesan más que el prestigio público.","groups":["supervisores","diáconos","líderes jóvenes"],"places":["Éfeso"]},
    {"code":"1TI","slug":"1-timoteo-5-6","start":5,"end":6,"title":"Viudas, ancianos, trabajo y riqueza","summary":"La carta organiza cuidado de viudas, rendición de cuentas de ancianos, relaciones laborales antiguas y una exhortación a contentamiento y generosidad frente al amor al dinero.","intent":"Proteger recursos comunitarios, honrar a personas vulnerables, investigar acusaciones con justicia y confrontar el uso de religión para enriquecerse.","cautions":"Las categorías de viudas responden a una red social antigua y no deben negar ayuda contemporánea. Las instrucciones a personas esclavizadas no legitiman esclavitud. El liderazgo acusado requiere investigación imparcial, no encubrimiento.","terms":["viudas","ancianos","acusación","contentamiento","amor al dinero","generosidad"],"reflection":"Una comunidad madura protege a quien carece de apoyo y somete a sus líderes a verdad y responsabilidad.","groups":["viudas","ancianos","personas esclavizadas","ricos"],"places":["Éfeso"]},
    {"code":"2TI","slug":"2-timoteo-1","start":1,"end":1,"title":"Memoria, don y depósito confiado","summary":"La carta recuerda la fe de Loida y Eunice, llama a reavivar el don y a no avergonzarse del testimonio ni del prisionero.","intent":"Fortalecer identidad y valentía mediante memoria familiar, Espíritu de poder, amor y dominio propio.","cautions":"«Dios no nos dio espíritu de cobardía» no debe usarse para culpar a personas con miedo, trauma o ansiedad. La valentía puede incluir pedir ayuda y establecer límites.","terms":["Loida","Eunice","don","testimonio","depósito"],"reflection":"La fe puede transmitirse mediante vínculos familiares y comunitarios sin exigir que cada historia sea idéntica.","groups":["Timoteo","familia de Timoteo","colaboradores"],"places":["Roma","Asia Menor"]},
    {"code":"2TI","slug":"2-timoteo-2","start":2,"end":2,"title":"Transmitir, trabajar bien y corregir con mansedumbre","summary":"Timoteo recibe imágenes de soldado, atleta, agricultor y obrero, y debe evitar discusiones inútiles y corregir con paciencia.","intent":"Formar docentes resistentes y cuidadosos que transmitan la enseñanza sin caer en peleas verbales o deseo de dominar.","cautions":"La imagen de soldado es metafórica. «Huir de pasiones juveniles» no justifica vergüenza de la adolescencia ni vigilancia invasiva; el énfasis es buscar justicia en comunidad.","terms":["soldado","atleta","agricultor","obrero","mansedumbre"],"reflection":"La fidelidad combina disciplina con paciencia; corregir bien importa tanto como tener razón.","groups":["Timoteo","maestros","jóvenes"],"places":["Asia Menor"]},
    {"code":"2TI","slug":"2-timoteo-3-4","start":3,"end":4,"title":"Escrituras, enseñanza y despedida","summary":"Frente a tiempos difíciles, Timoteo debe permanecer en lo aprendido, usar las Escrituras para formar y cumplir su servicio mientras la carta concluye con memoria de abandono y esperanza.","intent":"Dar continuidad a la enseñanza y a la misión cuando el liderazgo anterior está por desaparecer.","cautions":"Las listas de vicios no son herramientas para etiquetar generaciones enteras. «Predica a tiempo y fuera de tiempo» no autoriza invadir límites ni acosar. La Escritura requiere interpretación responsable.","terms":["últimos días","Escritura","enseñanza","corona","despedida"],"reflection":"Un legado fiel no depende de controlar el futuro, sino de formar personas capaces de discernir y servir.","groups":["Timoteo","maestros","colaboradores de Pablo"],"places":["Roma","Éfeso"]},
    {"code":"TIT","slug":"tito-1","start":1,"end":1,"title":"Ancianos y enseñanza confiable en Creta","summary":"Tito debe establecer ancianos de carácter probado y silenciar enseñanzas que destruyen hogares por interés económico.","intent":"Dar estabilidad a comunidades nuevas mediante liderazgo hospitalario, justo y capaz de enseñar y corregir.","cautions":"La cita sobre cretenses no autoriza generalización étnica. «Silenciar» se refiere a detener enseñanza dañina, no a censurar preguntas honestas o usar violencia.","terms":["ancianos","hospitalidad","enseñanza","Creta","ganancia"],"reflection":"El liderazgo digno crea seguridad y claridad sin construir una cultura de miedo.","groups":["cretenses","ancianos","maestros rivales"],"places":["Creta"]},
    {"code":"TIT","slug":"tito-2","start":2,"end":2,"title":"Grupos diversos y gracia educadora","summary":"Hombres y mujeres de distintas edades, jóvenes y personas esclavizadas reciben exhortaciones adaptadas; la gracia enseña una vida sobria y justa.","intent":"Hacer visible la coherencia del mensaje en relaciones cotidianas y en grupos con responsabilidades distintas.","cautions":"Las funciones domésticas reflejan cultura antigua y no fijan una única distribución moderna por género. Las instrucciones a esclavos no legitiman la institución.","terms":["sana enseñanza","ancianos","jóvenes","gracia","dominio propio"],"reflection":"La gracia no uniforma a todos, pero llama a cada persona a dignidad, autocontrol y servicio sin abuso.","groups":["hombres mayores","mujeres mayores","jóvenes","personas esclavizadas"],"places":["Creta"]},
    {"code":"TIT","slug":"tito-3","start":3,"end":3,"title":"Vida pública, salvación y buenas obras","summary":"La comunidad debe tratar con respeto a autoridades y vecinos, recordar que la salvación nace de misericordia y evitar disputas improductivas.","intent":"Formar una presencia pública amable y útil, arraigada en gracia y dedicada a necesidades reales.","cautions":"La sujeción a autoridades no exige obedecer abuso o injusticia. Evitar disputas no significa callar denuncias necesarias ni abandonar búsqueda de verdad.","terms":["autoridades","bondad","misericordia","renovación","buenas obras"],"reflection":"Recordar nuestra propia fragilidad reduce arrogancia y abre una vida pública más compasiva.","groups":["comunidades de Creta","autoridades","vecinos"],"places":["Creta","Nicópolis"]},
    {"code":"PHM","slug":"filemon-1","start":1,"end":1,"title":"Onésimo recibido como hermano","summary":"Pablo apela a Filemón en favor de Onésimo, se ofrece a cubrir una deuda y pide que la relación sea redefinida por amor y fraternidad.","intent":"Usar persuasión, comunión y responsabilidad económica para mover a una persona con poder hacia una acogida que reconozca dignidad y parentesco espiritual.","cautions":"No se debe romantizar el retorno de Onésimo ni suponer que toda reconciliación es segura. La carta no debe usarse para pedir a víctimas que vuelvan a relaciones coercitivas.","terms":["Onésimo","Filemón","hermano","deuda","comunión","acogida"],"reflection":"La reconciliación auténtica modifica el poder y asume costos; no se limita a palabras afectuosas.","groups":["Onésimo","Filemón","iglesia doméstica"],"places":["Colosas"]}
  ]$sections$::jsonb
);