-- FASE D · Bloque 4 · Poesía y sabiduría 4: Eclesiastés y Cantares
update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code in ('ECC','SNG');

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('eclesiastes-perfil','ECC','book',1,NULL::smallint,12,NULL::smallint,
   'Eclesiastés: límites, tiempo y gozo responsable',
   'Eclesiastés examina trabajo, placer, conocimiento, riqueza, injusticia, muerte y tiempo para mostrar que la vida no puede controlarse ni reducirse a una fórmula segura de éxito.',
   'El libro refleja una sociedad urbana y administrada donde riqueza, burocracia, comercio y desigualdad crean oportunidades y frustraciones. La identidad histórica exacta de Qohelet y la fecha de composición son debatidas.',
   'Qohelet pertenece a los Escritos y se lee durante Sucot en varias tradiciones judías. Su voz crítica convive dentro del canon con Proverbios y Job, ampliando la conversación sobre sabiduría.',
   'Una voz docente prueba proyectos y observaciones mediante repeticiones de hebel, «bajo el sol» y llamadas a disfrutar dones sencillos. Un epílogo editorial enmarca sus palabras.',
   'Desafiar la ilusión de control, revelar la fragilidad de logros humanos y orientar hacia una vida humilde que recibe el presente sin negar injusticia ni responsabilidad.',
   'Aceptar límites no equivale a rendirse. Puede liberar de la necesidad de dominar el futuro y permitir disfrutar trabajo, amistad, alimento y tiempo como regalos temporales.',
   'Hebel no debe traducirse siempre como «sin sentido» en sentido nihilista; puede comunicar vapor, transitoriedad, enigma o frustración. El libro no enseña que nada importa ni que la búsqueda de justicia sea inútil.',
   ARRAY['Qohelet','hebel','bajo el sol','tiempo','trabajo','gozo','muerte','límites']::text[],
   ARRAY['sabios','trabajadores','gobernantes','pobres','ricos']::text[],
   ARRAY['Jerusalén']::text[]),
  ('eclesiastes-1-2-experimentos','ECC','section',1,NULL::smallint,2,NULL::smallint,
   'El ciclo de la vida y los experimentos de Qohelet',
   'Qohelet observa ciclos de naturaleza y memoria, luego prueba sabiduría, placer, grandes proyectos y acumulación, concluyendo que ninguno puede asegurar significado o control permanente.',
   'Los proyectos reales, jardines, construcciones, servidores y tesoros evocan una élite urbana capaz de movilizar recursos, aunque la voz literaria no necesita identificarse directamente con Salomón histórico.',
   'La figura del rey sabio funciona como marco para una investigación extrema. La tradición debate si el nombre Salomón debe entenderse como autoría, personaje literario o asociación sapiencial.',
   'Una serie de pruebas en primera persona aumenta de escala y termina con la muerte como límite compartido por sabio y necio.',
   'Mostrar que el éxito, el conocimiento y el placer no pueden cargar por sí solos con el peso de dar seguridad última a la vida.',
   'Los logros pueden disfrutarse sin convertirlos en identidad absoluta. Preguntar qué permanece ayuda a distinguir responsabilidad presente de obsesión por controlar el legado.',
   'El texto no condena toda alegría, estudio o trabajo. Critica su incapacidad para garantizar permanencia y no debe usarse para despreciar educación, creatividad o metas saludables.',
   ARRAY['ciclos','memoria','sabiduría','placer','proyectos','legado']::text[],
   ARRAY['sabios','trabajadores','reyes']::text[],
   ARRAY['Jerusalén']::text[]),
  ('eclesiastes-3-6-tiempo','ECC','section',3,NULL::smallint,6,NULL::smallint,
   'Tiempo, injusticia, compañía y límites de la riqueza',
   'El poema sobre tiempos introduce observaciones sobre injusticia, opresión, rivalidad, soledad, gobierno y riqueza que no produce capacidad de disfrutar.',
   'La desigualdad, los tribunales corruptos, el trabajo competitivo y el patronazgo político eran realidades visibles en sociedades imperiales y urbanas.',
   'La afirmación de que Dios hace apropiada cada cosa en su tiempo convive con la incapacidad humana de abarcar toda la obra. La tradición ha usado esta tensión para hablar de providencia sin negar misterio.',
   'Un poema ordenado es seguido por escenas desordenadas de vida social. La forma misma contrasta el deseo de tiempo apropiado con experiencias injustas.',
   'Enseñar que reconocer estaciones no significa aprobar cada acontecimiento, y que el compañerismo, la justicia y la capacidad de recibir son más valiosos que la acumulación aislada.',
   'No todas las etapas pueden acelerarse. Compartir cargas y aceptar ayuda puede ser una forma de sabiduría frente a trabajo, duelo y cambio.',
   '«Todo tiene su tiempo» no debe usarse para justificar abuso, pasividad o tragedia como si cada acto humano fuera moralmente ordenado por Dios. El pasaje distingue observación del tiempo y aprobación ética.',
   ARRAY['tiempo','injusticia','opresión','compañía','riqueza','disfrute']::text[],
   ARRAY['trabajadores','oprimidos','gobernantes','ricos','pobres']::text[],
   ARRAY['tribunales','ciudad']::text[]),
  ('eclesiastes-7-10-sabiduria','ECC','section',7,NULL::smallint,10,NULL::smallint,
   'Sabiduría sobria en un mundo incierto',
   'Qohelet reúne reflexiones sobre corrección, extremos, autoridad, injusticia, reputación, palabras y decisiones de gobernantes, defendiendo una sabiduría modesta que reconoce excepciones.',
   'Consejeros, funcionarios, banquetes, tribunales y gobernantes forman el trasfondo de una sabiduría aplicada a la vida pública y privada.',
   'El temor de Dios aparece como orientación que evita convertir una sola regla en control absoluto. La tradición ha debatido dichos difíciles sobre género y humanidad dentro de su contexto retórico.',
   'Dichos breves y observaciones se enlazan por palabras clave, a veces tensándose entre sí para impedir conclusiones demasiado simples.',
   'Formar prudencia capaz de actuar sin exigir certeza total, escuchar corrección y reconocer que una regla general puede necesitar discernimiento en casos concretos.',
   'La humildad intelectual protege de decisiones impulsivas. No conocer todo el futuro no elimina la posibilidad de actuar con integridad hoy.',
   'Los dichos negativos sobre mujeres no deben generalizarse como doctrina sobre género; aparecen dentro de una búsqueda frustrada y son contrapesados por la afirmación de que la humanidad entera se ha desviado. La recomendación de obedecer al rey no exige tolerar injusticia sin límites.',
   ARRAY['prudencia','corrección','autoridad','reputación','palabras','incertidumbre']::text[],
   ARRAY['sabios','gobernantes','funcionarios','ciudadanos']::text[],
   ARRAY['corte','ciudad']::text[]),
  ('eclesiastes-11-12-final','ECC','section',11,NULL::smallint,12,NULL::smallint,
   'Riesgo responsable, juventud, envejecimiento y conclusión',
   'El cierre invita a actuar sin esperar condiciones perfectas, disfrutar responsablemente la juventud, recordar al Creador y reconocer el envejecimiento y la muerte antes del epílogo final.',
   'La siembra, el comercio marítimo y la incertidumbre del clima ilustran decisiones económicas que siempre implicaban riesgo. El poema del envejecimiento usa imágenes domésticas y urbanas.',
   'El consejo de recordar al Creador y temer a Dios sitúa el gozo dentro de responsabilidad. El epílogo reconoce que las palabras sabias pueden incomodar y orientar.',
   'Consejos sobre riesgo conducen a un poema altamente metafórico sobre deterioro físico y a un marco editorial que resume la enseñanza.',
   'Invitar a vivir plenamente sin negar consecuencias, aceptar la mortalidad y orientar decisiones hacia reverencia y responsabilidad.',
   'La juventud no es una etapa inferior ni la vejez una pérdida de dignidad. Cada temporada puede recibirse con honestidad, cuidado y propósito.',
   'El poema del envejecimiento no debe usarse para burlarse del cuerpo ni afirmar que la vida pierde valor con la edad. «Echa tu pan sobre las aguas» no es una promesa financiera automática.',
   ARRAY['riesgo','juventud','Creador','envejecimiento','mortalidad','temor de Dios']::text[],
   ARRAY['jóvenes','ancianos','trabajadores','sabios']::text[],
   ARRAY['campo','mar','ciudad']::text[]),
  ('cantares-perfil','SNG','book',1,NULL::smallint,8,NULL::smallint,
   'Cantares: poesía de amor, deseo y reciprocidad',
   'Cantares reúne poemas de admiración, búsqueda, ausencia, encuentro y compromiso entre voces amantes, celebrando el afecto y la reciprocidad mediante imágenes de jardines, ciudades y naturaleza.',
   'La poesía usa paisajes, perfumes, joyas, rebaños y espacios urbanos conocidos en el antiguo Cercano Oriente. La fecha, autoría y organización dramática exactas no se conocen con certeza.',
   'Shir haShirim se lee durante Pascua en la tradición judía y ha sido interpretado tanto como poesía de amor humano como alegoría de la relación entre Dios e Israel. La lectura cristiana posterior añadió asociaciones con Cristo y la iglesia.',
   'Las voces cambian entre una mujer, un hombre y un coro. Refranes sobre no despertar el amor, escenas de búsqueda y comparaciones poéticas forman una secuencia más lírica que narrativa.',
   'Honrar el amor comprometido, la admiración mutua, el deseo expresado con dignidad y la libertad de una voz femenina fuerte dentro de la poesía bíblica.',
   'El afecto sano reconoce la voz y el valor de la otra persona. La cercanía no elimina respeto, paciencia ni libertad para expresar deseo y límites.',
   'Debe leerse primero como poesía y no como manual anatómico ni código secreto. Las interpretaciones judías, cristianas o místicas son capas posteriores que deben identificarse como tales. El libro no obliga a una sola cronología romántica ni justifica posesión o presión dentro de una relación.',
   ARRAY['amor','reciprocidad','deseo','jardín','búsqueda','compromiso','Shir haShirim']::text[],
   ARRAY['amantes','jóvenes de Jerusalén','familias']::text[],
   ARRAY['Jerusalén','Líbano','jardines','campos']::text[]),
  ('cantares-1-2-admiracion','SNG','section',1,NULL::smallint,2,NULL::smallint,
   'Admiración mutua y despertar del amor',
   'Las voces expresan admiración, deseo de cercanía y disfrute de la presencia mutua mediante imágenes de fragancias, campos, flores y estaciones.',
   'La poesía amorosa antigua empleaba comparaciones con naturaleza, riqueza, animales y paisajes para comunicar belleza, vitalidad y pertenencia.',
   'La voz femenina inicia y conduce gran parte del poema, un rasgo significativo dentro de la literatura antigua. El refrán sobre no despertar el amor subraya oportunidad y disposición.',
   'Diálogos breves y un cambio de invierno a primavera crean movimiento desde anhelo hacia invitación.',
   'Presentar el amor como respuesta mutua que no necesita reducir a la otra persona a objeto ni adelantarse a su tiempo.',
   'La admiración puede expresarse sin comparación destructiva ni presión. El respeto al tiempo y a la disposición de ambos forma parte del afecto.',
   'Las metáforas no deben convertirse en estándares físicos para evaluar cuerpos reales. El refrán no establece una edad o calendario universal, sino una cautela poética sobre no forzar el amor.',
   ARRAY['admiración','primavera','voz femenina','tiempo','mutualidad']::text[],
   ARRAY['amantes','jóvenes de Jerusalén']::text[],
   ARRAY['campos','jardines','Jerusalén']::text[]),
  ('cantares-3-5-busqueda','SNG','section',3,NULL::smallint,5,NULL::smallint,
   'Búsqueda, celebración y distancia',
   'La mujer busca a quien ama en la ciudad, aparecen imágenes de procesión y celebración, y después una escena de demora conduce a una nueva búsqueda marcada por ausencia y vulnerabilidad.',
   'Las calles nocturnas, guardianes, procesiones y banquetes reflejan espacios urbanos y ceremoniales; no es seguro que todas las escenas formen una secuencia histórica literal.',
   'La tradición alegórica leyó la búsqueda como anhelo de Israel por Dios, pero el sentido poético inmediato sigue siendo la experiencia humana de cercanía y ausencia.',
   'Escenas de búsqueda se alternan con poemas de admiración y un centro de celebración. La repetición crea tensión entre presencia y pérdida.',
   'Mostrar que el amor incluye iniciativa y deseo, pero también momentos de falta de sincronía que no deben resolverse mediante control o violencia.',
   'La comunicación y la atención importan. Una relación sana no niega la vulnerabilidad que aparece cuando las personas no responden al mismo tiempo.',
   'La escena con los guardianes describe daño y no lo aprueba. No debe romantizarse el peligro ni usarse para sugerir que alguien merece sufrir por buscar afecto.',
   ARRAY['búsqueda','ciudad','celebración','ausencia','guardianes','vulnerabilidad']::text[],
   ARRAY['amantes','guardianes','jóvenes de Jerusalén']::text[],
   ARRAY['Jerusalén','calles','Líbano']::text[]),
  ('cantares-6-8-compromiso','SNG','section',6,NULL::smallint,8,NULL::smallint,
   'Reencuentro, reciprocidad y fuerza del amor',
   'Las voces vuelven a encontrarse, se expresan pertenencia mutua y admiración y el poema concluye afirmando que el amor es fuerte y no puede comprarse con riqueza.',
   'Viñedos, jardines, aldeas y sellos pertenecen a economía agraria, propiedad familiar y símbolos antiguos de identidad y compromiso.',
   'Cantares 8 ha sido central para lecturas judías sobre la fuerza del amor del pacto. La imagen del sello comunica cercanía y pertenencia, no control de una persona por otra.',
   'Refranes anteriores regresan, la fórmula de pertenencia se vuelve más equilibrada y el cierre contrasta amor y dinero.',
   'Concluir que el amor digno no se compra, no se fuerza y no anula la voz de ninguna persona; crece mediante reciprocidad, presencia y compromiso.',
   'El afecto profundo posee valor que no puede medirse económicamente. La pertenencia mutua debe convivir con dignidad, responsabilidad y libertad.',
   '«Fuerte como la muerte» es una comparación poética sobre intensidad, no una invitación a conductas peligrosas ni a demostrar amor mediante sufrimiento. La pertenencia mutua no significa posesión o pérdida de autonomía.',
   ARRAY['reencuentro','sello','pertenencia mutua','viñedo','amor','compromiso']::text[],
   ARRAY['amantes','familias','jóvenes de Jerusalén']::text[],
   ARRAY['jardines','viñedos','aldeas']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select
  data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/poesia-sabiduria/v1#' || data.slug,
  'poesia-sabiduria-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','poetry-wisdom','generated_by_ai',false,'review_level','editorial')
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();