-- FASE H / Bloque 3 — lote 001 de glosas españolas conservadoras.
-- Política: insert-only. No modifica biblical_lexical_entries ni sobrescribe glosas existentes.
-- Batch id: fase_h_es_batch_001_20260820
--
-- Reversión exacta, si fuera necesaria:
-- DELETE FROM public.biblical_hebrew_spanish_glosses
-- WHERE provenance->>'batch_id' = 'fase_h_es_batch_001_20260820';

with map(source_gloss, display_gloss_es) as (
  values
  ('terror','terror'),
  ('darkness','oscuridad'),
  ('abundance','abundancia'),
  ('foundation','fundamento'),
  ('net','red'),
  ('to cover','cubrir'),
  ('to gather','reunir'),
  ('to shine','brillar'),
  ('valley','valle'),
  ('burden','carga'),
  ('food','alimento'),
  ('to burn','quemar'),
  ('to shake','sacudir'),
  ('cord','cordón'),
  ('end','fin'),
  ('ruin','ruina'),
  ('to bind','atar'),
  ('to break','romper'),
  ('to divide','dividir'),
  ('wall','muro'),
  ('garment','vestidura'),
  ('step','paso'),
  ('strong','fuerte'),
  ('to crush','aplastar'),
  ('to mock','burlarse'),
  ('to rejoice','regocijarse'),
  ('to spread','extender'),
  ('to twist','torcer'),
  ('vision','visión'),
  ('youth','juventud'),
  ('bed','cama'),
  ('branch','rama'),
  ('cloud','nube'),
  ('desolation','desolación'),
  ('distress','angustia'),
  ('heap','montón'),
  ('height','altura'),
  ('locust','langosta'),
  ('possession','posesión'),
  ('pride','orgullo'),
  ('shame','vergüenza'),
  ('slaughter','matanza'),
  ('spice','especia'),
  ('strife','contienda'),
  ('to destroy','destruir'),
  ('to dwell','habitar'),
  ('to scatter','dispersar'),
  ('where?','¿dónde?'),
  ('woe!','¡ay!'),
  ('assembly','asamblea'),
  ('bough','rama'),
  ('bowl','cuenco'),
  ('bun','panecillo'),
  ('contempt','desprecio'),
  ('cry','grito'),
  ('division','división'),
  ('entrance','entrada'),
  ('fear','temor'),
  ('heat','calor'),
  ('hook','gancho'),
  ('leader','líder'),
  ('lock','cerradura'),
  ('merchandise','mercancía'),
  ('perfection','perfección'),
  ('pit','foso'),
  ('portion','porción'),
  ('pot','olla'),
  ('poverty','pobreza'),
  ('recompense','recompensa'),
  ('redemption','redención'),
  ('refuge','refugio'),
  ('robe','túnica'),
  ('scab','costra'),
  ('security','seguridad'),
  ('snare','trampa'),
  ('support','apoyo'),
  ('thought','pensamiento'),
  ('to bow','inclinarse'),
  ('to flow','fluir'),
  ('to hide','ocultar'),
  ('to oppress','oprimir'),
  ('to pierce','perforar'),
  ('to pour','verter'),
  ('to press','presionar'),
  ('to sink','hundirse'),
  ('to surround','rodear'),
  ('to watch','vigilar'),
  ('village','aldea'),
  ('work','trabajo'),
  ('wound','herida'),
  ('ambush','emboscada'),
  ('belt','cinturón'),
  ('bond','vínculo'),
  ('border','frontera'),
  ('cattle','ganado'),
  ('chain','cadena'),
  ('cleft','hendidura'),
  ('counsel','consejo'),
  ('delicacy','manjar'),
  ('delight','deleite'),
  ('dominion','dominio'),
  ('drought','sequía'),
  ('dung','estiércol'),
  ('error','error'),
  ('firstborn','primogénito'),
  ('fourth','cuarto'),
  ('fruit','fruto'),
  ('gloom','penumbra'),
  ('gold','oro'),
  ('guard','guardia'),
  ('hammer','martillo'),
  ('hole','agujero'),
  ('how?','¿cómo?'),
  ('incision','incisión'),
  ('jar','jarra'),
  ('judgment','juicio'),
  ('knowledge','conocimiento'),
  ('lamb','cordero'),
  ('light','luz'),
  ('likeness','semejanza'),
  ('lizard','lagarto'),
  ('meditation','meditación'),
  ('ostrich','avestruz'),
  ('pain','dolor'),
  ('plunder','botín'),
  ('praise','alabanza')
),
eligible as (
  select
    e.id as lexical_entry_id,
    e.source_gloss,
    map.display_gloss_es
  from public.biblical_lexical_entries e
  join map on map.source_gloss = e.source_gloss
  left join public.biblical_hebrew_spanish_glosses g
    on g.lexical_entry_id = e.id
  where e.language = 'hebrew'
    and e.review_status = 'approved'
    and e.enabled = true
    and e.display_gloss_es is null
    and g.lexical_entry_id is null
)
insert into public.biblical_hebrew_spanish_glosses (
  lexical_entry_id,
  display_gloss_es,
  alternative_glosses_es,
  confidence,
  derivation_method,
  source_gloss_snapshot,
  status,
  provenance
)
select
  lexical_entry_id,
  display_gloss_es,
  '{}'::text[],
  96,
  'exact_source_gloss_editorial_map_v1',
  source_gloss,
  'verified_derived',
  jsonb_build_object(
    'phase', 'FASE_H_BLOQUE_3',
    'batch_id', 'fase_h_es_batch_001_20260820',
    'source', 'STEPBible/TAHOT source_gloss en',
    'derivation', 'conservative exact English gloss mapping',
    'context_used_as_meaning', false
  )
from eligible
on conflict (lexical_entry_id) do nothing;
