-- FASE D · Bloque 4 · Lote histórico 1: Josué, Jueces y Rut
update public.biblical_sources
set provider_version = 'historicos-v1-2026-08-02',
    content_hash = encode(extensions.digest('vida-contexto-editorial|historicos-v1-2026-08-02', 'sha256'), 'hex'),
    metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
      'coverage', 'canonical-index-pentateuch-and-historical-books',
      'latest_batch', 'historical-books',
      'generated_by_ai', false
    ),
    updated_at = now()
where slug = 'vida-contexto-editorial';

update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code in ('JOS','JDG','RUT');

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('josue-perfil','JOS','book',1,NULL::smallint,24,NULL::smallint,
   'Josué: tierra, fidelidad y renovación del pacto',
   'Josué relata el paso del Jordán, las campañas en Canaán, la distribución de la tierra y la renovación final del pacto bajo el liderazgo de Josué.',
   'El libro se sitúa en la transición desde una comunidad itinerante hacia asentamientos tribales en Canaán. La relación entre el relato, la arqueología y la formación histórica de Israel continúa siendo debatida.',
   'En la tradición judía, Josué abre los Profetas Anteriores. La posesión de la tierra permanece vinculada a la Torá, a la responsabilidad comunitaria y a la fidelidad del pacto.',
   'Combina discursos, relatos de cruce y batalla, listas territoriales, ciudades de refugio y ceremonias de pacto. El inicio y el final destacan obediencia, memoria y elección.',
   'Mostrar que el cumplimiento de la promesa exige confianza y obediencia, y que la tierra es recibida como responsabilidad de pacto, no como posesión humana absoluta.',
   'La fidelidad de Dios no elimina decisiones difíciles ni responsabilidad ética. La memoria del camino debe conducir a una vida de servicio y justicia.',
   'Los relatos de conquista no constituyen una autorización general para guerras modernas, colonialismo ni desplazamiento religioso. El lenguaje de destrucción total, la evidencia arqueológica y las diferentes perspectivas textuales requieren tratamiento responsable.',
   ARRAY['Josué','Jordán','tierra','pacto','herencia','memoria']::text[],
   ARRAY['israelitas','cananeos','gabaonitas','tribus de Israel']::text[],
   ARRAY['Jordán','Jericó','Hai','Siquem','Canaán']::text[]),
  ('josue-1-5-entrada','JOS','section',1,NULL::smallint,5,NULL::smallint,
   'Preparación, cruce del Jordán y memoria',
   'Josué recibe el encargo de liderar, los espías son protegidos por Rahab, Israel cruza el Jordán y levanta piedras memoriales antes de celebrar la Pascua.',
   'El Jordán marca una frontera geográfica y narrativa. Los memoriales de piedra, la circuncisión y la Pascua conectan a la nueva generación con el éxodo y el Sinaí.',
   'Rahab ocupa un lugar destacado como extranjera que reconoce al Dios de Israel. El cruce y la Pascua renuevan la identidad antes de cualquier campaña militar.',
   'Discursos de ánimo, una misión de espionaje, un cruce milagroso y ritos de memoria forman una preparación progresiva para entrar en la tierra.',
   'Enseñar que el liderazgo depende de la Torá, que la fe puede aparecer fuera de Israel y que la acción futura debe comenzar recordando la gracia pasada.',
   'Antes de enfrentar desafíos, la comunidad es llamada a recordar, consagrarse y reconocer que la presencia de Dios no puede manipularse.',
   'La frase «sé fuerte y valiente» no promete éxito para cualquier proyecto personal; está ligada a una misión concreta y a la obediencia. Rahab no debe ser reducida únicamente a su ocupación, ignorando su agencia y hospitalidad.',
   ARRAY['valentía','Torá','Rahab','Jordán','memorial','Pascua']::text[],
   ARRAY['israelitas','cananeos']::text[],
   ARRAY['Jordán','Jericó','Gilgal']::text[]),
  ('josue-6-12-campanas','JOS','section',6,NULL::smallint,12,NULL::smallint,
   'Jericó, Hai y las campañas narradas',
   'La caída de Jericó, el pecado de Acán, la derrota y victoria en Hai, el pacto con Gabaón y varias campañas muestran avance, crisis y dependencia del pacto.',
   'Las ciudades-estado cananeas, las coaliciones regionales y el lenguaje militar pertenecen al antiguo Cercano Oriente. Los datos arqueológicos no ofrecen una reconstrucción simple y uniforme de todos los episodios.',
   'El relato contrasta la fe de Rahab con la infidelidad de Acán y presenta a los gabaonitas como un caso complejo de extranjeros incorporados mediante juramento.',
   'Victorias y derrotas se alternan para impedir que el avance se atribuya únicamente a capacidad militar. Las listas finales resumen campañas con lenguaje convencional de victoria.',
   'Comunicar que la fidelidad comunitaria importa, que el engaño y la codicia tienen consecuencias, y que los juramentos requieren responsabilidad incluso en situaciones ambiguas.',
   'El texto confronta la confianza en la fuerza y llama a examinar la relación entre obediencia, justicia y trato a quienes buscan protección.',
   'La violencia es moralmente difícil y no debe celebrarse de manera superficial. El término herem y las fórmulas de destrucción deben leerse dentro de su retórica antigua, sus tensiones canónicas y el rechazo de toda aplicación violenta moderna.',
   ARRAY['Jericó','Acán','Hai','Gabaón','herem','juramento']::text[],
   ARRAY['israelitas','cananeos','gabaonitas']::text[],
   ARRAY['Jericó','Hai','Gabaón','Hazor']::text[]),
  ('josue-13-21-herencia','JOS','section',13,NULL::smallint,21,NULL::smallint,
   'Distribución tribal, refugio y ciudades levíticas',
   'La tierra se asigna a las tribus, se reconocen zonas aún no ocupadas, las hijas de Zelofehad reciben su herencia y se establecen ciudades de refugio y ciudades levíticas.',
   'Las listas territoriales preservan memoria geográfica, reclamos tribales y organización administrativa. No todas las fronteras pueden identificarse con certeza en mapas modernos.',
   'La herencia está ligada a tribu, familia y responsabilidad. Las ciudades de refugio limitan la venganza de sangre, mientras que los levitas reciben ciudades en vez de un territorio continuo.',
   'El ritmo narrativo se vuelve documental mediante límites, nombres y asignaciones. Esa forma literaria comunica que la promesa también requiere administración justa.',
   'Mostrar que la tierra debe distribuirse, protegerse y organizarse de manera que existan acceso, refugio, culto y responsabilidad entre las tribus.',
   'La promesa espiritual no elimina la necesidad de estructuras justas. La comunidad debe convertir sus convicciones en protección concreta para personas vulnerables.',
   'Las fronteras antiguas no deben trasladarse directamente a disputas políticas modernas. Las ciudades de refugio limitan la violencia, pero no equivalen por sí mismas a un sistema jurídico contemporáneo completo.',
   ARRAY['herencia','tribus','ciudades de refugio','levitas','Zelofehad']::text[],
   ARRAY['tribus de Israel','levitas']::text[],
   ARRAY['Canaán','Silo','Hebrón','Siquem']::text[]),
  ('josue-22-24-renovacion','JOS','section',22,NULL::smallint,24,NULL::smallint,
   'Unidad tribal y elección del pacto',
   'Un conflicto por un altar es resuelto mediante diálogo, Josué pronuncia discursos finales y en Siquem el pueblo renueva su compromiso de servir a YHWH.',
   'Las tribus a ambos lados del Jordán necesitaban mantener vínculos políticos y religiosos. Los altares podían interpretarse como señales de identidad o como centros rivales de culto.',
   'La asamblea en Siquem repasa la historia desde los antepasados hasta la tierra y culmina en la conocida decisión de servir a Dios con integridad.',
   'El libro concluye con una crisis resuelta por investigación y conversación, seguida por una recapitulación histórica y una ceremonia de pacto.',
   'Llamar a la comunidad a verificar antes de acusar, conservar la unidad y escoger de manera consciente a quién servirá.',
   'La fidelidad no debe heredarse únicamente como costumbre; necesita una respuesta presente, honesta y acompañada por memoria comunitaria.',
   '«Yo y mi casa serviremos» no autoriza control coercitivo sobre la conciencia familiar. El pasaje describe responsabilidad de liderazgo y compromiso público, no manipulación espiritual.',
   ARRAY['altar','unidad','Siquem','servicio','pacto','elección']::text[],
   ARRAY['tribus de Israel']::text[],
   ARRAY['Jordán','Siquem']::text[]),
  ('jueces-perfil','JDG','book',1,NULL::smallint,21,NULL::smallint,
   'Jueces: ciclos de opresión y deterioro social',
   'Jueces narra una etapa fragmentada en la que Israel alterna infidelidad, opresión, clamor y liberación, mientras el orden social y religioso se deteriora progresivamente.',
   'El periodo refleja confederaciones tribales, ciudades cananeas y amenazas regionales antes de una monarquía centralizada. La cronología de los jueces no debe sumarse mecánicamente como una secuencia simple.',
   'En el Tanaj forma parte de los Profetas Anteriores. Sus relatos funcionan como memoria crítica de la infidelidad al pacto y de las consecuencias de abandonar la justicia.',
   'Una introducción doble, una serie de ciclos con libertadores y dos apéndices de caos crean una espiral descendente más que una colección de héroes ejemplares.',
   'Explicar que la liberación repetida no resuelve un corazón y una sociedad que rehúsan aprender, y preparar la pregunta por un liderazgo justo.',
   'Dios escucha a personas oprimidas, pero el libro también obliga a lamentar la normalización de violencia, idolatría y abuso dentro del propio pueblo.',
   'Los jueces no deben presentarse como modelos morales completos. El texto describe violencia sexual, guerra y venganza sin aprobar cada acto, y su estribillo sobre la ausencia de rey tampoco convierte automáticamente cualquier monarquía en solución divina.',
   ARRAY['jueces','opresión','clamor','liberación','idolatría','caos']::text[],
   ARRAY['israelitas','cananeos','madianitas','filisteos','amonitas']::text[],
   ARRAY['Canaán','Siquem','Galaad','Gaza']::text[]),
  ('jueces-1-3-patron','JDG','section',1,NULL::smallint,3,NULL::smallint,
   'Asentamiento incompleto y patrón de los jueces',
   'Las tribus no desplazan completamente a diversos pueblos y el narrador establece el ciclo de abandono, opresión, clamor y levantamiento de libertadores.',
   'La coexistencia con ciudades y poblaciones cananeas refleja un proceso regional complejo, no una ocupación instantánea y uniforme.',
   'La unidad interpreta la crisis mediante el pacto: olvidar la historia y adoptar otros cultos produce pérdida de identidad y vulnerabilidad.',
   'Dos introducciones explican geografía e interpretación teológica; luego Otoniel, Aod y Samgar ejemplifican el patrón inicial.',
   'Mostrar que las decisiones no resueltas y la pérdida de memoria pueden convertirse en patrones repetidos de dependencia y opresión.',
   'Reconocer un ciclo dañino es el primer paso para romperlo; la liberación externa necesita acompañarse de transformación interna.',
   'La presencia de pueblos vecinos no debe usarse para demonizar culturas actuales. La mano izquierda de Aod y otros detalles narrativos no contienen códigos místicos ocultos.',
   ARRAY['ciclo','olvido','Otoniel','Aod','opresión','liberación']::text[],
   ARRAY['israelitas','cananeos','moabitas']::text[],
   ARRAY['Canaán','Moab']::text[]),
  ('jueces-4-16-libertadores','JDG','section',4,NULL::smallint,16,NULL::smallint,
   'Débora, Gedeón, Jefté, Sansón y la espiral de liderazgo',
   'Los relatos de libertadores muestran victorias sorprendentes, pero también un deterioro creciente del carácter y de las decisiones de quienes lideran.',
   'Las amenazas provienen de coaliciones locales, madianitas, amonitas y filisteos. Las armas, alianzas y conflictos reflejan un territorio políticamente fragmentado.',
   'Débora es profetisa y líder; el cántico de Jueces 5 preserva una de las composiciones poéticas antiguas del libro. La tradición debate críticamente el voto de Jefté y la vida de Sansón.',
   'Los ciclos se hacen más extensos y ambiguos. La victoria militar permanece, pero el liderazgo se vuelve progresivamente más inestable y autodestructivo.',
   'Advertir que un don, una victoria o una función pública no garantizan madurez moral, y que decisiones impulsivas pueden dañar a la comunidad.',
   'Dios puede obrar mediante personas frágiles, pero esa verdad nunca debe utilizarse para excusar abuso, imprudencia o falta de rendición de cuentas.',
   'El voto de Jefté no enseña que Dios exija promesas destructivas. La historia de Sansón no legitima violencia, explotación sexual ni la idea de que el carisma compensa la ausencia de carácter.',
   ARRAY['Débora','Barac','Gedeón','Jefté','Sansón','liderazgo']::text[],
   ARRAY['israelitas','madianitas','amonitas','filisteos']::text[],
   ARRAY['Tabor','Ofra','Galaad','Gaza']::text[]),
  ('jueces-17-21-colapso','JDG','section',17,NULL::smallint,21,NULL::smallint,
   'Idolatría, violencia y colapso comunitario',
   'Los episodios de Micaía, la migración de Dan, el levita y su concubina y la guerra contra Benjamín muestran una sociedad donde religión, hospitalidad y justicia han colapsado.',
   'Las historias reflejan inseguridad tribal, santuarios domésticos, migración territorial y ausencia de instituciones capaces de proteger a personas vulnerables.',
   'Estos capítulos se leen como acusación contra todo Israel, no solamente contra una tribu. El abuso del lenguaje religioso intensifica la crítica.',
   'Dos apéndices conectados por levitas y por el estribillo «cada uno hacía lo que bien le parecía» llevan el libro a su punto más oscuro.',
   'Mostrar que la religión sin justicia puede convivir con idolatría, violencia sexual, venganza colectiva y decisiones políticas desastrosas.',
   'La comunidad creyente debe escuchar el sufrimiento de las víctimas y rechazar soluciones que reproduzcan el daño que pretenden corregir.',
   'La concubina no debe desaparecer detrás del debate político; es víctima de violencia extrema. El texto no prescribe el trato recibido ni justifica secuestros o castigos colectivos.',
   ARRAY['Micaía','Dan','levita','Benjamín','violencia','anarquía']::text[],
   ARRAY['danitas','benjaminitas','israelitas']::text[],
   ARRAY['Efraín','Dan','Gabaa','Silo']::text[]),
  ('rut-perfil','RUT','book',1,NULL::smallint,4,NULL::smallint,
   'Rut: lealtad, provisión y pertenencia',
   'Rut sigue a Noemí y a su nuera moabita desde pérdida y migración hasta provisión, redención familiar y una genealogía vinculada con David.',
   'La historia se desarrolla en la época de los jueces y refleja hambre, migración, espigueo, propiedad familiar, matrimonio y mecanismos de rescate dentro de una comunidad agraria.',
   'Rut es leída durante Shavuot. La inclusión de una mujer moabita en la historia de David destaca la fuerza de la hesed, la lealtad comprometida que cruza fronteras étnicas.',
   'La narración breve usa diálogos, bendiciones, ironía, cambios de vacío a plenitud y una genealogía final. Las iniciativas de Rut y Noemí impulsan la trama.',
   'Mostrar cómo la fidelidad cotidiana, la generosidad y las estructuras de cuidado pueden transformar una situación de vulnerabilidad y ampliar la comunidad del pacto.',
   'Dios suele ser reconocido mediante actos concretos de bondad, trabajo, hospitalidad y responsabilidad compartida, no únicamente mediante acontecimientos espectaculares.',
   'El libro no debe convertirse en una fórmula para conseguir pareja ni idealizar la dependencia económica. El término goel tiene funciones familiares y legales específicas que no equivalen exactamente a un romance moderno.',
   ARRAY['Rut','Noemí','Booz','hesed','goel','espigueo','David']::text[],
   ARRAY['moabitas','judíos de Belén']::text[],
   ARRAY['Moab','Belén']::text[]),
  ('rut-1-2-regreso','RUT','section',1,NULL::smallint,2,NULL::smallint,
   'Pérdida, regreso y espigueo',
   'Noemí vuelve a Belén acompañada por Rut, quien expresa lealtad y comienza a espigar en el campo de Booz para sostener a ambas mujeres.',
   'Las viudas y extranjeras enfrentaban gran vulnerabilidad. Las leyes de espigueo ofrecían una forma limitada de acceso a alimento mediante trabajo en los márgenes de la cosecha.',
   'La declaración de Rut expresa adhesión a Noemí, a su pueblo y a su Dios. Booz reconoce su conducta y actúa con protección más allá del mínimo legal.',
   'El capítulo inicial desciende hacia amargura y vacío; el segundo introduce encuentros, alimento y esperanza sin negar el duelo previo.',
   'Presentar la lealtad de Rut y la generosidad de Booz como respuestas humanas responsables dentro de una situación donde la providencia no elimina la necesidad de trabajar y proteger.',
   'La esperanza puede comenzar con decisiones pequeñas: acompañar, compartir recursos y crear condiciones seguras para quien se encuentra vulnerable.',
   'La frase de Rut se usa frecuentemente en bodas, pero su contexto principal es la lealtad de una nuera viuda hacia otra viuda. No debe borrarse el duelo ni romantizarse la precariedad.',
   ARRAY['duelo','lealtad','espigueo','Booz','providencia']::text[],
   ARRAY['moabitas','habitantes de Belén']::text[],
   ARRAY['Moab','Belén']::text[]),
  ('rut-3-4-redencion','RUT','section',3,NULL::smallint,4,NULL::smallint,
   'Petición, rescate familiar y genealogía',
   'Rut solicita protección a Booz, quien sigue un proceso público ante un pariente con prioridad, adquiere responsabilidades familiares y se casa con Rut.',
   'La puerta de la ciudad funcionaba como lugar de transacciones y testimonio público. Las costumbres de rescate de propiedad y preservación familiar se combinan de manera particular.',
   'Booz actúa como goel, aunque el relato no reproduce exactamente todas las disposiciones del levirato. La genealogía conecta a Obed con David.',
   'Una escena nocturna ambigua es seguida por un procedimiento legal público, bendiciones comunitarias, nacimiento y genealogía.',
   'Mostrar que la iniciativa de Rut y Noemí debe acompañarse de integridad, transparencia y responsabilidad legal por parte de Booz.',
   'La redención se vuelve visible cuando el poder se utiliza para proteger y restaurar, no para explotar la vulnerabilidad de otra persona.',
   'La escena de la era contiene lenguaje e implicaciones debatidas y no debe describirse con certeza más allá del texto. Tampoco debe presentarse a Booz como comprador de una mujer; el relato entrelaza propiedad, familia y matrimonio dentro de una cultura antigua.',
   ARRAY['goel','era','puerta de la ciudad','Obed','David','redención']::text[],
   ARRAY['moabitas','ancianos de Belén']::text[],
   ARRAY['Belén']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select
  data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/historicos/v1#' || data.slug,
  'historicos-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','historical-books','generated_by_ai',false,'review_level','editorial')
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();