-- FASE D · Bloque 4 · Profetas mayores 3: Ezequiel y Daniel
update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code in ('EZK','DAN');

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('ezequiel-perfil','EZK','book',1,NULL::smallint,48,NULL::smallint,
   'Ezequiel: gloria, responsabilidad, exilio y restauración',
   'Ezequiel ministra entre exiliados en Babilonia, interpreta la caída de Jerusalén, confronta idolatría y liderazgo, afirma responsabilidad personal y anuncia un corazón nuevo, un pueblo vivificado y una presencia restaurada.',
   'Ezequiel fue sacerdote y profeta entre deportados después de 597 a. C. Sus fechas se relacionan con el exilio de Joaquín, el sitio y la destrucción de Jerusalén y la reorganización de comunidades en Babilonia.',
   'El libro forma parte de los Profetas y contiene visiones cuya lectura fue tratada con cautela en tradición rabínica, especialmente la carroza divina y el templo final. La gloria puede acompañar al pueblo fuera de la tierra.',
   'Visiones, acciones simbólicas, alegorías, disputas y oráculos están organizados alrededor de la caída de Jerusalén: juicio antes de la noticia y restauración después de ella.',
   'Mostrar que Dios no está limitado al templo, que cada generación debe responder por sus decisiones y que la restauración requiere transformación interior, justicia y presencia.',
   'La pérdida de estructuras conocidas no significa ausencia divina. Un corazón renovado permite asumir responsabilidad sin quedar atrapado en culpa heredada o desesperanza.',
   'Las acciones simbólicas y visiones no deben imitarse literalmente ni emplearse para diagnosticar experiencias psicológicas. Las alegorías con lenguaje sexualizado requieren sensibilidad y no deben usarse para avergonzar a mujeres o víctimas de violencia.',
   ARRAY['Ezequiel','gloria','exilio','responsabilidad','corazón nuevo','Espíritu','templo']::text[],
   ARRAY['exiliados judíos','habitantes de Jerusalén','babilonios','sacerdotes']::text[],
   ARRAY['Babilonia','río Quebar','Jerusalén','templo']::text[]),
  ('ezequiel-1-11-gloria-juicio','EZK','section',1,NULL::smallint,11,NULL::smallint,
   'Llamado, carroza divina y salida de la gloria',
   'Ezequiel contempla una visión de seres vivientes y una plataforma móvil, recibe su llamado, realiza señales y ve prácticas corruptas en Jerusalén mientras la gloria abandona el templo.',
   'Los exiliados podían pensar que la presencia divina estaba limitada a Jerusalén. La visión usa imágenes imperiales y cósmicas para afirmar movilidad y soberanía en Babilonia.',
   'La visión de la merkavá fue objeto de interpretación mística posterior, pero su función inicial es sostener la presencia de Dios junto a los exiliados y denunciar el templo profanado.',
   'La visión inaugural domina el lenguaje del libro. Acciones simbólicas y recorridos por el templo culminan en una salida gradual de la gloria.',
   'Afirmar que la presencia divina no pertenece a una institución corrupta ni a un territorio exclusivo y que la santidad confronta prácticas ocultas detrás de símbolos religiosos.',
   'Dios puede encontrarse en desplazamiento y pérdida. La fidelidad institucional exige transparencia, porque un edificio sagrado no protege la injusticia.',
   'Las ruedas, ojos y seres vivientes son simbolismo visionario y no una descripción tecnológica. La merkavá y la Cábala son lecturas posteriores, no pruebas de poderes sobrenaturales utilizables.',
   ARRAY['merkavá','gloria','seres vivientes','templo','exilio','llamado']::text[],
   ARRAY['exiliados','sacerdotes','líderes de Jerusalén']::text[],
   ARRAY['río Quebar','Jerusalén','templo']::text[]),
  ('ezequiel-12-24-caida','EZK','section',12,NULL::smallint,24,NULL::smallint,
   'Responsabilidad, pastores falsos y certeza de la caída',
   'Acciones y parábolas confrontan falsos mensajes de paz, explican responsabilidad individual y colectiva y anuncian que Jerusalén no evitará la caída.',
   'Los exiliados recibían noticias y discursos contradictorios desde Judá. La demora aparente podía alimentar la expectativa de un retorno rápido.',
   'Ezequiel 18 rechaza el uso del proverbio sobre padres e hijos como excusa fatalista. Cada persona y generación puede volver y vivir.',
   'Proverbios, alegorías, listas históricas y disputas repiten la certeza del juicio. El capítulo 24 marca el inicio del sitio y una pérdida personal del profeta.',
   'Romper el fatalismo, confrontar liderazgo que promete seguridad falsa y llamar a una respuesta presente antes de que las consecuencias sean irreversibles.',
   'Nadie está condenado únicamente por la historia familiar. La responsabilidad personal abre espacio para cambio, aunque no borra efectos sociales heredados.',
   'Las alegorías de capítulos 16 y 23 contienen lenguaje humillante y no deben usarse para estigmatizar sexualidad femenina ni describirse de forma explícita. La pérdida de la esposa del profeta no debe convertirse en modelo para reprimir el duelo.',
   ARRAY['responsabilidad','arrepentimiento','falsos profetas','Jerusalén','sitio','pastores']::text[],
   ARRAY['exiliados','habitantes de Jerusalén','profetas','líderes']::text[],
   ARRAY['Babilonia','Jerusalén']::text[]),
  ('ezequiel-25-32-naciones','EZK','section',25,NULL::smallint,32,NULL::smallint,
   'Oráculos contra poderes vecinos',
   'Amón, Moab, Edom, Filistea, Tiro, Sidón y Egipto son confrontados por aprovechar la caída de Judá, ejercer orgullo comercial o confiar en poder imperial.',
   'Tiro era un centro marítimo y Egipto una potencia en declive frente a Babilonia. Los oráculos reflejan competencia regional y economía internacional.',
   'El lenguaje sobre el rey de Tiro fue aplicado posteriormente a Satanás en algunas tradiciones, pero el horizonte inmediato es un gobernante humano y su orgullo.',
   'Lamentos comerciales, imágenes de barcos, árboles y descenso al mundo de los muertos forman una colección de juicio contra imperios.',
   'Mostrar que aprovechar la desgracia ajena y convertir riqueza o poder en divinidad conduce a pérdida, y que ninguna nación queda fuera de evaluación moral.',
   'La prosperidad puede ocultar dependencia y vulnerabilidad. El duelo por una ciudad enemiga reconoce humanidad incluso dentro del juicio.',
   'Ezequiel 28 no debe presentarse como biografía segura del diablo sin explicar su referencia al gobernante de Tiro y sus relecturas posteriores. Las naciones antiguas no equivalen directamente a estados modernos.',
   ARRAY['Tiro','Egipto','orgullo','comercio','naciones','imperio']::text[],
   ARRAY['amonitas','moabitas','edomitas','filisteos','fenicios','egipcios']::text[],
   ARRAY['Tiro','Sidón','Egipto','Edom']::text[]),
  ('ezequiel-33-39-restauracion','EZK','section',33,NULL::smallint,39,NULL::smallint,
   'Vigilante, pastores, corazón nuevo y valle de huesos',
   'Después de conocerse la caída, Ezequiel renueva su llamado como vigilante, denuncia pastores abusivos y anuncia un pastor davídico, un corazón nuevo, el valle vivificado y la reunificación del pueblo.',
   'La destrucción transformó a los exiliados de minoría desplazada en supervivientes de una nación sin capital ni templo. La restauración debía imaginarse más allá de estructuras perdidas.',
   'El valle de huesos representa primero a la casa de Israel que declara perdida su esperanza. Gog y Magog simbolizan una amenaza final contra la comunidad restaurada y recibieron numerosas relecturas apocalípticas.',
   'Discursos pastorales, promesas de purificación, una gran visión de resurrección nacional y oráculos contra Gog forman una secuencia de reconstrucción de identidad.',
   'Afirmar que Dios confronta líderes que se alimentan del rebaño, restaura personas sin esperanza y puede reunir comunidades fragmentadas.',
   'La renovación espiritual incluye un corazón sensible, aliento para levantarse y liderazgo que sirve. Una comunidad dañada necesita más que regresar físicamente.',
   'El valle no debe reducirse exclusivamente a resurrección individual ni usarse para negar la realidad del trauma colectivo. Gog y Magog no deben identificarse con ligereza con países actuales.',
   ARRAY['vigilante','pastores','corazón nuevo','valle de huesos','Espíritu','Gog','reunificación']::text[],
   ARRAY['exiliados','casa de Israel','líderes']::text[],
   ARRAY['Israel','montañas de Israel']::text[]),
  ('ezequiel-40-48-templo','EZK','section',40,NULL::smallint,48,NULL::smallint,
   'Visión del templo, la tierra y el río de vida',
   'Una visión detallada presenta un templo, culto, distribución territorial y un río que transforma el paisaje, concluyendo con la ciudad llamada «YHWH está allí».',
   'La visión surge después de la destrucción del primer templo. Sus medidas y organización no coinciden plenamente con los templos históricos conocidos y funcionan como ideal de santidad y orden restaurado.',
   'La tradición debate si el templo es plano futuro, ideal simbólico o visión cultual. El río y la nueva distribución destacan presencia, vida y pertenencia, incluyendo al extranjero residente.',
   'Un recorrido guiado por medidas conduce desde la estructura hacia altar, gloria, tierra y agua vivificante. El final revierte la salida de la gloria en capítulos 10–11.',
   'Imaginar una restauración donde la presencia regresa, el liderazgo tiene límites, la tierra se distribuye y la vida fluye hacia espacios estériles.',
   'La esperanza necesita estructuras que protejan santidad y justicia, pero su centro no es la arquitectura sino la presencia que da vida.',
   'Las medidas no deben utilizarse para fijar fechas ni exigir una reconstrucción política moderna. Los sacrificios en la visión plantean debates dentro de interpretaciones cristianas y deben reconocerse sin armonización forzada.',
   ARRAY['templo','gloria','río','tierra','extranjero','presencia','santidad']::text[],
   ARRAY['Israel','sacerdotes','levitas','extranjeros residentes']::text[],
   ARRAY['Jerusalén','templo','mar Muerto']::text[]),
  ('daniel-perfil','DAN','book',1,NULL::smallint,12,NULL::smallint,
   'Daniel: fidelidad en imperios y esperanza apocalíptica',
   'Daniel combina relatos de judíos que sirven dentro de cortes extranjeras con visiones simbólicas sobre imperios, persecución, juicio y el reino duradero de Dios.',
   'Los relatos se sitúan en Babilonia y Persia, mientras varias visiones reflejan con especial detalle conflictos del periodo helenístico y la persecución de Antíoco IV. El libro utiliza hebreo y arameo.',
   'Daniel pertenece a los Escritos en el Tanaj, no a la sección de Profetas. Sus prácticas de oración, alimentación y fidelidad influyeron profundamente en comunidades judías bajo dominio extranjero.',
   'Los capítulos 1–6 son relatos cortesanos en tercera persona; 7–12 contienen visiones en primera persona. Los idiomas forman una estructura entrelazada y los símbolos reutilizan imágenes bíblicas y regionales.',
   'Enseñar que es posible servir con integridad dentro de sistemas imperiales sin adorarlos, y sostener a comunidades perseguidas mediante la certeza de que los imperios no son eternos.',
   'La fidelidad combina sabiduría, límites, oración y solidaridad. La esperanza apocalíptica ayuda a resistir sin atribuir poder definitivo a gobernantes violentos.',
   'Las bestias y números no deben convertirse en identificaciones seguras de políticos actuales ni calendarios del fin. La fecha de composición, la figura de Darío el medo y la relación entre horizonte babilónico y helenístico son debatidas.',
   ARRAY['Daniel','Babilonia','imperio','reino de Dios','bestias','Hijo de hombre','resurrección']::text[],
   ARRAY['judíos de la diáspora','babilonios','persas','griegos']::text[],
   ARRAY['Jerusalén','Babilonia','Susa','Persia']::text[]),
  ('daniel-1-6-corte','DAN','section',1,NULL::smallint,6,NULL::smallint,
   'Fidelidad y sabiduría en las cortes imperiales',
   'Daniel y sus compañeros preservan identidad, interpretan sueños, rechazan adoración imperial y sobreviven a decretos que convierten lealtad política en culto.',
   'Las cortes antiguas formaban funcionarios en lengua y literatura imperial. Los relatos usan nombres reales, banquetes, decretos y ascensos para mostrar tensiones de la diáspora.',
   'Las prácticas alimentarias, la oración hacia Jerusalén y el rechazo de imágenes expresan límites de asimilación. Los relatos fueron modelos de fidelidad para comunidades judías posteriores.',
   'Cada relato presenta una crisis, una negativa o incapacidad imperial, intervención de los sabios judíos y reconocimiento temporal de la soberanía divina.',
   'Mostrar que integrarse profesionalmente no requiere entregar la conciencia y que la autoridad humana pierde legitimidad cuando exige adoración o prohíbe oración.',
   'La fidelidad puede ser respetuosa y firme. Establecer límites antes de una crisis ayuda a responder sin improvisar cuando llega presión.',
   'La dieta de Daniel no es un plan universal de salud ni garantía de apariencia. Los relatos de liberación no prometen que toda persona fiel evitará daño, y no autorizan desafiar peligros innecesarios para probar a Dios.',
   ARRAY['dieta','sueños','estatua','horno','oración','foso de leones','fidelidad']::text[],
   ARRAY['judíos de la diáspora','babilonios','persas','funcionarios']::text[],
   ARRAY['Babilonia','Jerusalén']::text[]),
  ('daniel-7-9-visiones','DAN','section',7,NULL::smallint,9,NULL::smallint,
   'Bestias, Hijo de hombre y oración por restauración',
   'Daniel ve cuatro bestias, un tribunal celestial y una figura humana que recibe dominio; después visiones sobre imperios y una oración basada en Jeremías conducen a la compleja profecía de las semanas.',
   'Las bestias representan poderes imperiales. La visión del carnero y el macho cabrío se relaciona explícitamente con medos, persas y griegos, y la profanación refleja conflictos helenísticos.',
   'La figura «como hijo de hombre» puede representar al pueblo santo y también fue desarrollada individual y mesiánicamente en interpretaciones posteriores. La oración de Daniel asume responsabilidad comunitaria sin negar la fidelidad divina.',
   'Símbolos animales, escenas judiciales, interpretación angelical y una larga oración forman un movimiento desde terror hacia petición y esperanza.',
   'Deshumanizar el imperio al mostrarlo como bestia y afirmar que el dominio final pertenece a una forma humana de gobierno bajo Dios.',
   'La oración puede unir estudio de Escritura, confesión colectiva y esperanza. Reconocer pecado comunitario no obliga a aceptar culpa por acciones no cometidas personalmente.',
   'Las setenta semanas poseen múltiples interpretaciones judías y cristianas; no deben presentarse como una cronología indiscutible ni usarse para fijar fechas. «Hijo de hombre» requiere distinguir sentido de Daniel y usos posteriores.',
   ARRAY['cuatro bestias','Anciano de días','Hijo de hombre','setenta semanas','oración','imperios']::text[],
   ARRAY['santos','medos','persas','griegos','judíos']::text[],
   ARRAY['Babilonia','Susa','Jerusalén']::text[]),
  ('daniel-10-12-conflicto-esperanza','DAN','section',10,NULL::smallint,12,NULL::smallint,
   'Conflicto imperial, persecución y esperanza de resurrección',
   'Una última visión describe conflictos entre reinos del norte y sur, una persecución intensa, intervención de Miguel y una esperanza explícita de resurrección y vindicación.',
   'El detalle de las guerras se corresponde ampliamente con dinastías seléucidas y ptolemaicas y culmina en la opresión de Antíoco IV en el siglo II a. C.',
   'Miguel aparece como protector celestial de Israel. Daniel 12 es uno de los testimonios más claros del Tanaj sobre resurrección de muchos y vida perdurable.',
   'Una introducción visionaria conduce a una revisión simbólica de guerras históricas y termina con tiempos cifrados, sellamiento y descanso del profeta.',
   'Sostener a una comunidad perseguida afirmando que la violencia imperial tiene límite y que la fidelidad y la justicia recibirán vindicación más allá de la muerte.',
   'No comprender cada detalle no impide permanecer fiel. La esperanza futura debe fortalecer perseverancia y sabiduría, no alimentar obsesión o miedo.',
   'Los reyes del norte y sur no deben identificarse directamente con potencias actuales. Los números 1,290 y 1,335 días no autorizan fijar fechas del fin ni vender certeza profética.',
   ARRAY['rey del norte','rey del sur','Miguel','persecución','resurrección','tiempos']::text[],
   ARRAY['judíos perseguidos','seléucidas','ptolemeos']::text[],
   ARRAY['Persia','Grecia','Jerusalén']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/profetas-mayores/v1#' || data.slug,
  'profetas-mayores-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','major-prophets','generated_by_ai',false,'review_level','editorial')
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();