-- FASE D · Bloque 4 · Profetas mayores 3: Ezequiel
update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code = 'EZK';

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('ezequiel-perfil','EZK','book',1,NULL::smallint,48,NULL::smallint,
   'Ezequiel: presencia divina, responsabilidad y restauración en el exilio',
   'Ezequiel combina visiones, acciones simbólicas, oráculos y diseños de restauración dirigidos a una comunidad deportada que debe comprender la caída de Jerusalén y reconstruir su identidad lejos del templo.',
   'Ezequiel fue sacerdote y profeta entre deportados en Babilonia después de 597 a. C. Sus mensajes atraviesan los años previos y posteriores a la destrucción de Jerusalén en 587/586 a. C.',
   'En la tradición judía, las visiones del carro y del templo fueron tratadas con especial reverencia. El libro sostiene que la presencia de Dios puede acompañar al pueblo fuera de la tierra y del santuario destruido.',
   'La estructura avanza desde juicio sobre Jerusalén hacia oráculos sobre naciones, responsabilidad renovada, restauración de Israel y una visión final de tierra, templo y río vivificador.',
   'Explicar la catástrofe sin declarar ausente a Dios, desplazar la responsabilidad hacia cada generación y sostener que una comunidad devastada puede recibir un corazón y un espíritu renovados.',
   'La presencia divina no depende de un edificio. La responsabilidad personal y comunitaria abre espacio para cambio, memoria, justicia y nueva vida.',
   'Las acciones simbólicas y metáforas corporales no deben imitarse literalmente ni utilizarse para justificar coerción. Algunas imágenes matrimoniales y violentas requieren lenguaje pastoral cuidadoso y no deben reproducirse de forma gráfica.',
   ARRAY['Ezequiel','gloria','exilio','responsabilidad','corazón nuevo','espíritu','templo']::text[],
   ARRAY['judíos exiliados','babilonios','sacerdotes','pastores de Israel']::text[],
   ARRAY['Babilonia','río Quebar','Jerusalén','templo']::text[]),
  ('ezequiel-1-11-gloria-juicio','EZK','section',1,NULL::smallint,11,NULL::smallint,
   'Visión de la gloria y partida del templo',
   'Ezequiel recibe una visión de la gloria divina junto al río Quebar, es llamado como vigilante y contempla simbólicamente corrupción en Jerusalén y la partida de la gloria del templo.',
   'Los deportados vivían bajo administración babilónica y podían interpretar su distancia de Jerusalén como distancia de Dios. Las imágenes móviles responden a esa crisis geográfica y teológica.',
   'La visión del carro o merkavá tuvo gran impacto en la mística judía posterior, pero en su contexto primero afirma soberanía, movilidad y santidad divinas.',
   'Visión inaugural, rollo, acciones simbólicas y recorridos visionarios construyen una acusación progresiva contra la falsa seguridad del templo.',
   'Comunicar que la presencia de Dios alcanza el exilio y que una institución sagrada no puede proteger indefinidamente una comunidad que normaliza injusticia e idolatría.',
   'Dios puede encontrarse en lugares de desplazamiento. La pérdida de una estructura no significa necesariamente pérdida de toda posibilidad espiritual.',
   'Las criaturas, ruedas y ojos son lenguaje visionario, no diagramas mecánicos ni pruebas de tecnología antigua. La visión no autoriza especulación sensacionalista.',
   ARRAY['gloria','merkavá','vigilante','rollo','templo','exilio']::text[],
   ARRAY['exiliados judíos','habitantes de Jerusalén','sacerdotes']::text[],
   ARRAY['río Quebar','Babilonia','Jerusalén','templo']::text[]),
  ('ezequiel-12-24-signos-caida','EZK','section',12,NULL::smallint,24,NULL::smallint,
   'Signos proféticos y anuncio de la caída',
   'Acciones simbólicas, parábolas y acusaciones confrontan falsos profetas, liderazgo corrupto e infidelidad del pacto y anuncian que la caída de Jerusalén no será evitada por consignas optimistas.',
   'Mientras una parte del pueblo estaba deportada, Jerusalén seguía funcionando y algunos esperaban una pronta reversión. El avance babilónico hizo insostenible esa expectativa.',
   'El libro discute responsabilidad generacional y personal: cada persona responde por su camino, aunque viva dentro de consecuencias heredadas.',
   'Alegorías de vid, águilas, hermanas y olla se alternan con disputas proverbiales y acciones del profeta.',
   'Romper la negación colectiva y enseñar que la responsabilidad presente no puede delegarse completamente a antepasados, líderes o circunstancias.',
   'Reconocer consecuencias heredadas no elimina capacidad moral. Un cambio real empieza cuando se abandona la excusa y se busca un corazón distinto.',
   'Las alegorías de Ezequiel 16 y 23 contienen lenguaje sexualizado y violento que no debe reproducirse explícitamente ni utilizarse para humillar a mujeres o justificar abuso. El duelo del profeta no es una prohibición universal de expresar dolor.',
   ARRAY['acciones simbólicas','falsos profetas','responsabilidad','corazón','caída']::text[],
   ARRAY['exiliados','habitantes de Jerusalén','profetas','ancianos']::text[],
   ARRAY['Babilonia','Jerusalén']::text[]),
  ('ezequiel-25-32-naciones','EZK','section',25,NULL::smallint,32,NULL::smallint,
   'Oráculos contra naciones y orgullo imperial',
   'Ezequiel dirige oráculos contra Amón, Moab, Edom, Filistea, Tiro, Sidón y Egipto, denunciando violencia, explotación, orgullo comercial y confianza imperial.',
   'Tiro era un centro marítimo y comercial; Egipto seguía siendo una potencia regional. Las alianzas y rivalidades con Judá formaban parte de la política del antiguo Cercano Oriente.',
   'El juicio sobre vecinos e imperios afirma que la responsabilidad moral no termina en las fronteras de Israel. Las imágenes de Edén y monstruos acuáticos releen símbolos antiguos.',
   'Lamentos sobre reyes y ciudades usan hipérbole poética, listas comerciales y descensos al Seol para representar la caída del poder.',
   'Desenmascarar sistemas que convierten riqueza, comercio y fuerza militar en divinidad y mostrar que la grandeza no elimina responsabilidad.',
   'El éxito económico y político no es una medida suficiente de justicia. Una comunidad puede admirar capacidad y, al mismo tiempo, evaluar su costo humano.',
   'Los gobernantes de Tiro y Egipto no deben identificarse automáticamente con Satanás; las lecturas posteriores son interpretaciones teológicas, no el único sentido histórico. Los pueblos antiguos no equivalen directamente a estados modernos.',
   ARRAY['Tiro','Egipto','comercio','orgullo','naciones','Seol']::text[],
   ARRAY['amonitas','moabitas','edomitas','filisteos','fenicios','egipcios']::text[],
   ARRAY['Tiro','Sidón','Egipto','Edom','Filistea']::text[]),
  ('ezequiel-33-39-restauracion','EZK','section',33,NULL::smallint,39,NULL::smallint,
   'Vigilante, pastores, corazón nuevo y valle de huesos',
   'Después de confirmarse la caída de Jerusalén, el tono cambia hacia responsabilidad, crítica a pastores, restauración de la tierra, un corazón nuevo, el valle de huesos y la reunificación de Israel.',
   'La noticia de la destrucción transformó a la comunidad exiliada. Ya no se trataba de evitar el desastre, sino de construir identidad y futuro después de él.',
   'El valle de huesos representa primero la restauración nacional de una comunidad que se considera sin esperanza. La imagen de David como pastor sostiene expectativa de liderazgo justo.',
   'Discursos de vigilancia y responsabilidad conducen a metáforas pastorales, promesas de limpieza y una gran visión de resurrección colectiva.',
   'Mover a la comunidad desde culpa paralizante hacia responsabilidad y esperanza, y afirmar que la restauración requiere liderazgo distinto y transformación interior.',
   'Dios puede llamar vida a situaciones comunitarias que parecen terminadas. La esperanza no niega el exilio, sino que reabre posibilidades de pertenencia y servicio.',
   'Ezequiel 36 no debe usarse para afirmar superioridad étnica ni prosperidad territorial automática. El valle de huesos no fue escrito originalmente como descripción anatómica de resurrección individual, aunque recibió lecturas posteriores. Gog no debe identificarse sin evidencia con una nación contemporánea.',
   ARRAY['vigilante','pastores','corazón nuevo','espíritu nuevo','huesos secos','David','Gog']::text[],
   ARRAY['exiliados de Israel','pastores de Israel','naciones']::text[],
   ARRAY['Babilonia','montes de Israel','valle']::text[]),
  ('ezequiel-40-48-templo-rio','EZK','section',40,NULL::smallint,48,NULL::smallint,
   'Visión del templo, la tierra y el río de vida',
   'Una extensa visión describe un templo medido, retorno de la gloria, orden del culto, distribución de la tierra y un río que transforma el paisaje hasta culminar en la ciudad llamada «YHWH está allí».',
   'La visión responde a una comunidad cuyo templo había sido destruido. Sus medidas y divisiones no coinciden de forma sencilla con el templo anterior ni con construcciones posteriores.',
   'Las interpretaciones judías y cristianas debaten si el diseño es ideal, simbólico, programático o futuro. El centro es la santidad de la presencia y una tierra reorganizada con espacio para extranjeros residentes.',
   'La precisión arquitectónica conduce gradualmente desde muros y cámaras hacia agua, árboles, sanidad y una nueva distribución tribal.',
   'Imaginar una comunidad restaurada donde presencia, culto, justicia territorial y vida ecológica vuelven a estar relacionadas.',
   'La restauración no consiste solo en reconstruir edificios; busca una forma de convivencia donde la presencia divina produzca orden, hospitalidad y vida abundante.',
   'Las medidas no deben convertirse en planos obligatorios ni en calendario profético. Las regulaciones sacrificiales requieren distinguir contexto sacerdotal, desarrollo histórico y lecturas cristianas posteriores.',
   ARRAY['templo','gloria','río','sanidad','tierra','extranjero','YHWH está allí']::text[],
   ARRAY['tribus de Israel','sacerdotes','levitas','extranjeros residentes']::text[],
   ARRAY['Jerusalén','templo','mar Muerto','tierra de Israel']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/profetas-mayores/v1#' || data.slug,
  'profetas-mayores-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object(
    'coverage_batch','major-prophets',
    'generated_by_ai',true,
    'review_level','ai_assisted_editorial',
    'human_review_status','pending'
  )
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();