-- FASE D · Bloque 4 · Lote histórico 2: Samuel y Reyes
update public.biblical_books
set metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('coverage_status', 'context_ready'),
    updated_at = now()
where code in ('1SA','2SA','1KI','2KI');

with source as (
  select id from public.biblical_sources where slug = 'vida-contexto-editorial'
),
data(
  slug, book_code, scope_kind, chapter_start, verse_start, chapter_end, verse_end,
  title, summary, historical_context, jewish_context, literary_context,
  authorial_intent, theological_reflection, interpretive_cautions,
  key_terms, people_groups, places
) as (
  values
  ('1-samuel-perfil','1SA','book',1,NULL::smallint,31,NULL::smallint,
   '1 Samuel: profecía, monarquía y discernimiento del liderazgo',
   '1 Samuel narra la transición desde los jueces hacia la monarquía mediante Samuel, Saúl y el ascenso de David, mostrando posibilidades y peligros del poder.',
   'El libro refleja una sociedad tribal bajo presión filistea, el surgimiento de instituciones monárquicas y tensiones entre autoridad profética, sacerdotal y real.',
   'Samuel es contado entre los Profetas Anteriores. La petición de un rey se evalúa de manera ambivalente: puede responder a una necesidad política, pero también expresar deseo de ser como las demás naciones.',
   'Tres trayectorias se entrelazan: Samuel crece mientras la casa de Elí declina; Saúl asciende y fracasa; David es ungido y espera mientras es perseguido.',
   'Examinar qué hace legítimo a un líder ante Dios: no apariencia, carisma ni éxito militar, sino escucha, obediencia, justicia y responsabilidad.',
   'El llamado y el don no sustituyen el carácter. La autoridad saludable acepta corrección, protege al vulnerable y no convierte la misión en defensa del propio ego.',
   'El libro no enseña que toda crítica al líder sea rebelión. Los episodios de guerra, espíritu dañino y consulta a la médium de Endor requieren análisis contextual; no deben usarse para diagnosticar enfermedades ni promover prácticas ocultistas.',
   ARRAY['Samuel','Saúl','David','monarquía','profecía','obediencia']::text[],
   ARRAY['israelitas','filisteos','amalecitas']::text[],
   ARRAY['Silo','Ramá','Gilgal','Gabaá','Belén']::text[]),
  ('1-samuel-1-7-samuel-arca','1SA','section',1,NULL::smallint,7,NULL::smallint,
   'Samuel, la casa de Elí y el arca',
   'Ana ora por un hijo, Samuel es dedicado al servicio, la casa de Elí es juzgada y el arca pasa por territorio filisteo antes de que Israel vuelva a buscar a Dios.',
   'Silo funcionaba como centro cultual antes del templo de Jerusalén. Los conflictos con los filisteos revelan presiones militares y competencia por símbolos de poder.',
   'La oración de Ana celebra una inversión de poder que anticipa temas del libro: Dios levanta al humilde y confronta al arrogante. El arca no puede ser manipulada como amuleto.',
   'Nacimiento, cántico, llamado profético, derrota militar y retorno del arca forman una secuencia en la que la palabra de Dios reemplaza la confianza supersticiosa.',
   'Mostrar que Dios escucha el dolor, confronta el abuso religioso y no permite que objetos sagrados sustituyan una relación de obediencia.',
   'La oración honesta puede incluir angustia profunda; el servicio espiritual exige integridad y la presencia de Dios no pertenece a ninguna institución humana.',
   'La esterilidad no debe explicarse como castigo personal. El pecado de los hijos de Elí no autoriza generalizar contra todas las familias pastorales, y el arca no debe compararse con objetos religiosos modernos de forma simplista.',
   ARRAY['Ana','Samuel','Elí','arca','Silo','oración']::text[],
   ARRAY['israelitas','filisteos','sacerdotes']::text[],
   ARRAY['Silo','Asdod','Ecrón','Quiriat-jearim']::text[]),
  ('1-samuel-8-15-saul','1SA','section',8,NULL::smallint,15,NULL::smallint,
   'La petición de rey y el fracaso de Saúl',
   'Israel pide un rey, Saúl es escogido y confirmado, obtiene victorias, pero decisiones impulsivas y desobediencia deterioran su liderazgo.',
   'La monarquía ofrecía coordinación militar y administrativa, pero también impuestos, reclutamiento, confiscación y centralización del poder, riesgos denunciados por Samuel.',
   'La tradición conserva tanto la legitimación de Saúl como la crítica a la monarquía. El mandato contra Amalec pertenece a una memoria antigua de guerra y juicio que plantea serias preguntas éticas.',
   'La narración alterna versiones de la elección de Saúl y luego contrasta su apariencia prometedora con su incapacidad para escuchar y asumir responsabilidad.',
   'Enseñar que el poder solicitado para resolver inseguridad puede crear nuevas opresiones, y que obedecer no equivale a conservar una imagen pública religiosa.',
   'El liderazgo requiere reconocer errores sin culpar al pueblo ni usar el culto para encubrir decisiones. La humildad inicial debe sostenerse mediante rendición de cuentas.',
   '«Obedecer es mejor que sacrificar» no debe usarse para exigir sumisión ciega a líderes humanos. El relato de Amalec no autoriza genocidio moderno ni violencia religiosa.',
   ARRAY['rey','Saúl','Samuel','obediencia','Amalec','sacrificio']::text[],
   ARRAY['israelitas','amonitas','filisteos','amalecitas']::text[],
   ARRAY['Ramá','Mizpa','Gilgal','Gabaá']::text[]),
  ('1-samuel-16-31-david-saul','1SA','section',16,NULL::smallint,31,NULL::smallint,
   'David, Saúl y la espera bajo persecución',
   'David es ungido, vence a Goliat, sirve en la corte, establece amistad con Jonatán y huye de Saúl, mientras evita tomar el poder mediante violencia directa contra el rey.',
   'El servicio cortesano, las bandas armadas, los matrimonios políticos y los refugios fronterizos reflejan una monarquía temprana todavía inestable.',
   'La elección de David enfatiza que Dios no juzga únicamente por apariencia. La amistad con Jonatán y los lamentos posteriores ocupan un lugar importante en la memoria de lealtad.',
   'El ascenso público de David corre en paralelo con la caída psicológica y política de Saúl. Escenas repetidas de persecución y perdón demoran deliberadamente la llegada de David al trono.',
   'Mostrar que una promesa no justifica apresurar el poder por medios corruptos y que la verdadera valentía incluye dominio propio, lealtad y espera.',
   'No toda oportunidad es autorización. La persona herida por un líder puede mantener límites, buscar seguridad y negarse a reproducir el mismo abuso.',
   'La angustia de Saúl no debe reducirse a posesión demoníaca ni utilizarse para estigmatizar enfermedad mental. David tampoco debe idealizarse ignorando decisiones ambiguas entre los filisteos.',
   ARRAY['David','Goliat','Jonatán','Saúl','unción','espera']::text[],
   ARRAY['israelitas','filisteos']::text[],
   ARRAY['Belén','Gabaá','Nob','En-gadi','Gat']::text[]),
  ('2-samuel-perfil','2SA','book',1,NULL::smallint,24,NULL::smallint,
   '2 Samuel: reino de David, pacto y consecuencias del poder',
   '2 Samuel presenta la consolidación del reino de David, la promesa dinástica, sus victorias y el colapso familiar y político que sigue a su abuso contra Betsabé y Urías.',
   'La unificación de tribus, la captura de Jerusalén, la administración real y las rebeliones internas reflejan la formación de un estado territorial en el antiguo Levante.',
   'La promesa a la casa de David se vuelve central para la esperanza bíblica, pero el libro conserva una crítica severa al rey y no oculta su pecado ni sus consecuencias.',
   'Una primera mitad de ascenso y estabilidad se quiebra en el capítulo 11. Desde allí, conflictos familiares, rebeliones y violencia responden narrativamente al abuso del rey.',
   'Afirmar la fidelidad del pacto sin convertirla en inmunidad para el gobernante; el mismo rey ungido permanece bajo la palabra profética y la justicia.',
   'La gracia no borra responsabilidad ni consecuencias. El poder debe proteger, y cuando explota a otra persona necesita verdad, arrepentimiento y reparación.',
   'David no debe presentarse como modelo perfecto ni Betsabé como seductora; el texto subraya la iniciativa y autoridad del rey. Las guerras y ejecuciones no son automáticamente aprobadas por el narrador.',
   ARRAY['David','Jerusalén','pacto davídico','Betsabé','Natán','Absalón']::text[],
   ARRAY['israelitas','filisteos','amonitas','arameos']::text[],
   ARRAY['Hebrón','Jerusalén','Rabá','Mahánayim']::text[]),
  ('2-samuel-1-10-reino','2SA','section',1,NULL::smallint,10,NULL::smallint,
   'Consolidación del reino y promesa a la casa de David',
   'David lamenta a Saúl y Jonatán, reina primero en Hebrón, unifica las tribus, establece Jerusalén, lleva el arca y recibe una promesa dinástica.',
   'Jerusalén ofrecía una capital situada fuera de los centros tribales principales. Las alianzas, campañas y administración fortalecieron una monarquía en expansión.',
   'El traslado del arca vincula reino y culto, mientras 2 Samuel 7 distingue entre la casa que David desea construir y la casa dinástica que Dios promete establecer.',
   'Lamentos, relatos de guerra, celebración cultual y un oráculo de pacto construyen la imagen de una monarquía legitimada pero dependiente de Dios.',
   'Mostrar que el reino se recibe como encargo, que el culto no puede controlarse y que la promesa divina excede los proyectos personales del rey.',
   'La gratitud por una responsabilidad recibida debe producir humildad, memoria y cuidado concreto, como se ve en la bondad de David hacia Mefiboset.',
   'El episodio de Uza no debe usarse para producir miedo supersticioso. La danza de David no resuelve por sí sola el complejo conflicto con Mical, que debe leerse con sensibilidad hacia su historia y posición.',
   ARRAY['Hebrón','Jerusalén','arca','pacto davídico','Mefiboset']::text[],
   ARRAY['judíos','tribus de Israel','filisteos']::text[],
   ARRAY['Hebrón','Jerusalén']::text[]),
  ('2-samuel-11-20-crisis','2SA','section',11,NULL::smallint,20,NULL::smallint,
   'Abuso de David y crisis de la casa real',
   'David toma a Betsabé, organiza la muerte de Urías y es confrontado por Natán; después su familia atraviesa violencia sexual, asesinato, rebelión y guerra interna.',
   'El rey concentraba capacidad militar, judicial y doméstica. Esa asimetría de poder es esencial para entender la responsabilidad de David y la vulnerabilidad de quienes le rodeaban.',
   'La parábola de Natán permite que el rey pronuncie juicio antes de reconocerse a sí mismo. Tamar y otras personas heridas obligan a leer la historia desde las víctimas, no solo desde la dinastía.',
   'El capítulo 11 funciona como punto de quiebre. A partir de allí, palabras como tomar, enviar y espada reaparecen en consecuencias familiares y políticas.',
   'Denunciar el abuso de poder y mostrar que la confesión no vuelve inexistente el daño causado ni exime al liderazgo de afrontar consecuencias.',
   'El arrepentimiento verdadero necesita escuchar a quienes sufrieron, nombrar el mal sin eufemismos y abandonar la protección de reputaciones por encima de personas.',
   'Betsabé no dio consentimiento en condiciones de poder equivalentes y no debe ser culpada. La violación de Tamar no debe convertirse en detalle secundario de una historia sobre Absalón; exige reconocimiento explícito de la víctima y del fracaso de quienes callaron.',
   ARRAY['Betsabé','Urías','Natán','Tamar','Amnón','Absalón','abuso de poder']::text[],
   ARRAY['casa de David','amonitas','israelitas']::text[],
   ARRAY['Jerusalén','Rabá','Mahánayim']::text[]),
  ('2-samuel-21-24-apendices','2SA','section',21,NULL::smallint,24,NULL::smallint,
   'Memoria, cánticos, guerreros y el censo',
   'Una colección final reúne hambre y reparación con gabaonitas, guerras, un cántico, últimas palabras, listas de guerreros y el censo que conduce a una plaga y a la compra de una era.',
   'Los apéndices preservan memorias de distintas etapas del reinado y conectan violencia pasada, responsabilidad colectiva, culto y el lugar futuro del templo.',
   'El cántico reaparece en Salmos, y la era de Arauna queda vinculada en la tradición con el lugar del templo. Los relatos también mantienen preguntas difíciles sobre justicia intergeneracional.',
   'La estructura no sigue una cronología simple; organiza materiales alrededor de violencia, oración, guerreros y altar, creando un cierre teológico del reinado.',
   'Mostrar que incluso al final del reinado permanecen deudas históricas, necesidad de justicia y dependencia de misericordia.',
   'Una vida de liderazgo debe terminar reconociendo tanto gratitud como daño pendiente. La adoración responsable no busca ofrecer a Dios algo que no cueste nada.',
   'La entrega de descendientes de Saúl a los gabaonitas es moralmente compleja y no prescribe justicia moderna. El censo posee explicaciones textuales distintas y no debe usarse para condenar toda planificación o estadística.',
   ARRAY['gabaonitas','cántico','guerreros','censo','Arauna','altar']::text[],
   ARRAY['israelitas','gabaonitas','filisteos']::text[],
   ARRAY['Jerusalén','era de Arauna']::text[]),
  ('1-reyes-perfil','1KI','book',1,NULL::smallint,22,NULL::smallint,
   '1 Reyes: templo, sabiduría y división del reino',
   '1 Reyes narra la sucesión de Salomón, la construcción del templo, el esplendor y fracaso de su reinado, la división del reino y el conflicto profético durante la casa de Acab.',
   'El libro refleja administración imperial, proyectos de construcción, comercio, trabajo forzado, alianzas matrimoniales y la división política entre Israel y Judá.',
   'Forma parte de los Profetas Anteriores y evalúa a los reyes según fidelidad a la Torá y al culto. El templo es central, pero no puede proteger a una nación injusta.',
   'El esplendor de Salomón se vuelve gradualmente advertencia; tras la división, fórmulas regias alternan con extensas narraciones proféticas de Elías.',
   'Evaluar la monarquía desde la alianza: sabiduría, culto y éxito pierden su sentido cuando se separan de justicia, lealtad y límites al poder.',
   'Los dones pueden convertirse en instrumentos de orgullo. La presencia de Dios no queda encerrada en edificios ni garantiza aprobación de sistemas opresivos.',
   'La riqueza de Salomón no debe usarse como promesa de prosperidad personal. Los relatos sobre otras religiones no autorizan hostilidad hacia sus practicantes actuales, y la sequía de Elías no debe manipularse como fórmula para controlar el clima.',
   ARRAY['Salomón','templo','sabiduría','reino dividido','Elías','Acab']::text[],
   ARRAY['israelitas','judíos','fenicios','arameos']::text[],
   ARRAY['Jerusalén','Samaria','Tiro','Carmelo']::text[]),
  ('1-reyes-1-11-salomon','1KI','section',1,NULL::smallint,11,NULL::smallint,
   'Salomón: sucesión, templo y contradicciones del esplendor',
   'Salomón asegura el trono, pide sabiduría, organiza el reino, construye el templo y recibe reconocimiento internacional, pero acumula poder, riqueza, matrimonios y cultos rivales.',
   'Los proyectos monumentales exigían impuestos, mano de obra y alianzas. La descripción del reino refleja aspiraciones imperiales y contactos comerciales amplios.',
   'La dedicación del templo reconoce que los cielos no pueden contener a Dios y pide atención también para el extranjero. La caída de Salomón se interpreta como división del corazón.',
   'La unidad asciende desde la sabiduría hasta la gloria del templo y la visita de la reina de Sabá, pero concluye con una evaluación crítica que anticipa la división.',
   'Mostrar que la sabiduría debe gobernar también los deseos y estructuras del propio líder; el éxito externo no compensa la infidelidad interna.',
   'La oración por discernimiento sigue siendo valiosa, pero necesita acompañarse de límites, justicia laboral y fidelidad sostenida cuando aumenta la influencia.',
   'La cantidad de esposas pertenece a diplomacia real y no es modelo matrimonial. La afirmación de que mujeres extranjeras desviaron a Salomón no elimina su responsabilidad personal ni justifica xenofobia.',
   ARRAY['Salomón','sabiduría','templo','reina de Sabá','trabajo forzado','idolatría']::text[],
   ARRAY['israelitas','fenicios','pueblos vecinos']::text[],
   ARRAY['Jerusalén','Tiro','Ofir']::text[]),
  ('1-reyes-12-16-division','1KI','section',12,NULL::smallint,16,NULL::smallint,
   'División del reino y competencia por la lealtad',
   'La dureza de Roboam provoca la separación del norte; Jeroboam establece santuarios rivales y una sucesión inestable de reyes consolida dos reinos enfrentados.',
   'Tributos, trabajo forzado, rivalidades tribales y control de lugares de culto influyeron en la ruptura política. Israel y Judá desarrollaron dinastías y capitales diferentes.',
   'El libro critica los becerros de Betel y Dan como una política religiosa que busca impedir la peregrinación a Jerusalén. Los profetas desafían tanto al norte como al sur.',
   'Consejos opuestos, un discurso imprudente y fórmulas repetidas sobre reyes producen una narrativa acelerada de fragmentación.',
   'Advertir que ignorar el sufrimiento social y usar la religión para asegurar poder político puede dividir una comunidad durante generaciones.',
   'El liderazgo debe escuchar antes de aumentar cargas. La unidad auténtica no se conserva mediante amenazas ni control espiritual.',
   'El texto refleja la perspectiva teológica de Jerusalén y debe compararse con datos históricos sin negar esa orientación. Los becerros no deben confundirse simplistamente con una negación total de YHWH, sino con una representación y sistema cultual condenados por el narrador.',
   ARRAY['Roboam','Jeroboam','reino dividido','Betel','Dan','trabajo forzado']::text[],
   ARRAY['israelitas del norte','judíos']::text[],
   ARRAY['Siquem','Betel','Dan','Jerusalén','Samaria']::text[]),
  ('1-reyes-17-22-elias','1KI','section',17,NULL::smallint,22,NULL::smallint,
   'Elías, Acab y la disputa por justicia y lealtad',
   'Elías anuncia sequía, es sostenido junto con una viuda, confronta a los profetas de Baal, huye al Horeb y denuncia el asesinato y despojo de Nabot por la casa real.',
   'La alianza de Acab y Jezabel con Fenicia tuvo dimensiones políticas, económicas y religiosas. La propiedad ancestral de Nabot chocó con concepciones monárquicas de control territorial.',
   'El Carmelo dramatiza la pregunta por la lealtad, mientras Horeb corrige la expectativa de que Dios siempre actúe mediante espectáculo. Nabot representa la defensa de la herencia frente al poder.',
   'Milagros de provisión, confrontación pública, crisis personal y denuncia judicial presentan a Elías como profeta poderoso pero también vulnerable.',
   'Mostrar que Dios sostiene al extranjero vulnerable, confronta sistemas de idolatría y defiende la justicia cuando el poder intenta convertir la ley en herramienta de despojo.',
   'La persona fiel puede experimentar agotamiento después de una victoria. Escuchar, descansar y recibir nueva dirección también forman parte de la vida espiritual.',
   'El episodio del Carmelo no autoriza violencia religiosa ni pruebas públicas para obligar a Dios a actuar. Jezabel no debe convertirse en insulto contra mujeres; es una figura real específica dentro de una política de poder.',
   ARRAY['Elías','Acab','Jezabel','Baal','Horeb','Nabot','justicia']::text[],
   ARRAY['israelitas','fenicios','arameos']::text[],
   ARRAY['Querit','Sarepta','Carmelo','Horeb','Jezreel']::text[]),
  ('2-reyes-perfil','2KI','book',1,NULL::smallint,25,NULL::smallint,
   '2 Reyes: profecía, reforma, caída y exilio',
   '2 Reyes continúa las historias de Elías y Eliseo, sigue las dinastías de Israel y Judá, narra la caída de Samaria y culmina con la destrucción de Jerusalén y el exilio babilónico.',
   'Asiria y Babilonia dominan el escenario internacional. Inscripciones imperiales, campañas militares, tributos y deportaciones ayudan a situar numerosos acontecimientos del libro.',
   'El libro interpreta el exilio mediante el pacto y la voz profética, pero conserva también relatos de misericordia, reforma y una pequeña esperanza en la liberación final de Joaquín.',
   'Ciclos proféticos iniciales dan paso a una narración regia cada vez más marcada por amenazas imperiales. Dos caídas —Samaria y Jerusalén— estructuran el desenlace.',
   'Explicar que la injusticia, la idolatría y el rechazo persistente de corrección tienen consecuencias históricas, sin presentar el desastre como ausencia definitiva de esperanza.',
   'La fidelidad requiere escuchar advertencias antes de la crisis. Incluso después de la pérdida, la memoria, el arrepentimiento y pequeños signos de restauración mantienen abierta la historia.',
   'El exilio no debe usarse para afirmar que toda tragedia nacional es castigo directo identificable. Las deportaciones y guerras describen sufrimiento real y no deben romantizarse como simples lecciones espirituales.',
   ARRAY['Eliseo','Asiria','Babilonia','Samaria','Jerusalén','exilio','reforma']::text[],
   ARRAY['israelitas','judíos','asirios','babilonios','arameos']::text[],
   ARRAY['Samaria','Jerusalén','Damasco','Nínive','Babilonia']::text[]),
  ('2-reyes-1-8-eliseo','2KI','section',1,NULL::smallint,8,NULL::smallint,
   'Transición a Eliseo y señales en tiempos de crisis',
   'Elías es llevado, Eliseo recibe su manto y realiza señales de provisión, sanidad, protección y discernimiento en medio de guerras y hambre.',
   'Los grupos proféticos, conflictos arameos, deudas familiares y asedios muestran una sociedad vulnerable donde profecía y vida cotidiana se cruzan.',
   'Naamán, extranjero arameo, recibe sanidad y reconoce al Dios de Israel. Las historias subrayan que la misericordia puede cruzar fronteras nacionales.',
   'Una colección de relatos breves alterna necesidades domésticas y crisis políticas, mostrando una palabra profética presente tanto en hogares como en cortes.',
   'Presentar el ministerio profético como servicio que confronta reyes, protege comunidades y atiende a viudas, enfermos y extranjeros.',
   'La acción de Dios no depende de prestigio. La humildad para recibir una instrucción sencilla puede abrir un camino de sanidad y reconciliación.',
   'Las sanidades no deben convertirse en promesa de resultado inmediato para toda enfermedad. El relato de los osos y los jóvenes contiene dificultades de traducción y contexto y no autoriza violencia contra quienes se burlan.',
   ARRAY['Elías','Eliseo','Naamán','viuda','sanidad','Aram']::text[],
   ARRAY['israelitas','arameos','grupos proféticos']::text[],
   ARRAY['Jordán','Jericó','Sunem','Samaria','Damasco']::text[]),
  ('2-reyes-9-17-samaria','2KI','section',9,NULL::smallint,17,NULL::smallint,
   'Jehu, dinastías del norte y caída de Samaria',
   'Jehu destruye la casa de Acab y el culto de Baal, pero mantiene prácticas condenadas; después varias dinastías conducen al reino del norte hasta la conquista asiria.',
   'El siglo VIII a. C. estuvo marcado por expansión asiria, vasallaje, golpes de estado y deportaciones. La caída de Samaria ocurrió tras resistencia a ese imperio.',
   'La evaluación de Israel insiste en la mezcla de culto, injusticia y rechazo profético. Los samaritanos posteriores no deben reducirse sin matices al relato de poblaciones trasladadas.',
   'La violencia de Jehu parece cumplir un juicio, pero el narrador limita su aprobación y muestra que la reforma incompleta no transforma el sistema.',
   'Mostrar que derribar un símbolo corrupto no basta si el nuevo liderazgo reproduce violencia, oportunismo y formas distintas de infidelidad.',
   'La reforma verdadera necesita coherencia y no puede medirse solo por enemigos derrotados. La historia comunitaria requiere aprender antes de que las consecuencias sean irreversibles.',
   'La masacre ejecutada por Jehu no es modelo de reforma religiosa. La explicación teológica de la caída debe convivir con el análisis histórico del imperialismo asirio y no justificar desprecio hacia comunidades samaritanas actuales.',
   ARRAY['Jehu','casa de Acab','Samaria','Asiria','deportación','reforma incompleta']::text[],
   ARRAY['israelitas del norte','asirios','arameos']::text[],
   ARRAY['Jezreel','Samaria','Nínive']::text[]),
  ('2-reyes-18-25-juda','2KI','section',18,NULL::smallint,25,NULL::smallint,
   'Judá entre reforma, invasión y exilio',
   'Ezequías resiste a Asiria, Manasés representa una grave infidelidad, Josías reforma el culto al encontrarse el libro de la ley y Babilonia finalmente destruye Jerusalén.',
   'La campaña de Senaquerib, el ascenso babilónico y las deportaciones están ampliamente conectados con fuentes del antiguo Cercano Oriente. Jerusalén cayó en 586/587 a. C. según los sistemas cronológicos usados.',
   'La Pascua y la lectura de la Torá ocupan el centro de la reforma de Josías. El exilio se convierte en una crisis de tierra, templo, rey e identidad.',
   'Relatos extensos de Ezequías y Josías interrumpen fórmulas regias, pero no revierten por completo una trayectoria que termina con sitio, destrucción y exilio.',
   'Afirmar que la oración y la reforma importan, pero que generaciones de violencia e injusticia pueden producir consecuencias que una acción tardía no elimina automáticamente.',
   'Buscar a Dios en crisis incluye recordar, reformar prácticas y sostener esperanza sin negar pérdidas. La última escena de Joaquín sugiere que el exilio no es la última palabra.',
   'La enfermedad de Ezequías no debe utilizarse para prescribir señales milagrosas. La reforma de Josías no autoriza destruir personas o culturas, y la caída de Jerusalén no debe emplearse para culpar a víctimas de guerras modernas.',
   ARRAY['Ezequías','Senaquerib','Manasés','Josías','Babilonia','Jerusalén','exilio']::text[],
   ARRAY['judíos','asirios','babilonios']::text[],
   ARRAY['Jerusalén','Laquis','Babilonia']::text[])
)
insert into public.biblical_context_units (
  slug, book_code, source_id, scope_kind, chapter_start, verse_start,
  chapter_end, verse_end, title, summary, historical_context, jewish_context,
  literary_context, authorial_intent, theological_reflection,
  interpretive_cautions, key_terms, people_groups, places,
  source_locator, provider_version, content_hash, review_status, enabled, metadata
)
select
  data.slug, data.book_code, source.id, data.scope_kind,
  data.chapter_start::smallint, data.verse_start::smallint,
  data.chapter_end::smallint, data.verse_end::smallint,
  data.title, data.summary, data.historical_context, data.jewish_context,
  data.literary_context, data.authorial_intent, data.theological_reflection,
  data.interpretive_cautions, data.key_terms, data.people_groups, data.places,
  'vida://corpus/contexto/historicos/v1#' || data.slug,
  'historicos-v1-2026-08-02',
  encode(extensions.digest(concat_ws('|', data.slug, data.title, data.summary,
    data.historical_context, data.jewish_context, data.literary_context,
    data.authorial_intent, data.theological_reflection, data.interpretive_cautions), 'sha256'), 'hex'),
  'approved', true,
  jsonb_build_object('coverage_batch','historical-books','generated_by_ai',false,'review_level','editorial')
from data cross join source
on conflict (slug) do update set
  book_code=excluded.book_code, source_id=excluded.source_id, scope_kind=excluded.scope_kind,
  chapter_start=excluded.chapter_start, verse_start=excluded.verse_start,
  chapter_end=excluded.chapter_end, verse_end=excluded.verse_end,
  title=excluded.title, summary=excluded.summary,
  historical_context=excluded.historical_context, jewish_context=excluded.jewish_context,
  literary_context=excluded.literary_context, authorial_intent=excluded.authorial_intent,
  theological_reflection=excluded.theological_reflection,
  interpretive_cautions=excluded.interpretive_cautions,
  key_terms=excluded.key_terms, people_groups=excluded.people_groups, places=excluded.places,
  source_locator=excluded.source_locator, provider_version=excluded.provider_version,
  content_hash=excluded.content_hash, review_status=excluded.review_status,
  enabled=excluded.enabled, metadata=excluded.metadata, updated_at=now();