-- FASE D · Bloque 4 · 1–2 Tesalonicenses
select internal.import_biblical_context_batch(
  'paulinas-tesalonicenses',
  'paulinas-tesalonicenses-v1-2026-08-02',
  $books$[
    {
      "code":"1TH","slug":"1-tesalonicenses","name":"1 Tesalonicenses","chapters":5,
      "summary":"1 Tesalonicenses anima a una comunidad reciente que enfrenta presión social, agradece su fe y colaboración, aclara dudas sobre personas fallecidas antes del regreso de Cristo y llama a una vida santa, esperanzada y responsable.",
      "historical":"Tesalónica era una ciudad portuaria y capital de Macedonia dentro del Imperio romano. La carta suele fecharse alrededor del año 50 d. C. y es considerada una de las cartas paulinas más antiguas conservadas.",
      "jewish":"El lenguaje de elección, santidad, día del Señor y resurrección nace de Escrituras y expectativas judías. La polémica de 2:14–16 requiere especial cuidado por su historia de uso antijudío y sus cuestiones textuales e históricas.",
      "literary":"Acción de gracias, recuerdos de la misión, informe de Timoteo y exhortaciones forman una carta pastoral cálida que responde a inquietudes concretas.",
      "intent":"Fortalecer una comunidad vulnerable, defender la integridad del ministerio, orientar sexualidad y trabajo y ofrecer esperanza compartida ante el duelo y la expectativa del regreso de Cristo.",
      "reflection":"La esperanza cristiana consuela sin negar el duelo y produce una vida sobria, amorosa y responsable en el presente.",
      "cautions":"El encuentro con el Señor en el aire no debe convertirse en cronograma indiscutible ni en motivo para abandonar responsabilidades. 1 Tesalonicenses 2 no autoriza culpar colectivamente al pueblo judío.",
      "terms":["parusía","día del Señor","santidad","esperanza","resurrección","trabajo"],
      "groups":["tesalonicenses","judíos","gentiles","autoridades romanas"],
      "places":["Tesalónica","Macedonia","Atenas"]
    },
    {
      "code":"2TH","slug":"2-tesalonicenses","name":"2 Tesalonicenses","chapters":3,
      "summary":"2 Tesalonicenses sostiene a una comunidad perseguida, corrige alarma sobre la llegada del día del Señor y llama a perseverar, discernir mensajes y trabajar de manera responsable.",
      "historical":"La carta presupone presión sobre las comunidades y confusión escatológica. Su autoría paulina es debatida por diferencias de tono, estilo y relación con 1 Tesalonicenses.",
      "jewish":"El lenguaje de revelación, rebelión, templo, juicio y día del Señor proviene de tradiciones apocalípticas judías. Sus símbolos deben explicarse dentro de ese mundo antes de aplicaciones posteriores.",
      "literary":"Dos acciones de gracias rodean una enseñanza apocalíptica, una petición de oración y exhortaciones sobre disciplina, trabajo y paz.",
      "intent":"Evitar que la esperanza se transforme en pánico, especulación o abandono de la vida común, y sostener a quienes padecen injusticia.",
      "reflection":"Esperar el futuro de Dios exige firmeza, discernimiento y responsabilidad cotidiana, no miedo constante ni pasividad.",
      "cautions":"El «hombre de iniquidad» y el «que detiene» tienen múltiples interpretaciones y no deben identificarse con figuras actuales sin evidencia. La disciplina comunitaria no autoriza negar alimento o ayuda básica.",
      "terms":["día del Señor","rebelión","hombre de iniquidad","restricción","tradición","trabajo"],
      "groups":["tesalonicenses","perseguidores","personas ociosas"],
      "places":["Tesalónica","Macedonia"]
    }
  ]$books$::jsonb,
  $sections$[
    {"code":"1TH","slug":"1-tesalonicenses-1-3","start":1,"end":3,"title":"Fe, misión y cuidado pastoral","summary":"Pablo agradece la respuesta de la comunidad, recuerda una misión sin manipulación y expresa alivio al recibir el informe de Timoteo sobre su perseverancia.","intent":"Fortalecer vínculos de confianza y mostrar que el liderazgo apostólico sirve con ternura, trabajo y transparencia.","cautions":"Las metáforas parentales no justifican control espiritual ni dependencia emocional. La polémica sobre Judea no debe convertirse en acusación étnica colectiva.","terms":["fe","amor","esperanza","Timoteo","trabajo","cuidado"],"reflection":"El acompañamiento sano celebra el crecimiento ajeno y busca fortalecer, no poseer, a la comunidad.","groups":["tesalonicenses","misioneros","comunidades de Judea"],"places":["Tesalónica","Atenas","Macedonia"]},
    {"code":"1TH","slug":"1-tesalonicenses-4","start":4,"end":4,"title":"Santidad, amor fraternal y esperanza ante el duelo","summary":"La comunidad recibe instrucciones sobre sexualidad responsable, amor, trabajo tranquilo y el destino de quienes fallecieron antes de la venida del Señor.","intent":"Relacionar esperanza futura con respeto corporal, amor concreto, trabajo digno y consuelo mutuo.","cautions":"La santidad sexual no debe usarse para vergüenza corporal ni control coercitivo. El lenguaje de descenso, trompeta y nubes es apocalíptico y admite distintas lecturas.","terms":["santificación","amor fraternal","trabajo","duelo","resurrección","parusía"],"reflection":"La esperanza acompaña a quien llora y recuerda que ninguna persona fiel queda olvidada.","groups":["tesalonicenses","personas en duelo"],"places":["Tesalónica"]},
    {"code":"1TH","slug":"1-tesalonicenses-5","start":5,"end":5,"title":"Día del Señor, discernimiento y vida comunitaria","summary":"El día llega inesperadamente, por lo que la comunidad es llamada a sobriedad, ánimo, paciencia, oración, gratitud y evaluación de las profecías.","intent":"Reemplazar la especulación cronológica con vigilancia ética, cuidado mutuo y discernimiento comunitario.","cautions":"«Orar sin cesar» no exige actividad verbal continua ni culpa por descansar. Probar profecías significa evaluarlas; no aceptar afirmaciones espirituales sin evidencia.","terms":["día del Señor","sobriedad","discernimiento","profecía","paz"],"reflection":"Estar preparados significa vivir despiertos al bien, sostener al débil y examinar con honestidad lo que se afirma en nombre de Dios.","groups":["comunidad tesalonicense","líderes locales"],"places":["Tesalónica"]},
    {"code":"2TH","slug":"2-tesalonicenses-1","start":1,"end":1,"title":"Perseverancia, justicia y alivio","summary":"La carta agradece el crecimiento de la comunidad bajo presión y expresa esperanza de justicia y alivio cuando Cristo sea revelado.","intent":"Sostener a quienes sufren sin pedirles que consideren buena la persecución ni que tomen venganza por sí mismos.","cautions":"Las imágenes de juicio no autorizan odio, amenazas religiosas ni certeza sobre el destino eterno de personas concretas.","terms":["perseverancia","persecución","justicia","alivio","revelación"],"reflection":"La confianza en la justicia de Dios puede liberar de la venganza y sostener acciones presentes de protección y verdad.","groups":["tesalonicenses","perseguidores"],"places":["Tesalónica"]},
    {"code":"2TH","slug":"2-tesalonicenses-2","start":2,"end":2,"title":"Alarma escatológica, rebelión y firmeza","summary":"La comunidad no debe dejarse sacudir por mensajes que afirman que el día ya llegó; antes se describe una rebelión, una figura de iniquidad y una acción restrictiva misteriosa.","intent":"Frenar el pánico producido por mensajes supuestamente autorizados y llamar a permanecer firmes en la enseñanza recibida.","cautions":"No existe consenso sobre cada símbolo. No deben aplicarse a presidentes, tecnologías, iglesias o acontecimientos actuales como identificación segura.","terms":["día del Señor","rebelión","hombre de iniquidad","engaño","tradición"],"reflection":"La firmeza espiritual incluye no dejarse gobernar por mensajes alarmistas, aunque utilicen lenguaje religioso.","groups":["tesalonicenses","maestros alarmistas"],"places":["Tesalónica"]},
    {"code":"2TH","slug":"2-tesalonicenses-3","start":3,"end":3,"title":"Oración, trabajo y corrección fraterna","summary":"Pablo pide oración, reafirma la fidelidad de Dios y corrige a quienes abandonaron el trabajo y alteraban la vida comunitaria.","intent":"Proteger la cooperación, evitar que la expectativa futura destruya la responsabilidad presente y corregir sin tratar al hermano como enemigo.","cautions":"«El que no quiera trabajar, que no coma» se refiere a quien puede y se niega deliberadamente dentro de una situación concreta; no justifica negar ayuda a menores, enfermos, desempleados o personas vulnerables.","terms":["oración","fidelidad","trabajo","disciplina","paz"],"reflection":"La comunidad puede establecer límites y, al mismo tiempo, corregir sin deshumanizar ni abandonar a quien necesita apoyo.","groups":["tesalonicenses","personas ociosas","trabajadores"],"places":["Tesalónica"]}
  ]$sections$::jsonb
);